### PR TITLE
fix(cdk/stepper): Linear stepper after initialization navigating to previous step issue

### LINKED ISSUE #15449: Linear stepper stuck on the step after re-initialization
#### What is the expected behavior?
After linear stepper reinitialization (f.e. web-app reload) all previously filled out forms of steps restore their valid state from storage and stepper restore selectedIndex. All these forms should be considered as visited and completed so user can navigate back without restriction.

#### What is the current behavior?
User completed step 1 and 2 and stay on step 3.
States of forms on step 1 and 2 are saved in storage.
After reload, forms on step 1 and 2 restore its states, so the steps are valid and `selectedIndex` set to step 3.
User can't navigate back to step 2, despite the fact that this step is valid. User can only navigate to step 1.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-a5jw17

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
    "@angular/cdk": "^7.3.1",
    "@angular/core": "7.2.4",
    "@angular/material": "^7.3.1",
    "typescript": "3.2.4",
 ```
Windows 8.1; Google Chrome 72.0.3626.121;

### PR DESCRIPTION
**Pull request by mistrykaran91**
Set all the previous steps as interacted if it's linear step and is not the first step.

Fixes #15449

### CODE REVIEW

**Review by mmalerba — APPROVED** [review]

File: src/cdk/stepper/stepper.ts [hunk 1]
```diff
@@ -402,6 +402,17 @@ export class CdkStepper implements AfterContentInit, AfterViewInit, OnDestroy {
...
       this._selectedIndex = 0;
     }
+
+    // For linear step and selected index is greater than zero,
+    // set all the previous steps to interacted so that we can navigate to previous steps.
+    if (this.linear && this._selectedIndex > 0) {
+      this.steps
+        .toArray()
+        .slice(0, this._selectedIndex)
+        .map(step => {
```
Comment (mmalerba) [inline src/cdk/stepper/stepper.ts:412]: rather than using `.map` for this, can you use `for (const step of ...)`

Comment (mistrykaran91) [reply src/cdk/stepper/stepper.ts]: Made the changes as per the comments.

**Review by mmalerba — APPROVED** [review]

**Comment by mistrykaran91** [comment]
@mmalerba does the `action:merge` tag will be added later or do I need to do something else too ?

**Comment by mmalerba** [comment]
The changes were merged into the following branches: main, 19.1.x, 19.2.x
