### PR TITLE
fix(drag-drop): boundary not accounting for scrolling

### LINKED ISSUE #18597: [drag-drop] cdkDragBoundary positions not updating during viewport scrolling
#### Reproduction

[https://stackblitz.com/edit/angular-v8fc5s](https://stackblitz.com/edit/angular-v8fc5s)
 
 
#### Expected Behavior

cdkDragBoundary should always be honored. The cached boundary positions appear to not be updating during viewport scrolling, producing phantom edges and/or enabling dragging outside of the boundary. See below gif.

#### Actual Behavior

GIF

#### Environment

- Angular: 9
- CDK/Material: 9.0.1
- Browser(s): all

### PR DESCRIPTION
**Pull request by crisbeto**
When the user starts dragging, we cache the `ClientRect` of the boundary so we know the area around which to limit the preview. The problem is that we weren't updating the cached position which cause it to behave incorrectly if the user scrolled after they start dragging.

These changes fix the issue by updating cached position. This ended up slightly more complicated than expected, because it has to interact with the auto scrolling.

I've also moved around some utilities for dealing with `ClientRect` so that they can be reused.

Fixes #18597.

### CODE REVIEW

File: src/cdk/drag-drop/drag-ref.ts [hunk 1]
```diff
@@ -770,11 +771,21 @@ export class DragRef<T = any> {
...
+      const currentScrollPosition = this._viewportRuler.getViewportScrollPosition();
+
+      // Re-adjust the cached boundary ClientRect if the page is scrolled.
+      if (oldScrollPosition && this._boundaryRect) {
+        const topDifference = oldScrollPosition.top - currentScrollPosition.top;
+        const leftDifference = oldScrollPosition.left - currentScrollPosition.left;
+        adjustClientRect(this._boundaryRect, topDifference, leftDifference);
+      }
+
+      this._scrollPosition = currentScrollPosition;
```
Comment (jelbourn) [inline src/cdk/drag-drop/drag-ref.ts]: Move this block into its own method?

File: src/cdk/drag-drop/drag-ref.ts [hunk 2]
```diff
@@ -770,11 +771,21 @@ export class DragRef<T = any> {
     this._pointerMoveSubscription = this._dragDropRegistry.pointerMove.subscribe(this._pointerMove);
     this._pointerUpSubscription = this._dragDropRegistry.pointerUp.subscribe(this._pointerUp);
     this._scrollSubscription = this._dragDropRegistry.scroll.pipe(startWith(null)).subscribe(() => {
-      this._scrollPosition = this._viewportRuler.getViewportScrollPosition();
+      const oldScrollPosition = this._scrollPosition;
+      const currentScrollPosition = this._viewportRuler.getViewportScrollPosition();
+
+      // Re-adjust the cached boundary ClientRect if the page is scrolled.
```
Comment (jelbourn) [inline src/cdk/drag-drop/drag-ref.ts]: Include the reason why the rect needs to be updated?

**Comment by crisbeto** [comment]
The feedback has been addressed @jelbourn.
