### PR TITLE
fix(material/slider): Ticks updated wrongly if the max property 0

### LINKED ISSUE #23913: bug(mat-slider): Max value not updating correctly when new value is 0
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

I am changing slider's max value in my component while/after doing some works. And it seems it has a problem updating visually when new max value is 0. 

### Reproduction

Steps to reproduce:
1. Define slider like this: `<mat-slider min="0" [displayWith]="displayValue" [max]="maxValue" step="1" [thumbLabel]="true" [tickInterval]="1" [(ngModel)]="sliderValue" (ngModelChange)="changeSliderValue()"></mat-slider>`
2. Default sliderValue is 0, maxValue is 0.
3. Click a button and change maxValue - let's say to 6. Updates slider and ticks correctly.
4. Click another button and change maxValue to 0. Updates slider and ticks incorrectly, shows previous ticks.
5. You can see the same bug here: [https://material.angular.io/components/slider/examples](url)

### Expected Behavior

Updating slider and ticks correctly.

### Actual Behavior

Updated slider and ticks incorrectly.

### Environment

- Angular: 10.2.0
- CDK/Material: 11.0.2
- Browser(s): Chome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 x64

### PR DESCRIPTION
**Pull request by DMezhenskyi**
When we get equal min & max value for the slider then we can get division by zero which leads to an improper style value for the background-size (Infinity%). This fix introduces a tiny function that checks if we deal with finite numbers during calculations where potentially division by zero may occur.

Fixes #23913

### CODE REVIEW

File: src/material/slider/slider.ts [hunk 1]
```diff
@@ -503,6 +503,10 @@ export class MatSlider
     const shouldInvertAxis = this._shouldInvertAxis();
     return this._getDirection() == 'rtl' && !this.vertical ? !shouldInvertAxis : shouldInvertAxis;
   }
+  /** It returns safe tick interval percent coercing NaN and Infinity to fallback */
+  private _getTickIntervalPercent(fallback = 0) {
```
Comment (crisbeto) [inline src/material/slider/slider.ts:507]: Instead of defining the getter and having to check that it's a safe number every time, it might be easier to update `_updateTickIntervalPercent` so that `_tickIntervalPercent` is never assigned an invalid number in the first place.

Comment (DMezhenskyi) [reply src/material/slider/slider.ts]: Yeah, I didn't somehow notice that `_updateTickIntervalPercent` is the only one place where we assign value to this property. Ok, then it absolutely makes sense. I just pushed refactored code

**Review by crisbeto — APPROVED** [review]
LGTM
