### PR TITLE
fix(material/form-field): update state if control changes

### LINKED ISSUE #29402: bug(mat-form-field): CSS class generated by controlType of  MatFormFieldControl is static, never changes if the control changes
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

`mat-form-field` is able to generate a CSS class based on the value of MatFormFieldControl's controlType. The problem is that when the `MatFormFieldControl` implementation changes dynamically the field always has the initial MatFormFieldControl CSS class, for example if the initial control is a `mat-input` and later changes to a `mat-select` the CSS class on the field will always be `mat-mdc-form-field-type-mat-input`

Note: The documentation says the prefix for the generated CSS class is `mat-form-field-type` but the real ones have the prefix `mat-mdc-form-field-type`. This could be a documentation bug or a regression from the legacy controls, but the prefix is a different bug that this one I am reporting.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/qbaesq

Steps to reproduce:

1. The demo shows two fields one that initially uses a `mat-input` and the other a `mat-select`
2. The button on the top switch the implementations of MatFormFieldControl used on the fields
3. After the switch an error is shown below each field, the error is a check that the field contains the correct CSS class for the control implementation.

### Expected Behavior

No error should be shown because each field switch dynamically the control generated CSS class.

### Actual Behavior

Fields don't change to the control CSS class dynamically, it always stays on the same initial class.

### Environment

- Angular: 18.0.6
- CDK/Material: 18.0.6
- Browser(s): Firefox, Chromium
- Operating System (e.g. Windows, macOS, Ubuntu): Linux (Fedora)

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the form field wasn't accounting for the case where the form control is swapped out.

Fixes #29402.

### CODE REVIEW

File: src/material/form-field/form-field.ts [hunk 1]
```diff
@@ -365,17 +368,23 @@ export class MatFormField
...
-    this._initializeControl();
     this._initializeSubscript();
     this._initializePrefixAndSuffix();
     this._initializeOutlineLabelOffsetSubscriptions();
   }
 
   ngAfterContentChecked() {
     this._assertFormFieldControl();
+
+    if (this._control !== this._previousControl) {
```
Comment (crisbeto) [inline src/material/form-field/form-field.ts:379]: Another option for this would've been to use signals, but it seems like `_control` is set up as some sort of backwards compatibility layer so I didn't want to change it into a computed which would've been breaking.

File: src/material/form-field/form-field.ts [hunk 2]
```diff
@@ -409,25 +418,31 @@ export class MatFormField
   }
 
   /** Initializes the registered form field control. */
-  private _initializeControl() {
+  private _initializeControl(previousControl: MatFormFieldControl<unknown> | null) {
```
Comment (mmalerba) [inline src/material/form-field/form-field.ts:421]: why pass previousControl in, can't we just read it off the class like we do for control?

**Review by mmalerba — APPROVED** [review]

File: src/material/form-field/form-field.ts (hunk 2 above)
Comment (crisbeto) [reply src/material/form-field/form-field.ts:421]: I wanted to keep the code that re-assigns it in the `ngAfterContentChecked` since that's the only place where we check it.
