### PR TITLE
build: fix release output containing invalid imports sometimes

### LINKED ISSUE #20179: bug(bidi): latest 10.1.2 fail to compile due module resolution
#### Expected Behavior

What behavior were you expecting to see?
In version 10.1.1
In NPM package `@angular\cdk\esm2015\bidi\directionality.js`
```
import * as i1 from "./dir-document-token";
```
Which resolve correctly

#### Actual Behavior

What behavior did you actually see?
In NPM package `@angular\cdk\esm2015\bidi\directionality.js`
```
import * as i1 from "@angular/cdk/bidi/dir-document-token";
```
which does not resolve

#### Environment

- Angular: 10.0.7
- CDK/Material: Specified above
- Browser(s): does not affected
- Operating System (e.g. Windows, macOS, Ubuntu):  does not affected

### PR DESCRIPTION
**Pull request by devversion**
A very subtle issue has surfaced in our release output. Based on
previous builds that have been performed locally by the caretaker
performing the release, the release output might differ and contain
invalid module imports that break ES2015 output.

Notably the es2015 output is not primarily used by the CLI. It uses
the flat ES2015 output instead.

The issue surfaces because of a bug in `@bazel/typescript` where the
`moduleName` for source files is leaking between TSC worker runs. This
means that source files are incorrectly referenced by module name,
instead of relative path when the prodmode ES2015 output is built.
Deep paths to source files are not supported as per Angular Package format.

We patch the fix that is pending upstream to ensure our release output
works: https://github.com/bazelbuild/rules_typescript/pull/504. Once the
fix upstream lands (which might take quite some time; given g3 sync and
sync with the rules_nodejs repository), we can remove the patch and
update to the latest version of `@bazel/typescript`.

Fixes #20179.

### CODE REVIEW

File: tools/postinstall/apply-patches.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ const chalk = require('chalk');
  * Version of the post install patch. Needs to be incremented when
  * existing patches or edits have been modified.
  */
-const PATCH_VERSION = 6;
+const PATCH_VERSION = 8;
```
Comment (josephperrott) [inline tools/postinstall/apply-patches.js:17]: What happened to 7!?

Did we skip it because seven eight nine?   <sup>[explanation link](https://explainthejoke.com/2013/01/24/7-8-9/) for those who haven't heard this joke

Comment (devversion) [reply tools/postinstall/apply-patches.js:17]: hahah. I was expecting that you notice. I messed up the patch in my first PR pushes, and to make it run in the fixup I needed to increment it twice.

Comment (josephperrott) [reply tools/postinstall/apply-patches.js:17]: Sounds good, just wanted to confirm.

Comment (devversion) [reply tools/postinstall/apply-patches.js:17]: yeah, thanks for raising this. Could have totally also been by accident from local testing.
