### PR TITLE
fix(material/chips): allow for role to be overwritten on chip list and chip

### LINKED ISSUE #15787: Allow custom roles for chip groups and chips
#### Please describe the feature you would like to request.
MatChipList and MatChip do not support providing `role` attribute. Add support for that.

#### What is the use-case or motivation for this proposal?
I want to use MatChipList and MatChip as radiobox and radio respectively for better accessibility support. But can't override.

#### Is there anything else we should know?
Should be a trivial change. I can send a PR.

### PR DESCRIPTION
**Pull request by crisbeto**
Allows for the ARIA `role` of the `mat-chip-list` and `mat-chip` to be overwritten.

Fixes #15787.

### CODE REVIEW

File: src/lib/chips/chip-list.ts [hunk 1]
```diff
@@ -165,7 +165,18 @@ export class MatChipList extends _MatChipListMixinBase implements MatFormFieldCo
   }
 
   /** The ARIA role applied to the chip list. */
-  get role(): string | null { return this.empty ? null : 'listbox'; }
+  @Input()
+  get role(): string | null {
```
Comment (crisbeto) [inline src/lib/chips/chip-list.ts]: Note: I'm not a fan of this property signature (having `| null`), but I kept it for backwards compatibility. Since the property was readonly until now we could get away with changing it to just be a `string`.
