### PR TITLE
fix(cdk/text-field): Long multiline textfield  focus issue

### LINKED ISSUE #20255: bug(text field): Long multiline text field - scrolled up on input
#### Reproduction

[https://monosnap.com/file/mKU40IcGQvhrgnhN9U3TLpAeouTj2g](https://monosnap.com/file/mKU40IcGQvhrgnhN9U3TLpAeouTj2g)

Steps to reproduce:
1. open [https://v9.material.angular.io/cdk/text-field/examples](https://v9.material.angular.io/cdk/text-field/examples) in ie11
2. find example "Auto-resizing textarea"
3. inspect text field in the bottom of page
4. uncheck element.style max-height (or you can try to reproduce it without cdkAutosizeMaxRows)
5. insert very long text into the text field (about 50 lines) - height of content must to be higher than viewport's height
6. put the cursor on the third line from the end (not on last line)
7. enter some letter
 
 
#### Expected Behavior

The cursor and the letter just entered remain in the viewport.

#### Actual Behavior

The scroll moved up to the top of textarea

#### Environment

- Angular: 9.1.0
- CDK/Material: 9.2.4 and 10.0.0
- Browser(s): ie11
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by mistrykaran91**
When we have a long multiline textfield and put the cursor on almost an end (For example, on 3rd last line), the scroll moves up to the top of textarea. This fix will cache the `scrollTop` in the`resizeToFitContent` method

Fixes #20255

### CODE REVIEW

File: src/cdk/text-field/autosize.ts [hunk 1]
```diff
@@ -367,6 +367,8 @@ export class CdkTextareaAutosize implements AfterViewInit, DoCheck, OnDestroy {
     // it to receive focus on IE and Edge.
     if (!this._destroyed.isStopped && this._hasFocus) {
       textarea.setSelectionRange(selectionStart, selectionEnd);
+      textarea.blur();
```
Comment (mmalerba) [inline src/cdk/text-field/autosize.ts:370]: I'm worried this could have some kind of accessibility consequences. I see that the original issue was filed as affecting ie11 which isn't a browser we support at this point. Unless this is known to affect other browsers that we do still support I'm inclined to just leave this as is

**Review by mmalerba — CHANGES_REQUESTED** [review]

File: src/cdk/text-field/autosize.ts (hunk 1 above)
Comment (mistrykaran91) [reply src/cdk/text-field/autosize.ts:370]: I had tested it on Chrome and it was not working as expected, I mean it was causing the same issue as mentioned. But it causes issue only when its very long text. So, if we do not want to fix the issue, better to close ? :)

Comment (mmalerba) [reply src/cdk/text-field/autosize.ts:370]: If setting scrollTop fixes it, that should be ok. Another option might be [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)

Comment (mistrykaran91) [reply src/cdk/text-field/autosize.ts:370]: I'll try to with those few options and check whether it works well or not.

Comment (mistrykaran91) [reply src/cdk/text-field/autosize.ts]: @mmalerba, I have updated the MR.

File: src/cdk/text-field/autosize.ts [hunk 2]
```diff
@@ -164,6 +165,7 @@ export class CdkTextareaAutosize implements AfterViewInit, DoCheck, OnDestroy {
           this._renderer.listen('window', 'resize', () => this._resizeEvents.next()),
           this._renderer.listen(this._textareaElement, 'focus', this._handleFocusEvent),
           this._renderer.listen(this._textareaElement, 'blur', this._handleFocusEvent),
+          this._renderer.listen(this._textareaElement, 'scroll', this._handleScrollEvent),
```
Comment (mmalerba) [inline src/cdk/text-field/autosize.ts:168]: do we need to add a new listener, or can we just cache this at the same time we're caching the line-height, etc.?

Comment (mistrykaran91) [reply src/cdk/text-field/autosize.ts:168]: I now assign the `scrollTop` in `resizeToFitContent` so where we will cache ? Not sure about it.

Comment (mistrykaran91) [reply src/cdk/text-field/autosize.ts]: @mmalerba I have updated the MR, does this look good ?

**Comment by mistrykaran91** [comment]
@mmalerba, seems to be similar issue, this one - https://github.com/angular/components/issues/8992

**Review by mmalerba — APPROVED** [review]
This looks good to me!

**Comment by mistrykaran91** [comment]
@mmalerba let me know if you want me to rebase the branch with the latest changes in main.

**Comment by mmalerba** [comment]
It looks like there's no conflicts so its fine for now, we just need to run it against google's internal tests and see if anything fails

**Comment by mistrykaran91** [comment]
@mmalerba just to be double sure won't it fix this one too - https://github.com/angular/components/issues/8992 ? Or I'm missing something

**Comment by Sn0oze** [comment]
Today I updated the CDK version from v18.x to v19.2.8 during the Angular v18 to v19 migration of our mono repo and noticed a regression in our textarea component that uses the CdkTextareaAutosize. 
After some bisecting, I conclude that this fix must be the cause as the regression appears from version 19.2.4 and onwards, which is the first release that includes this fix.

The regression happens when enough rows have been inserted at the bottom of the text area to reach the maxRows limit and cause the textarea to overflow. 
While inserting new rows, the scroll container does not properly scroll to the inserted rows. This bug can also be observed on the official [Auto-resizing textarea](https://material.angular.io/cdk/text-field/examples#text-field-autosize-textarea) example.
To reproduce the bug it is enough to focus the text area and keep the enter key pressed. 
The same interaction works as expected in [v18](https://v18.material.angular.io/cdk/text-field/examples#text-field-autosize-textarea) of the Auto-resizing textarea example
