### PR TITLE
fix(table): error when nesting tables

### LINKED ISSUE #18768: bug(Table): Angular 9: caching column definitions breaks nesting tables
#### Reproduction

Steps to reproduce:
1. Open [this](https://stackblitz.com/edit/angular-nested-mat-table?file=package.json) StackBlitz from [this](https://stackoverflow.com/a/57839402) StackOverflow answer regarding nested material tables using Angular 8.
2. Observe that clicking on table rows causes the table to expand/collapse and show nested data.
3. Upgrade Angular to 9.0.5. For convenience, [here's](https://stackblitz.com/edit/angular-nested-mat-table-xggusf?file=package.json) a StackBlitz with this completed.
 
#### Expected Behavior

Nested material tables in each mat-row with those columns defined, opening and closing as intended. No errors.

#### Actual Behavior

Expanding a row works the first time, then fails, leaving the table in a bad state throwing errors to the effect of `Duplicate column definition name provided` - the expansion/collapse functionality completely stops working at this point.

One _can_ work around this by creating a dummy component who's sole purpose is to pass the data to another instance of `mat-table` - I've shown this in a [fork](https://angular-nested-mat-table-rlai7s.stackblitz.io) of the Angular 9 StackBlitz. _Note: I didn't preserve the filters from the original StackBlitz, as that was not part of the functionality in question._

#### Environment

- Angular: 9.0.5
- CDK/Material: 9.1.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by crisbeto**
Previously we used to support nesting tables, but in v9 we had to make some changes in order to handle all cases in Ivy. As a result, nesting was broken due to parent tables picking up the cell definitions of their children. These changes add some logic to account for tables being nested.

Fixes #18768.

### CODE REVIEW

File: src/cdk/table/row.ts [hunk 1]
```diff
@@ -90,8 +93,11 @@ const _CdkHeaderRowDefBase: CanStickCtor&typeof CdkHeaderRowDefBase =
   selector: '[cdkHeaderRowDef]',
   inputs: ['columns: cdkHeaderRowDef', 'sticky: cdkHeaderRowDefSticky'],
 })
-export class CdkHeaderRowDef extends _CdkHeaderRowDefBase implements CanStick, OnChanges {
-  constructor(template: TemplateRef<any>, _differs: IterableDiffers) {
+export class CdkHeaderRowDef extends _CdkHeaderRowDefBase implements CanStick, OnChanges { //
```
Comment (andrewseguin) [inline src/cdk/table/row.ts]: Trailing `//`

File: src/cdk/table/table.spec.ts [hunk 2]
```diff
@@ -482,6 +482,19 @@ describe('CdkTable', () => {
...
   });
 
+  it('should be able to nest tables', () => {
+    const thisFixture = createComponent(NestedHtmlTableApp);
+    thisFixture.detectChanges();
+    const outerTable = thisFixture.nativeElement.querySelector('table');
+    const innerTable = outerTable.querySelector('table');
+
+    expect(outerTable).toBeTruthy();
+    expect(outerTable.querySelector('tbody').rows.length).toBe(3);
```
Comment (andrewseguin) [inline src/cdk/table/table.spec.ts]: Would like to add tests regarding the cells as well, rather than just the row count. Can you test the table contents?

Comment (crisbeto) [reply src/cdk/table/table.spec.ts]: I wanted to avoid testing the contents, because it gets weird with whitespace once you start nesting elements. I'll add assertions for the number of cells.
