### PR TITLE
fix(material/sidenav): only trap focus when backdrop is enabled

### LINKED ISSUE #26572: bug(mat-sidenav): There is no focus trap when Sidenav position is 'end'
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

11

### Description

When you opens the Sidenav in over mode the focus shouldn't leave the Sidenav when it is open. it works in case the Sidenav opens in the left side. but in the right side it is broken.

### Reproduction

Steps to reproduce:
[stackBlitz](https://stackblitz.com/edit/angular-96vr4f?file=src%2Fapp%2Fsidenav-mode-example.html)
1. Open the Stackblitz example
2. choose Mode: Over
3. click on the toggle button
4. In the keyboard, click on the tab several times.

### Expected Behavior

The focus shouldn't leave the Sidenav.

### Actual Behavior

The focus leaves the side pane and there is no way to return to Sidenav with the keyboard.

### Environment

- Angular: 14.2.10
- CDK/Material: 14.2.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by zarend**
Correct when Sidenav enabled focus trapping. When backdrop is show, trap focus. Do no trap focus when backdrop is not shown.

Existing behavior is that Sidenav traps focus whenever it is not in side mode. This causes the end user to not be able to interact with the sidenav content when the mode is push/over, backdrop is disabled and using ConfigurableFocusTrapFactory (#26572).

With this commit applied, Sidenav always traps focus when backdrop is shown. Sidenav never traps focus when backdrop is not shown, regardless of what mode the sidenav is in, focus trapping will respect if the backdrop is shown or not shown.

Fix this issue by correcting boolean logic for detecting if backdrop is enabled and using that logic to determine when to trap focus. Add an example that injects ConfigurableFocusTrapFactory.

Fix #26572

### CODE REVIEW

File: src/material/sidenav/drawer.ts [hunk 1]
```diff
@@ -595,8 +595,9 @@ export class MatDrawer implements AfterViewInit, AfterContentChecked, OnDestroy
   /** Updates the enabled state of the focus trap. */
   private _updateFocusTrapState() {
     if (this._focusTrap) {
-      // The focus trap is only enabled when the drawer is open in any mode other than side.
-      this._focusTrap.enabled = this.opened && this.mode !== 'side';
```
Comment (crisbeto) [inline src/material/sidenav/drawer.ts:599]: Mostly trying to understand the reasoning here: don't we still want to trap focus when the mode is `over`? In that case the sidenav basically acts as a dialog so I would expect that it needs focus trapping as well.

Comment (mmalerba) [reply src/material/sidenav/drawer.ts:599]: I thing the thinking is that the backdrop enforces the modal-ness from the mouse perspective and the focus-trap enforces it from the keyboard perspective, so it makes sense to tie those together. That way we're presenting the same modal-ness to both mouse and keyboard users

**Review by mmalerba — APPROVED** [review]
LGTM

File: src/material/sidenav/drawer.ts (hunk 1 above)
Comment (zarend) [reply src/material/sidenav/drawer.ts:599]: By default, the Drawer has a backdrop when the mode is `over`. Developer may override the default backdrop behavior using the `hasBackdrop` Input, so `over` mode will still have a backdrop unless the developer does `[hasBackdrop]="false"`.

^ That's right, Miles.

For accessibility, it doesn't make sense if you can interact with the mouse and not with the keyboard – or visa versa. We've had issue reports from developers that found focus trapping to be too aggressive when there is no backdrop (#https://github.com/angular/components/issues/26572).

**Comment by zarend** [comment]
Since this was last reviewed: fixed issue with showing backdrop when there are both a start and end sidenav. Add `_drawerHasBackdrop` method to simplify logic.
