### PR TITLE
fix(material/list): remove previously removed API

### LINKED ISSUE #26005: bug(List): MatSelectionListChange requires again a deprecated property
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

The options attribute was removed in v14 of Angular Material, but it seems like it has been added back in v15 even though it has been directly included in the documentation as a deprecated attribute. 

### Reproduction

Steps to reproduce:
1. Create a project with Angular Material 13 that uses the MatSelectionListChange class. Class requires 3 attributes: Source, Option and Options
2. Migrate the project to Angular Material 14: The Option attribute has been removed and code needs to be updated to get rid of it 
3. Migrate the project to Angular 15: The Option attribute is added back, and has again been included in the documentation directly as a deprecated attribute.

### Expected Behavior

I didn't expect the Option attribute to be part of MatSelectionListChange since it was already removed in v14

### Actual Behavior

The attribute is again present and required in v15

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Any

### PR DESCRIPTION
**Pull request by crisbeto**
In #21974 the `MatSelectionChange.option` property was removed, but we accidentally re-added it during the MDC switch. These changes re-remove the property.

Fixes #26005.

### CODE REVIEW

File: src/material/list/selection-list.ts [hunk 1]
```diff
@@ -46,12 +46,6 @@ export class MatSelectionListChange {
   constructor(
     /** Reference to the selection list that emitted the event. */
     public source: MatSelectionList,
-    /**
-     * Reference to the option that has been changed.
-     * @deprecated Use `options` instead, because some events may change more than one option.
-     * @breaking-change 12.0.0
-     */
-    public option: MatListOption,
```
Comment (crisbeto) [inline src/material/list/selection-list.ts:54]: Point for discussion: not sure whether this is a breaking change. Technically we already removed this a couple of major versions ago.

Comment (devversion) [reply src/material/list/selection-list.ts:54]: Yeah, I wasn't sure either (see issue comment). I would be good trying but at the same time we could just wait until next major.

**Review by devversion — APPROVED** [review]
LGTM (if we decide to not treat this as a breaking change).

File: src/material/list/selection-list.ts (hunk 1 above)
Comment (mmalerba) [reply src/material/list/selection-list.ts:54]: I think its ok to not treat as breaking. Nobody should be using it since it was already removed, and though it was accidentally briefly added back it _was_ still marked as deprecated.

**Review by mmalerba — APPROVED** [review]
