### PR TITLE
fix(drag-drop): unable to start dragging in list if dragged item is destroyed

### LINKED ISSUE #18628: [DragDrop] Model & view update during drag breaks drag & drop
Reproduction scenario is trivial. This can happen in muli-user environments where data updates are pushed and merged live.

#### Reproduction
https://stackblitz.com/edit/components-issue-crtxst?file=src%2Fapp%2Fexample-component.html

1. Open repro - there are 4 buttons,
2. Wait 3 seconds - there are 2 different buttons. They can be dragged,
3. Now refresh the page, and as soon as it loads start dragging "Button 1". Hold it,
4. After 3 seconds model is updated, dragging is cancelled, and dragging is no longer possible.
 
On stackblitz, I don't see any errors logged. However, on my production app, I got something logged via Sentry that points to this transpiled piece of code in fesm2015/drag-drop.js:

```
1078                 (event) => {
1079                     if (!event || (event.target === this._preview && event.propertyName === 'transform')) {
1080                         this._preview.removeEventListener('transitionend', handler);
1081                         resolve();
1082                         clearTimeout(timeout);
1083                     }
1084                 }))));
```

with error being:
`TypeError: Cannot read property 'removeEventListener' of null`

 
#### Expected Behavior
Dragging should be possible with new items

#### Actual Behavior
Dragging doesn't work until page is reloaded

#### Environment
- Angular: 9.0.2
- CDK/Material: 9.0.1
- Browser(s): Chrome 80
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

### PR DESCRIPTION
**Pull request by crisbeto**
We currently have some logic which cleans up the dragging state if the dragged item is destroyed, but nothing notifies the parent drop list which leaves it in the dragging state. Next time the user tries to drag, they won't be able to, because the list still thinks that its dragging. These changes add some logic to abort the dragging if the dragged item is removed from the list.

Fixes #18628.

### CODE REVIEW

File: src/cdk/drag-drop/drop-list-ref.ts [hunk 1]
```diff
@@ -367,11 +367,20 @@ export class DropListRef<T = any> {
...
     this._draggables = items;
     items.forEach(item => item._withDropContainer(this));
 
     if (this.isDragging()) {
-      this._cacheItems();
+      const draggedItems = previousItems.filter(item => item.isDragging());
+
+      // If all of the items being dragged were removed
+      // from the list, abort the current drag sequence.
+      if (draggedItems.every(item => items.indexOf(item) === -1)) {
```
Comment (mmalerba) [inline src/cdk/drag-drop/drop-list-ref.ts:379]: won't this still have an issue if only some of the items have been destroyed?

Comment (crisbeto) [reply src/cdk/drag-drop/drop-list-ref.ts:379]: The problem here is that nothing ever tells the list that dragging has stopped. If only part of the dragged items are destroyed mid-drag, there should be at least one left to notify the list once it's dropped.

Comment (mmalerba) [reply src/cdk/drag-drop/drop-list-ref.ts:379]: Ah ok, I misunderstood. I thought the issue was with trying to attach items that had been destroyed
