### PR TITLE
fix(material/checkbox): focus not moved to input when clicking on touch target

### LINKED ISSUE #26486: bug(checkbox): no persistent focus indicator if clicked on outer touch target padding
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

 no persistent focus indicator if clicked on outer touch target padding... leading to non convenient keyboard (tab / shift+tab) controls.

checkbox-indicator

### Reproduction

Steps to reproduce:
1. https://material.angular.io/components/checkbox/overview
2. click on the outer edges vs click on the center

### Expected Behavior

1. remaining focus indicator is set.
or
2. edges should not be clickable/no hover focus/no cursor.

### Actual Behavior

 no persistent focus indicator if clicked on outer touch target padding... leading to non convenient keyboard (tab / shift+tab) controls.

### Environment

- Angular: 15.1.1
- CDK/Material: 15.1.1
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): all

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that while we were toggling the checked state of a checkbox when its touch target is clicked, we weren't moving focus to the internal `input`.

Fixes #26486.

### CODE REVIEW

File: src/material/checkbox/checkbox.ts [hunk 1]
```diff
@@ -380,6 +380,9 @@ export abstract class _MatCheckboxBase<E>
         });
       }
 
+      // Normally the input should be focused already, but if the click comes from something
+      // like the touch target, then we might have to focus it ourselves.
+      // this._inputElement.nativeElement.focus();
```
Comment (Totati) [inline src/material/checkbox/checkbox.ts:385]: It seems you have just added comments.

Comment (crisbeto) [reply src/material/checkbox/checkbox.ts]: ops, thanks for flagging it. I was in a rush and forgot to re-enable the fix.

**Review by devversion — APPROVED** [review]
