### PR TITLE
fix(material/input): Number input not changing on wheel interaction

### LINKED ISSUE #29074: bug(COMPONENT): Unexpected Behavior with Number Input and MatTooltip Scrolling
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

In Angular Material, when a with matInput is used, the expected behavior is that scrolling over this input field scrolls the page. However, if I hover over any element with MatTooltip, then focus back on the number input field, the scrolling behavior unexpectedly changes. Instead of scrolling the page, it increments or decrements the number in the input. This issue can also occur on the Angular Material official [website](https://v11.material.angular.io/components/tooltip/overview).

image

This is not the expected behavior : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

### Reproduction

StackBlitz link: https://stackblitz.com/angular/porobbapdry?file=src%2Fapp%2Ftooltip-delay-example.ts
Steps to reproduce:
1. Navigate to a page with a with matInput.
2. Hover over an element with MatTooltip.
3. Focus on the number input field.
4. Try scrolling over the number input field.

### Expected Behavior

The expected and consistent user experience is that scrolling over a number input field should scroll the page, not change the input's value. This unexpected behavior disrupts the user experience, especially in forms with tooltips and number inputs.

### Actual Behavior

When a field with matInput is focused, and the user scrolls with the mouse wheel, the default behavior is for the page itself to scroll, not the number in the input field. However, this behavior changes after interacting with an element that has MatTooltip. Specifically, after hovering over a MatTooltip element and then focusing on the number input field, scrolling with the mouse wheel no longer scrolls the page. Instead, it changes the value in the number input field, incrementing or decrementing it. This is inconsistent with the expected behavior and occurs even on the Angular Material official website.

### Environment

- Angular: 16
- CDK/Material: 16
- Browser(s): Chrome
- Operating System Windows + macOS + ArchLinux

### PR DESCRIPTION
**Pull request by ChristophWieske**
In blink and webkit browsers the default behavior of increasing or decreasing a focused number input on wheel events is broken until a wheel event listener is explicitly added.

Fixes #29074

### CODE REVIEW

**Comment by ChristophWieske** [comment]
Tried to add a test as well, but wasn´t able to trigger the inputs default wheel behavior with dispatched events. I assume it only works with trusted events.

Added a section to the dev app that shows the scenario that triggered the issue (number input + tooltip).

File: src/material/input/input.ts [hunk 1]
```diff
@@ -197,6 +198,25 @@ export class MatInput
     if (!this._isTextarea && getSupportedInputTypes().has(this._type)) {
       (this._elementRef.nativeElement as HTMLInputElement).type = this._type;
     }
+
+    // In blink and webkit browsers a focused number input does not increment or decrement the value
+    // on mouse wheel interaction unless a wheel event listener is attached to it or one of its ancestors or a passive wheel listener is attached somewhere in the DOM.
+    // For example: Hitting a tooltip once enables the mouse wheel input for all number inputs as long as it exists.
+    // In order to get reliable and intuitive behavior we apply a wheel event on our own
+    // thus making sure increment and decrement by mouse wheel works every time.
+    if (
```
Comment (crisbeto) [inline src/material/input/input.ts:207]: Consider moving this out into a private method since the setter is getting pretty big.

File: src/material/input/input.ts [hunk 2]
```diff
@@ -197,6 +198,25 @@ export class MatInput
...
+      !this._webkitBlinkWheelListenerAttached &&
+      this._type === 'number' &&
+      (this._platform.BLINK || this._platform.WEBKIT)
+    ) {
+      this._elementRef.nativeElement.addEventListener('wheel', this._WebkitBlinkWheelListener);
```
Comment (crisbeto) [inline src/material/input/input.ts:212]: Should we bind this outside the `NgZone`?

File: src/material/input/input.ts [hunk 3]
```diff
@@ -527,4 +551,10 @@ export class MatInput
       el.setSelectionRange(0, 0);
     }
   };
+
+  private _WebkitBlinkWheelListener = (): void => {
```
Comment (crisbeto) [inline src/material/input/input.ts:555]: The naming of this will likely trigger a lint warning.

**Comment by ChristophWieske** [comment]
@crisbeto I applied your feedback and fixed linter errors. Have a look.

**Review by crisbeto — APPROVED** [review]

**Review by crisbeto — APPROVED** [review]
