### PR TITLE
fix(material/slider): make value non-nullable

### LINKED ISSUE #22444: Make slider value non-nullable
#### Documentation Feedback

The linked docs give the type of `value` as `number | null` but the overview never describes a state when the value can actually be `null`.  They say "The initial value is set to the minimum value unless otherwise specified".

If the value actually can be `null`, an example of this should be provided.  If the value is never `null` (which seems to make more sense?) then the API should be updated so that `value` is simply `number`.

**Affected documentation page:** https://material.angular.io/components/slider/api

### PR DESCRIPTION
**Pull request by crisbeto**
Makes the value of the slider a `number`, rather than `number | null` in order to make it easier to use.

Fixes #22444.

### CODE REVIEW

File: src/material/slider/slider.ts [hunk 1]
```diff
@@ -233,16 +228,16 @@ export class MatSlider extends _MatSliderBase
...
   /** Value of the slider. */
   @Input()
-  get value(): number | null {
+  get value(): number {
     // If the value needs to be read and it is still uninitialized, initialize it to the min.
     if (this._value === null) {
       this.value = this._min;
     }
-    return this._value;
+    return this._value || 0;
```
Comment (wagnermaciel) [inline src/material/slider/slider.ts:236]: If 0 is not in the range of the min and max, won't this cause errors? E.g. for a slider with `min: -200` and `max: -100`

Comment (crisbeto) [reply src/material/slider/slider.ts:236]: We have some tests that seems like they allow cases like that. The `|| 0` here is necessary, because TS can't infer that the `_value` is guaranteed to be a number due to the `this.value = this._min;` above. I'll change it to a type cast instead.

**Review by wagnermaciel — APPROVED** [review]
LGTM
