### PR TITLE
fix(material/schematics): combine style resets

### LINKED ISSUE #32495: bug(setup): duplicate margin and font-family
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

19

### Description

when you add material to a new project, it duplicates the font-family and margin because it generate both the old and new rules

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. in a new angular project run `ng add @angular/material`
2. select any of the predefined theme

### Expected Behavior

to only have

```
body {
  color-scheme: light;
  background-color: var(--mat-sys-surface);
  color: var(--mat-sys-on-surface);
  font: var(--mat-sys-body-medium);

  // Reset the user agent margin.
  margin: 0;
}
```
added to the sttyles.scss

### Actual Behavior

it also generated
```
body {
  margin: 0;
  font-family: Roboto, 'Helvetica Neue', sans-serif;
}
```
which is unused

### Environment

Angular CLI       : 21.0.2
Angular           : 21.0.3
Node.js           : 22.14.0
Package Manager   : npm 10.9.2
Operating System  : win32 x64

┌───────────────────────────┬───────────────────┬───────────────────┐
│ Package                   │ Installed Version │ Requested Version │
├───────────────────────────┼───────────────────┼───────────────────┤
│ @angular/build            │ 21.0.2            │ ^21.0.2           │
│ @angular/cdk              │ 21.0.2            │ ^21.0.2           │
│ @angular/cli              │ 21.0.2            │ ^21.0.2           │
│ @angular/common           │ 21.0.3            │ ^21.0.0           │
│ @angular/compiler         │ 21.0.3            │ ^21.0.0           │
│ @angular/compiler-cli     │ 21.0.3            │ ^21.0.0           │
│ @angular/core             │ 21.0.3            │ ^21.0.0           │
│ @angular/forms            │ 21.0.3            │ ^21.0.0           │
│ @angular/material         │ 21.0.2            │ ^21.0.2           │
│ @angular/platform-browser │ 21.0.3            │ ^21.0.0           │
│ @angular/platform-server  │ 21.0.3            │ ^21.0.0           │
│ @angular/router           │ 21.0.3            │ ^21.0.0           │
│ @angular/ssr              │ 21.0.2            │ ^21.0.2           │
│ rxjs                      │ 7.8.2             │ ~7.8.0            │
│ typescript                │ 5.9.3             │ ~5.9.2            │
│ vitest                    │ 4.0.15            │ ^4.0.8            │
└───────────────────────────┴───────────────────┴───────────────────┘

### PR DESCRIPTION
**Pull request by crisbeto**
Prior to #31522 we had two places with style resets, because the user could either use a custom theme or one of the pre-built ones. After the change all themes are "custom" so we don't need the extra branch in the logic.

These changes combine the style resets into the theme and remove the wording around "custom" from the code.

Fixes #32495.

### CODE REVIEW

File: src/material/schematics/ng-add/theming/theming.ts [hunk 1]
```diff
@@ -69,16 +69,16 @@ async function insertCustomTheme(
...
     // Normalize the path through the devkit utilities because we want to avoid having
     // unnecessary path segments and windows backslash delimiters.
-    const customThemePath = normalize(join(project.sourceRoot, defaultCustomThemeFilename));
+    const themePath = normalize(join(project.sourceRoot, defaultThemeFilename));
 
-    if (host.exists(customThemePath)) {
-      logger.warn(`Cannot create a custom Angular Material theme because
-          ${customThemePath} already exists. Skipping theme generation.`);
+    if (host.exists(themePath)) {
+      logger.warn(`Cannot create a Angular Material theme because
```
Comment (tjshiu) [inline src/material/schematics/ng-add/theming/theming.ts]: nit: 
```suggestion
      logger.warn(`Cannot create an Angular Material theme because
```

File: src/material/schematics/ng-add/theming/create-theme.ts [hunk 2]
```diff
@@ -6,9 +6,9 @@
  * found in the LICENSE file at https://angular.dev/license
  */
 
-/** Create custom theme for the given application configuration. */
-export function createCustomTheme(userPaletteChoice: string): string {
-  const colorPalettes = new Map<string, {primary: string; tertiary: string}>([
```
Comment (tjshiu) [inline src/material/schematics/ng-add/theming/create-theme.ts:11]: Do we wanna keep these types ? I don't understand why remove them?

Comment (crisbeto) [reply src/material/schematics/ng-add/theming/create-theme.ts:11]: TS can easily infer them from the constructor so we don't need to specify them.

**Comment by crisbeto** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: a364de5d01c46fe94bd44813b0e584f4b80aa7bc
- 21.0.x: 454bf9608919e0c7807afd4010551d05e1776637
