### PR TITLE
docs(tree): fix example that shows empty checklists as selected

### LINKED ISSUE #20085: bug(MatTreeModule): Tree with checkboxes example - Reversed checkbox selected values when node has no child
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Open Tree with checkboxes on StackBlitz https://stackblitz.com/angular/krgkldbxvgb?file=src%2Fapp%2Ftree-checklist-example.ts
2. Add  example: {}  to const TREE_DATA 
 
#### Expected Behavior

What behavior were you expecting to see?

The added node this.checklistSelection should be selected when the node is selected and should show not selected when the node is not selected.

#### Actual Behavior

What behavior did you actually see?

For the added node the selection values are reversed.
#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

### PR DESCRIPTION
**Pull request by crisbeto**
We determine whether a node is selected in the checklist example using `Array.prototype.every`, but the problem is that `every` returns true for empty arrays which looks weird in our example.

Fixes #20085.

### CODE REVIEW

File: src/components-examples/material/tree/tree-checklist/tree-checklist-example.ts [hunk 1]
```diff
@@ -171,9 +171,9 @@ export class TreeChecklistExample {
   /** Whether all the descendants of the node are selected. */
   descendantsAllSelected(node: TodoItemFlatNode): boolean {
     const descendants = this.treeControl.getDescendants(node);
-    const descAllSelected = descendants.every(child =>
-      this.checklistSelection.isSelected(child)
-    );
+    const descAllSelected = descendants.length > 0 && descendants.every(child => {
+      return this.checklistSelection.isSelected(child);
```
Comment (mmalerba) [inline src/components-examples/material/tree/tree-checklist/tree-checklist-example.ts:175]: nit: why add the `{}` and `return`?

Comment (crisbeto) [reply src/components-examples/material/tree/tree-checklist/tree-checklist-example.ts:175]: I just find it more readable compared to the multi-line arrow function with an implicit return.

Comment (mmalerba) [reply src/components-examples/material/tree/tree-checklist/tree-checklist-example.ts:175]: I prefer the implicit return, but I don't think we have an official style on way or the other
