### PR TITLE
fix(chips/testing): exclude icons from getText result

### LINKED ISSUE #20503: bug(MatChipHarness): Chip Text contains "cancel"
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Create a chip list with cancel buttons, as in autocomplete example https://stackblitz.com/angular/lmgdmgnkkxbb?file=src%2Fapp%2Fchips-autocomplete-example.ts
2. Get MatChipListHarness, call "getChips()" on it and then "getText()" on one of the chip harnesses.
 
 
#### Expected Behavior

What behavior were you expecting to see?

Text of chip includes only the label, e.g. "Lemon".

#### Actual Behavior

What behavior did you actually see?

Text of chip includes "cancel" text from within the mat-icon as well, e.g. "Lemoncancel".

#### Environment

- Angular: 10.1.0
- CDK/Material: 10.2.0
- Browser(s): Chrome 85 
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

### PR DESCRIPTION
**Pull request by crisbeto**
Excludes the text of icons from the result of the `getText` method.

Fixes #20503.

### CODE REVIEW

**Review by devversion — APPROVED** [review]
Nice! LGTM

File: src/material/chips/testing/chip-harness.ts [hunk 1]
```diff
@@ -31,7 +31,7 @@ export class MatChipHarness extends ComponentHarness {
 
   /** Gets the text of the chip. */
   async getText(): Promise<string> {
-    return (await this.host()).text();
+    return (await this.host()).text({exclude: '.mat-chip-avatar, .mat-chip-trailing-icon'});
```
Comment (mischkl) [inline src/material/chips/testing/chip-harness.ts:34]: Should also exclude `'.mat-icon'`

Comment (mmalerba) [reply src/material/chips/testing/chip-harness.ts:34]: @crisbeto do you know if we expect people to use mat-icon directly in mat-chip without marking it as an avatar or trailing icon?

Comment (crisbeto) [reply src/material/chips/testing/chip-harness.ts]: I believe that all our examples go through the avatar or the trailing icon directives. I've added `.mat-icon` to the selector anyway since it doesn't require any maintenance on our end.

**Review by mmalerba — APPROVED** [review]
LGTM

**Comment by mischkl** [comment]
Please also see https://github.com/angular/components/issues/20503#issuecomment-689007455 - the with() method may also need to be updated.

**Comment by crisbeto** [comment]
The `with` method goes through `MatChipHarness.getText` which will have the exclusion logic once this PR lands.
