### PR TITLE
fix(list): allow for list and list items to be disabled

### LINKED ISSUE #17574: mat-action-list missing disabled styles
See https://github.com/angular/components/issues/763#issuecomment-548873994

Disabling the items in `mat-action-list` does not apply a disabled style. This can be seen in our dev-app.

### PR DESCRIPTION
**Pull request by crisbeto**
Adds the ability to disable all variants of the list. Currently it's only the selection list that can be disabled.

Fixes #17574.

### CODE REVIEW

File: src/material/list/list.ts [hunk 1]
```diff
@@ -160,6 +167,8 @@ export class MatListSubheaderCssMatStyler {}
   exportAs: 'matListItem',
   host: {
     'class': 'mat-list-item',
+    '[class.mat-list-item-disabled]': 'disabled',
+    '[attr.aria-disabled]': 'disabled',
```
Comment (crisbeto) [inline src/material/list/list.ts]: Not completely sure whether we want this. I added it because the list items can also be links.

File: src/material/list/list.ts [hunk 2]
```diff
@@ -204,6 +213,14 @@ export class MatListItem extends _MatListItemMixinBase implements AfterContentIn
     }
   }
 
+  /** Whether the option is disabled. */
+  @Input()
+  get disabled() { return this._disabled || !!(this._list && this._list.disabled); }
```
Comment (devversion) [inline src/material/list/list.ts]: Should we limit this to list-items inside a nav-list or action-list? For standard text list-items the term `option` (as in the JSDoc) seems incorrect and disabling seems weird too.

This is what Jeremy wrote in the past: https://github.com/angular/components/pull/3624#issuecomment-301623063 and this would match my expectation that we only allow disabled for such list items. Not sure how can we achieve this, but at least by mentioning it in the jsdoc, or by throwing if this changes for standard list items?

Comment (crisbeto) [reply src/material/list/list.ts]: It's mostly a visual thing anyway so there shouldn't be any harm if somebody ends up doing it for a plain list. Having it be limited to nav/action lists would mean to create dedicated components for those lists or throwing in the setter here which seems unnecessary.

Comment (devversion) [reply src/material/list/list.ts]: Yeah I never proposed that we should have separate components for items of either nav-list, action-list or standard list. Though I don't see anything wrong with throwing. I don't feel strong about it either. At least though I'd expect that we make it clear in the JSDoc. `"option"` seems to be ambiguous and not clear in the context of a list-item.

File: src/material/list/list.scss [hunk 3]
```diff
@@ -300,6 +300,10 @@ mat-action-list {
   outline: none;
 }
 
+.mat-list-item-disabled {
+  pointer-events: none;
```
Comment (jelbourn) [inline src/material/list/list.scss]: This would also disable tooltips, I think we'd want to avoid

File: src/material/list/list.ts (hunk 1 above)
Comment (jelbourn) [reply src/material/list/list.ts]: It would be invalid to put `aria-disabled` on something that doesn't have a role (implicit or explicit), so we should probably want to at least avoid applying an invalid state

File: src/material/list/list.scss (hunk 3 above)
Comment (crisbeto) [reply src/material/list/list.scss]: How would we prevent clicking on it though? We've done something similar to support disabled tabs in the tab nav bar.

**Comment by crisbeto** [comment]
Sorry for the delayed response @jelbourn, I must've missed the notification. The feedback has been addressed, can you take another look. As for the contrast ratio on disabled items, I haven't checked it but it's the same as what we have in master for selection lists.

File: src/material/list/list.scss (hunk 3 above)
Comment (jelbourn) [reply src/material/list/list.scss]: Yeah, the tabs thing is why I thought about this (someone mentioned it in a bug). I don't know of another way to do this other than `preventDefault` / `stopPropagation`

Comment (crisbeto) [reply src/material/list/list.scss]: We can't rely on `preventDefault`/`stopPropagation`, because we don't have a way of ensuring that our event listeners are invoked before the user's.

**Comment by Ammonix** [comment]
when will this get merged?
