### PR TITLE
fix(material/badge): insert inline description for non-interactive hosts

### LINKED ISSUE #26190: feat(badge): a badge with some meaningful information should not have the aria-hidden=true attribute
### For accessibility purposes,

When you have a badge which communicates some meaningful information such as a number or something else, it should not have the aria-hidden=true attribute

So is it possible to create in the API a new "matBadgeAriaHidden" directive to set it manually according to the relevance of the badge content?

### Use Case

_No response_

### PR DESCRIPTION
**Pull request by jelbourn**
The badge current applies `aria-describedby` to surface the developer-provided description. However, assistive technology generally doesn't read these description on non-interactive elements. So, we can take advantage of our handy `InteractivityChecker` and do something different if the host is not focusable; we add the description inline as the next sibling with `.cdk-visually-hidden`.

Fixes #26190

### CODE REVIEW

File: src/material/badge/badge.ts [hunk 1]
```diff
@@ -238,15 +254,37 @@ export class MatBadge extends _MatBadgeBase implements OnInit, OnDestroy, CanDis
       this._badgeElement.textContent = newContentNormalized;
     }
 
+    if (!this._isHostInteractive()) {
+      if (!this._inlineBadgeDescription) {
+        this._inlineBadgeDescription = this._renderer.createElement('span') as HTMLSpanElement;
```
Comment (crisbeto) [inline src/material/badge/badge.ts:259]: We don't need to go through the renderer for this. The badge uses the renderer so view encapsulation works correctly, but this element doesn't need it.

File: src/material/badge/badge.ts [hunk 2]
```diff
@@ -238,15 +254,37 @@ export class MatBadge extends _MatBadgeBase implements OnInit, OnDestroy, CanDis
...
+        this._inlineBadgeDescription.classList.add('cdk-visually-hidden');
+      }
+      this._inlineBadgeDescription.textContent = this.description;
+
+      const host = this._elementRef.nativeElement;
+      host.parentElement?.insertBefore(this._inlineBadgeDescription, host.nextSibling);
```
Comment (crisbeto) [inline src/material/badge/badge.ts:265]: I think the `nextSibling` here can be undefined.

File: src/material/badge/badge.ts [hunk 3]
```diff
@@ -238,15 +254,37 @@ export class MatBadge extends _MatBadgeBase implements OnInit, OnDestroy, CanDis
       this._badgeElement.textContent = newContentNormalized;
     }
 
+    if (!this._isHostInteractive()) {
```
Comment (crisbeto) [inline src/material/badge/badge.ts:257]: This fires in `ngOnInit` and whenever the content changes. Isn't it possible for the element to become non-interactive between those two, e.g. if it's on a button that becomes disabled.

File: src/material/badge/badge.ts [hunk 4]
```diff
@@ -129,9 +130,15 @@ export class MatBadge extends _MatBadgeBase implements OnInit, OnDestroy, CanDis
   /** Visible badge element. */
   private _badgeElement: HTMLElement | undefined;
 
+  /** Inline badge description. Used when the badge is applied to non-interactive host elements. */
+  private _inlineBadgeDescription: HTMLElement | undefined;
```
Comment (crisbeto) [inline src/material/badge/badge.ts:134]: The badge itself is already an inline element in the host element, but it has an `aria-hidden`. Couldn't we get the same result by removing the `aria-hidden` in non-interactive hosts?

File: src/material/badge/badge.ts (hunk 2 above)
Comment (crisbeto) [inline src/material/badge/badge.ts:265]: Does this have to be a sibling of the badge? Maybe we can add the element inside the badge?

File: src/material/badge/badge.ts [hunk 5]
```diff
@@ -242,12 +258,46 @@ export class MatBadge extends _MatBadgeBase implements OnInit, OnDestroy, CanDis
...
+      this._ariaDescriber.describe(this._elementRef.nativeElement, newDescription);
+    } else {
+      this._updateInlineDescription();
+    }
+  }
+
+  private _updateInlineDescription() {
+    // Create the inline description element if it doesn't exist
+    if (!this._inlineBadgeDescription) {
+      this._inlineBadgeDescription = document.createElement('span');
```
Comment (crisbeto) [inline src/material/badge/badge.ts:290]: We should use the document from the `DOCUMENT` token since it accounts for SSR.

Comment (jelbourn) [reply src/material/badge/badge.ts]: Done

**Review by crisbeto — APPROVED** [review]
LGTM
