### PR TITLE
fix(drag-drop): fix drag start delay behavior to allow scrolling (#16224)

### LINKED ISSUE #16224: drag-drop: Drag delay does not allow scrolling on mobile devices
#### Reproduction

StackBlitz: https://angular-wls93x.stackblitz.io

Steps to reproduce:
1. Create a draggable element with a start delay (cdkDragStartDelay) of 1 second
2. Try scrolling by pressing on the draggable element as the start point and dragging immediately
 

#### Expected Behavior

Since the drag start delay was not elapsed when the scroll intention, I was expecting 
1. The drag to be cancelled
2. To be able to scroll

#### Actual Behavior

1. I was not able to scroll
2. The drag element was teleported to my finger after the delay was elapsed (one second)

#### Environment

- Angular:  8.0.1
- CDK/Material: 8.0.0
- Browser(s): Chrome (74.0.3729.169)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by Aboisier**
The current implementation of the drag start delay does not allow scrolling on mobile devices.
Instead, the draggable element gets teleported to the cursor once the delay is elapsed.

In order to handle this use case, we cancel the drag sequence if the cursor moves before
the drag start delay is elapsed and we disable native drag interactions only when the
drag sequence is started instead of when it is initialized.

The drag start delay was also integrated to the drag drop demo.

Fixes #16224

### CODE REVIEW

**Comment by Aboisier** [comment]
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here (e.g. `I signed it!`) and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google.com/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fangular%2Fcomponents%2Fpull%2F16228) for more info**.

I signed it!

**Comment by Aboisier** [comment]
Hey, @crisbeto ! I don't mean to be bothersome or anything, I noticed most PRs get reviewed within a few day. Since it's been almost two weeks since I created this PR, I was wondering if it fell between the cracks or if it was normal for outside contributions to take a bit longer. 

Thanks a lot!

File: src/cdk/drag-drop/drag-ref.ts [hunk 1]
```diff
@@ -504,12 +504,18 @@ export class DragRef<T = any> {
       const distanceX = Math.abs(pointerPosition.x - this._pickupPositionOnPage.x);
       const distanceY = Math.abs(pointerPosition.y - this._pickupPositionOnPage.y);
       const isOverThreshold = distanceX + distanceY >= this._config.dragStartThreshold;
+      const isDelayElapsed = (Date.now() >= this._dragStartTime + (this.dragStartDelay || 0));
```
Comment (crisbeto) [inline src/cdk/drag-drop/drag-ref.ts]: You don't need the parentheses around the entire expression here.

File: src/cdk/drag-drop/drag-ref.ts [hunk 2]
```diff
@@ -504,12 +504,18 @@ export class DragRef<T = any> {
...
 
       // Only start dragging after the user has moved more than the minimum distance in either
       // direction. Note that this is preferrable over doing something like `skip(minimumDistance)`
       // in the `pointerMove` subscription, because we're not guaranteed to have one move event
       // per pixel of movement (e.g. if the user moves their pointer quickly).
-      if (isOverThreshold && (Date.now() >= this._dragStartTime + (this.dragStartDelay || 0))) {
+      if (isOverThreshold) {
+        if (!isDelayElapsed) {
```
Comment (crisbeto) [inline src/cdk/drag-drop/drag-ref.ts]: If I'm following it correctly, it seems like we'll keep starting and ending dragging sequences until the delay has elapsed. Don't we want to not start the sequence in the first place? This feels like it could lead some issues like events being dispatched when they shouldn't be.

File: src/cdk/drag-drop/directives/drag.spec.ts [hunk 3]
```diff
@@ -798,22 +847,17 @@ describe('CdkDrag', () => {
       let currentTime = 0;
 
       const fixture = createComponent(StandaloneDraggable);
-      fixture.componentInstance.dragStartDelay = '1000';
+      fixture.componentInstance.dragStartDelay = '500';
```
[the remark this answers is not in the document]
Comment (Aboisier) [reply src/cdk/drag-drop/directives/drag.spec.ts]: The test used to:
1. Click (T 0)
2. Move the mouse (T 750)
3. Expect that the element did not move (T 750)
4. Move the mouse again (T 1250)
5. Expect the object to have moved (T 1250)

The test does not reflect the new behaviour I am suggesting. The first mouse move, because it is performed before the drag start delay, now cancels the drag sequence. The moving before the delay is elapsed is tested [here](https://github.com/angular/components/pull/16228/files#diff-fcb7ef452d47367765744a0eb1e4676bR775). This test ensures that moving after the delay is elapsed moves the element.

File: src/cdk/drag-drop/directives/drag.spec.ts [hunk 4]
```diff
@@ -596,18 +596,28 @@ describe('CdkDrag', () => {
       expect(dragElement.style.transform).toBeFalsy();
     }));
 
-    it('should enable native drag interactions if dragging is disabled', fakeAsync(() => {
+    it('should enable native drag interactions if not dragging', fakeAsync(() => {
```
[the remark this answers is not in the document]
Comment (Aboisier) [reply src/cdk/drag-drop/directives/drag.spec.ts]: That makes sense! I'll add it back. I foresee only one small difference in the test; the `webkitUserDrag` will now be falsy by default.

File: src/cdk/drag-drop/drag-ref.ts (hunk 2 above)
Comment (Aboisier) [reply src/cdk/drag-drop/drag-ref.ts]: If the pointer moves before the drag start delay has elapsed, then the drag sequence is ended. Since ending the sequence removes the subscription to `pointermove`, this method won't be called until the user releases the click and initializes a new sequence. This means the sequence will not be started/ended a bunch of times. At least, that's my understanding. I might be missing something here!

File: src/dev-app/drag-drop/drag-drop-demo.html [hunk 5]
```diff
@@ -69,3 +69,11 @@ <h2>Axis locking</h2>
     </mat-select>
   </mat-form-field>
 </div>
+
+<div>
+  <h2>Drag start delay</h2>
+
+  <mat-form-field>
+    <input matInput placeholder="Drag start delay" value="100" [(ngModel)]="dragStartDelay">
```
Comment (crisbeto) [inline src/dev-app/drag-drop/drag-drop-demo.html]: Can we leave this at 0 so it matches the default?

File: src/dev-app/drag-drop/drag-drop-demo.ts [hunk 6]
```diff
@@ -21,6 +21,7 @@ import {CdkDragDrop, moveItemInArray, transferArrayItem} from '@angular/cdk/drag
 })
 export class DragAndDropDemo {
   axisLock: 'x' | 'y';
+  dragStartDelay: number = 0;
```
Comment (crisbeto) [inline src/dev-app/drag-drop/drag-drop-demo.ts]: You can omit the `: number` here. We're only explicit about it in the source code so that our doc generation tooling can pick it up.

**Comment by Aboisier** [comment]
Don't worry about it, thanks for the review! I believe I addressed all your comments. It seems like there's an issue with the build though. I assume it will be fixed by #16436 .
