### PR TITLE
fix(cdk/drag-drop): add generic parameter for item type in CdkDragDrop

### LINKED ISSUE #23208: feat(CdkDragDrop): Add type bounds for item in CdkDragDrop event
#### Feature Description

Currently, all events except `CdkDragDrop` have `item: CdkDrag<T>;`
`CdkDragDrop` has `item: CdkDrag;`

It would be nice to also add a type bound there.

#### Use Case

I had to modify my `CdkDrag` data type on my current project. It would have been nice if the code editor could pick the changes an highlight the places where I had to propagate the changes. Because of no type bounds, all my `item.data` variable had `any` type and thus it was harder to track.

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the `CdkDragDrop` event didn't have a way of typing the item.

Fixes #23208.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

File: src/cdk/drag-drop/drag-events.ts [hunk 1]
```diff
@@ -54,13 +54,13 @@ export interface CdkDragExit<T = any, I = T> {
...
 /** Event emitted when the user drops a draggable item inside a drop container. */
-export interface CdkDragDrop<T, O = T> {
+export interface CdkDragDrop<T, O = T, I = T> {
   /** Index of the item when it was picked up. */
   previousIndex: number;
   /** Current index of the item. */
   currentIndex: number;
   /** Item that is being dropped. */
-  item: CdkDrag;
+  item: CdkDrag<I>;
```
Comment (mmalerba) [inline src/cdk/drag-drop/drag-events.ts:63]: I think this has to be `target: major` because `item` as changed from `CdkDrag<any>` to `CdkDrag<I>` which can break people's code.

Comment (crisbeto) [reply src/cdk/drag-drop/drag-events.ts:63]: It's not worth going through the deprecation process for this. I'll default it to `any` instead,
