### PR TITLE
fix(cdk/collections): SelectionModel does not always respect the compareWith function

### LINKED ISSUE #25878: bug(selection-model): SelectionModel does not always respect the compareWith function
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

SelectionModel does not always respect the `compareWith` function.

The lines in SelectionModel where it goes wrong:

https://github.com/angular/components/blob/14.1.3/src/cdk/collections/selection-model.ts#L212
https://github.com/angular/components/blob/14.1.3/src/cdk/collections/selection-model.ts#L97

### Reproduction

https://stackblitz.com/edit/components-issue-8zah2s?file=src/app/example-component.ts

Steps to reproduce:
1. Set up a selection model with multiple selection and `compareWith` function.
2. Select an item.
3. Try to deselect the item but pass a copy of the original item.

### Expected Behavior

The item is deselected because it is equal to the original item according to the `compareWith` function.

### Actual Behavior

The item is not deselected because the current implementation uses `Set.delete` to remove the item.

### Environment

- Angular: 14.1.3
- CDK/Material: 14.1.3

### PR DESCRIPTION
**Pull request by FrenchTechLead**
Fixed bug in SelectionModel where compareWith function was not consistently respected in deselect method.

Fixes #25878

### CODE REVIEW

**Comment by FrenchTechLead** [comment]
@crisbeto @andrewseguin Could you please take a look at this PR? It addresses an issue within my company.

File: src/cdk/collections/selection-model.ts [hunk 1]
```diff
@@ -76,7 +76,17 @@ export class SelectionModel<T> {
    */
   deselect(...values: T[]): boolean | void {
     this._verifyValueAssignment(values);
-    values.forEach(value => this._unmarkSelected(value));
+    if (this.compareWith) {
+      values.forEach(v1 => {
+        this._selection.forEach(v2 => {
+          if (this.compareWith?.call(undefined, v1, v2)) {
```
Comment (crisbeto) [inline src/cdk/collections/selection-model.ts:82]: Shouldn't this logic already be covered inside `_unmarkSelected`? It goes through each value and checks it with `isSelected` which will take the `compareWith` function into account.

Comment (FrenchTechLead) [reply src/cdk/collections/selection-model.ts:82]: Yes, the isSelected does that, but the objective is to deselect by utilizing the actual reference, as the deselection process employs this._selection.delete(value) internally, which only works when the actual object reference is provided. (variable v2)

Comment (crisbeto) [reply src/cdk/collections/selection-model.ts:82]: I see. In that case I think that we should make the change in `_markSelected` and `_unmarkSelected`.

Comment (FrenchTechLead) [reply src/cdk/collections/selection-model.ts:82]: I got it, I can work on that on this PR.

Comment (FrenchTechLead) [reply src/cdk/collections/selection-model.ts]: It turns out that `_markSelected` does not need to be modified since it checks that a value isn't already selected before marking it selected. `if (!this.isSelected(value))`.

I created a private function `_getComparableValue` that could be reused (or even make public if there are some use-cases for it) in order to get a comparable selected value using the provided `compareWith` function.

File: src/cdk/collections/selection-model.ts [hunk 2]
```diff
@@ -238,6 +233,21 @@ export class SelectionModel<T> {
   private _hasQueuedChanges() {
     return !!(this._deselectedToEmit.length || this._selectedToEmit.length);
   }
+
+  /** Returns a value that is comparable to inputValue by applying compareWith function, returns the same inputValue otherwise. */
```
Comment (FrenchTechLead) [inline src/cdk/collections/selection-model.ts:237]: I end up creating the `_getConcreteValue` that returns  any comparable selected value, or returns the value passed as a parameter.
`_getConcreteValue` is called before selection / deselection.

File: src/cdk/collections/selection-model.ts (hunk 1 above)
Comment (FrenchTechLead) [reply src/cdk/collections/selection-model.ts]: I end up creating the `_getConcreteValue` that returns  any comparable selected value, or returns the value passed as a parameter.
`_getConcreteValue` is called before selection / deselection.

File: src/cdk/collections/selection-model.ts [hunk 3]
```diff
@@ -131,14 +131,7 @@ export class SelectionModel<T> {
...
   isSelected(value: T): boolean {
-    if (this.compareWith) {
-      for (const otherValue of this._selection) {
-        if (this.compareWith(otherValue, value)) {
-          return true;
-        }
-      }
-      return false;
-    }
+    value = this._getConcreteValue(value);
```
Comment (crisbeto) [inline src/cdk/collections/selection-model.ts:134]: Maybe just inline this into the `has` call given that it isn't used anywhere else.

File: src/cdk/collections/selection-model.ts [hunk 4]
```diff
@@ -238,6 +233,21 @@ export class SelectionModel<T> {
...
   }
+
+  /** Returns a value that is comparable to inputValue by applying compareWith function, returns the same inputValue otherwise. */
+  private _getConcreteValue(inputValue: T): T {
+    let concreteValue = inputValue;
+    if (!this.compareWith) {
+      return concreteValue;
+    } else {
+      this._selection.forEach(selectedValue => {
+        if (this.compareWith?.call(undefined, inputValue, selectedValue)) {
```
Comment (crisbeto) [inline src/cdk/collections/selection-model.ts:244]: The `?.` here is going to generate extra code. You can use `!.` since we know that it'll be defined.

File: src/cdk/collections/selection-model.ts [hunk 5]
```diff
@@ -238,6 +233,21 @@ export class SelectionModel<T> {
...
+          concreteValue = selectedValue;
```
Comment (crisbeto) [inline src/cdk/collections/selection-model.ts:245]: Don't we want to break here once we find the first match?

File: src/cdk/collections/selection-model.ts [hunk 6]
```diff
@@ -238,6 +233,21 @@ export class SelectionModel<T> {
...
+        }
+      });
+      return concreteValue;
```
Comment (crisbeto) [inline src/cdk/collections/selection-model.ts:248]: Wouldn't we want to return the `inputValue` if there is no match?

File: src/cdk/collections/selection.spec.ts [hunk 7]
```diff
@@ -279,4 +279,24 @@ describe('SelectionModel', () => {
     let singleSelectionModel = new SelectionModel();
     expect(singleSelectionModel.isMultipleSelection()).toBe(false);
   });
+
+  it('should deselect value if comparable to another one', () => {
+    type T = {key: number; value: string};
```
Comment (crisbeto) [inline src/cdk/collections/selection.spec.ts:284]: Instead of `T`, this should use a proper name like `Item`. We use `T` to name the generic params.

File: src/cdk/collections/selection-model.ts (hunk 3 above)
Comment (FrenchTechLead) [reply src/cdk/collections/selection-model.ts]: Yes, edited !

File: src/cdk/collections/selection-model.ts (hunk 4 above)
Comment (FrenchTechLead) [reply src/cdk/collections/selection-model.ts]: Thanks, i didn't know about the ! operator in js  (corrected).

File: src/cdk/collections/selection-model.ts (hunk 5 above)
Comment (FrenchTechLead) [reply src/cdk/collections/selection-model.ts:244]: Yep !

File: src/cdk/collections/selection-model.ts (hunk 6 above)
Comment (FrenchTechLead) [reply src/cdk/collections/selection-model.ts]: shouldn't change anything since we first assign `concreteValue  `to `inputValue `, edited for clarity.

File: src/cdk/collections/selection.spec.ts (hunk 7 above)
Comment (FrenchTechLead) [reply src/cdk/collections/selection.spec.ts]: Agree, corrected!

File: src/cdk/collections/selection-model.ts (hunk 6 above)
Comment (FrenchTechLead) [reply src/cdk/collections/selection-model.ts]: Ultimately, there is no need to create the `concreteValue` variable, we'll just `return` inside of the `for` loop in order to break it when there is a match.

**Review by crisbeto — APPROVED** [review]
LGTM
