### PR TITLE
fix(cdk/schematics): handle templates with byte order mark

### LINKED ISSUE #27057: mdc-migration gives "character is out of bounds" without any context
### Command

generate

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When I run:
ng generate @angular/material:mdc-migration

It asks me which directory and which components. No matter what I select, it shows the following right after:

Migrating components:
Migrating project: my-app
**Character is out of bounds**

No files get migrated. Nothing else happens. I don't know where I can look for the logs to see what exactly was out of bounds.

### Minimal Reproduction

ng generate @angular/material:mdc-migration

leave blank for default

press enter for just 'button'

### Exception or Error

```text
Character is out of bounds
```

### Your Environment

```text
Angular CLI: 16.0.0
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin arm64

Angular: 16.0.0
... animations, cdk, cdk-experimental, cli, common, compiler
... compiler-cli, core, forms, language-service, localize
... material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@nguniversal/builders           16.0.0
@nguniversal/common             16.0.0
@nguniversal/express-engine     16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      4.9.5
webpack                         4.46.0
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that migrations may throw a "Character out of bounds" error if a template is using BOM.

Fixes #27057.

### CODE REVIEW

**Review by andrewseguin — APPROVED** [review]

File: src/cdk/schematics/update-tool/component-resource-collector.ts [hunk 1]
```diff
@@ -155,7 +155,7 @@ export class ComponentResourceCollector {
           return;
         }
 
-        const fileContent = this._fileSystem.read(templatePath);
+        const fileContent = stripBom(this._fileSystem.read(templatePath) || '');
```
Comment (devversion) [inline src/cdk/schematics/update-tool/component-resource-collector.ts:158]: just fyi: need to be very careful here. It depends on the virtual tree and update recorder, whether they auto-insert the BOM offset or not. I just remember some issues there

**Review by devversion — APPROVED** [review]

File: src/cdk/schematics/update-tool/component-resource-collector.ts (hunk 1 above)
Comment (crisbeto) [reply src/cdk/schematics/update-tool/component-resource-collector.ts:158]: I figured it would be okay since it fixed the error and we've had that call for CSS files for a long time now.
