### PR TITLE
fix(material/input): inconsistently reading name from input with ngModel

### LINKED ISSUE #18624: MatInputHarness.getName() fails with MatInput and ngModel
#### Reproduction
I am trying to get the name of a `MatInput` control which is bound to a component property `name` as:
`<input matInput [name]="name" [(ngModel)]="model">`

I am using the `getName()` method of `MatInputHarness` as: 

```
const input = await loader.getHarness(MatInputHarness);
expect(await input.getName()).not.toBe('')
```

but the expectation fails. If I remove the `ngModel` directive, the test passes successfully.

https://stackblitz.com/edit/components-issue-atwks1
 
 
#### Expected Behavior

The test should pass

#### Actual Behavior

The test fails

#### Environment

- Angular: 9.0.2
- CDK/Material: 9.1.0
- Browser(s): 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by crisbeto**
If an input has a `name` binding and an `ngModel`, the input harness won't be able to read the name from the DOM, because `ngModel` doesn't proxy it. These changes add the proxy behavior to the `MatInput` directive, similarly to what we we're doing for `required`, `placeholder`, `readonly` etc.

Fixes #18624.

### CODE REVIEW

File: src/material/input/input.ts [hunk 1]
```diff
@@ -163,6 +164,12 @@ export class MatInput extends _MatInputMixinBase implements MatFormFieldControl<
    */
   @Input() placeholder: string;
 
+  /**
+   * Name of the input.
+   * @docs-private
+   */
+  @Input() name: string;
```
Comment (devversion) [inline src/material/input/input.ts:171]: Out of curiosity: Do you know why things like `readonly` are not docs-private, but this is?

Comment (crisbeto) [reply src/material/input/input.ts:171]: I don't know the context behind it. I saw that `id` and `placeholder` were `docs-private`.

Comment (mmalerba) [reply src/material/input/input.ts:171]: I don't have a strong opinion. I guess I'd vote for making them all not `@docs-private` so there's less ugly comments to look at - but thats not a great reason
