### PR TITLE
fix(form-field): incorrect assumptions about page direction

### LINKED ISSUE #17390: Mat-form  outline border
I noticed a small bug in outline border calcualtion:
this is an issue with setting a  **_previousDirection** variable in form-field.ts
1- the initial value is 'ltr', regardless if the page is originally loaded with 'rtl' layout.
2- in subscribtion of _dir.changes you call   
this.updateOutlineGap(); before setting the value in    
 this._previousDirection = this._dir.value;  
so the outlineGap calculated on the old value

my work around:
add style of mat-label to:
background-color: white;
padding:10px;

so no need to calculate outline gap.

please advice

### PR DESCRIPTION
**Pull request by crisbeto**
These changes undo the changes from #15415 because they were making incorrect assumptions about the page starting off as LTR, and they were calling `updateOutlineGap` with an outdated value for the direction. This is causing issues like #17390.

I'm not totally sure what was being fixed by these changes, because the test that was added didn't fail even if I reverted all of the changes. From what I can tell the problem #15415 was trying to solve was that the outline gap might be updated too early on a direction change, before the browser has had the chance to recalculate the layout. These changes switch to recalculating inside a `requestAnimationFrame` after direction changes, in order to give the browser enough time to recalculate.

Fixes #17390.

### CODE REVIEW

File: src/material/form-field/form-field.ts [hunk 1]
```diff
@@ -356,8 +347,13 @@ export class MatFormField extends _MatFormFieldMixinBase
 
     if (this._dir) {
       this._dir.change.pipe(takeUntil(this._destroyed)).subscribe(() => {
-        this.updateOutlineGap();
-        this._previousDirection = this._dir.value;
+        if (typeof requestAnimationFrame === 'function') {
+          this._ngZone.runOutsideAngular(() => {
```
Comment (mmalerba) [inline src/material/form-field/form-field.ts]: Shouldn't this whole `if-else` be wrapped in `runOutsideAngular`? Currently it looks like it runs in the zone if the browser doesn't support `requestAnimationFrame` and outside if it does

Comment (crisbeto) [reply src/material/form-field/form-field.ts]: `updateOutlineGap` doesn't do any zone-ey things, we only need to run `requestAnimationFrame` on the outside because it can trigger change detection otherwise.
