### PR TITLE
fix(cdk/menu): not closing when inside shadow DOM

### LINKED ISSUE #26107: bug(cdk Menu / Portal): Portal/Menu isAttached() not working in ShadowDOM
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When **CDK Menu** is placed in component inside **ShadowDom-encapsulated** component, the menu trigger _does_ open the menu, but _does not_ toggle it (when it's open then the click doesn't closes it).
I tracked the issue down through _cdk Menu -> overlayRef -> PortalOutlet -> isAttached()_

### Reproduction

Steps to reproduce:
1. Have ShadowDom component
2. Put Angular CDK Menu in this component
3. Try to toggle _cdkMenuTriggerFor_

### Expected Behavior

Should work same as when not in ShadowDom component.

### Actual Behavior

_cdkMenuTriggerFor_ inside ShadowDom doesn't toggle Menu.

Here is the stackblitz with reproducted bug:
**https://stackblitz.com/edit/angular-ivy-rq5d9a?file=src/app/app.module.ts**

Stackblitz is ng 14, but this bug is still there in **Angular 15**.

### Environment

- Angular: 15^
- CDK/Material: 15^

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the CDK menu wasn't closing on outside clicks when the trigger is inside the shadow DOM. The problem is that reading the `Event.target` doesn't work as expected in the shadow DOM and we have to go through a helper.

Fixes #26107.

### CODE REVIEW

File: src/cdk/menu/menu-trigger.ts [hunk 1]
```diff
@@ -191,20 +192,20 @@ export class CdkMenuTrigger extends CdkMenuTriggerBase implements OnDestroy {
...
-
     this._ngZone.runOutsideAngular(() => {
       fromEvent(this._elementRef.nativeElement, 'mouseenter')
         .pipe(
           filter(() => !this.menuStack.isEmpty() && !this.isOpen()),
           takeUntil(this.destroyed),
         )
         .subscribe(() => {
+          // Closes any sibling menu items and opens the menu associated with this trigger.
+          const toggleMenus = () =>
```
Comment (crisbeto) [inline src/cdk/menu/menu-trigger.ts:203]: Unrelated change, I just noticed that we can move this function closer to its call site.

**Review by devversion — APPROVED** [review]
