### PR TITLE
fix(form-field): outline gap not calculated in shadow dom

### LINKED ISSUE #17262: mat-form-field does not display outline label properly in ShadowDom
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

https://stackblitz.com/edit/angular-geqne7?file=app/form-field-appearance-example.ts

Steps to reproduce:
1. Go to https://stackblitz.com/edit/angular-geqne7?file=app/form-field-appearance-example.ts
2. Select the form field and see the outline label to be under the input outline

 
#### Expected Behavior

What behavior were you expecting to see?
The label should be on top of the input outline

This is because of the condition here:

https://github.com/angular/components/blob/master/src/material/form-field/form-field.ts#L532 in the method
```
updateOutlineGap() {
...
    if (!document.documentElement!.contains(this._elementRef.nativeElement)) {
      this._outlineGapCalculationNeededImmediately = true;
      return;
    }
...
}
```

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular: 8.2.1
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):  MacOS

### PR DESCRIPTION
**Pull request by crisbeto**
Currently we check whether the form field is inside the DOM using `documentElement.contains(formField)` so that we don't try to calculate the outline gap. The problem is that `contains` won't catch elements inside the shadow DOM. These changes rework the check to use `getRootNode` instead.

Fixes #17262.

### CODE REVIEW

File: src/material/form-field/form-field.ts [hunk 1]
```diff
@@ -582,4 +582,20 @@ export class MatFormField extends _MatFormFieldMixinBase
   private _getStartEnd(rect: ClientRect): number {
     return this._previousDirection === 'rtl' ? rect.right : rect.left;
   }
+
+  /** Checks whether the form field is attached to the DOM. */
+  private _isAttachedToDOM(): boolean {
```
Comment (mmalerba) [inline src/material/form-field/form-field.ts]: Do we currently use a similar pattern elsewhere in the library? If so might make sense to put as a utility in cdk or material/core

Comment (crisbeto) [reply src/material/form-field/form-field.ts]: I did a quick a search and it doesn't look like we do.
