### PR TITLE
fix(cdk/schematics): fix resolving modules in ng update

### LINKED ISSUE #21160: bug(cdk): DevkitFileSystem mistakenly assumes not a directory
Under some circumstances (I assume related to execution context), the `e instanceof PathIsDirectoryException` check in `DevkitFileSystem.exists` does not work. This causes the file/module resolution for the build tsconfig (`files: ['main.ts', 'polyfill.ts]`) to fail.

#### Reproduction

Unclear. Maybe run `ng update @angular/core @angular/cli` and `ng update @angular/cdk` separately?
 
 
#### Expected Behavior

The migrations include all files referenced in `main.ts`.

#### Actual Behavior

Only `main.ts` and `polyfill.ts` are resolved.

#### Environment

- Angular: 11.0.2
- CDK/Material: 11.0.1
- Browser(s): -
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

### PR DESCRIPTION
**Pull request by kyubisation**
Closes #21160

### CODE REVIEW

File: src/cdk/schematics/ng-update/devkit-file-system.ts [hunk 1]
```diff
@@ -46,10 +46,13 @@ export class DevkitFileSystem extends FileSystem {
...
     // directory exists. It throws a specific error though if a directory
     // is being read as a file. We use that to check if a directory exists.
+    // Depending on execution context, the instanceof check might not work,
+    // in which case we fall back to asserting exception class name.
     try {
       return this._tree.get(fileOrDirPath) !== null;
     } catch (e) {
-      if (e instanceof PathIsDirectoryException) {
+      if (e instanceof PathIsDirectoryException ||
+          e?.constructor?.name === 'PathIsDirectoryException') {
```
Comment (crisbeto) [inline src/cdk/schematics/ng-update/devkit-file-system.ts:55]: This feels a little hacky, but maybe we don't need the try/catch anymore? The comment says that, at the time of writing, there was no API to check whether a directory exists, but looking at the methods on `this._tree`, it has both `getDir` and `exists`.

Comment (kyubisation) [reply src/cdk/schematics/ng-update/devkit-file-system.ts:55]: I was uncertain, if this was due to internal restrictions.
I will investigate if this could simply be changed to exists.

**Comment by kyubisation** [comment]
@crisbeto The material schematics tests runs into a memory issue. I suspect this is due to the migration now correctly resolving all related files, but I cannot say for certain. Do you have an idea on how this could be fixed?

**Comment by crisbeto** [comment]
Even if it is resolving more files than before, we'd have to try really hard to get it to run out of memory. Could it be hitting an infinite loop somewhere? Also does this happen if you run the tests locally?

**Comment by kyubisation** [comment]
Yes, I'm trying to investigate it right now. I need to setup the bazel debugging...

**Comment by kyubisation** [comment]
I have currently narrowed it down to the material-imports.spec.ts and the hammer-migration-v9.spec.ts. I'm currently debugging it, to see what is happening.

**Comment by kyubisation** [comment]
Ok, the problem seems to be, that getDir in the HostTree treats a non-existent file path as a potential directory. This means getDir cannot be used to assert a path being a directory (and is also does not expose the isDirectory of its nested host).
I'll see if there is an alternative solution.

**Comment by kyubisation** [comment]
@crisbeto I have refactored the directory check to query, if the parent directory has the given directory as a subdir. Please have another look.

File: src/cdk/schematics/ng-update/devkit-file-system.ts [hunk 2]
```diff
@@ -77,4 +69,15 @@ export class DevkitFileSystem extends FileSystem {
     const {subdirs: directories, subfiles: files} = this._tree.getDir(dirPath);
     return {directories, files};
   }
+
+  private _isExistingDirectory(dirPath: Path) {
+    if (dirPath === NormalizedRoot) {
```
Comment (crisbeto) [inline src/cdk/schematics/ng-update/devkit-file-system.ts:74]: Is this supposed to be `instanceof NormalizedRoot` or is there something passing in the actual class?

**Review by crisbeto — COMMENTED** [review]
Thank you for reworking it, it's looking much better! One more comment and it should be good to go.

File: src/cdk/schematics/ng-update/devkit-file-system.ts (hunk 2 above)
Comment (kyubisation) [reply src/cdk/schematics/ng-update/devkit-file-system.ts:74]: This is to check if the given directory is root (NormalizedRoot = `/`). If it is root, we can just assume it exists.
If it is not root, the normal parent/child check happens.
Or did I misunderstand your question?

Comment (crisbeto) [reply src/cdk/schematics/ng-update/devkit-file-system.ts:74]: The part I'm confused by is that we're looking for a specific class here (`NormalizedRoot`) and I wasn't sure whether that's intentional. So you're saying that `NormalizedRoot` is a special value passed in only for the root directory?

Comment (kyubisation) [reply src/cdk/schematics/ng-update/devkit-file-system.ts:74]: Ah, I see
Yes, as in Path and NormalizedRoot are simply typed strings. Due to this the `===` comparison works, which I believe is intended by the Angular CLI Devkit.
https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/core/src/virtual-fs/path.ts#L49

**Review by crisbeto — APPROVED** [review]
LGTM and thank you for taking the time to get rid of our old workaround.

**Comment by kyubisation** [comment]
No problem, thank you for the quick response. 😃 
Do you think a release with this fix is possible this week or is that unlikely?
Depending on this we will wait for the release or try to provide a workaround internally in our company.

**Comment by crisbeto** [comment]
Since this is only schematics code, it can be merged in quicker, but I can't guarantee when it'll be released.

**Comment by kyubisation** [comment]
Ok, that's not a problem.
The workaround is to simply run `ng update package --migrateOnly --from=10 --to=11`, so we can live with that.

**Comment by kyubisation** [comment]
@crisbeto I tested this with a few real life projects from our company and discovered an additional problem. When projects import package.json, typescript checks potential entry points (e.g /package.json/package.json and /package.json/index.ts) which would result in a failure with getDir. To avoid this I added a check to verify that the parent "directory" is not an existing file.
