### PR TITLE
fix(material/button): cdk-focus classes not being applied

### LINKED ISSUE #25618: bug(Button): cdk-focus classes not being applied
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.1

### Description

Buttons do not have `.cdk-focused`, `.cdk-keyboard-focused`, nor `.cdk-mouse-focused` classes applied upon focus, as seen in the [demo](https://next.material.angular.io/components/button/overview). Considering that [previous button behavior](https://material.angular.io/components/button/overview) apply those classes upon focus, this does not seem to be intended behavior.

### Reproduction

Steps to reproduce:
1. Focus button with mouse or keyboard
2. Examine button element in DevTools

### Expected Behavior

Upon focusing button with mouse, it should have both `.cdk-focused` and `.cdk-mouse-focused` classes applied to it. Upon focusing button with keyboard, it should have both `.cdk-focused` and `.cdk-keyboard-focused` classes applied to it.

### Actual Behavior

Upon focusing button with mouse and keyboard, no `.cdk-focused-*` classes were applied.

### Environment

- Angular: 15.0.0-next.0
- CDK/Material: 15.0.0-next.0
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

### PR DESCRIPTION
**Pull request by kevinjihwanlee**
Fixes a bug in the Angular Material `button` component where cdk-focused, cdk-keyboard-focused, cdk-mouse-focused were not being applied upon respective focus. This is because there was no FocusManager set up with the MDC buttons like the legacy button did.

Fixes #25618

### CODE REVIEW

File: src/material/button/button-base.ts [hunk 1]
```diff
@@ -95,6 +103,7 @@ export class MatButtonBase
     elementRef: ElementRef,
     public _platform: Platform,
     public _ngZone: NgZone,
+    private _focusMonitor: FocusMonitor,
```
Comment (crisbeto) [inline src/material/button/button-base.ts:106]: You should use the new `inject` function to get the focus monitor. That way you can avoid all the constructor changes.

Comment (crisbeto) [inline src/material/button/button-base.ts:106]: Should we use the focus monitor styles for the focus styles?

Comment (kevinjihwanlee) [reply src/material/button/button-base.ts]: Great point - done.

Comment (kevinjihwanlee) [reply src/material/button/button-base.ts]: Are you referring to these styles here: https://github.com/angular/components/blob/main/src/material/legacy-button/_button-base.scss#L67 I believe that should be the only one for the button component. Visually I can't tell the difference between having those styles or not, but maybe they were included with the legacy button for a reason.

Comment (crisbeto) [reply src/material/button/button-base.ts]: Those are the focus styles for the legacy button. I was referring to these https://github.com/angular/components/blob/main/src/material/button/_button-theme-private.scss#L21.

Comment (kevinjihwanlee) [reply src/material/button/button-base.ts]: Got it, added `.cdk-focused` - would that suffice?

Comment (crisbeto) [reply src/material/button/button-base.ts]: I think that we should match the behavior of the old button where the focus indication is only shown for keyboard and programmatic focus. Also the `:focus` selector is now redundant and can be removed.

Comment (kevinjihwanlee) [reply src/material/button/button-base.ts]: Makes sense - done.

**Comment by crisbeto** [comment]
The code LGTM, but one of the CI checks is failing. You can run `yarn approve-api button` and commit the changed file to fix it.

File: src/material/button/_button-theme-private.scss [hunk 2]
```diff
@@ -18,8 +18,11 @@
     opacity: map.get($opacities, hover);
   }
 
-  &:focus .mat-mdc-button-persistent-ripple::before {
-    opacity: map.get($opacities, focus);
+  .cdk-program-focused,
```
Comment (crisbeto) [inline src/material/button/_button-theme-private.scss:21]: Ah actually these selectors should be prefixed with `&`, otherwise the button focus indication will show when it's inside of any focused element.

Comment (kevinjihwanlee) [reply src/material/button/_button-theme-private.scss]: Good catch - done.

**Review by crisbeto — APPROVED** [review]
LGTM
