### PR TITLE
fix(list): matching item not preselected if added after init

### LINKED ISSUE #16062: `MatSelectionList` should update option selection state when list of options changes
#### What is the expected behavior?
`MatSelectionList` should update option selection state when list of options changes

#### What is the current behavior?
If you change the list of options after the view has been initialised, `MatSelectionList` does not update the model of the new options to reflect that they are selected in the model.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-ptk4tc?file=app/app.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest StackBlitz template

#### Is there anything else we should know?
`MatSelectionList` should listen to `options.changes` on the `options` `QueryList`: https://github.com/angular/components/blob/fc0b971509d0ec0b4a227aa403c31a5f5b0e6f26/src/material/list/selection-list.ts#L323

This is how `MatSelect` works:
https://github.com/angular/components/blob/9eeb4b5aa0473c0815a73bfe3c2ed6164d86a3b3/src/material/select/select.ts#L550

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes a `mat-list-option` that is added after initialization not being selected, even if it matches the control value.

Fixes #16062.

### CODE REVIEW

File: src/material/list/selection-list.ts [hunk 1]
```diff
@@ -385,13 +386,22 @@ export class MatSelectionList extends _MatSelectionListMixinBase implements Focu
...
-      this._tempValues = null;
+    if (this._value) {
+      this._setOptionsFromValues(this._value);
     }
 
+    this.options.changes.pipe(takeUntil(this._destroyed)).subscribe(() => {
+      if (this._value) {
+        // Needs to be deferred, because we're changing bindings as the result of a query
+        // change which results in a "Changed after checked error".
+        Promise.resolve().then(() => {
```
Comment (jelbourn) [inline src/material/list/selection-list.ts]: Could the option deal with this itself? It will be able to read its parent's state without needing the extra change detection cycle

**Comment by crisbeto** [comment]
I've reworked it based on the feedback @jelbourn. It caused a couple of other things to get cleaned up as well.
