### PR TITLE
fix(material/tabs): allow for tablist aria-label and aria-labelledby to be set

### LINKED ISSUE #29486: feat(MatTab): MatTabGroup
### Feature Description

According to the [Tabs Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/), if the tab list has a visible label, the element with role tablist has `aria-labelledby` set to a value that refers to the labelling element. Otherwise, the tablist element has a label provided by `aria-label`.

MaTabGroup does not allow users to [provide an accessible label via `aria-label` or `aria-labelledby` for the element with role tablist](https://github.com/angular/components/blob/43c166c1efa882291140a0c958b8dbad4c0923fb/src/material/tabs/tab-header.html#L24).

### Use Case

Users of this component can provide a label through either `aria-label` or `aria-labelledby`.

### PR DESCRIPTION
**Pull request by crisbeto**
According to the [W3C reference implementation](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/), the inner `tablist` can be labelled using `aria-label` or `aria-labelledby`. These changes add an input to allow them to be set.

Fixes #29486.

### CODE REVIEW

File: src/material/tabs/tab-group.ts [hunk 1]
```diff
@@ -242,6 +242,12 @@ export class MatTabGroup implements AfterContentInit, AfterContentChecked, OnDes
 
   private _backgroundColor: ThemePalette;
 
+  /** Aria label of the inner `tablist` of the group. */
+  @Input('aria-label') ariaLabel: string;
```
Comment (crisbeto) [inline src/material/tabs/tab-group.ts:246]: I'm a bit on the fence if this should be `aria-label` or something like `tabListAriaLabel`. I went with the shorter one, because the `mat-tab-group` doesn't have a `role`.

Comment (amysorto) [reply src/material/tabs/tab-group.ts:246]: It also seems some of out other components (like [autocomplete](https://material.angular.io/components/autocomplete/api#MatAutocomplete)) follow the same too with just calling the input ariaLabel

**Review by amysorto — APPROVED** [review]
