### PR TITLE
fix(cdk/testing): errors in harnesses when using Vitest

### LINKED ISSUE #32389: bug(mouse): Click triggered with TestHarnesses causes crashes on Vitest using jsdom
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When testing click behaviors using Angular's `TestHarness` (e.g., `MatButtonHarness.click()`) in a Vitest environment with jsdom, the test fails with the following error:

```
TypeError: Failed to construct 'PointerEvent': member view is not of type Window.
```

This issue is caused by the presence of the `view: window` property in the `MouseEvent` options, which is not supported in jsdom. This is a known limitation in Vitest (see [vitest-dev/vitest#4685](https://github.com/vitest-dev/vitest/issues/4685)).

A temporary solution is to configure Vitest to use the `vmThreads` pool in the `defineConfig`:

```javascript
export default defineConfig({
  test: {
    pool: 'vmThreads',
  }
});
```

However, this workaround is not ideal, as it is unclear, non-obvious, and may not be recommended for all use cases.

### Reproduction

Steps to reproduce:
1. `ng new whatever` using @angular/cli@21
2. `ng add @angular/material`
3. Import `MatButton` in `App` component
4. Add the following method
   ```ts
   protected sayHello(): void {
     alert('Hello World!');
   }   
   ```
5. Add matButton element in template
   ```html
    <button matButton="filled" (click)="sayHello()">Click Me!</button>
    ```
6. Add test case
    ```ts
    it('should open alert with hello world when click me button is clicked', async () => {
      const fixture = TestBed.createComponent(App);
      const loader = TestbedHarnessEnvironment.loader(fixture);

      vi.stubGlobal('alert', vi.fn());

      const button = await loader.getHarness(
        MatButtonHarness.with({
          text: 'Click Me!',
        })
      );

      await button.click();

      expect(alert).toHaveBeenCalledWith('Hello World!');
    });
    ```
7. Run `ng test` 
8. Observe the test failure with the above error.

### Expected Behavior

Should not fail

### Actual Behavior

`TypeError: Failed to construct 'PointerEvent': member view is not of type Window.`

### Environment

- Angular: 21.0.0
- CDK/Material: 21.0.0
- Node: 24.11.1
- Operating System: Windows 11

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that we were hitting an error due to the DOM implementation that Vitest is using when constructing events.

Fixes #32389.

### CODE REVIEW

File: src/cdk/testing/testbed/fake-events/event-objects.ts [hunk 1]
```diff
@@ -165,3 +165,12 @@ export function createFakeEvent(type: string, bubbles = false, cancelable = true
...
   Object.defineProperty(event, propertyName, {get: () => value, configurable: true});
 }
+
+/** Gets the `view` that should be passed to synthetically-created DOM events */
+function getEventView(): Window | undefined {
+  // Passing `window` as the `view` on for events in Vitest throws
+  // `member view is not of type Window`. Detect when we're in a Vitest
+  // environment and leave it as undefined. See #32389.
+  // @ts-expect-error Expect the error since we don't have typings for Vitest.
+  return typeof vi === 'undefined' && typeof window !== 'undefined' && window ? window : undefined;
```
Comment (alan-agius4) [inline src/cdk/testing/testbed/fake-events/event-objects.ts]: This problem seems confined to JSDOM implementations, and doesn't impact Vitest broadly. Considering Vitest's compatibility with alternative DOMs (e.g., HappyDOM) and browser execution, we should refine the existing check for greater specificity.

```ts
return typeof window !== 'undefined' && !window.jsdom ? window : undefined;
```

PS: the comment also needs to be updated.

File: src/cdk/testing/testbed/fake-events/event-objects.ts [hunk 2]
```diff
@@ -165,3 +165,13 @@ export function createFakeEvent(type: string, bubbles = false, cancelable = true
 function defineReadonlyEventProperty(event: Event, propertyName: string, value: any) {
   Object.defineProperty(event, propertyName, {get: () => value, configurable: true});
 }
+
+/** Gets the `view` that should be passed to synthetically-created DOM events */
+function getEventView(): Window | undefined {
+  // Passing `window` as the `view` on for events when the environment is using jsdom
+  // ends up throwing `member view is not of type Window` (see #32389). Leave it as
+  // `undefined` for such cases.
+  return typeof window !== 'undefined' && window && !(window as Window & {jsdom?: unknown}).jsdom
```
Comment (alan-agius4) [inline src/cdk/testing/testbed/fake-events/event-objects.ts:174]: NIT, redundant check

```suggestion
  return typeof window !== 'undefined' && !(window as Window & {jsdom?: unknown}).jsdom
```

Comment (crisbeto) [reply src/cdk/testing/testbed/fake-events/event-objects.ts:174]: The check is there because technically `window` can be `null` which is `typeof === 'object'`.

**Comment by crisbeto** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: d41d397a09f19951fb5d732d51c8b270616c2e94
- 21.0.x: ccc12c3879b3b58d6821e80ba1ef79db25a49572
