### PR TITLE
fix(cdk/tree): enter/space key on child node should not toggle parent node expansion

### LINKED ISSUE #33120: bug(material/tree): Keyboard toggling child node collapses parent in mat-tree with mat-nested-tree-node
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When using `mat-tree` with `mat-nested-tree-node`, toggling a child node via keyboard (Enter or Space) unexpectedly collapses the parent node.

This issue is reproducible using the official Angular Material documentation example "Tree with nested nodes (childrenAccessor)".

### Reproduction

StackBlitz link: https://stackblitz.com/edit/9v65gmui?file=src%2Fexample%2Ftree-nested-child-accessor-overview-example.ts
Steps to reproduce:
1. Create a mat-tree using mat-nested-tree-node.
2. Expand a parent node so that child nodes are visible.
3. Use keyboard navigation (Tab / Arrow keys) to focus a child node.
4. Press Enter or Space to toggle the child node.
5. Observe that the parent node collapses.

### Expected Behavior

Pressing Enter/Space on a focused child node should toggle only the selected child node.
The parent node should remain expanded and unaffected.

### Actual Behavior

Toggling a child node using the keyboard causes the parent node to collapse.

Image

### Environment

- Angular: 21.1.0
- CDK/Material: 21.1.0
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

### PR DESCRIPTION
**Pull request by ok7sai**
Fixes #33120

### CODE REVIEW

File: src/cdk/tree/toggle.ts [hunk 1]
```diff
@@ -17,8 +17,8 @@ import {CdkTree, CdkTreeNode} from './tree';
   selector: '[cdkTreeNodeToggle]',
   host: {
     '(click)': '_toggle(); $event.stopPropagation();',
-    '(keydown.Enter)': '_toggle(); $event.preventDefault();',
-    '(keydown.Space)': '_toggle(); $event.preventDefault();',
+    '(keydown.Enter)': '_toggle(); $event.preventDefault(); $event.stopPropagation();',
+    '(keydown.Space)': '_toggle(); $event.preventDefault(); $event.stopPropagation();',
```
Comment (crisbeto) [inline src/cdk/tree/toggle.ts]: Maybe we should move this logic into a method where we pass in `$event` instead?

**Review by crisbeto — APPROVED** [review]

File: src/cdk/tree/toggle.ts (hunk 1 above)
Comment (ok7sai) [reply src/cdk/tree/toggle.ts]: Yea I was thinking of moving that to `_toggle()` as well. Will fix that.

**Review by adolgachev — APPROVED** [review]

**Comment by ok7sai** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: b916ef907fc15fd889ff0fe6fdb7c054331c906b
- 21.2.x: 3a3852d45a4bbcfb23b46ca00e0eba1d70081ba3
