### PR TITLE
fix(cdk/table): support hydration

### LINKED ISSUE #28355: bug(mat-table): Mat Table has skip hydration attribute
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

I've noticed a lot of material components have ngSkipHydration attribute present such as mat-table. 

The sidenav component fixed this issue recently in https://github.com/angular/components/pull/28340 and I'm very grateful. Hoping to see all the rest of the components have this fix.

### Reproduction

Steps to reproduce:
1. ng new example --ssr
2. add mat-table 

### Expected Behavior

Hydration working as expected when using mat-table

### Actual Behavior

I still see double flicker rendering which means the hydration is not properly working

### Environment

- Angular: 17.0.8
- CDK/Material: 17.0.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by crisbeto**
Reworks the table so that it can support hydration. There were a few issues that broke hydration:
1. There wasn't a catch-all `ng-content` slot which meant that the comment nodes representing the table content were dropped, causing an error.
2. The table needs to conditionally wrap some content with native table sections (`thead`,  `tbody` etc.) which was done with direct DOM manipulation. This breaks hydration because Angular won't know about those elements.

The first issue is easily resolved by adding an `ng-content` element. It shouldn't affect existing tables, since all the projected content is composed of comment nodes.

The second issue is a bit trickier, because we were using content queries to resolve the individual table outlets. Wrapping them in a conditional breaks the query so we have to use something else to resolve them. I've worked around it by using DI which doesn't have the exact same timing, but it appears to be close enough.

Fixes #28355.

### CODE REVIEW

File: src/cdk/table/table.ts [hunk 1]
```diff
@@ -879,6 +872,73 @@ export class CdkTable<T> implements AfterContentChecked, CollectionViewer, OnDes
...
+      this._footerRowOutlet &&
+      this._noDataRowOutlet
+    ) {
+      this._hasRendered = true;
+      this._render();
+    }
+  }
+
+  /** Renders the table if its state has changed. */
+  private _render(): void {
```
Comment (crisbeto) [inline src/cdk/table/table.ts:895]: This is a big diff, but I basically just moved the code from `ngAfterContentChecked` into a separate method.

**Review by wagnermaciel — APPROVED** [review]
