### PR TITLE
fix(datepicker): support dateClass on year and multi-year views

### LINKED ISSUE #20017: bug(mat-calendar): The dateClass callback is not called then in month view.
#### Reproduction

Steps to reproduce:
1.  Have a mat-calendar like:
```
              <mat-calendar
                [minDate]="today"
                [maxDate]="serviceMaxDate"
                [dateFilter]="filterDates"
                [dateClass]="classDates"
                [selected]="selectedDate"
                (selectedChange)="selectedDateChanges($event)">
              </mat-calendar>
```
2. Select -> years (on top) -> select a year -> then dateFilter is called (for all year dates) but the dateClass is not. So I don't get css classes on months cells.  
 
 
#### Expected Behavior

I should be able to put css classes on month cells just like the days cells.

#### Actual Behavior

Only while in date view the dateClass callback is called for all month days.

#### Environment

- Angular: 9
- CDK/Material: 9.2.4,
- Browser(s): Chrome 83+
- Operating System: Windows 10

### PR DESCRIPTION
**Pull request by crisbeto**
We have a `dateClass` input that allows consumers to set classes to particular date cells, however currently we only invoke it inside the month view. These changes pass it along to the year and multi-year views too and provide the name of the view that invoked it so that cases like the first date of a month and a month cell can be distinguished.

Fixes #20017.

### CODE REVIEW

File: src/material/datepicker/calendar-body.ts [hunk 1]
```diff
@@ -21,11 +21,13 @@ import {
...
 
-/**
- * Extra CSS classes that can be associated with a calendar cell.
- */
+/** Extra CSS classes that can be associated with a calendar cell. */
 export type MatCalendarCellCssClasses = string | string[] | Set<string> | {[key: string]: any};
 
+/** Function that can generate the extra classes that should be added to a calendar cell. */
+export type MatCalendarCellClassFunction<D> =
+    (date: D, view: 'month' | 'year' | 'multi-year') => MatCalendarCellCssClasses;
```
Comment (mmalerba) [inline src/material/datepicker/calendar-body.ts:29]: Do we have a type alias for `'month' | 'year' | 'multi-year'` somewhere? I thought we did, but I could be crazy

File: src/material/datepicker/multi-year-view.spec.ts [hunk 2]
```diff
@@ -387,3 +408,16 @@ class MultiYearViewWithMinMaxDate {
...
+
+
+@Component({
+  template: `
+    <mat-multi-year-view [activeDate]="activeDate" [dateClass]="dateClass"></mat-multi-year-view>
+  `
+})
+class MultiYearViewWithDateClass {
+  activeDate = new Date(2017, JAN, 1);
+  dateClass(date: Date) {
```
Comment (mmalerba) [inline src/material/datepicker/multi-year-view.spec.ts:420]: can we have a test that uses the second parameter as well?

**Comment by mmalerba** [comment]
I'm re-classifying this as `target: minor` since it seems more like a new feature

File: src/material/datepicker/calendar-body.ts (hunk 1 above)
Comment (crisbeto) [reply src/material/datepicker/calendar-body.ts:29]: I think we've just been doing it inline.

File: src/material/datepicker/multi-year-view.spec.ts (hunk 2 above)
Comment (crisbeto) [reply src/material/datepicker/multi-year-view.spec.ts:420]: Good call, adding the test actually caught something that I missed while copying code around.

**Comment by crisbeto** [comment]
I've reworked it based on the feedback.
