### PR TITLE
fix(drag-drop): detect changes on custom preview/placeholder before measuring

### LINKED ISSUE #18622: ngClass behaving differently than regular classes with cdk-drag-drop
I have different types of elements in my `*cdkDropList` that need different placholder hights when dragging them around. Since the array has objects with a property `type`, I added those types as CSS classes and tried to add them dynamically using `[ngClass]`. However, these dynamically generated classes behave differently than when I'm setting them as "regular" CSS classes.

This is what happens, when I set the classes dynamically:

[![The placeholder and the elements in the `dropList` overlap][1]][1]

The placeholder and the elements in the `dropList` overlap. Here's the relevant code:

`example.component.ts`
```typescript
contentItems: ContentItem[] = [
  { type: 'text', /* more props */ },
  { type: 'text', /* more props */ },
  { type: 'image', /* more props */ }
];
```
`example.component.html`
```html
<div *ngFor="let item of contentItems" class="editor-item" cdkDrag>
  <div [ngClass]="['dropzone-placeholder', item.type]" *cdkDragPlaceholder>
    <p>{{ 'EDITOR.INSERT HERE' | translate }}</p>
  </div>

  <app-language-tab-editor *ngIf="item.type === 'text'"></app-language-tab-editor>
  <app-image-upload *ngIf="item.type === 'image'"></app-image-upload>
</div>
```
`example.component.scss`
```scss
$dropzone-placeholder-dark: #00973B;
$dropzone-placeholder-light: #00973B0D;
$text-placeholder-height: 135px;
$image-placeholder-height: 375px;

.dropzone-placeholder {
  border: 1px dashed $dropzone-placeholder-dark;
  color: $dropzone-placeholder-dark;
  background: $dropzone-placeholder-light;

  &.text {
    height: $text-placeholder-height;
  }

  &.image {
    height: $image-placeholder-height;
  }
}
```

I currently only have two different types, but the goal is to make it easily expandable to add more later on. I have also already tried to instead use `class="dropzone-placeholder {{ item.type }}"` as well as `[class]="'dropzone-placeholder ' + item.type"`, to no avail.

After further testing I have also found out, that it generally doesn't work using `[ngClass]`, even if we don't use a variable. Using `[ngClass]="['dropzone-placeholder', 'text']"` didn't work either.

This is the expected behaviour:

[![The placeholder and the elements in the `dropList` don't overlap and are instead placed properly below each other][2]][2]

The placeholder and the elements in the `dropList` don't overlap and are instead placed properly below each other. This behaviour can currently only be achieved by setting the classes regularily, but the HTML is rather unpleasant to look at, since the code would get messily redundant in the future:

`example.component.html`
```html
<div *ngFor="let item of contentItems" class="editor-item" cdkDrag>
  <div *ngIf="item.type === 'text'">
    <div class="dropzone-placeholder reorder text" *cdkDragPlaceholder>
      <p>{{ 'EDITOR.INSERT HERE' | translate }}</p>
    </div>
  </div>
  <div *ngIf="item.type === 'image'">
    <div class="dropzone-placeholder reorder image" *cdkDragPlaceholder>
      <p>{{ 'EDITOR.INSERT HERE' | translate }}</p>
    </div>
  </div>

  <app-language-tab-editor *ngIf="item.type === 'text'"></app-language-tab-editor>
  <app-image-upload *ngIf="item.type === 'image'"></app-image-upload>
</div>
```

  [1]: https://i.stack.imgur.com/uShI0.png
  [2]: https://i.stack.imgur.com/eSJIK.png

#### Environment

- Angular: v8.3.25
- CDK: v8.2.3
- Browser(s): Chrome, Firefox
- Operating System: Windows 10 (1803)

### PR DESCRIPTION
**Pull request by crisbeto**
When a custom preview/placeholder is created, its dimensions are measured so that they can be used while sorting. The problem is that we weren't detecting changes after creation which can cause the dimensions to be incorrect, if they change based on a data binding. These changes check for changes after inserting the embedded view.

Fixes #18622.

### CODE REVIEW

File: src/cdk/drag-drop/drag-ref.ts [hunk 1]
```diff
@@ -884,6 +884,7 @@ export class DragRef<T = any> {
     if (previewTemplate) {
       const viewRef = previewConfig!.viewContainer.createEmbeddedView(previewTemplate,
                                                                       previewConfig!.context);
+      viewRef.detectChanges();
```
Comment (jelbourn) [inline src/cdk/drag-drop/drag-ref.ts]: Rather than directly calling `detectChanges`, couldn't we instead defer measuring until Angular completes the change detection it needs to do anyway?

Comment (crisbeto) [reply src/cdk/drag-drop/drag-ref.ts]: Almost none of the drag&drop events trigger change detection so we can't really depend on it since it can happen at any time for other reason. This only detects on a small chunk of the tree anyway.
