### PR TITLE
fix(slide-toggle): clicks not landing correctly in some cases on Chrome

### LINKED ISSUE #18269: mat-slide-toggle fails to toggle upon mouse click when text is selected elsewhere on form
#### Reproduction

Using Chrome, see the following StackBlitz:   https://stackblitz.com/edit/angular-1ztoyy

Steps to reproduce:
1. Upon page load, note that the mat-slide-toggle properly responds to click events by toggling itself.
2. After 5 seconds, the page is programmatically selecting text in a nearby textbox. (You can also reproduce the issue by manually selecting the text.)
3. Without clicking anywhere else, try the mat-slide-toggle again, and note that it no longer toggles upon click. (The ripple effect does appear, indicating that it knows it has been clicked. Interestingly, double-click does work.)
4. Clicking elsewhere on the form restores the expected behavior (presumably because this causes the selected text to be de-selected). 
 
#### Expected Behavior

The mat-slide-toggle control should toggle its state when clicked.

#### Actual Behavior

After selecting text in another field, the mat-slide-toggle no longer toggles its state when clicked.

#### Environment

- Angular: 9.0.0-rc.9    (This does not appear to be an issue in Angular 8 / Material 8)
- CDK/Material: Material 9.0.0-rc.8
- Browser(s):  Chrome 79.0.3945.130 (64-bit) (issue does not appear to occur in Edge or Firefox)
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10 x64

### PR DESCRIPTION
**Pull request by crisbeto**
Any time the slide toggle host receives focus we forward it immediately to the underlying `input` element. This bouncing around of focus seems to interrupt click events in some cases on Chrome. These changes make it so that we only forward focus for events originating from the keyboard or programmatically.

Fixes #18269.

### CODE REVIEW

File: src/material/slide-toggle/slide-toggle.ts [hunk 1]
```diff
@@ -193,7 +192,13 @@ export class MatSlideToggle extends _MatSlideToggleMixinBase implements OnDestro
     this._focusMonitor
       .monitor(this._elementRef, true)
       .subscribe(focusOrigin => {
-        if (!focusOrigin) {
+        // Only forward focus manually when it was received programmatically or through the
+        // keyboard. We should not do this for mouse/touch focus for two reasons:
+        // 1. It can prevent clicks from landing in Chrome (see #18269).
+        // 2. They're already handled by the wrapping `label` element.
+        if (focusOrigin === 'keyboard' || focusOrigin === 'program') {
+          this._inputElement.nativeElement.focus();
```
Comment (devversion) [inline src/material/slide-toggle/slide-toggle.ts]: Related to that, did we consider forwarding the focus origin here? (through `focusVia`)?

Comment (crisbeto) [reply src/material/slide-toggle/slide-toggle.ts]: I don't mind changing it if you feel strongly about it. I didn't do it, because there's nothing reacting to different focus origins on the input anyway so it seemed redundant.

Comment (devversion) [reply src/material/slide-toggle/slide-toggle.ts]: Yeah, it was mostly for sanity. I don't feel strongly about it. Let's just leave it as is.
