### PR TITLE
fix(scrolling): viewport ruler events being run inside zone

### LINKED ISSUE #18471: mat-drawer-container triggers angular detection cycles on window:resize
#### Reproduction

https://stackblitz.com/edit/angular-se13bg?file=src%2Fapp%2Fsidenav-drawer-overview-example.html

Steps to reproduce:
1. `<mat-drawer-container></mat-drawer-container>`
 
#### Expected Behavior

`mat-drawer-container` should not trigger angular detection cycle when the window is resized

#### Actual Behavior

`mat-drawer-container` triggers angular detection cycles on window:resize

#### Environment

- Angular: 9
- CDK/Material: 9

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes the `resize` and `orientationchange` events of the `ViewportRuler` being run inside the `NgZone`, if the subscription comes from inside the zone.

Fixes #18471.

### CODE REVIEW

File: src/cdk/scrolling/viewport-ruler.ts [hunk 1]
```diff
@@ -30,25 +30,32 @@ export class ViewportRuler implements OnDestroy {
...
+      // because we complete the `change` stream on destroy.
+      this.change().subscribe(() => this._updateViewportSize());
     });
   }
 
   ngOnDestroy() {
-    this._invalidateCache.unsubscribe();
+    window.removeEventListener('resize', this._changeListener);
+    window.removeEventListener('orientationchange', this._changeListener);
+    this._change.complete();
```
Comment (diicar) [inline src/cdk/scrolling/viewport-ruler.ts]: maybe you need to check if its a browser here too  ?

Comment (crisbeto) [reply src/cdk/scrolling/viewport-ruler.ts]: Ah, thank you. This will throw if it's in a non-browser environment.

**Comment by crisbeto** [comment]
Bumping to a P2 since we got a report about this potentially affecting perf.

File: src/cdk/scrolling/viewport-ruler.ts [hunk 2]
```diff
@@ -30,25 +30,35 @@ export class ViewportRuler implements OnDestroy {
...
+      if (_platform.isBrowser) {
+        // Note that bind the events ourselves, rather than going through something like RxJS's
+        // `fromEvent` so that we can ensure that they're bound outside of the NgZone.
+        window.addEventListener('resize', this._changeListener);
+        window.addEventListener('orientationchange', this._changeListener);
+      }
+
+      // We don't need to keep track of the subscription,
+      // because we complete the `change` stream on destroy.
+      this.change().subscribe(() => this._updateViewportSize());
```
Comment (llorenspujol) [inline src/cdk/scrolling/viewport-ruler.ts]: Here I would change a little bit the piece code, I would do something like:

```ts
    this._change = _platform.isBrowser ?
      merge(fromEvent(window, 'resize'), fromEvent(window, 'orientationchange'))
        .pipe(runOutsideZone(ngZone)) :
      observableOf();

```
where:

```ts
/** Runs this observable outside the zone */
function runOutsideZone<T>(zone: NgZone): any {
  return (source: Observable<T>): Observable<T> => {
      return new Observable(observer => {
          return zone.runOutsideAngular<Subscription>(() => source.subscribe(observer));
      });
  };
}
```

Seems cleaner and more understandable IMO, also is less code.

**Comment by llorenspujol** [comment]
Is there any blocking issue that causes this MR to not be merged? Just for know.

I also miss the 'zone re-entering' of the subscriptions that need it. For example the select component & the paginated-tab-header.

Here I have a proposal MR (same of this one, I actually copy the tests, thanks @crisbeto) where I do this 'zone re-enterings':

https://github.com/angular/components/pull/18548/files
