### PR TITLE
fix(material/checkbox): no color assigned if defaults don't have a color

### LINKED ISSUE #21031: MatCheckbox not rendering check for undefined color when using default options
#### Reproduction

https://stackblitz.com/edit/angular-yyan4s?file=src%2Fapp%2Fcheckbox-overview-example.html

Steps to reproduce:
1.  Adding the default behavior provider ```    {
      provide: MAT_CHECKBOX_DEFAULT_OPTIONS,
      useValue: { clickAction: "noop" } as MatCheckboxDefaultOptions
    }```
2. Setting any checkbox via input, for example: ```<mat-checkbox [checked]="true">Checked</mat-checkbox>```
 
 
#### Expected Behavior

image

#### Actual Behavior

What behavior did you actually see?

image

#### Environment

- Angular: 11
- CDK/Material: 11
- Browser(s): Firefox 82
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes an issue where a `mat-checkbox` wouldn't have a `color`, if the `MAT_CHECKBOX_DEFAULT_OPTIONS` was provided without one.

Fixes #21031.

### CODE REVIEW

File: src/material-experimental/mdc-checkbox/checkbox.ts [hunk 1]
```diff
@@ -46,6 +46,9 @@ import {numbers} from '@material/ripple';
 
 let nextUniqueId = 0;
 
+// Default checkbox configuration.
+const defaults = MAT_CHECKBOX_DEFAULT_OPTIONS_FACTORY();
```
Comment (crisbeto) [inline src/material-experimental/mdc-checkbox/checkbox.ts:50]: Invoking the factory directly feels a little weird, but I'm trying to avoid repeating the default color across different files.

Comment (mmalerba) [reply src/material-experimental/mdc-checkbox/checkbox.ts:50]: Yeah I'm not even sure why its a factory, feels like it could just be provided with `useValue`. I'm fine with doing this, we can revisit if it ever becomes problematic.

**Review by mmalerba — APPROVED** [review]
LGTM
