### PR TITLE
fix(autocomplete): reopening closed autocomplete when coming back to tab

### LINKED ISSUE #12337: mat-autocomplete panel reopens again after browser tab switch
#### What is the expected behavior?
Autocomplete panel should stay closed regardless of whether it has the focus when the user switches browser tab.

#### What is the current behavior?
Autocomplete panel reopens itself after the user switches browser tab, without user's interaction. See steps below.

#### What are the steps to reproduce?
1) Go to https://material.angular.io/components/autocomplete/overview
2) Select any option on any drop down. Keep the focus on the same drop down.
3) Notice that the autocomplete panel has closed.
4) Switch to another browser tab]
5) Switch back to the previous browser tab.
6) Notice that the autocomplete panel has been opened again, without user interaction.

Note that it works as expected if the user remove focus from the drop down in step 2). Switching tab doesn't reopen the autocomplete panel.

#### What is the use-case or motivation for changing an existing behavior?
It's confusing for the user when the autocomplete panel reopens itself again without user's interaction. The user selected an option. The autocomplete panel state should be closed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.4.1 (the one running on material.angular.io), Linux, latest Chrome.

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes a closed autocomplete being reopened, if the user moves to another tab and coming back to the current one, while the input is still focused.

Fixes #12337.

### CODE REVIEW

File: src/lib/autocomplete/autocomplete-trigger.ts [hunk 1]
```diff
@@ -135,6 +135,13 @@ export class MatAutocompleteTrigger implements ControlValueAccessor, OnDestroy {
   /** Subscription to viewport size changes. */
   private _viewportSubscription = Subscription.EMPTY;
 
+  /**
+   * Whether the autocomplete can open the next time it is focused. Used to prevent a focused,
+   * closed autocomplete from being reopened if the user switches to another tab and then
+   * comes back.
```
Comment (jelbourn) [inline src/lib/autocomplete/autocomplete-trigger.ts]: Clarify "browser tab" to disambiguate from a tabs component?

File: src/lib/autocomplete/autocomplete-trigger.ts [hunk 2]
```diff
@@ -178,9 +185,20 @@ export class MatAutocompleteTrigger implements ControlValueAccessor, OnDestroy {
...
+    if (typeof window !== 'undefined') {
+      _zone.runOutsideAngular(() => {
+        window.addEventListener('blur', this._windowBlurHandler);
+      });
+    }
+  }
 
   ngOnDestroy() {
+    if (typeof window !== 'undefined') {
+      window.removeEventListener('blur', this._windowBlurHandler);
```
Comment (jelbourn) [inline src/lib/autocomplete/autocomplete-trigger.ts]: This will be a good use for the [Page Lifecycle API](https://developers.google.com/web/updates/2018/07/page-lifecycle-api)... someday.

File: src/lib/autocomplete/autocomplete-trigger.ts [hunk 3]
```diff
@@ -613,4 +633,12 @@ export class MatAutocompleteTrigger implements ControlValueAccessor, OnDestroy {
     return !element.readOnly && !element.disabled && !this._autocompleteDisabled;
   }
 
+  /**
+   * Event handler for when the window is blurred. Needs to be an
+   * arrow function in order to preserve the context.
+   */
+  private _windowBlurHandler = () => {
```
Comment (jelbourn) [inline src/lib/autocomplete/autocomplete-trigger.ts]: Move this up to live next to the other class properties?

File: src/lib/autocomplete/autocomplete-trigger.ts [hunk 4]
```diff
@@ -613,4 +633,12 @@ export class MatAutocompleteTrigger implements ControlValueAccessor, OnDestroy {
...
+    this._canOpenOnNextFocus =
+        document.activeElement !== this._element.nativeElement || this.panelOpen;
```
Comment (jelbourn) [inline src/lib/autocomplete/autocomplete-trigger.ts]: Add a comment that explains the rationale behind this logic?

File: src/lib/autocomplete/autocomplete-trigger.ts (hunk 2 above)
Comment (crisbeto) [reply src/lib/autocomplete/autocomplete-trigger.ts]: The browser support isn't too horrible tbh, but I think that this is case is simple enough that we can get away with the event.

**Comment by crisbeto** [comment]
Feedback has been addressed @jelbourn.
