### PR TITLE
Dialog and bottom sheet not setting aria-modal

### LINKED ISSUE #25676: bug(MatDialog): Regression with aria-modal
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.x

### Description

Since Angular 14 the aria-modal attribute in the mat-dialog-container is configurable, but the option is not present in the configuration class : MatDialogConfig.
As such we can't have aria-modal in the mat-dialog-container

### Reproduction

Steps to reproduce:
1. open a dialog with MatDialog

### Expected Behavior

- aria-modal="true" is present in the mat-dialog-container

or

- presence of an ariaModal variable in the MatDialogConfig class

### Actual Behavior

- aria-modal is not present in the mat-dialog-container

or

- ariaModal is not known in the MatDialogConfig class

### Environment

- Angular: 14.1.1
- CDK/Material: 14.1.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the dialog and bottom sheet weren't setting `aria-modal` anymore. We had data bindings for it, but they didn't work and we hadn't noticed because host bindings aren't being type checked. This regression likely happened during the switch to the CDK dialog.

Fixes #25676.

### CODE REVIEW

File: src/material/dialog/dialog-config.ts [hunk 1]
```diff
@@ -104,6 +104,9 @@ export class MatDialogConfig<D = any> {
   /** Aria label to assign to the dialog element. */
   ariaLabel?: string | null = null;
 
+  /** Whether this a modal dialog. Used to set the `aria-modal` attribute. */
```
Comment (devversion) [inline src/material/dialog/dialog-config.ts:107]:
```suggestion
  /** Whether this is a modal dialog. Used to set the `aria-modal` attribute. */
```

(also for the bottom sheet)

**Review by devversion — APPROVED** [review]
