### PR TITLE
fix(datepicker): emitting dateChange event when opposite range input changes

### LINKED ISSUE #19968: bug(mat-date-range-picker): updating form control value causes `(dateChanged)` to emit
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-pmxj3r

Steps to reproduce:
1. Open the StackBlitz
2. The component is listening for the `(dateChange)` event on the `MatStartDate` directive, and will invoke the `onStartDateChange` method
3. The component is listening for the `(dateChange)` event on the `MatEndDate` directive, and will invoke the `onEndDateChange` method
4. The `range` form control value is updated with a date range. The `(dateChange)` event then fires on both the `MatStartDate` and `MatEndDate` directives.
 
#### Expected Behavior

What behavior were you expecting to see?

Nothing should be logged to the console. Consistent with how other angular material components work I would not expect `(dateChange)` to emit if the value of the form control is programatically updated.

#### Actual Behavior

What behavior did you actually see?

The following was logged to the console:
```
MatEndDate (dateChange) emitted
MatStartDate (dateChange) emitted
```

#### Environment

- Angular:
- CDK/Material: 10.0.1
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

### PR DESCRIPTION
**Pull request by crisbeto**
Adds some logic to prevent date range inputs from emitting their `dateChange` and `dateInput` events when a value is assigned to the opposite input.

Fixes #19968.

### CODE REVIEW

File: src/material/datepicker/date-range-input-parts.ts [hunk 1]
```diff
@@ -238,6 +238,10 @@ export class MatStartDate<D> extends _MatDateRangeInputBase<D> implements CanUpd
     }
   }
 
+  protected _canEmitChangeEvent = (event: DateSelectionModelChange<DateRange<D>>): boolean => {
+    return event.source !== this && event.source !== this._rangeInput._endInput;
```
Comment (mmalerba) [inline src/material/datepicker/date-range-input-parts.ts:242]: Is the `event.source !== this` part necessary? The single date input doesn't check this

Comment (crisbeto) [reply src/material/datepicker/date-range-input-parts.ts]: It's not necessary since the check is inside the base class. It's a leftover from when I was trying something different. Removed.
