### PR TITLE
fix(material/schematics): migrate more cases in the theming API schematic

### LINKED ISSUE #22599: bug(material/core/theming): after v12 update ng serve reload time for theming changes is too high
### Reproduction

https://github.com/DevIntent/material.angular.io/tree/pre-sass-migrations

Steps to reproduce:
1. Clone
2. yarn
3. yarn start
4. Change files as mentioned below an observe reload times

### Expected Behavior

After updating to v12 via `ng update`, my app should be generally usable for development and `ng serve` rebuild times in dev mode should be comparable or better than v11.

#### This is what I saw in a real world app

`ng serve` reload perf in a small-medium app

- TypeScript change: 1.8s
- Simple Sass change to a single feature component: 1.8s
- Change to styles.scss in root: 17s
- Change to a palette or other theming config: 110-120s
- Change to an independent variable in the same file as the theme config: 110-120s
- Change to a partial that is imported into styles.scss and used but doesn’t touch theming: 75s

#### From material.angular.io

`ng serve` reload perf after update to v12 w/o running opt-in migration and w/o running sass-migrator

- TypeScript change: 2.9s
- Simple Sass change to a single feature component: 2.8s
- Change to styles.scss in root: 15s
- Change to a palette or other theming config: 56-78s
- Change to an independent variable in the same file as the theme config: 74-77s
- Change to an independent style in the same file as the theme config: 81s
- Change to a simple partial that is imported into styles.scss and not used and doesn’t touch theming: 15s

These are both pretty small projects and the rebuild times for theming changes are pretty hard to handle. I'm worried that larger projects will see an even large impact here (4+ minutes or more to rebuild).

Running `ng generate @angular/material:themingApi` migrates the project's theming config to use Sass modules. After that ng serve rebuild times are expected to go back to normal.

- TypeScript change: 2.3s
- Simple Sass change to a single feature component: 2.1s
- Change to styles.scss in root: 14s
- Change to a palette or other theming config: 72s
- Change to an independent variable in the same file as the theme config: 68s

You can test this in this branch: https://github.com/DevIntent/material.angular.io/tree/post-theme-migration

Using latest `master` that has run both the theming migration and sass-migrator:

- TypeScript change: 7s
- Simple Sass change to a single feature component: 6s
- Change to styles.scss in root: 6s
- Change to a palette or other theming config: 8s
- Change to an independent variable in the same file as the theme config: 8s

### Environment

- Angular: 12.0.0-next.9, 12.0.0-rc.0, 12.0.0-rc.1
- CDK/Material: 12.0.0-next.7, 12.0.0-rc.0, 12.0.0-rc.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Catalina

### PR DESCRIPTION
**Pull request by crisbeto**
Includes the following improvements to the `themingApi` schematic:

1. No longer runs against files in the `node_modules`. This was happening by accident.
2. Remove the quotes around the values of `$mat-small` and `$mat-xsmall` since they were causing Sass syntax errors.
3. Migrates Material/CDK symbols, even if there are no imports for the old theming bundle. This allows us to handle symbols that were imported transitively.
4. Reverts the logic from #22438 that doesn't drop imports if there are no Material/CDK symbol usages within the file. I think that we want to do this after all, because the old import could slow down build times and we can be relatively certain that any usages have been migrated.

Fixes #22599.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

**Review by devversion — APPROVED** [review]

**Review by Splaktar — APPROVED** [review]
LGTM

File: src/material/schematics/ng-generate/theming-api/migration.ts [hunk 1]
```diff
@@ -37,19 +37,21 @@ export function migrateFileContent(content: string,
...
-    }
+  // Try to migrate the symbols even if there are no imports. This is used
+  // to cover the case where the Components symbols were used transitively.
+  content = migrateMaterialSymbols(content, newMaterialImportPath, materialResults.namespaces);
+  content = migrateCdkSymbols(content, newCdkImportPath, cdkResults.namespaces);
+  content = replaceRemovedVariables(content, removedMaterialVariables);
+
+  // We can assume that the migration has taken care of any Components symbols that were
+  // imported transitively so we can always drop the old imports. We also assume that imports
+  // to the new entrypoints have been added already.
```
Comment (Splaktar) [inline src/material/schematics/ng-generate/theming-api/migration.ts:48]:
```suggestion
  // to the new entry points have been added already.
```
