### PR TITLE
Preview popover fixes

### LINKED ISSUE #28974: bug(cdk/drag-drop): new preview container breaks styling
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.3.5

### Description

I have a html table where each tr has the cdkDrag directive so i can sort them. If the drag preview is outside of the table the styling breaks so i have set the cdkDragPreviewContainer to parent, which still works but since the latest update there is a new wrapper div around the table row which breaks the styling and html semantics because we now have a div instead of a tr in the table body.

I would expect that there is an option to disable the wrapping div or maybe even having it opt in as it breaks existing styling. The popover also comes with some own user agent styling which was not there before.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-ycfvod?file=src%2Fmain.ts
Steps to reproduce:
1. 
2.

### Expected Behavior

I would expect the tr to be directly inside the parent container when i set cdkDragPreviewContainer to parent.

### Actual Behavior

The tr is inside a div instead of the parent container.

### Environment

- Angular: 17.3.6
- CDK/Material: 17.3.6
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

### PR DESCRIPTION
**Pull request by crisbeto**
Includes the following fixes related the preview popovers:

### fix(cdk/drag-drop): reset user agent color on preview popover
After #28945 the preview is inserted into a `popover` element which has a user agent styling of `color: canvastext`. These changes reset it to `inherit` to match the old behavior.

### fix(cdk/drag-drop): remove preview wrapper
Switches back to positioning the preview directly instead of using a wrapper which can be breaking for existing apps. Instead we load a stylesheet dynamically with the necessary resets.

Fixes #28974.

### CODE REVIEW

File: src/cdk/drag-drop/preview-ref.ts [hunk 1]
```diff
@@ -169,15 +137,18 @@ export class PreviewRef {
         'pointer-events': 'none',
         // We have to reset the margin, because it can throw off positioning relative to the viewport.
         'margin': '0',
-        'position': 'absolute',
+        'position': 'fixed',
         'top': '0',
         'left': '0',
+        'z-index': this._zIndex + '',
```
Comment (mmalerba) [inline src/cdk/drag-drop/preview-ref.ts:143]: do we need z-index if its in a popover?

File: src/cdk/drag-drop/resets.scss [hunk 2]
```diff
@@ -0,0 +1,10 @@
+@layer cdk-resets {
+  .cdk-drag-preview {
+    background: none;
+    border: none;
+    pointer-events: none;
```
Comment (mmalerba) [inline src/cdk/drag-drop/resets.scss:5]: I see `pointer-events` and `margin` are set both here and in the strictly-enforced styles styles, do we want them to be user overridable or no?

Comment (crisbeto) [reply src/cdk/drag-drop/resets.scss]: Removed.

File: src/cdk/drag-drop/preview-ref.ts (hunk 1 above)
Comment (crisbeto) [reply src/cdk/drag-drop/preview-ref.ts:143]: We still have it, because there's a public API to set it and it case we're running on a browser that doesn't support popovers.

Comment (mmalerba) [reply src/cdk/drag-drop/preview-ref.ts:143]: I think all the browsers we support also support popover, but I guess we can leave it until we deprecate the zindex API

**Review by mmalerba — APPROVED** [review]
LGTM
