### PR TITLE
fix(cdk/listbox): prevent wrong activeItemIndex after browser tab switch

### LINKED ISSUE #27474: bug(listbox): focus issue when moving back from another tab
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

Switching tabs can lead to a state where focused item is different from the item that will be toggled when pressing `Space`. That seems to be because `ActiveDescendantKeyManager` wrongly resets the `activeItemIndex` to 0, when tab is changed.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/8l74u6?file=src%2Fexample%2Fcdk-listbox-multiple-example.html,src%2Fexample%2Fcdk-listbox-multiple-example.ts
1. select "Chinese" and then "Italian". Active index is correctly 2.
2. move to another tab
3. move back to the stackblitz tab
4. Now "Italian" is still shown as the focused item, and is in fact focused (document.activeElement is the "Italian"'s LI item),
    But pressing Space will toggle the first item.

As shown in the example, it seems the issue is rooted in ListKeyManager changing the activeItemIndex to 0, when focus is lost by moving to another. Here is how activeItemIndex is not in sync with the focused item, after moving back to stackblitz tab:
image

### Expected Behavior

Pressing Space after moving back to the example's tab should toggle "Italian", which was and is still focused.

### Actual Behavior

Pressing Space after moving back to the example's tab toggles "Chinese" which is not focused.

### Environment

- Angular: 15,16
- CDK/Material: 16.1.5
- Browser(s): Chrome (and probably other browsers)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

### PR DESCRIPTION
**Pull request by behzadmehrabi**
The `activeItemIndex` property of the cdk/listbox component tracks which item in the listbox is currently active or focused. However, some browsers (e.g. Chrome and Firefox) trigger the `focusout` event when the user switches tabs and returns, and set `event.relatedTarget` to null. This causes the `activeItemIndex` to be out of sync with the actual focused element, leading to incorrect behavior and user confusion. To fix this, we use `document.activeElement` as a fallback for `event.relatedTarget`, and update the `activeItemIndex` accordingly.

Fixes #27474.

### CODE REVIEW

File: src/cdk/listbox/listbox.ts [hunk 1]
```diff
@@ -783,7 +783,9 @@ export class CdkListbox<T = unknown> implements AfterContentInit, OnDestroy, Con
    * @param event The focusout event
    */
   protected _handleFocusOut(event: FocusEvent) {
-    const otherElement = event.relatedTarget as Element;
+    // Some browsers (e.g. Chrome and Firefox) trigger the focusout event when the user switches tabs and returns.
+    // In this case, event.relatedTarget is null, so we use document.activeElement as a fallback.
+    const otherElement = (event.relatedTarget ?? document.activeElement) as Element;
```
Comment (crisbeto) [inline src/cdk/listbox/listbox.ts:788]: I think that this is risky because we don't know if the `focusout` happened because of a tab switch or because the user actually left the listbox. Couldn't we restore the `activeTabIndex` when focus comes back to the current tab?

Comment (behzadmehrabi) [reply src/cdk/listbox/listbox.ts:788]: mmm...I don't get risk that you are talking about. they focused out of the listbox either way and we check to see if the next focused element is either the listbox itself or a child of it...right?

I thought of maybe using `Page Visibility API`, but something surprising happens in Firefox (115)...when switching fast between tabs, it triggers 'focusout' but not the 'visibiltychange'. :/

Comment (crisbeto) [reply src/cdk/listbox/listbox.ts:788]: My understanding is that during a "regular" `focusout` event (one within the same tab) the `document.activeElement` might still be the element that is losing focus, rather than the element that focus went to. I'm concerned that if the `focusout` happens within the listbox and the browser decides not to set a `relatedTarget` for some reason, we wouldn't have a way of distinguishing it from the users switching tabs.

As for detecting when the user has switched to a different tag: I think that the `blur` handler on `window` should be enough.

Comment (behzadmehrabi) [reply src/cdk/listbox/listbox.ts]: Sorry for the delay. Could you please take a look?
Appreciate your help. ;)

File: src/cdk/listbox/listbox.ts [hunk 2]
```diff
@@ -418,6 +418,19 @@ export class CdkListbox<T = unknown> implements AfterContentInit, OnDestroy, Con
   /** Whether the listbox currently has focus. */
   private _hasFocus = false;
 
+  /** A reference to the option that was active before the listbox lost focus. */
+  private _previousActiveItem: CdkOption<T> | null = null;
+
+  constructor() {
+    fromEvent(window, 'blur')
```
Comment (crisbeto) [inline src/cdk/listbox/listbox.ts:425]: I think that we should run this outside of the `NgZone`.

File: src/cdk/listbox/listbox.ts [hunk 3]
```diff
@@ -418,6 +418,19 @@ export class CdkListbox<T = unknown> implements AfterContentInit, OnDestroy, Con
...
+      .pipe(takeUntil(this.destroyed))
+      .subscribe(() => {
```
Comment (crisbeto) [inline src/cdk/listbox/listbox.ts:427]: Can we move this into a separate class member so we don't have so much logic in the constructor?

File: src/cdk/listbox/listbox.ts [hunk 4]
```diff
@@ -418,6 +418,19 @@ export class CdkListbox<T = unknown> implements AfterContentInit, OnDestroy, Con
   /** Whether the listbox currently has focus. */
   private _hasFocus = false;
 
+  /** A reference to the option that was active before the listbox lost focus. */
+  private _previousActiveItem: CdkOption<T> | null = null;
```
Comment (crisbeto) [inline src/cdk/listbox/listbox.ts:422]: Should we call this something like `_activeItemOnWindowBlur` so it's more obvious what it's used for.

File: src/cdk/listbox/listbox.ts [hunk 5]
```diff
@@ -783,6 +796,11 @@ export class CdkListbox<T = unknown> implements AfterContentInit, OnDestroy, Con
    * @param event The focusout event
    */
   protected _handleFocusOut(event: FocusEvent) {
+    // Some browsers (e.g. Chrome and Firefox) trigger the focusout event when the user returns back to the document.
+    // To prevent losing the active item in this case, we store it in `_previousActiveItem` and restore it on the window `blur` event
+    // This ensures that the `activeItem` matches the actual focused element when the user returns to the document.
+    this._previousActiveItem = this.listKeyManager.activeItem;
```
Comment (crisbeto) [inline src/cdk/listbox/listbox.ts:802]: Instead of resetting this on each `focusout` event, would it make more sense to make something like this?

```
if (this. _activeItemOnWindowBlur) {
  this._activeItemOnWindowBlur = null;
  return;
}
```

Comment (behzadmehrabi) [reply src/cdk/listbox/listbox.ts:802]: yeah you're right...I'll reset it.
what do you think we should name the class member? :))

File: src/cdk/listbox/listbox.ts (hunk 3 above)
Comment (behzadmehrabi) [reply src/cdk/listbox/listbox.ts]: Done

File: src/cdk/listbox/listbox.ts (hunk 5 above)
Comment (behzadmehrabi) [reply src/cdk/listbox/listbox.ts]: Done

File: src/cdk/listbox/listbox.ts [hunk 6]
```diff
@@ -418,6 +419,13 @@ export class CdkListbox<T = unknown> implements AfterContentInit, OnDestroy, Con
   /** Whether the listbox currently has focus. */
   private _hasFocus = false;
 
+  /** A reference to the option that was active before the listbox lost focus. */
+  private _previousActiveOption: CdkOption<T> | null = null;
+
+  constructor(private _ngZone: NgZone) {
```
Comment (crisbeto) [inline src/cdk/listbox/listbox.ts:425]: This should use the `inject` function rather than constructor-based injection. We're trying to use it for all new code.

**Review by crisbeto — APPROVED** [review]
LGTM
