### PR TITLE
fix(form-field): FormField with outline doesn't work well with dir="r…

### LINKED ISSUE #14944: FormField with outline doesn't work well with dir="rtl"
#### What is the expected behavior?
screen shot 2019-01-25 at 00 18 27

#### What is the current behavior?
screen shot 2019-01-25 at 00 17 36

#### What are the steps to reproduce?
[Stackblitz example with steps to reproduce the issue](https://stackblitz.com/edit/material2-mat-form-field-outline-rtl-issue)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
**Latest Angular, Material, Typescript**
**OS**: OSX, Ubuntu
**Browser**: All browsers

#### Is there anything else we should know?
This issue only happen when changing between routes. Like in the StackBlitz example

### PR DESCRIPTION
**Pull request by Suresh918**
Form field with outline is not working because Directionality service  is not giving latest direction. So the direction is always 'ltr' even if we set to 'rtl'. These changes will fetch the latest direction.
Fixes #14944

### CODE REVIEW

**Comment by banminkyoz** [comment]
Hi @crisbeto,

For this issue. I want to use dir for my whole entire app. So i'v to set and remove it manually on DOM (Base on a global variable). But it seem doesn't work well.

Is there a valid way that i can get it to work. It painful if i have to use dir for all of the component i have 😢

**Comment by banminkyoz** [comment]
I'v also tried to use dir in the wrapper container inside the app. It worked, but sometime, when i changing route, it still having this problem (Only see it on the mat-form-field with outline appearance)

**Comment by banminkyoz** [comment]
I'v also tried a demo app. 

To reproduce:

1. Go to input example page
2. Click `LTR`
3. Change to any other examples page and go back to input example page
4. Click `RTL`

image

**Comment by Suresh918** [comment]
@crisbeto 
Here the issue is that the outline update logic (gaps, widths calculations, outline styles update etc in updateOutlineGap method). is getting executed before the element direction changes in the UI. Even if the direction changes from 'ltr' to 'rtl' , the logic is getting executed on 'ltr' direction only. After that the direction of element is getting changed in the UI. That's why we are getting wrong outlines ('ltr' outlines to 'rtl' vice versa).

To fix this I'm storing the previous direction and doing the outline update logic  on that so that UI and logic are in sync.

**Comment by banminkyoz** [comment]
@crisbeto can you review @Suresh918 's new updates. Thank you very much 👍

**Comment by Suresh918** [comment]
@crisbeto @jelbourn @mmalerba Can you please review the above changes

File: src/lib/form-field/form-field.ts [hunk 1]
```diff
@@ -336,7 +338,10 @@ export class MatFormField extends _MatFormFieldMixinBase
     });
 
     if (this._dir) {
-      this._dir.change.pipe(takeUntil(this._destroyed)).subscribe(() => this.updateOutlineGap());
+      this._dir.change.pipe(takeUntil(this._destroyed)).subscribe(() => {
+        this.updateOutlineGap();
+        this._previousDirection = this._dir.value;
```
Comment (mmalerba) [inline src/lib/form-field/form-field.ts]: why is the direction not updated until after calling `updateOutlineGap`?

Comment (mmalerba) [reply src/lib/form-field/form-field.ts]: Oh sorry I just read your explanation above, can you add a comment to the code. It looks wrong at first glance, without a note explaining it.

Comment (crisbeto) [reply src/lib/form-field/form-field.ts]: Even looking at the description on the PR, I'm not quite sure whether this will cover all the cases. [The event will only if a new value is set](https://github.com/angular/material2/blob/master/src/cdk/bidi/dir.ts#L56). Also we probably need a unit test for this.

Comment (Suresh918) [reply src/lib/form-field/form-field.ts]: @crisbeto @mmalerba "gulp test" and "gulp serve:devapp" are not working in my local. Do I need to do any configuration changes? Can you help me in running test cases? Even I tried "karma run", that's also giving errors in the console.

Comment (Suresh918) [reply src/lib/form-field/form-field.ts]: gulp test is working fine when i updated the node packages. But is there any way to run specific test suite ?

Comment (Suresh918) [reply src/lib/form-field/form-field.ts]: @crisbeto @mmalerba I added test cases and comments. Can you please review those.

**Comment by Suresh918** [comment]
@crisbeto @mmalerba  Can you please review the changes.

File: src/lib/input/input.spec.ts [hunk 2]
```diff
@@ -1448,6 +1448,61 @@ describe('MatInput with appearance', () => {
...
+      fakeDirectionality.value = 'rtl';
+      fakeDirectionality.change.next('rtl');
+      outlineFixture.detectChanges();
+      flush();
+      outlineFixture.detectChanges();
+
+      let wrapperElement = outlineFixture.nativeElement;
+      let outlineStart = wrapperElement.querySelector('.mat-form-field-outline-start');
+      // outlineGapPadding 5px + containerRect margin/padding in worst case 3px
+      const maxOutlineStart = '8px';
```
Comment (mmalerba) [inline src/lib/input/input.spec.ts]: why not just make this a number?

**Comment by andrewseguin** [comment]
Change passed tests internally, just needs to be rebased and we can merge it in

**Comment by mmalerba** [comment]
I've gone ahead and merged in upstream/master for you @Suresh918

**Comment by kyoz** [comment]
@mmalerba Can we have this merge in next release, it's seem pending for a long time. Thank you :heart:
