### PR TITLE
fix(menu): throw error if menu contains its own trigger

### LINKED ISSUE #19941: bug(mat-menu): Clicking a [matMenuTriggerFor] inside its own mat-menu crashes JS
Note: This might be an invalid use case, as it's wrongly using a directive. Still, it wouldn't hurt to have a safety check to prevent this.

#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-japg2m?file=src%2Fapp%2Fmenu-overview-example.html

Steps to reproduce:
```
<button [matMenuTriggerFor]="menu">Open</button>
<mat-menu #menu="matMenu">
  <button [matMenuTriggerFor]="menu">Close</button>
</mat-menu>
```
1. Click "Open"
2. Click Close
3. Open console and observe fatal error:
```
ERROR Error: Maximum call stack size exceeded
ERROR Error: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
```
 
 
#### Expected Behavior

Page (main JS thread) shouldn't crash when having a closing button inside the menu.

#### Actual Behavior

Page (main JS thread) crashes.

#### Environment

- Angular: 10.x
- CDK/Material: 10.x
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

### PR DESCRIPTION
**Pull request by crisbeto**
If the consumer puts a trigger inside a menu and passes the menu back to the trigger, we'll go into an infinite loop and throw a cryptic error message. These changes detect such a case and throw a better error. Example of a case that will be flagged:

```
<mat-menu #menu="matMenu">
  <button [matMenuTriggerFor]="menu"></button>
</mat-menu>
```

Fixes #19941.

### CODE REVIEW

**Comment by tomasdev** [comment]
Excellent!!!

**Comment by tomasdev** [comment]
OMG that was fast!! Thank you so much @crisbeto !!!!

File: src/material/menu/menu-trigger.ts [hunk 1]
```diff
@@ -121,6 +121,10 @@ export class MatMenuTrigger implements AfterContentInit, OnDestroy {
     this._menuCloseSubscription.unsubscribe();
 
     if (menu) {
+      if (menu === this._parentMenu) {
```
Comment (jelbourn) [inline src/material/menu/menu-trigger.ts:124]: Let's only do this in dev mode
(thinking long term to when we'll be able to drop dev mode checks from the prod output)

**Comment by crisbeto** [comment]
I've addressed the feedback. I added a dev mode check around the other assertion as well.
