### PR TITLE
mat-tooltip: ensure message is converted to string

### LINKED ISSUE #20684: bug(tooltip): Closure-compiled code skips toString() in Tooltip.message setter
#### Background

In 
https://github.com/angular/components/blob/e99ca0ac9b0088d20d5d680092cd7ea5624934c0/src/material/tooltip/tooltip.ts#L212, we see:

```ts
  set message(value: string) {
    this._ariaDescriber.removeDescription(this._elementRef.nativeElement, this._message);

    // If the message is not a string (e.g. number), convert it to a string and trim it.
    this._message = value != null ? `${value}`.trim() : '';
```

The intention of the code is to convert non-strings, then trim.

#### Reproduction

Steps to reproduce:

1. Compile `MatTooltip` component with Closure Compiler (Google JS Compiler) with `--use_types_for_optimization`.
2. Pass a non-string object to `MatTooltip.message`'s setter. (in the case causing the crash for me, someone was passing an `Error` object)

#### Expected Behavior

The input gets coerced to a string, and the `.trim()` call succeeds.

#### Actual Behavior

Closure compiler optimises out the stringification, and the `.trim()` call fails with `trim is not a function`. Closure compiler outputs this code:

```
this.mH = null != a ? a.trim() : "";
```

Closure compiler has optimised out the stringify step.

#### Environment

- Angular: Latest
- CDK/Material: Latest
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

### PR DESCRIPTION
**Pull request by mhansen**
This ensures that the Closure Compiler doesn't optimise out the format-string stringification.

I've only changed the setter's argument type, and have left `TooltipComponent.message` to be declared as string, with the reasoning that most users will want a type error if they try to set a non-string type.

I'm trying to maintain the runtime API of this code in the face of type-based optimisations.

Fixes #20684

### CODE REVIEW

File: src/material/tooltip/tooltip.ts [hunk 1]
```diff
@@ -205,7 +205,7 @@ export class MatTooltip implements OnDestroy, AfterViewInit {
   /** The message to be displayed in the tooltip */
   @Input('matTooltip')
   get message() { return this._message; }
-  set message(value: string) {
+  set message(value: any) {
```
Comment (crisbeto) [inline src/material/tooltip/tooltip.ts:208]: I don't think that we should sacrifice type safety to appease Closure. Can we try one of these solutions to stop it from being optimized away (imagine the quotes are backticks)?

1. `"${(value as any)}".trim()`
2. `"${value} ".trim()`. Note the extra whitespace at the end which will be removed by `trim`.

**Comment by mhansen** [comment]
Sure, I can give these a go. I might try the first option tomorrow -- I
imagine an overzealous compiler might still optimize out the extra space
and the trim call (probably not, but maybe one day?)

File: src/material/tooltip/tooltip.ts (hunk 1 above)
Comment (mhansen) [reply src/material/tooltip/tooltip.ts]: Thanks, just gave that a go. First option:

```
function x(value: string) {
  return `${(value as any)}`.trim();
}
console.log(x(document.domain));
```

still elides the stringification:

```
console.log(document.domain.trim());
```

Comment (mhansen) [reply src/material/tooltip/tooltip.ts]: Second option works:
```
function x(value: string) {
  return `${value} `.trim();
}
console.log(x(document.domain));
```
compiles to
```
console.log((document.domain+" ").trim());
```

Comment (mhansen) [reply src/material/tooltip/tooltip.ts]: Another option (I think this is my favourite) that works:

```
function x(value: string) {
  return String(value).trim();
}
console.log(x(document.domain));
```
compiles to
```
console.log(String(document.domain).trim());
```

Comment (crisbeto) [reply src/material/tooltip/tooltip.ts]: I like the third option as well, just make sure to add a comment about why we have to write it this way.

Comment (mhansen) [reply src/material/tooltip/tooltip.ts]: Done, thanks for your thoughtful review -- this is much better :-)

**Review by crisbeto — APPROVED** [review]
LGTM

**Comment by mhansen** [comment]
Looks like the `lint` CI is failing for a commit that isn't mine?

```
✘  Invalid commit message
test(material-experimental): add missing test coverage (#20678)
```

That's not my commit message
