### PR TITLE
fix(material/input): do not override existing aria-describedby value

### LINKED ISSUE #19528: bug(input): matInput overwrites aria-described by
Copied from internal bug report:

According to https://material.angular.io/components/input/overview#accessibility:

> Any mat-error and mat-hint are automatically added to the input's aria-describedby list,...

but it seems they are not added but replace the pre-existing aria-describedby, see [here](https://github.com/angular/components/blob/8008218223b621d9bedb857c56364eceb85cd89e/src/material/input/input.ts#L84)

We use the aria-describedby to announce keyboard shortcuts for sending the form, and that breaks if matInput overwrites this.

Would it be possible to store the previous aria-describedby attribute and maintain it whenever setting this? That seems more inline with the docs and allows e.g. our use case.

cc: @rehmsen

### PR DESCRIPTION
**Pull request by devversion**
The form-field notifies controls whenever hints or errors have
been displayed. It does this, so that controls like the input
can refresh their `aria-describedby` value to point to the errors
and hints.

This currently has the downside of overriding existing
`aria-describedby` values that have been manually set by
developers. We could fix this by reading the initial value
and merging it with the ids received from the form-field.

Fixes #19528

### CODE REVIEW

File: src/material/input/input.ts [hunk 1]
```diff
@@ -232,7 +234,8 @@ export class MatInput extends _MatInputMixinBase implements MatFormFieldControl<
     _defaultErrorStateMatcher: ErrorStateMatcher,
     @Optional() @Self() @Inject(MAT_INPUT_VALUE_ACCESSOR) inputValueAccessor: any,
     private _autofillMonitor: AutofillMonitor,
-    ngZone: NgZone) {
+    ngZone: NgZone,
+    @Attribute('aria-describedby') private _initialAriaDescribedBy?: string|null) {
```
Comment (devversion) [inline src/material/input/input.ts:238]: @mmalerba This is more of a proposal at this point. I feel slightly unhappy that we'd need to do this for all custom form-field controls. I think that it would be correct though to not override static `aria-described` values.

Possible solutions:

1. Go with the one currently outlined in this PR. That might be cumbersome/repetitive to add to all custom controls. There is some duplication anyway already.. and it's inevitable to elide all of it.
2. Pass the initial described by value to the abstract form-control, and then the form-field will merge it automatically. That means less work for custom controls (except for still doing the attribute injection)
3. Accept `aria-described` on the form-field and merge it there (before calling `setDescribedByIds`). That is most convenient for controls, but less for users as we'd still silently override existing `aria-describedby` values.

Note that all of these approaches have the downside of not supporting dynamically changing `aria-describedby` values. It wouldn't be easy to detect these attribute changes, unless we make it an input. I have a feeling that the ideal solution would be **(2)** with the use of an `@Input('aria-describedby`) userAriaDescribedBy: string = ''`. That would be the only line custom controls would need to add then.

Comment (mmalerba) [reply src/material/input/input.ts:238]: I would probably add an `@Input` to the `matInput`, you _can_ use it outside of the form field, but that's not something we go out of our way to support

Comment (devversion) [reply src/material/input/input.ts:238]: yeah, that's fair. We can make it clear with a small comment on the input. I'll experiment with it. thx for the feedback so far.

Comment (devversion) [reply src/material/input/input.ts]: @mmalerba Updated the proposal. Please have another look when you get a chance.

File: src/material/form-field/form-field-control.ts [hunk 2]
```diff
@@ -63,6 +63,12 @@ export abstract class MatFormFieldControl<T> {
    */
   readonly autofilled?: boolean;
 
+  /**
+   * Value of `aria-describedby` that should be merged with the described-by ids
+   * which are set by the form-field.
+   */
+  readonly userAriaDescribedBy?: string;
```
Comment (mmalerba) [inline src/material/form-field/form-field-control.ts:70]: can we add a bit about this to the docs?

Comment (devversion) [reply src/material/form-field/form-field-control.ts:70]: yeah, that's fair. Added it to the guide and updated our custom control example.

File: guides/creating-a-custom-form-field-control.md [hunk 3]
```diff
@@ -339,15 +339,30 @@ controlType = 'example-tel-input';
 
 #### `setDescribedByIds(ids: string[])`
 
-This method is used by the `<mat-form-field>` to specify the IDs that should be used for the
-`aria-describedby` attribute of your component. The method has one parameter, the list of IDs, we
-just need to apply the given IDs to our host element.
+This method is used by the `<mat-form-field>` to set element ids that should be used for the
```
Comment (mmalerba) [inline guides/creating-a-custom-form-field-control.md:342]: Nice, I think this makes it a lot more clear why both properties exist / what they're for

**Comment by jelbourn** [comment]
@devversion can you rebase when you get a chance?

**Comment by devversion** [comment]
@jelbourn Done

**Comment by devversion** [comment]
This is green now and rebased.
