### PR TITLE
Form field aria-describedby fixes

### LINKED ISSUE #30011: bug(mat-form-field): Form field removes aria-describedby attribute added by AriaDescriber
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

Hello,

We have mat input inside the mat form field, and noticed that the input's `aria-describedby` attribute gets removed on focus or state change if the `aria-describedby` ids were added by [AriaDescriber](https://source.corp.google.com/piper///depot/google3/third_party/javascript/angular_components/src/cdk/a11y/aria-describer/aria-describer.ts;rcl=696175970;l=57). When the input receives focus, [`_syncDescribedByIds`](https://source.corp.google.com/piper///depot/google3/third_party/javascript/angular_components/src/material/form-field/form-field.ts;l=634-673?q=third_party%2Fjavascript%2Fangular_components%2Fsrc%2Fmaterial%2Fform-field%2Fform-field.ts&ct=os&sq=package:piper%20file:%2F%2Fdepot%2Fgoogle3%20-file:google3%2Fexperimental#:~:text=633-,634,-635) is run, but it determines that the list of `ids` is empty, causing `aria-describedby` attribute to be removed from the input.

It seems that `_syncDescribedByIds` does not account for ids added by `AriaDescriber`, and solution may be an update to the `_syncDescribedByIds` logic.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-starter-1gvgxn?file=src%2Fmain.ts
Steps to reproduce:
1. Observe that <input> has `aria-describedby` attribute.
2. Focus on the <input> by clicking on it.
3. Observe that `aria-describedby` attribute is removed from <input>.

### Expected Behavior

`aria-describedby` attribute that were added via `AriaDescriber` should not be removed.

### Actual Behavior

`aria-describedby` attribute that were added via `AriaDescriber` are removed.

### Environment

- Angular:
- CDK/Material: 18.2.13
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

### PR DESCRIPTION
**Pull request by crisbeto**
Includes the following fixes for how we deal with `ariab-describedby` in the form field:

### fix(material/form-field): avoid touching the DOM on each state change 

Currently we set the `aria-describedby` every time the state of the form control changes. This is excessive, because it only needs to happen if the error state or `userAriaDescribedBy` change.

### fix(material/input): preserve aria-describedby set externally 

Currently there are two sources of an `aria-describedby` for a `matInput`: the IDs of the hint/error message in the form field and any custom ones set through `aria-describedby`. This is insufficient, because the ID can also come from a direct DOM manipulation like in the `AriaDescriber`.

These changes tweak the logic to try and preserve them, because currently they get overwritten.

Fixes #30011.

### CODE REVIEW

File: src/material/form-field/form-field.ts [hunk 1]
```diff
@@ -426,10 +428,22 @@ export class MatFormField
     this._stateChanges?.unsubscribe();
     this._stateChanges = control.stateChanges.subscribe(() => {
       this._updateFocusState();
-      this._syncDescribedByIds();
       this._changeDetectorRef.markForCheck();
     });
 
+    // Updating the `aria-describedby` touches the DOM. Only do it if it actually needs to change.
+    this._describedByChanges?.unsubscribe();
+    this._describedByChanges = control.stateChanges
```
Comment (crisbeto) [inline src/material/form-field/form-field.ts:436]: I tried basing this on top of signals, but the timing was off because I had to run `_syncDescribedByIds` in an effect.

Comment (mmalerba) [reply src/material/form-field/form-field.ts:436]: Ideally we'll do a bigger refactor at some point and replace `syncDescribedByIds` with a signal, `describedByIds`

**Review by mmalerba — APPROVED** [review]

File: src/material/form-field/form-field.ts (hunk 1 above)
Comment (crisbeto) [reply src/material/form-field/form-field.ts:436]: Yep, I'd argue pretty much all the properties in the `FormFieldControl` should be signals.
