### PR TITLE
fix(material/schematics): generate code that works in strict CLI projects

### LINKED ISSUE #21981: bug(material/schematics): table schematic does not generate code that works with strict mode
#### Reproduction

Steps to reproduce:
1. `ng new` with strict mode on
2. ` ng add @angular/material`
3. ` ng g @angular/material:table table`
4. `npm start`
 
 
#### Expected Behavior

What behavior were you expecting to see?
The app should build and work.

#### Actual Behavior

What behavior did you actually see?
```ts
Error: src/app/table/table-datasource.ts:44:3 - error TS2564: Property 'paginator' has no initializer and is not definitely assigned in the constructor.

44   paginator: MatPaginator;
     ~~~~~~~~~


Error: src/app/table/table-datasource.ts:45:3 - error TS2564: Property 'sort' has no initializer and is not definitely assigned in the constructor.

45   sort: MatSort;
     ~~~~


Error: src/app/table/table.component.ts:13:28 - error TS2564: Property 'paginator' has no initializer and is not definitely assigned in the constructor.

13   @ViewChild(MatPaginator) paginator: MatPaginator;
                              ~~~~~~~~~


Error: src/app/table/table.component.ts:14:23 - error TS2564: Property 'sort' has no initializer and is not definitely assigned in the constructor.

14   @ViewChild(MatSort) sort: MatSort;
                         ~~~~


Error: src/app/table/table.component.ts:15:24 - error TS2564: Property 'table' has no initializer and is not definitely assigned in the constructor.
[39m[0m
15   @ViewChild(MatTable) table: MatTable<TableItem>;
                          ~~~~~


Error: src/app/table/table.component.ts:16:3 - error TS2564: Property 'dataSource' has no initializer and is not definitely assigned in the constructor.

16   dataSource: TableDataSource;
     ~~~~~~~~~~


Error: src/app/table/table.component.html:20:34 - error TS2532: Object is possibly 'undefined'.

20       [length]="dataSource?.data.length"
                                    ~~~~~~

  src/app/table/table.component.ts:9:16
    9   templateUrl: './table.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component TableComponent.
```

#### Environment

- Angular: 11.2.1
- CDK/Material: 11.2.1
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Catalina

Relates to https://github.com/angular/components/issues/17135

### PR DESCRIPTION
**Pull request by Splaktar**
- fix `strictNullChecks` errors
- fix `strictPropertyInitialization` errors
- default to smaller paginator rows so that paging works out of the box
- fix tslint errors from default CLI settings

Fixes #21981

### CODE REVIEW

File: src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__-datasource.ts.template [hunk 1]
```diff
@@ -54,46 +54,54 @@ export class <%= classify(name) %>DataSource extends DataSource<<%= classify(nam
...
-    // stream for the data-table to consume.
-    const dataMutations = [
-      observableOf(this.data),
-      this.paginator.page,
-      this.sort.sortChange
-    ];
+     if (this.paginator && this.sort) {
+       // Combine everything that affects the rendered data into one update
+       // stream for the data-table to consume.
+       const dataMutations = [
```
Comment (crisbeto) [inline src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__-datasource.ts.template:60]: While we're at it, it might be better to pass these in as individual parameters to `merge`, rather than creating an array and then spreading it.

**Review by crisbeto — APPROVED** [review]
LGTM
