### PR TITLE
fix(a11y): focus monitor not checking children if monitor is called multiple times with different parameters

### LINKED ISSUE #19218: bug(MatSort/MatTooltip): Sort headers keyboard focus indicator not working when the header has a MatTooltip
#### Reproduction
Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-bvhoxg?file=src/app/table-sorting-example.html

Steps to reproduce:
1. Tab through the table columns and notice the weight header column does not have a keyboard focussed indicator. 
2. If you remove the tooltip the column the indicator works as expected.
  
#### Expected Behavior
What behavior were you expecting to see?
All columns should get the keyboard focussed indicator. Not only the columns without a tooltip.

#### Actual Behavior
What behavior did you actually see?
The header with the tooltip did not get the keyboard focussed indicator.

#### Environment
- Angular: 9+
- CDK/Material: 9+
- Browser(s): FF 75, Chrome 81 and Edge 81
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

First issue: https://github.com/angular/components/issues/17716

### PR DESCRIPTION
**Pull request by crisbeto**
With the current logic, if an element is being monitored with `checkChildren` set to `true` and then we start monitoring it with `false`, the initial monitor call will stop checking the children, because we take the `checkChildren` value from the most-recent call. This is something that we discussed in https://github.com/angular/components/pull/19135#discussion_r412471591, but now we have a case where it can happen: setting a tooltip on a sort header. The sort header looks for child focus, whereas the tooltip doesn't, causing the sort focus indication to break.

These changes fix the issue by treating all focus as `checkChildren`, as soon as there's at least one call to `monitor` with `checkChildren` turned on.

Fixes #19218.

### CODE REVIEW

File: src/cdk/a11y/focus-monitor/focus-monitor.ts [hunk 1]
```diff
@@ -235,11 +235,14 @@ export class FocusMonitor implements OnDestroy {
...
     const rootNode = (_getShadowRoot(nativeElement) as HTMLElement|null) || this._getDocument();
+    const cachedInfo = this._elementInfo.get(nativeElement);
 
     // Check if we're already monitoring this element.
-    if (this._elementInfo.has(nativeElement)) {
-      const cachedInfo = this._elementInfo.get(nativeElement)!;
-      cachedInfo.checkChildren = checkChildren;
+    if (cachedInfo) {
+      if (checkChildren) {
+        cachedInfo.checkChildren = true;
```
Comment (crisbeto) [inline src/cdk/a11y/focus-monitor/focus-monitor.ts:243]: @mmalerba I think that this will work for most of the cases, but I'm not sure whether it's ideal. This means that the initial subscriber that signed up only for focus events on the element will now get emissions from children as well. Ideally, we'd be keeping track of two separate streams: own focus and child focus, but I didn't do it in this PR, because there are some issues with having two streams:

1. There can be a conflict between the CSS focus classes, because both the `checkChildren` and the non-`checkChildren` calls are trying to set the same classes on the same element.
2. We'd need a way to match focus either to the own focus stream or the child focus stream. Matching it is easy, but it can have performance implications, because we'd have to loop through and check all of the monitored elements on each `focus` and `blur` event.
3. We'd have to introduce a `checkChildren` parameter on `stopMonitoring` so that the two streams can be stopped independently. This would either have to be breaking API change, or we'd introduce memory leaks in people's code, because their `stopMonitoring` calls won't work anymore.

Comment (mmalerba) [reply src/cdk/a11y/focus-monitor/focus-monitor.ts:243]: Ok those are some good points, especially #⁠1. Can you file a design issue with the above and link it in a TODO? This PR seems like the best option for the moment, but it would be good to have that documented

**Comment by crisbeto** [comment]
I've addressed the feedback @mmalerba.
