### PR TITLE
fix(datepicker): not showing single-day comparison ranges

### LINKED ISSUE #20100: bug(mat-date-range-picker): comparison range not rendered if the range is a single day
#### Reproduction

StackBlitz: https://stackblitz.com/edit/components-issue-e3gewx

Steps to reproduce:
1. Have a comparison range of a single day
2. Open date range picker
 
 
#### Expected Behavior

What behavior were you expecting to see?
The date range picker to show the single day in the comparison range in yellow

#### Actual Behavior

What behavior did you actually see?
No comparison range indicated at all in the date range picker

#### Environment

- Angular: 10.0.3
- CDK/Material: 10.1.0
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu):  All

### PR DESCRIPTION
**Pull request by crisbeto**
The logic that determines whether we show something as being a range doesn't allow for the start and end to be on the same date, because it increases the CSS complexity a lot. As a result, we aren't able to render ranges that start and end on the same day. This isn't a problem for the main range, because we style its start and end as selected which looks exactly the same as the start/end of a range, however it breaks down for the comparison range since it doesn't have the same selected styling for its start/end cells.

These changes fix the issue by introducing a special class for the case where the comparison range is for a single day. While it's not ideal, it's preferrable to complicating the CSS for the range styling.

Fixes #20100.

### CODE REVIEW

File: src/material/datepicker/calendar-body.ts [hunk 1]
```diff
@@ -270,6 +270,23 @@ export class MatCalendarBody implements OnChanges, OnDestroy {
...
+   * the regular range, because when it happens, the selected styles take over and still show where
+   * the range would've been, however we don't have these selected styles for a comparison range.
+   * This function is used to apply a class that serves the same purpose as the one for selected
+   * dates, but it only applies in the context of a comparison range.
+   */
+  _isComparisonIdentical(value: number) {
+    // Note that we don't need to null check the start/end
+    // here, because the `value` will always be defined.
+    return this.comparisonStart === this.comparisonEnd && value === this.comparisonStart &&
+           value === this.comparisonEnd;
```
Comment (mmalerba) [inline src/material/datepicker/calendar-body.ts:287]: Do we need the last clause? I think the first 2 together imply the 3rd

Comment (crisbeto) [reply src/material/datepicker/calendar-body.ts:287]: Good point. Removing.
