### PR TITLE
fix(cdk/a11y): allow for multiple browser-generated description containers

### LINKED ISSUE #23499: feat(COMPONENT): allow multiple instances of AriaDescriber
#### Feature Description

Allow to have several [AriaDescriber](https://github.com/angular/components/blob/master/src/cdk/a11y/aria-describer/aria-describer.ts) containers on a same page.
Today the container of `AriaDescriber` is necessarily appended to body, with an hardcoded id, and any pre-existing container is removed.

I see At least 3 different options to achieve this:

1. Do something similar to what's done in [LiveAnnouncer](https://github.com/angular/components/blob/master/src/cdk/a11y/live-announcer/live-announcer.ts): use an Injection token to inject the container.

2. Make the following constant customizable: MESSAGES_CONTAINER_ID . So that each instance of `AriaDescriber` can have his own container.

3. Do something similar to [OverlayContainer](https://github.com/angular/components/blob/master/src/cdk/overlay/overlay-container.ts) so that the container can be moved somewhere else on the page, and stop relying on the ID the remove it 

In all cases, the following const should be customizable: `CDK_DESCRIBEDBY_ID_PREFIX`, otherwise elements with duplicated ID will be created on the page.

#### Use Case

In the context of micro frontends, we may end up with 2 Angular Material instances on the same page.

Today, a second instance of `AriaDescriber` would remove the container of the first one, making it ineffective.

### PR DESCRIPTION
**Pull request by crisbeto**
Currently the `AriaDescriber` is set up to clear all description containers whenever it is instantiated, in order to avoid duplicates coming in from the server. The problem is that there are legitimate use cases where we could have multiple containers (e.g. multiple CDK instances in a micro frontend architecture).

These changes rework the internal setup of the `AriaDescriber` so that it only clears containers from server and it doesn't touch containers coming from other describer instances.

Fixes #23499.

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM

File: src/cdk/a11y/aria-describer/aria-describer.ts [hunk 1]
```diff
@@ -77,8 +98,8 @@ export class AriaDescriber implements OnDestroy {
     if (typeof message !== 'string') {
       // We need to ensure that the element has an ID.
       setMessageId(message);
```
Comment (Yqnn) [inline src/cdk/a11y/aria-describer/aria-describer.ts:100]: The same ID would be assigned twice if the AriaDescriber symbol is packaged twice :
image

Comment (crisbeto) [reply src/cdk/a11y/aria-describer/aria-describer.ts:100]: Hmm, how would that happen? We're keeping the counter for unique IDs outside of the class so it'll be global for all instances: https://github.com/angular/components/blob/master/src/cdk/a11y/aria-describer/aria-describer.ts#L36. The only way I can see this happening is if the script was somehow loaded twice.

Comment (yann-armelin) [reply src/cdk/a11y/aria-describer/aria-describer.ts:100]: Yes having the library loaded twice may happend (even if not recommended for performance).


*My use case is the following*: I'm developing a prebuilt UI component that can handle payment with various payment methods in a secure way. It's a full angular application wrapped inside a single Javascript file, and that can be used in any website, no matter the framework it uses.
If the website is also using Angular CDK, the AriaDescriber script will be loaded twice.

( Having the CDK_DESCRIBEDBY_ID_PREFIX variable customizable would be enough to work around this issue )

Comment (crisbeto) [reply src/cdk/a11y/aria-describer/aria-describer.ts:100]: Supporting this won't be practical on our end, because even if we did handle it in the `AriaDescriber`, we have many more places that are set up in a similar way and which could break by generating duplicate IDs.

**Comment by RadhikaGunisetty** [comment]
@crisbeto Please rebase this PR.

**Comment by crisbeto** [comment]
Rebased.

File: src/cdk/a11y/aria-describer/aria-describer.ts [hunk 2]
```diff
@@ -148,49 +168,54 @@ export class AriaDescriber implements OnDestroy {
...
-    messageRegistry.delete(key);
+    this._messageRegistry.get(key)?.messageElement?.remove();
+    this._messageRegistry.delete(key);
   }
 
   /** Creates the global container for all aria-describedby messages. */
   private _createMessagesContainer() {
-    if (!messagesContainer) {
-      const preExistingContainer = this._document.getElementById(MESSAGES_CONTAINER_ID);
+    if (this._messagesContainer) {
```
Comment (andrewseguin) [inline src/cdk/a11y/aria-describer/aria-describer.ts:183]: An internal test broke because the tooltip's message was changed and they wanted to confirm the aria-describeby was accurate. After the tooltip's message is changed, the container was removed but not set to null, so when it tried to set up the new message, this just returned.

Fix: When calling `this._messagesContainer?.remove()`, also set it to null.

Comment (crisbeto) [reply src/cdk/a11y/aria-describer/aria-describer.ts:183]: Done.
