### PR TITLE
Bug #29047 - Glitchy password form field 

### LINKED ISSUE #29047: Glitchy password form field
### Documentation Feedback

Example of password form field is glitching when you are clicking show/hide button while there is no text in the field. I solved it by adding $event.stopPropagation() on button click event.

### Affected documentation page

https://material.angular.io/components/form-field/overview

### PR DESCRIPTION
**Pull request by maruthumj**
fixes #29047

### CODE REVIEW

File: src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.ts [hunk 1]
```diff
@@ -14,4 +14,8 @@ import {MatFormFieldModule} from '@angular/material/form-field';
 })
 export class FormFieldPrefixSuffixExample {
   hide = true;
+  clickEvent(event: any) {
```
Comment (crisbeto) [inline src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.ts:17]: You can replace the any here with MouseEvent.

Comment (maruthumj) [reply src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.ts:17]: Thanks for your valuable input. Will do the same 🙂

Comment (maruthumj) [reply src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.ts]: > You can replace the any here with MouseEvent.

pushed the changes. please verify

**Review by crisbeto — APPROVED** [review]
