### PR TITLE
fix(platform): detect and ignore scrollBehavior polyfills

### LINKED ISSUE #17847: CdkVirtualScrollViewport smooth scroll not working in Safari
#### Reproduction

Here's a fork of virtual scroll demo with a button to reproduce the issue:
https://stackblitz.com/edit/angular-virtual-scroll-smooth-ios

Steps to reproduce:
1. Call scrollToOffset/scrollToIndex with `'smooth'` behavior on Safari
 
 
#### Expected Behavior

Viewport scrolls smoothly

#### Actual Behavior

Viewport scrolls immediately in Safari and smoothly in good browsers

#### Environment

- Angular: 8.2.3
- CDK/Material: 8.2.3
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS/iOS

#### Other details

This is probably because it uses native scrollIntoView with behavior and it is not supported in Safari. If Angular team will not include the fallback with its CDK, it is probably good to mention this limitation on the Scrolling demo page of the CDK.

### PR DESCRIPTION
**Pull request by crisbeto**
We use the `supportsScrollBehavior` function to check whether to try and pass in the scroll options object to `Scrollable.scrollTo` since passing it in on a browser that doesn't support it won't do anything. The problem is that the only way to detect if scroll behavior is supported is to look for the `scrollBehavior` property on a DOM element's CSS styles, however this will cause scroll behavior polyfills to be ignored since they only modify `Element.prototype.scrollTo`.

These changes try to detect whether `scrollTo` has been polyfilled, and if it has, we consider it as being supported.

Fixes #17847.

### CODE REVIEW

File: src/cdk/platform/features/scrolling.ts [hunk 1]
```diff
@@ -28,9 +28,38 @@ export const enum RtlScrollAxisType {
...
+      // At this point we have 3 possibilities: `scrollTo` isn't supported at all, it's
+      // supported but it doesn't handle scroll behavior, or it has been polyfilled.
+      const scrollToFunction: Function|undefined = Element.prototype.scrollTo;
+
+      if (scrollToFunction) {
+        // We can detect if the function has been polyfilled by calling `toString` on it. Native
+        // functions are obfuscated using `[native code]`, whereas if it was overwritten we'd get
+        // the actual function source. Via https://davidwalsh.name/detect-native-function. Consider
+        // polyfilled functions as supporting scroll behavior.
+        scrollBehaviorSupported = /\{\s*\[native code\]\s*\}/.test(scrollToFunction.toString());
```
Comment (crisbeto) [inline src/cdk/platform/features/scrolling.ts:55]: This is a little hacky, but it seems to work. Another approach I was considering was similar to the `getRtlScrollAxisType` which creates an element and tries to scroll it which is definitely better, but I decided not to do it, because it doesn't actually detect if `scrollBehavior` is supported, but rather that the `ScrollOption` object parameter is supported. While that would fix the original issue of polyfills not being picked up, it would mean that the name of `supportsScrollBehavior` wouldn't match with what it was actually doing.

File: src/cdk/platform/features/scrolling.ts [hunk 2]
```diff
@@ -28,9 +28,38 @@ export const enum RtlScrollAxisType {
...
+    } else {
+      // At this point we have 3 possibilities: `scrollTo` isn't supported at all, it's
+      // supported but it doesn't handle scroll behavior, or it has been polyfilled.
+      const scrollToFunction: Function|undefined = Element.prototype.scrollTo;
+
+      if (scrollToFunction) {
+        // We can detect if the function has been polyfilled by calling `toString` on it. Native
+        // functions are obfuscated using `[native code]`, whereas if it was overwritten we'd get
+        // the actual function source. Via https://davidwalsh.name/detect-native-function. Consider
+        // polyfilled functions as supporting scroll behavior.
```
Comment (jelbourn) [inline src/cdk/platform/features/scrolling.ts:54]: I don't quite understand- if we treat a polyfill as fully supported, why check for a native implementation?

Comment (crisbeto) [reply src/cdk/platform/features/scrolling.ts:54]: The problem is that pretty much all browsers support these two signatures: `scrollTo(options: {top: number, left: number, behavior: string})` or `scrollTo(top: number, left: number)`, whereas Safari only supports the latter. If we were to pass in an object to Safari nothing would happen so we have to detect if it's polyfilled. A bit above we detect whether the `behavior` parameter is supported which is a good indicator that the object is supported too.

Comment (jelbourn) [reply src/cdk/platform/features/scrolling.ts:54]: Wouldn't this check return `true` for Safari, then, when the behavior config isn't supported?

Comment (crisbeto) [reply src/cdk/platform/features/scrolling.ts:54]: I messed it up here, because I didn't negate the check. It should be correct now.

Comment (jelbourn) [reply src/cdk/platform/features/scrolling.ts:54]: Yay code review

Comment (waterplea) [reply src/cdk/platform/features/scrolling.ts:54]: I used to check for focusOptions preventScroll support with this technique:

```
    let supported = false;

    document.createElement('div').focus({
        get preventScroll() {
            supported = true;

            return false;
        },
    });
```

Looks like it could work here too, to check if browser tries to retrieve value of behavior key in a passed object.
