### PR TITLE
fix(material/datepicker): calendar reopening on spacebar selection

### LINKED ISSUE #23305: bug(datepicker): Hitting space key to select date reopens picker on Firefox
#### Reproduction

Steps to reproduce:
1. Open [https://material.angular.io/components/datepicker/overview](https://material.angular.io/components/datepicker/overview) with Firefox.
2. See first example on page ('Basic datepicker'). Press button to open the picker.
3. Try pressing space key to save the date. 
 
#### Expected Behavior
Should save the date and close the picker.

#### Actual Behavior
Datepicker closes then instantly reopens.

#### Environment
Firefox v90.0.2

- Angular: v10.2.x, but also present in v12.1.x
- CDK/Material: v10.2.x, but also present in v12.1.x
- Browser(s): Firefox v90.0.2
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the Material calendar was reopening immediately when a date is selected using the spacebar on Firefox.

Fixes #23305.

### CODE REVIEW

File: src/material/datepicker/month-view.ts [hunk 1]
```diff
@@ -285,9 +288,14 @@ export class MatMonthView<D> implements AfterContentInit, OnChanges, OnDestroy {
         break;
       case ENTER:
       case SPACE:
-        if (!this.dateFilter || this.dateFilter(this._activeDate)) {
-          this._dateSelected({value: this._dateAdapter.getDate(this._activeDate), event});
+        this._selectionKeyPressed = true;
```
Comment (mmalerba) [inline src/material/datepicker/month-view.ts:291]: Do we need the `_selectionKeyPressed` stuff? I would think if we get a `keyup` for `ENTER`/`SPACE` it's safe to assume there was a `keydown`

Comment (crisbeto) [reply src/material/datepicker/month-view.ts:291]: The keydown could've come from outside the calendar. E.g. the browser fires the `click` when doing an `ENTER` keydown on the datepicker toggle.

**Review by mmalerba — APPROVED** [review]
