### PR TITLE
fix(cdk/text-field): avoid page jump on auto-resize

### LINKED ISSUE #23834: bug(cdkTextareaAutosize): autosize scrolls parent to top at each key hit with ngZoneEventCoalescing enabled
#### Reproduction

1. open in chrome https://stackblitz.com/edit/angular-dqeq92?file=src%2Fapp%2Fdialog-content-example.html
2. type a few line breaks or texts into the textarea until the the div's scrollbar appear
3. scroll to the bottom and type more line breaks or text

#### Expected Behavior
The scroll position of the div should not be changed.

#### Actual Behavior
After each key hit the div gets scrolled to top. So its not possible to see what is currently typed.

#### Environment

- Angular: 12.2.11
- CDK/Material: 12.2.9
- Browser(s): Chrome, Edge (Chromium), Opera
- Operating System: Windows

When `ngZoneEventCoalescing` is set to false, it works in Chrome as expected.
It seems like its related to #23233. In firefox it works as expected.

When the firefox work around in the autosize Directive is used for chrome too, then it works fine. But I'm not really know, if it has some other side effects when using the work around for chrome too. https://github.com/angular/components/blob/a931de54a786597b34259e461c2cf3ab6edc590a/src/cdk/text-field/autosize.ts#L227-L237

### PR DESCRIPTION
**Pull request by CorentinDeBoisset**
When we measure the size of the autosize textarea, we make it temporarily smaller which can cause the scroll position to shift. These changes add a workaround that assign a temporary margin-bottom while measuring.

Fixes #23834

### CODE REVIEW

**Comment by mmalerba** [comment]
reassigning to @crisbeto since he was the author of the firefox-specific fix

File: src/cdk/text-field/autosize.ts [hunk 1]
```diff
@@ -237,17 +237,14 @@ export class CdkTextareaAutosize implements AfterViewInit, DoCheck, OnDestroy {
     const element = this._textareaElement;
     const previousMargin = element.style.marginBottom || '';
     const isFirefox = this._platform.FIREFOX;
-    const needsMarginFiller = isFirefox && this._hasFocus;
```
Comment (crisbeto) [inline src/cdk/text-field/autosize.ts:240]: I think we still need the `_hasFocus` part of this check. Otherwise we'll end up applying the margin on elements the user isn't interacting with.

**Comment by crisbeto** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: c62c64f21fdbe8d818da519f774c4783a5f77f27
- 21.0.x: fe273390ddffeae2f3c17f030684031885c28f7f
