### PR TITLE
fix(input/testing): unable to set the value of inputs that don't respond to typing

### LINKED ISSUE #18790: bug(MatInputHarness): Does not properly set value with <input type="color">
#### Reproduction

See StackBlitz: https://stackblitz.com/edit/components-issue-3u5pnf?file=src/app/app.component.spec.ts 

Steps to reproduce:
1. Using the MatInputHarness, `setValue('#123456')` (or any other color) of an `<input type="color">`.
2. Use `getValue()` to get the result.
 
#### Expected Behavior

The value should be `#123456`.

#### Actual Behavior

It is always `#000000`.

#### Environment

- Angular: 9.0.6
- CDK/Material: 9.1.2
- Browser(s): Chrome 80.0.3987.132, Safari 13.0.5
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 10.15.3

### PR DESCRIPTION
**Pull request by crisbeto**
The `setValue` method of the input harness is set up so that it types out the value in the input. This won't work for inputs that don't respond to typing (e.g. `color`). These changes add an extra call that also sets the `value` property of the input, on top of typing into it.

Fixes #18790.

Note: not sure whether the change to the `TestElement` signature needs to be made optional first.

### CODE REVIEW

File: src/material/input/testing/input-harness.ts [hunk 1]
```diff
@@ -111,5 +111,10 @@ export class MatInputHarness extends MatFormFieldControlHarness {
     if (newValue) {
       await inputEl.sendKeys(newValue);
     }
+
+    // Some input types won't respond to key presses (e.g. `color`) so to be sure that the
+    // value is set, we also set the property after the keyboard sequence. Note that we don't
+    // want to do it before, because it can cause the value to be entered twice.
+    await inputEl.setProperty('value', newValue);
```
Comment (devversion) [inline src/material/input/testing/input-harness.ts]: We should update the method description, right? The goal for this method was to simulate the real input typing (e.g. in e2e tests). I'm wondering if this special logic should be opt-in through a flag, or a separate method? Just throwing out some idea's here.

Comment (crisbeto) [reply src/material/input/testing/input-harness.ts]: The method still does what is said in the description, but it has a fallback for the input that you can't type in.

Comment (devversion) [reply src/material/input/testing/input-harness.ts]: Yeah, but that should be documented IMO. If the value cannot be set through typing (e.g. `readonly`) then I don't expect it to have the new value.

Comment (devversion) [reply src/material/input/testing/input-harness.ts]: That's actually why I'm thinking whether it would make sense to have this as a separate method (explaining the use-case and downsides)

Comment (crisbeto) [reply src/material/input/testing/input-harness.ts]: I think that would confuse people more than anything, because we'd have two ways of doing more or less the same. The consumer cares about that the value is set, they probably don't care whether it's through typing or a property.

Comment (devversion) [reply src/material/input/testing/input-harness.ts]: I definitely would care on my end if I'd write an e2e test and want to test whether the input is type-able or not (i.e. if `readonly` works properly). I'm not saying that a separate method is the right and only option, but it _could_ be one. At least, documenting is important IMO.

Maybe @mmalerba has more thoughts on this.

Comment (mmalerba) [reply src/material/input/testing/input-harness.ts]: I don't think we want to add this functionality at all. The idea of the harnesses is that they interact with your component like a user would. A user doesn't get to set properties. The way I would expect people to do this in their tests is that they test whatever path in their code causes this property to be set, then they can check that it was actually set using the harness

Comment (crisbeto) [reply src/material/input/testing/input-harness.ts]: That makes it impossible to interact with some elements though. E.g. the dropdown of the `color` input is inside the Shadow DOM and isn't accessible via a selector.

Comment (mmalerba) [reply src/material/input/testing/input-harness.ts]: That seems like a pretty rare case. I think that should probably be outside the scope of the harness system, and we just give people a way to get the element, e.g.: 
`TestbedHarnessEnvironment.getElement(el: TestElement): Element`

Comment (crisbeto) [reply src/material/input/testing/input-harness.ts]: I'm fine with exposing the element and have a way of setting native properties directly, but I was under the impression that we want to avoid having people interact with the `TestElement`.

Comment (mmalerba) [reply src/material/input/testing/input-harness.ts]: Yeah, as a general rule of thumb I don't want to expose `TestElement`s to users unless there's a good reason to do so. I would consider this a good reason though

Comment (crisbeto) [reply src/material/input/testing/input-harness.ts]: Wouldn't it be a little inconsistent though? Also it assumes that people know the internals of the harness. Since `getValue` is based on the `value` property there are cases where it'll work correctly (e.g. if you initialized the input with `value="foo"`) and others where it won't.

Comment (mmalerba) [reply src/material/input/testing/input-harness.ts]: I'm open to changing how `getValue` works, but I definitely don't want to add a `setProperty` method to `TestElement`. I think the idea of interacting with components like a user would is pretty core to the way the harnesses were designed and I wouldn't want to start violating that

File: src/cdk/testing/test-element.ts [hunk 2]
```diff
@@ -113,6 +113,9 @@ export interface TestElement {
   /** Gets the value of a property of an element. */
   getProperty(name: string): Promise<any>;
 
+  /** Sets the value of a property of an input. */
+  setInputValue(value: string): Promise<void>;
```
Comment (mmalerba) [inline src/cdk/testing/test-element.ts:117]: I think this should be an optional method until a future version. It's a breaking change if its required, since people have to update their implementations of `TestElement`
