### PR TITLE
fix(button-toggle): value cleared when replacing with list that still contains the selected value

### LINKED ISSUE #15297: mat-button-toggle-group selected button deselects on data-binding change
#### What is the expected behavior?
The mat-button-toggle-group retains the currently selected button toggle when updating data-sources (an array of objects with a string property).

#### What is the current behavior?
When using a mat-button-toggle-group with an ngFor, if the array of items being iterated over is changed to a different list of items, then the 'should be selected' button toggle becomes deselected.

#### What are the steps to reproduce?
ver. 7.3.1
https://stackblitz.com/edit/mat-button-toggle-issue
ver. 7.2.0
https://stackblitz.com/edit/mat-button-toggle-issue-working

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
My current version of angular material is 7.3.3, the last version I can find that the issue is not present is version 7.2.0.

#### Other Info

My guess is this issue is related to this [commit.](https://github.com/angular/material2/commit/98f01424588d665335954b02f1a4f52b08ada2fb)

### PR DESCRIPTION
**Pull request by crisbeto**
In #14627 we added some logic that removes the selected button toggle from the selection when it's destroyed. In an attempt to work around a "changed after checked" error we wrapped the call in a `Promise.resolve`, however that introduced an issue where we might end up overwriting a subsequent value, if it happens immediately after a button is destroyed. These changes move some things around to ensure that we don't overwrite the user's value.

Fixes #15297.

### CODE REVIEW

File: src/lib/button-toggle/button-toggle.ts [hunk 1]
```diff
@@ -278,14 +282,11 @@ export class MatButtonToggleGroup implements ControlValueAccessor, OnInit, After
       this._selectionModel.deselect(toggle);
     }
 
-    // Only emit the change event for user input.
-    if (isUserInput) {
-      this._emitChangeEvent();
+    if (deferEvents) {
```
Comment (jelbourn) [inline src/lib/button-toggle/button-toggle.ts]: Add a comment here that explains why this is used? 

I'm generally not a fan of [flag arguments](https://martinfowler.com/bliki/FlagArgument.html), but I don't have another suggestion here that wouldn't involve more work.

Comment (crisbeto) [reply src/lib/button-toggle/button-toggle.ts]: I'm not a fan of them either, but in this case it's a private API so it should be fine.

Comment (jelbourn) [reply src/lib/button-toggle/button-toggle.ts]: Yeah, I'm okay with it going in. I think it would be useful to have a comment here like
```
// We defer emitting the change event in some cases because...
```

Comment (crisbeto) [reply src/lib/button-toggle/button-toggle.ts]: Done.

**Comment by jelbourn** [comment]
@crisbeto this passes presubmit, just needs a rebase
