### PR TITLE
fix(material/snack-bar): live region not working when modal is open

### LINKED ISSUE #26708: bug(dialog/snackbar): a11y - Snackbar contents do not vocalize while dialog is open
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When opening a snackbar from within a dialog (with VoiceOver enabled), the snackbar contents are not vocalized. If the snackbar remains on the screen, the contents are vocalized as soon as the dialog is closed.

This is a very similar issue to: https://github.com/angular/components/issues/22733 

I suspect a similar fix could be applied (adding aria-owns to the dialog for any active snackbars).

Note: I am able to work around this issue by setting the dialog's aria-modal attribute to false.

### Reproduction

Steps to reproduce:
1. Open a dialog
2. While the dialog is open, trigger a snackbar with VoiceOver enabled.

Repro: https://stackblitz.com/edit/components-issue-kqprn4?file=src%2Fapp%2Fdialog-content-example.ts

### Expected Behavior

The snackbar contents should be vocalized

### Actual Behavior

The snackbar contents are not vocalized until the dialog is closed (if the snackbar is still visible).

### Environment

- Angular: 15.2.0
- CDK/Material: 15.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS
- Screen reader: VoiceOver

### PR DESCRIPTION
**Pull request by crisbeto**
Implements a workaround to the issue where some browsers don't expose live elements to the accessibility tree if there's an `aria-modal` on the page.

Fixes #26708.

### CODE REVIEW

File: src/material/snack-bar/snack-bar-container.ts [hunk 1]
```diff
@@ -220,6 +231,54 @@ export abstract class _MatSnackBarContainerBase extends BasePortalOutlet impleme
...
+    // TODO(crisbeto): consider de-duplicating this with the `LiveAnnouncer`.
+    // Note that the selector here is limited to CDK overlays at the moment in order to reduce the
+    // section of the DOM we need to look through. This should cover all the cases we support, but
+    // the selector can be expanded if it turns out to be too narrow.
+    const id = this._liveElementId;
+    const modals = this._document.querySelectorAll(
+      'body > .cdk-overlay-container [aria-modal="true"]',
+    );
+
+    for (let i = 0; i < modals.length; i++) {
```
Comment (devversion) [inline src/material/snack-bar/snack-bar-container.ts:253]: Nit: Could use `for (const modal of modals)`

File: src/material/snack-bar/snack-bar-container.ts [hunk 2]
```diff
@@ -220,6 +231,54 @@ export abstract class _MatSnackBarContainerBase extends BasePortalOutlet impleme
...
+    }
+  }
+
+  /** Clears the references to the live element from any modals it was added to. */
+  private _clearFromModals() {
+    this._trackedModals.forEach(modal => {
+      const ariaOwns = modal.getAttribute('aria-owns');
+
+      if (ariaOwns) {
+        const newValue = ariaOwns.replace(this._liveElementId, '').trim();
```
Comment (devversion) [inline src/material/snack-bar/snack-bar-container.ts:272]: What happens if it would be in the middle of other ids? e.g. `aria-owns="existing <snackbar> some-other-added"`? I guess that is very unlikely to ever happen but want to see what you think.

**Review by devversion — APPROVED** [review]

File: src/material/snack-bar/snack-bar-container.ts (hunk 2 above)
Comment (crisbeto) [reply src/material/snack-bar/snack-bar-container.ts:272]: I think that would be fine since it would just leave a whitespace which the browser is going to ignore.

File: src/material/snack-bar/snack-bar-container.ts (hunk 1 above)
Comment (crisbeto) [reply src/material/snack-bar/snack-bar-container.ts:253]: That doesn't work, because `querySelectorAll` returns a `NodeList`.

Comment (devversion) [reply src/material/snack-bar/snack-bar-container.ts:253]: A node list is iterable, so it should work: https://developer.mozilla.org/en-US/docs/Web/API/NodeList

But no need to follow-up. As said, a nit.
