### PR TITLE
fix(material/tree): aria-expanded attribute should not appear in the leaf node

### LINKED ISSUE #21143: Tree does not follow the expected ARIA structure
Reference https://www.w3.org/TR/wai-aria-practices-1.1/#tree_roles_states_props

First of all, our entire concept of a flat tree isn't super compatible with the expected ARIA structure for trees. Each `treeitem` element is supposed to either contain or `aria-own` a `role="group"` element that contains all of its child nodes. To keep the notion of the flat-tree alive, we've have to use `aria-owns` in a way that looks something like this:
```html
<div role="tree">
  <div role="treeitem" aria-owns="greek-children">Greek</div>
  <div role="group" id="greek-children">
    <div role="treeitem">Alpha</div>
    <div role="treeitem">Beta</div>
    <div role="treeitem">Gamma</div>
  </div>
</div>
```

Which means that it would be the responsibility of the tree to figure out where to insert these `role="group"` elements, which I'm not totally sure is possible. 

The nested tree is easier to reconcile, since we actually do nest the nodes; the main problem is that we're missing the `role="group"` element for nodes that have children. The desired structure would look something like
```html
<div role="tree">
  <div role="treeitem">
    Greek
    <div role="group">
      <div role="treeitem">Alpha</div>
      <div role="treeitem">Beta</div>
      <div role="treeitem">Gamma</div>
    </div>
  </div>
</div>
```

### LINKED ISSUE #21922: bug(cdk-tree): aria-expanded attribute should not appear in the leaf node
#### Reproduction

Example to reproduce issue
https://material.angular.io/cdk/tree/examples

Steps to reproduce:
Inspect the leaf node of cdk-tree from dev tools
image
Based on [W3.org aria practices for tree view](https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView), it mentions that: "Each element with role treeitem that serves as a parent node has aria-expanded set to false when the node is in a closed state and set to true when the node is in an open state. **End nodes do not have the aria-expanded attribute because, if they were to have it, they would be incorrectly described to assistive technologies as parent nodes.**"
 
 
 
#### Expected Behavior

There should be no aria-expanded attribute appearing on the leaf node

#### Actual Behavior

aria-expanded is setting as false on the leaf node

#### Environment

- CDK/Material: newest version

### PR DESCRIPTION
**Pull request by DBowen33**
Fixed an issue to where leaf nodes were wrongly being assigned the aria-expanded attribute, which could confuse screen reader users.

https://screencast.googleplex.com/cast/NjMzNDkwNjM4MzcyODY0MHxkMTY5ZTdkNC05Mw

Fixes #21922
Fixes #21143

### CODE REVIEW

File: src/cdk/tree/tree.ts [hunk 1]
```diff
@@ -321,7 +321,7 @@ export class CdkTree<T, K = T> implements AfterContentChecked, CollectionViewer,
   exportAs: 'cdkTreeNode',
   host: {
     'class': 'cdk-tree-node',
-    '[attr.aria-expanded]': 'isExpanded',
+    '[attr.aria-expanded]': 'isLeafNode',
```
Comment (andrewseguin) [inline src/cdk/tree/tree.ts:324]: I think it makes more sense to create a new function `isLeafNode` to use in conjunction with this conditional:

`isLeafNode() ? null : isExpanded`

RIght now, it's not obvious why `isLeafNode` is returning the expansion state rather than just a `true` or `false` of whether it's a leaf node

Comment (DBowen33) [reply src/cdk/tree/tree.ts]: Added recommended changes, thanks!

**Review by andrewseguin — APPROVED** [review]
