### PR TITLE
fix(tooltip): avoid adding same aria description as trigger's aria-label

### LINKED ISSUE #16719: [Paginator] - NVDA lector read buttons twice
#### Reproduction

Steps to reproduce:
1. Lanuch NVDA lector
2. TAB to pagination, eg. next page button
3. Lector will read it "next page button next page"
 
 
#### Expected Behavior

What behavior were you expecting to see?
Lector will read buttons only once.

#### Actual Behavior

What behavior did you actually see?
Lector read buttons twice.

#### Environment

- Angular: 8.0.3
- CDK/Material: 80.2
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

#### Solution

You can add [attr.aria-describedby]="null" and it will be work correctly.

### PR DESCRIPTION
**Pull request by crisbeto**
We automatically add an `aria-describedby` to the triggers of tooltips so that assistive technologies can read out the tooltip text. As a part of this process, the `AriaDescriber` has some functionality that checks whether the element doesn't have an `aria-label` with the same value already, and if it does, it avoids adding the description. The problem is that tooltips add this description very early in their lifecycle which means that if the element has a data-bound `aria-label`, it won't be detected by the `AriaDescriber`, as is the case for the buttons in the `mat-paginator`. These changes work around the issue by deferring the setting of the description.

Fixes #16719.

### CODE REVIEW

File: src/material/tooltip/tooltip.ts [hunk 1]
```diff
@@ -180,7 +180,15 @@ export class MatTooltip implements OnDestroy, OnInit {
       this.hide(0);
     } else {
       this._updateTooltipMessage();
-      this._ariaDescriber.describe(this._elementRef.nativeElement, this.message);
+      this._ngZone.runOutsideAngular(() => {
+        // The `AriaDescriber` has some functionality that avoids adding a description if it's the
+        // same as the `aria-label` of an element, however we can't know whether the tooltip trigger
+        // has a data-bound `aria-label` or when it'll be set for the first time. We can avoid the
+        // issue by deferring the description by a tick so Angular has time to set the `aria-label`.
+        Promise.resolve().then(() => {
```
Comment (crisbeto) [inline src/material/tooltip/tooltip.ts]: For the record, I'm not a fan of having to add this, but it's the least evil of all the alternatives (e.g. doing our own change detection in one of the `after*Checked` hooks to see if there's an `aria-label` or adding a `MutationObserver`).
