### PR TITLE
fix(google-maps): allow ground overlay bounds to be changed

### LINKED ISSUE #20865: feat(google-maps): allow ability to update bounds in GroundOverlay
#### Feature Description

Allow the ability to update the bounds of a GroundOverlay.

#### Use Case

 Currently it updates opacity, URL so I think it would be useful to allow bounds to update if possible

### PR DESCRIPTION
**Pull request by crisbeto**
Allows for the bounds of the Google Maps ground overlay to be changed after initialization. This case is different from other similar components, because Google Maps doesn't provide an API to change the bounds so we have to recreate the overlay any time they change.

Fixes #20865.

### CODE REVIEW

File: src/google-maps/map-ground-overlay/map-ground-overlay.ts [hunk 1]
```diff
@@ -46,14 +49,21 @@ export class MapGroundOverlay implements OnInit, OnDestroy {
...
+    this._bounds.next(bounds);
+  }
 
   /** Whether the overlay is clickable */
   @Input() clickable: boolean = false;
 
   /** Opacity of the overlay. */
   @Input()
   set opacity(opacity: number) {
+    console.log('received', opacity);
```
Comment (jelbourn) [inline src/google-maps/map-ground-overlay/map-ground-overlay.ts:66]: leftover log

Comment (crisbeto) [reply src/google-maps/map-ground-overlay/map-ground-overlay.ts]: Fixed.

**Review by jelbourn — APPROVED** [review]
LGTM

File: src/google-maps/map-ground-overlay/map-ground-overlay.ts [hunk 2]
```diff
@@ -46,7 +49,13 @@ export class MapGroundOverlay implements OnInit, OnDestroy {
   }
 
   /** Bounds for the overlay. */
-  @Input() bounds: google.maps.LatLngBounds|google.maps.LatLngBoundsLiteral;
+  @Input()
+  get bounds(): google.maps.LatLngBounds|google.maps.LatLngBoundsLiteral {
```
Comment (mbehrlich) [inline src/google-maps/map-ground-overlay/map-ground-overlay.ts:53]: I think it will be confusing to have both a "bounds" getter as well as the original "getBounds" method below. The pattern I have following has been to call get<property> on the underlying object instead of what is stored on the BehaviorSubject.

File: src/google-maps/map-ground-overlay/map-ground-overlay.ts [hunk 3]
```diff
@@ -77,21 +86,30 @@ export class MapGroundOverlay implements OnInit, OnDestroy {
   constructor(private readonly _map: GoogleMap, private readonly _ngZone: NgZone) {}
 
   ngOnInit() {
-    if (!this.bounds && (typeof ngDevMode === 'undefined' || ngDevMode)) {
-      throw Error('Image bounds are required');
```
Comment (mbehrlich) [inline src/google-maps/map-ground-overlay/map-ground-overlay.ts:81]: Why was the error removed?

File: src/google-maps/map-ground-overlay/map-ground-overlay.ts (hunk 2 above)
Comment (crisbeto) [reply src/google-maps/map-ground-overlay/map-ground-overlay.ts:53]: We need the getter for backwards compatibility since `bounds` used to be a regular property before.

File: src/google-maps/map-ground-overlay/map-ground-overlay.ts (hunk 3 above)
Comment (crisbeto) [reply src/google-maps/map-ground-overlay/map-ground-overlay.ts:81]: I removed it since none of the other components that accept bounds had a hard error like this.

Comment (mbehrlich) [reply src/google-maps/map-ground-overlay/map-ground-overlay.ts:81]: I think only rectangle accepts a bounds other than this one. The reason that I implemented an error here was that the Google Maps JavaScript API marks bounds as a required input, whereas for rectangle it's optional.

Comment (crisbeto) [reply src/google-maps/map-ground-overlay/map-ground-overlay.ts:81]: Since Angular templates are dynamic, the value could come in asynchronously after `ngOnInit`. I'd rather avoid throwing an error since it isn't any more difficult for us to support it.

File: src/google-maps/map-ground-overlay/map-ground-overlay.ts (hunk 2 above)
Comment (mbehrlich) [reply src/google-maps/map-ground-overlay/map-ground-overlay.ts:53]: Ah, that makes sense.

File: src/google-maps/map-ground-overlay/map-ground-overlay.ts [hunk 4]
```diff
@@ -77,21 +86,30 @@ export class MapGroundOverlay implements OnInit, OnDestroy {
...
+        if (bounds) {
+          this._ngZone.runOutsideAngular(() => {
+            this.groundOverlay = new google.maps.GroundOverlay(this._url.getValue(), bounds, {
+              clickable: this.clickable,
+              opacity: this._opacity.value,
+            });
+          });
+          this._assertInitialized();
+          this.groundOverlay.setMap(this._map.googleMap!);
+          this._eventManager.setTarget(this.groundOverlay);
```
Comment (mbehrlich) [inline src/google-maps/map-ground-overlay/map-ground-overlay.ts:111]: Will the clear out any event listeners? Should we test that events still work on reconstituted overlays?

File: src/google-maps/map-ground-overlay/map-ground-overlay.ts (hunk 3 above)
Comment (mbehrlich) [reply src/google-maps/map-ground-overlay/map-ground-overlay.ts:81]: Okay, I guess that's fine with me.

File: src/google-maps/map-ground-overlay/map-ground-overlay.ts (hunk 4 above)
Comment (crisbeto) [reply src/google-maps/map-ground-overlay/map-ground-overlay.ts:111]: It will remove the listeners, but now that I'm looking at it again, it seems like they won't be transferred to the new target. We probably haven't hit it until now, because we haven't had a case where we re-initialize a map object. This seems like it should be fixed in a separate PR since it could affect the other map components.

Comment (mbehrlich) [reply src/google-maps/map-ground-overlay/map-ground-overlay.ts:111]: I think we should hold off on submitting this pr then until the other one fixing the event manager goes through. We don't want changing the bounds to break someone's click handler

Comment (crisbeto) [reply src/google-maps/map-ground-overlay/map-ground-overlay.ts:111]: Sure, marking as blocked.

**Comment by crisbeto** [comment]
Unblocking now that #20897 has been merged.

**Review by mbehrlich — APPROVED** [review]
LGTM
