### PR TITLE
fix(cdk/table): resolve breaking constructor changes

### LINKED ISSUE #20422: bug(CdkTable): CdkTable constructor parameters changed in a patch version
The constructor parameters of CdkTable changed in version 10.1.2 (see: https://github.com/angular/components/compare/10.1.1...10.1.2#diff-86c33ad9a24e48674baaf250f4035a11). 

**This issue might be not considered a bug if we do not assume CDK components API is something that should conform semver versioning.** 
However, in my opinion, parameters of a public constructor should be rather treated as a part of the public API. Especially for a CDK, which is meant to be used and extended by others. Thus such a breaking change should be done in major versions only according to the semver standard. 

The particular breaking change:
https://github.com/angular/components/commit/71a2a171b8abb926631045b616483878ac326592#diff-86c33ad9a24e48674baaf250f4035a11R430

The change causes our Barista library to fail the compilation. However, I've originally spotted the problem during development of our product that uses the Barista lib and it was much more cumbersome, because there was no compilation error - the library was already prebuilt and the only error that we got was a runtime one (both Jest and browser):
```
    TypeError: Cannot read property 'nativeElement' of null

      at DtTable.CdkTable (../src/cdk/table/table.ts:442:24)
      at DtTable._DtTableBase [as constructor] (libs/barista-components/table/src/base-table.ts:64:5)
      at new DtTable (libs/barista-components/table/src/table.ts:166:5)
      at createClass (../packages/core/src/view/provider.ts:290:7)
      at createDirectiveInstance (../packages/core/src/view/provider.ts:142:7)
      at createViewNodes (../packages/core/src/view/view.ts:314:28)
      at callViewAction (../packages/core/src/view/view.ts:647:7)
      at execComponentViewsAction (../packages/core/src/view/view.ts:570:7)
      at createViewNodes (../packages/core/src/view/view.ts:342:3)
      at createRootView (../packages/core/src/view/view.ts:216:3)
      at callWithDebugContext (../packages/core/src/view/services.ts:638:23)
      at Object.debugCreateRootView [as createRootView] (../packages/core/src/view/services.ts:119:10)
      at ComponentFactory_.create (../packages/core/src/view/refs.ts:92:27)
      at initComponent (../packages/core/testing/src/test_bed.ts:618:28)
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Object.onInvoke (../packages/core/src/zone/ng_zone.ts:326:29)
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.run (node_modules/zone.js/dist/zone.js:143:47)
      at NgZone.run (../packages/core/src/zone/ng_zone.ts:180:50)
      at TestBedViewEngine.createComponent (../packages/core/testing/src/test_bed.ts:622:56)
      at Function.TestBedViewEngine.createComponent (../packages/core/testing/src/test_bed.ts:245:36)
      at libs/cmc/home/feature/src/lib/network-zones/details/table/cmc-network-zone-details-table.component.spec.ts:92:23
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.run (node_modules/zone.js/dist/zone.js:143:47)
```
 
As far as I researched, a similar issue was closed: #20308, however Angular 10.0.10 doesn't seem to solve this specific issue. 

#### Reproduction

Real world reproduction example:
1. Clone our open source component library: https://github.com/dynatrace-oss/barista
1. Install dependencies and build it:
  ```npm install && npm run build```
  The build should pass fine.
1. Update the `@angular/cdk` dependency
1. Re-install dependencies and rebuild it - the build will fail:
  ```
ERROR in libs/barista-components/table/src/base-table.ts:64:5 - error TS2554: Expected 8 arguments, but got 7.
 64     super(
 65       differs,
...
 71       platform,
 72     );
```

It can be easily reproduced with a Stackblitz example as well. Please, let me know if you'd like that. Although, I don't think it's necessary - the issue can be easily spotted even with a static analysis. 

#### Expected Behavior

Patch version should not contain API breaking changes.

#### Actual Behavior

The constructor parameter change causes compilation errors in the library using the CDK directly, and runtime errors for projects using it indirectly by a precompiled dependency.

#### Environment

- Angular: 10.0.12
- CDK/Material: 10.1.3
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): N/A

### PR DESCRIPTION
**Pull request by crisbeto**
In #19964 and #19750 some breaking constructor changes were made which eventually got released as a part of a patch branch which doesn't follow our breaking changes policy.

These changes make the new constructor parameters optional and add fallbacks to the old behavior.

Fixes #20422.

cc @kseamon @MichaelJamesParsons

### CODE REVIEW

File: src/cdk/table/table.ts [hunk 1]
```diff
@@ -443,14 +443,18 @@ export class CdkTable<T> implements AfterContentChecked, CollectionViewer, OnDes
...
-      // be provided.
+
+      /**
+       * @deprecated `_coalescedStyleScheduler` and `_viewRepeater` parameters to become required.
+       * @breaking-change 11.0.0
+       */
       @Optional() @Inject(_VIEW_REPEATER_STRATEGY)
-      protected readonly _viewRepeater: _ViewRepeater<T, RenderRow<T>, RowContext<T>>) {
+        protected readonly _viewRepeater?: _ViewRepeater<T, RenderRow<T>, RowContext<T>>,
+      @Optional() @Inject(_COALESCED_STYLE_SCHEDULER)
```
Comment (crisbeto) [inline src/cdk/table/table.ts:456]: I'm not totally sure whether the lightweight token makes sense here since the base class always provides a style scheduler which means that the code will always be retained. I added one since the lint rule flagged it. cc @devversion

**Comment by kseamon** [comment]
Can you say fixed rather than reverted? From the description I was worried that the optimizations were being rolled back but I see that’s not the case.

**Comment by MichaelJamesParsons** [comment]
LGTM, thanks for looking into this!

File: src/cdk/table/table.ts (hunk 1 above)
Comment (devversion) [reply src/cdk/table/table.ts:456]: Did it flag the parameter because you had `@Optional` on it initially? I think as per [this discussion](https://github.com/angular/components/pull/19920#discussion_r452181383) it shouldn't have that. I can't see the diff on how it was before; so maybe the code was different.

Generally, I think it _could_ makes sense if one extends the class and provides an explicit constructor where he doesn't want to use the coalesced style scheduler (and now doesn't have to pay the size cost of it).

Once this becomes required, the lightweight token doesn't make any sense anymore though, but we probably can persist it then to avoid another breaking change? Could also see us doing a lint rule exception for this.

**Review by devversion — APPROVED** [review]
LGTM. Just replied to the lightweight token comment you added.

File: src/cdk/table/table.ts (hunk 1 above)
Comment (crisbeto) [reply src/cdk/table/table.ts:456]: I see now, I forgot that we had a special case for `@breaking-change`. It probably didn't work, because I used a single comment for `_viewRepeater` and `_coalescedStyleScheduler`.

Comment (devversion) [reply src/cdk/table/table.ts:456]: Yeah, the breaking change logic we removed though since you made the point that parameters using `@breaking-change` and are "to be made required" shouldn't be `@Optional` in the first place. 

And sounds good. I think it doesn't matter a lot 👍
