### PR TITLE
fix(ng-add): ng add @angular/material fails in library projects

### LINKED ISSUE #19156: Adding Material to a Library Project (Could not find the project main file inside of the workspace config)
I am trying to build an Angular Library project that has Material installed. It was not working in my original project so I decided to create a new workspace and library project from scratch. Here are the commands I used.
```
ng new test-workspace --create-application=false
cd .\test-workspace\
ng generate library test
ng add @angular/material
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Choose a prebuilt theme name, or "custom" for a custom theme: Indigo/Pink
? Set up global Angular Material typography styles? Yes
? Set up browser animations for Angular Material? Yes
UPDATE package.json (1434 bytes)
√ Packages installed successfully.
Could not find the project main file inside of the workspace config (projects/test/src)
```
After this step I was going to add the following...

```
    "@angular/cdk": "^9.2.1",
    "@angular/material": "^9.2.1
```
...to the peerDependencies of test-workspace\projects\test\package.json but I do not know what do to do with the error I received after trying to install Material. Is this more of a warning than an error?

```
Could not find the project main file inside of the workspace config (projects/test/src)
```
Any help would be greatly appreciated. 

Thanks

```
Angular CLI: 9.1.1
Node: 12.16.1
OS: win32 x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-ng-packagr   0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@angular/cdk                       9.2.1
@angular/cli                       9.1.1
@angular/material                  9.2.1
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
ng-packagr                         9.1.1
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
```

### PR DESCRIPTION
**Pull request by trik**
Skip app related ng-add steps when working with library projects

close #19156

### CODE REVIEW

File: src/material/schematics/ng-add/setup-project.ts [hunk 1]
```diff
@@ -33,13 +33,21 @@ const noopAnimationsModuleName = 'NoopAnimationsModule';
...
-    addThemeToAppStyles(options),
-    addFontsToIndex(options),
-    addMaterialAppStyles(options),
-    addTypographyClass(options),
-  ]);
+  return (host: Tree) => {
+    const workspace = getWorkspace(host);
+    const project = getProjectFromWorkspace(workspace, options.project);
+
+    if (project.projectType === 'application') {
```
Comment (devversion) [inline src/material/schematics/ng-add/setup-project.ts:40]: Should we print a warning instead of exiting silently? Also would you be able to create a test for this?

Comment (trik) [reply src/material/schematics/ng-add/setup-project.ts:40]: yeah, it's a good idea..
it would be great if we could prevent asking for ng-add parameters but as far as i know, x-prompt variables can't be defined conditionally based on project type, right?
sure, i'll provide a unit test case

Comment (devversion) [reply src/material/schematics/ng-add/setup-project.ts:40]: Yeah, I think we can't conditionally show prompts.

File: src/material/schematics/ng-add/index.spec.ts [hunk 2]
```diff
@@ -418,3 +418,33 @@ describe('ng-add schematic', () => {
...
+    runner.logger.subscribe(e => {
+      if (e.level === 'error') {
+        errorOutput.push(e.message);
+      } else if (e.level === 'warn') {
+        warnOutput.push(e.message);
+      }
+    });
+  });
+
+  it('should warn that the material has beend added to a library project', async () => {
```
Comment (rafaelss95) [inline src/material/schematics/ng-add/index.spec.ts:443]:
```suggestion
  it('should warn that the material has been added to a library project', async () => {
```

Comment (devversion) [reply src/material/schematics/ng-add/index.spec.ts:443]: I'd propose `should warn if a library project is targeted`.

File: src/material/schematics/ng-add/setup-project.ts [hunk 3]
```diff
@@ -33,13 +33,23 @@ const noopAnimationsModuleName = 'NoopAnimationsModule';
...
+      return chain([
+        addAnimationsModule(options),
+        addThemeToAppStyles(options),
+        addFontsToIndex(options),
+        addMaterialAppStyles(options),
+        addTypographyClass(options),
+      ]);
+    }
+    context.logger.warn('Your project is a library. The Angular Material schematics cannot ' +
+      'set up theming, typography and animations in this kind of project.');
```
Comment (devversion) [inline src/material/schematics/ng-add/setup-project.ts:50]: How about:

```
Unable to set up Angular Material in a library project as there is no special setup required.
If you intended to run the schematic for a different project, pass the `--project` option.
```

cc. @jelbourn if you have any better ideas.

File: src/material/schematics/ng-add/setup-project.ts [hunk 4]
```diff
@@ -33,13 +33,25 @@ const noopAnimationsModuleName = 'NoopAnimationsModule';
...
+        addThemeToAppStyles(options),
+        addFontsToIndex(options),
+        addMaterialAppStyles(options),
+        addTypographyClass(options),
+      ]);
+    }
+    context.logger.warn(
+        'Unable to set up Angular Material in a library project as there is no special ' +
+        'setup required. If you intended to run the schematic for a different project, ' +
+        'pass the `--project` option.');
```
Comment (devversion) [inline src/material/schematics/ng-add/setup-project.ts:52]: I just came across this again. I think we need to update the message slightly. If library authors run `ng add @angular/material`, then they probably only expect us to add the dependency. This is done by the CLI already, so the message that we're unable to setup Angular Material might be misleading.

Can we rephrase is so that we just explain that there is no special setup needed for libraries?

Comment (trik) [reply src/material/schematics/ng-add/setup-project.ts:52]: @devversion something like
`Angular Material has been added to your library project dependencies. This kind of projects does not require any further setup. If you intended to run the schematic for a different project, pass the `--project` option.`

Comment (devversion) [reply src/material/schematics/ng-add/setup-project.ts:52]: I'm sorry. I wanted to get back to you as soon as possible, but so many other things were going on and I forgot. 

I'd propose something like:

```
Angular Material has been set up in your workspace. There is no additional
setup required for consuming Angular Material in your library project.

If you intended to run the schematic on a different project, pass the `--project` option.
```

Comment (trik) [reply src/material/schematics/ng-add/setup-project.ts]: @devversion no worries. updated and rebased

Comment (devversion) [reply src/material/schematics/ng-add/setup-project.ts]: Awesome, thx for addressing! Looks like there is a test failure. I'll add merge ready when that is solved.
