### PR TITLE
fix(scrolling): update virtual scroll viewport size on resize

### LINKED ISSUE #16802: cdk-virtual-scroll: viewport does not render correct number of items after browser zoom
See https://stackblitz.com/edit/angular-ndhumn for repro. If the page is refreshed after zooming everything works as expected, so its probably a cached size that needs to be re-measured after zooming

### PR DESCRIPTION
**Pull request by crisbeto**
We currently cache the size of the virtual scroll viewport, but it may become inaccurate if it's a percentage of the page viewport and the page is resized. These changes add an extra call that'll update the virtual scroll viewport on resize.

Fixes #16802.

### CODE REVIEW

File: src/cdk/scrolling/virtual-scroll-viewport.ts [hunk 1]
```diff
@@ -142,18 +149,33 @@ export class CdkVirtualScrollViewport extends CdkScrollable implements OnInit, O
...
   constructor(public elementRef: ElementRef<HTMLElement>,
               private _changeDetectorRef: ChangeDetectorRef,
               ngZone: NgZone,
               @Optional() @Inject(VIRTUAL_SCROLL_STRATEGY)
                   private _scrollStrategy: VirtualScrollStrategy,
               @Optional() dir: Directionality,
-              scrollDispatcher: ScrollDispatcher) {
+              scrollDispatcher: ScrollDispatcher,
+              /**
+               * @deprecated `viewportRuler` parameter to become required.
```
Comment (mmalerba) [inline src/cdk/scrolling/virtual-scroll-viewport.ts]: I would just mark this `@breaking-change`, not `@deprecated` since the change is making it required rather than removing it

**Comment by mmalerba** [comment]
Apply `merge-ready` once the comment is addressed

File: src/cdk/scrolling/virtual-scroll-viewport.ts (hunk 1 above)
Comment (crisbeto) [reply src/cdk/scrolling/virtual-scroll-viewport.ts]: I’ve been marking these as deprecated in other places, because it’s something standard that’ll show up in people’s tooling, whereas breaking-change is something we made up.

Comment (mmalerba) [reply src/cdk/scrolling/virtual-scroll-viewport.ts]: I see, I'm not sure if this will show up the way we want though, it will probably show `viewportRuler` as a deprecated param. What might work better is TS's method overloading. We can mark the old signature deprecated and the new one not deprecated.

Obviously we already have this same pattern all over the code base, but it might be nice to start doing it the way I suggested going forward, I'll leave it up to you

Comment (crisbeto) [reply src/cdk/scrolling/virtual-scroll-viewport.ts]: Good point that we should be using overloads instead, but I realized that Ivy won't generate the correct code if the constructor is overloaded with a different number of parameters. I've submitted a PR to fix the compiler here https://github.com/angular/angular/pull/34590 so until that gets released I'll keep it as is.
