### PR TITLE
fix(autocomplete): unable to open panel via click inside shadow dom

### LINKED ISSUE #15606: autocomplete: broken in Angular elements
#### What is the expected behavior?
Focusing `matInput` should show autocomplete options when Angular application used as custom element.

#### What is the current behavior?
Focusing `matInput` showing and instantly hiding autocomplete options when Angular application used as custom element.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-vx5mxk
Example above - the simpliest case of using the app as custom element.
Row `encapsulation: ViewEncapsulation.ShadowDom` in the `app.component.ts` makes the autocomplete bug.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
This problem hidden in `_getOutsideClickStream` function in `autocomplete-trigger.ts` file.
In this function `event.target` always have custom element tag as value.
Also `formField.contains(clickTarget)` result false.
These variables makes return result of filter (in line 329) false positive.
That's why autocomplete options list instantly closing.

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes clicking on an input to open its autocomplete not working if the consumer is using `ViewEncapsulation.ShadowDom`. The issue comes from the fact that inside the shadow DOM the `event.target` is set to the shadow root, rather than the element being clicked.

Fixes #15606.

### CODE REVIEW

File: src/cdk/platform/features/shadow-dom.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+ * Copyright Google LLC All Rights Reserved.
+ *
+ * Use of this source code is governed by an MIT-style license that can be
+ * found in the LICENSE file at https://angular.io/license
+ */
+
+let shadowDomIsSupported: boolean;
+
+/** Checks whether the user's browser support Shadow DOM. */
+export function supportsShadowDom(): boolean {
```
Comment (jelbourn) [inline src/cdk/platform/features/shadow-dom.ts]: I'm a little hesitant to add this as a public API since we'll probably drop support for IE11 in early 2020, at which point I don't think it would be necessary any more.

File: src/lib/autocomplete/autocomplete-trigger.ts [hunk 2]
```diff
@@ -201,14 +207,24 @@ export class MatAutocompleteTrigger implements ControlValueAccessor, OnDestroy {
...
+  ngAfterViewInit() {
     if (typeof window !== 'undefined') {
-      _zone.runOutsideAngular(() => {
+      this._zone.runOutsideAngular(() => {
         window.addEventListener('blur', this._windowBlurHandler);
       });
-    }
 
-    this._scrollStrategy = scrollStrategy;
+      if (supportsShadowDom()) {
```
Comment (jelbourn) [inline src/lib/autocomplete/autocomplete-trigger.ts]: Is this strictly necessary? Is checking for the existence of `getRootNode` here not enough?

Comment (crisbeto) [reply src/lib/autocomplete/autocomplete-trigger.ts]: `getRootNode` isn't strictly related to Shadow DOM. E.g. calling it on a regular element will return the `document`.

File: src/cdk/platform/features/shadow-dom.ts (hunk 1 above)
Comment (crisbeto) [reply src/cdk/platform/features/shadow-dom.ts]: I wasn't sure where to put it. It's a bit too generic to have inside a component.

Comment (jelbourn) [reply src/cdk/platform/features/shadow-dom.ts]: Let's just give it an underscore prefix

**Comment by crisbeto** [comment]
I've addressed the feedback @jelbourn.

**Comment by jelbourn** [comment]
Caretaker note: the build rule for autocomplete needs to be updated to include cdk/platform

@crisbeto can you rebase?

**Comment by crisbeto** [comment]
Rebased.

**Comment by Splaktar** [comment]
Looks like another rebase is needed. This would be nice to get in.

**Comment by crisbeto** [comment]
Rebased. Also bumping to a P2 since we've had more reports of this issue since I opened the PR.

**Comment by mmalerba** [comment]
needs rebase

**Comment by crisbeto** [comment]
Rebased.

**Comment by vadjs** [comment]
When it will be merged?
