### PR TITLE
fix(google-maps): ensure that a mapTypeId is always passed in

### LINKED ISSUE #22082: bug(google-maps): Map won't load after assigning new options
#### Reproduction

Use StackBlitz to reproduce your issue: (maps are not in stackblitz, unable to create sample there)

```ts
@Component({
  selector: 'rita-inquiry',
  template: `
    <button (click)="draggable.next(!draggable.value)">toggle</button>
    <google-map width="100%" height="100%" [options]="(mapOptions | async)!"></google-map>
  `,
  styleUrls: ['./inquiry.component.scss']
})
export class InquiryComponent {
  @ViewChild(GoogleMap) readonly map!: GoogleMap;

  readonly draggable = new BehaviorSubject(true);
  readonly mapOptions: Observable<google.maps.MapOptions> = combineLatest([
    this.draggable.pipe(
      map((draggable): Pick<google.maps.MapOptions, 'draggable' | 'draggableCursor'> => {
        return {
          draggable,
          draggableCursor: draggable ? undefined : 'default',
        };
      }),
    ),
  ]).pipe(
    map(([draggable], index) => {
      let initialMapOptions: Pick<google.maps.MapOptions, 'center' | 'zoom'> = {};
      if (!index) {
        initialMapOptions = {
          center: { lat: 49.8037633, lng: 15.4749126 },
          zoom: 8,
        };
      } else {
        initialMapOptions = {
          center: this.map.getCenter(),
          zoom: this.map.getZoom(),
        };
      }

      return {
        ...initialMapOptions,
        panControl: false,
        zoomControl: false,
        mapTypeControl: true,
        scaleControl: true,
        streetViewControl: true,
        streetViewControlOptions: {
          position: google.maps.ControlPosition.LEFT_BOTTOM,
        },
        fullscreenControl: false,
        //overviewMapControl: false,
        ...draggable,
      };
    }),
  );
}
```

Steps to reproduce:
1. Have an app with google maps included
2. Create a component with the code above
3. Click button 2 times
4. Move map (and observe how no tiles are loading)
 
 
#### Expected Behavior

When re-enabling dragging, I would assume, the map would work once again

#### Actual Behavior

No tiles are loading any more

#### Environment

- Angular: 11.2.3
- CDK/Material: 11.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by crisbeto**
We pass in `mapTypeId` as undefined if the provided options don't have it. This seems to trigger a bug in Google Maps where it stops loading map tiles.

These changes fix the issue by always providing a `mapTypeId`.

Fixes #22082.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

**Review by mbehrlich — APPROVED** [review]

File: src/google-maps/google-map/google-map.ts [hunk 1]
```diff
@@ -35,7 +35,8 @@ interface GoogleMapsWindow extends Window {
 /** default options set to the Googleplex */
 export const DEFAULT_OPTIONS: google.maps.MapOptions = {
   center: {lat: 37.421995, lng: -122.084092},
-  zoom: 17
+  zoom: 17,
+  mapTypeId: 'roadmap'
```
Comment (andrewseguin) [inline src/google-maps/google-map/google-map.ts:39]: Getting this error internally:
```
TS2322: Type 'string' is not assignable to type 'MapTypeId | undefined'.
```

Could we instead do `'roadmap' as MapTypeId` to resolve that?

Comment (crisbeto) [reply src/google-maps/google-map/google-map.ts]: Done, although it's weird that our CI didn't catch it.

Comment (andrewseguin) [reply src/google-maps/google-map/google-map.ts]: Yeesh now I'm getting this

```
TS2352: Conversion of type 'string' to type 'MapTypeId' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

Comment (crisbeto) [reply src/google-maps/google-map/google-map.ts]: Done.
