### PR TITLE
fix(button): focus method does not respect specified origin

### LINKED ISSUE #17174: MatButton.focus ignores origin argument
`MatButton` implements `FocusableOption` which implements `focus(origin?: FocusOrigin)`. However, it actually implements just `focus(unused, extraArgumentsHere)`.

#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-qrhvfh

Steps to reproduce:
1. Get reference to `MatButton`
2. Call `MatButton.focus(origin)` where `origin = 'keyboard'|'mouse'|whatever`
 
 
#### Expected Behavior
Focus should be via `'origin'`, and class `cdk-origin-focused` should be applied

#### Actual Behavior
Focus is always done via `'program'` and `cdk-program-focused` is applied

#### Workaround

Focus can be done via FocusMonitor instead.

#### Environment

- Angular: 7.0.0
- CDK/Material: 8.1.4
- Browser(s): Version 77.0.3865.75 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Debian Rodette

### PR DESCRIPTION
**Pull request by devversion**
It looks like `MatButton` at some point has been refactored
to implement the `FocusableOption` interface so that it can
be used easily in the `FocusKeyManager`.

Currently since the `origin` parameter in the `focus` method
is not respected, the `FocusKeyManager#setFocusOrigin` method
is a noop for button elements. Additionally consumers of
`MatButton` who pass in a specific `FocusOrigin` when calling
the `focus` method will be surprised that the `origin` is simply
ignored (even though it's part of the public method signature; just
prefixed with an underscore).

We should just respect the focus origin to make the method
less confusing and to properly implement the `FocusableOption`.

Fixes #17174

### CODE REVIEW

File: src/material/button/button.ts [hunk 1]
```diff
@@ -119,10 +119,8 @@ export class MatButton extends _MatButtonMixinBase
   }
 
   /** Focuses the button. */
-  focus(_origin?: FocusOrigin, options?: FocusOptions): void {
-    // Note that we aren't using `_origin`, but we need to keep it because some internal consumers
-    // use `MatButton` in a `FocusKeyManager` and we need it to match `FocusableOption`.
-    this._getHostElement().focus(options);
+  focus(origin: FocusOrigin = 'program', options?: FocusOptions): void {
```
Comment (paulferaud) [inline src/material/button/button.ts]: `FocusOrigin` has the definition `'touch' | 'mouse' | 'keyboard' | 'program' | null;` (Notice the `null`)

I think the correct(-er) fix would be to do:
```
focus(origin: FocusOrigin = null, options?: FocusOptions)
```
And let the `FocusMonitor` handle it however it wants to handle an unset `FocusOrigin` (which happens to be to treat it as 'program').

Comment (devversion) [reply src/material/button/button.ts]: I see your point. But I feel like explicitly having program as default is reasonable since this method intends to focus the button programmatically (unless a specific origin had been specified)
