### PR TITLE
fix(progress-spinner/testing): harness selector not matching mat-spinner selector

### LINKED ISSUE #19649: MatProgressSpinner harness does not contemplate mat-spinner alias
# Context
In the Angular Material documentation, it is said you can either use `<mat-progress-spinner>` or `<mat-spinner>` to place spinner components:

> The progress-spinner supports two modes, "determinate" and "indeterminate". The `<mat-spinner>` component is an alias for `<mat-progress-spinner mode="indeterminate">`.

# Issue
When using harnesses to test the application, there's no harness for the `<mat-spinner>` element and the `MatProgressSpinnerHarness` just includes selector for `mat-progress-spinner`, and not their alias `mat-spinner`:

https://github.com/angular/components/blob/264c20d19667074af9981d0de86e67fea4efa0d8/src/material/progress-spinner/testing/progress-spinner-harness.ts#L17

Should the selector be able to match both spinners? Or maybe we're missing a `MatSpinnerHarness` here? 🤔

Thanks!

### PR DESCRIPTION
**Pull request by crisbeto**
The progress spinner has two variations: `mat-progress-spinner` and `mat-spinner`, but the test harness was only accounting for the former.

Fixes #19649.

### CODE REVIEW

File: src/material/progress-spinner/testing/progress-spinner-harness.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ import {ProgressSpinnerHarnessFilters} from './progress-spinner-harness-filters'
 /** Harness for interacting with a standard mat-progress-spinner in tests. */
 export class MatProgressSpinnerHarness extends ComponentHarness {
   /** The selector for the host element of a `MatProgressSpinner` instance. */
-  static hostSelector = 'mat-progress-spinner';
+  static hostSelector = 'mat-progress-spinner,mat-spinner';
```
Comment (davidlj95) [inline src/material/progress-spinner/testing/progress-spinner-harness.ts:17]: not sure about that, but I've seen in other harnesses they use an array of selectors when more than one is needed here 🤔

Comment (crisbeto) [reply src/material/progress-spinner/testing/progress-spinner-harness.ts:17]: It seems like the other places have an array and they `join` it into a comma-separate string so the result should be the same.

Comment (davidlj95) [reply src/material/progress-spinner/testing/progress-spinner-harness.ts:17]: right! thanks 👍
