### PR TITLE
fix(material/menu): set correct focus origin on item when opened via keyboard

### LINKED ISSUE #21241: bug(menu): When opening menu with keyboard, focus is set to the first item, but focus origin is set to "program".
#### Motivation

When opening a menu with keyboard as demonstrated in the repro steps below, focus moves to the first menu item (which is correct), but the focus origin is set to "program". This is a problem because some Angular Material consumers (in particular products internal to Google) have styles that depend upon the appropriate focus origin class. In my case, I have strong focus indicator styles that are only supposed to appear when the class `.cdk-keyboard-focused` is present. When opening a menu with a keyboard, I expect my strong focus indicator to render on the first menu item, but it does not.

Note that this is a problem in both the old Material and new MDC menus.

#### Problem & Solution

The problematic line is [here](https://github.com/angular/components/blob/master/src/material/menu/menu-trigger.ts#L335). Menu only tracks whether it was opened by a "mouse" or "touch" focus origin, and if it is neither of those, it defaults to "program". The easiest solution seems to be to update menu to also track "keyboard" focus origin. The `_handleKeydown` event handler will need to update the `_openedBy` focus origin to "keyboard". I'm open to other ideas as well.

#### Reproduction

Steps to reproduce:
1. Go to https://stackblitz.com/angular/xkpoabmbqpb?file=src/app/material-module.ts
2. Open the menu with the "Enter" key.
3. Observe that the class `.cdk-program-focused` is present on the first menu item.
 
#### Expected Behavior

I expect the class `.cdk-keyboard-focused` to be present on the first menu item.

#### Actual Behavior

Observe that the class `.cdk-program-focused` is present on the first menu item.

#### Environment

- Angular: Latest
- CDK/Material: Latest
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that we were setting the `program` focus origin on the first menu item, even though the user opened it using the keyboard.

Fixes #21241.

### CODE REVIEW

File: src/material/menu/menu-trigger.ts [hunk 1]
```diff
@@ -103,7 +103,7 @@ export class MatMenuTrigger implements AfterContentInit, OnDestroy {
 
   // Tracking input type is necessary so it's possible to only auto-focus
   // the first item of the list when the menu is opened via the keyboard
-  _openedBy: 'mouse' | 'touch' | null = null;
+  _openedBy: 'mouse' | 'touch' | 'keyboard' | null = null;
```
Comment (zelliott) [inline src/material/menu/menu-trigger.ts:106]: Should we just type this to `FocusOrigin`?

File: src/material/menu/menu-trigger.ts [hunk 2]
```diff
@@ -519,6 +519,7 @@ export class MatMenuTrigger implements AfterContentInit, OnDestroy {
   /** Handles key presses on the trigger. */
   _handleKeydown(event: KeyboardEvent): void {
     const keyCode = event.keyCode;
+    this._openedBy = 'keyboard';
```
Comment (zelliott) [inline src/material/menu/menu-trigger.ts:522]: I think this change alone could potentially cause a very subtle bug that we may not care about. It's possible for this method to be called and not actually open the menu. For example, if focus is on the menu trigger button and one presses some key that is not Enter or Space. In that case, `this_openedBy` will be set to `keyboard`, even though the menu was not actually opened by keyboard.

This means that a subsequent programmatic call to open the menu would cause this line (`this.menu.focusFirstItem(this._openedBy || 'program');`) within `_initMenu` to focus the first menu item with `keyboard` origin, even though we'd expect for it to be opened with `program` origin.

Again, I think this is a very minor bug and maybe something we don't care about. But one potential fix is to conditionally set `this._openedBy = 'keyboard';` based upon if the menu is actually opened. I'm not sure if it's possible to know whether or not the menu will be opened in this method, but we could use a heuristic (e.g. if Enter or Space are pressed or if the submenu conditions below are true).

**Comment by zelliott** [comment]
Left two minor bugs, otherwise LGTM.

File: src/material/menu/menu-trigger.ts (hunk 1 above)
Comment (crisbeto) [reply src/material/menu/menu-trigger.ts:106]: It's not all the values of `FocusOrigin` though. I've changed it to `Exclude<FocusOrigin, 'program'>` instead.

File: src/material/menu/menu-trigger.ts (hunk 2 above)
Comment (crisbeto) [reply src/material/menu/menu-trigger.ts:522]: I think that's very unlikely to happen, because we set the value to something different next time it is opened. I've added an extra check so we only set this when the Enter key is pressed.

Comment (zelliott) [reply src/material/menu/menu-trigger.ts]: SGTM. You might want to check to Space as well. Also, I think we also want to set it to `keyboard` when opening a sub menu with arrow keys?

**Comment by zelliott** [comment]
@annieyw Any update on this? Thanks!

**Comment by 4oo** [comment]
Thanks for fixing this @crisbeto ! I'm looking forward to this as it will unblock some a11y work we're doing.

**Review by jelbourn — APPROVED** [review]
LGTM
