### PR TITLE
fix(cdk/drag-drop): don't disable native dragging on inactive handles

### LINKED ISSUE #20974: bug(drag-drop): scrolling on mobile blocked for disabled drag handle
#### Reproduction
A cdkDropList (any kind of drag-drop-countainer would most likely have this issue as well) with disabled cdkDrag items which have a drag handle inside.
https://angular-st9rbb.stackblitz.io/
https://stackblitz.com/edit/angular-st9rbb?file=src%2Fapp%2Fcdk-drag-drop-disabled-example.html

Steps to reproduce:
1. Switch browser to mobile view / use touchscreen
2. Try to scroll by first touching the drag handle and moving up/down
  
#### Expected Behavior
Scrolling (with a touch screen) is possible, even on the drag handle if the cdkDrag item is disabled.

#### Actual Behavior
Scrolling is impossible, because the drag handle blocks scrolling, even if it is disabled:
cdk-drag-issue

#### Environment

- Angular: 10.0.0
- CDK/Material: 10.0.0 (also tested with latest 10.2.7 and issue persists)
- Browser(s): Chrome, Firefox, iOS Safari, Android Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, iOS, Android

### PR DESCRIPTION
**Pull request by crisbeto**
Currently we disable native drag interactions on handles once when they're registered, however this can block scrolling on mobile devices if the handle is inactive (either it is disabled or the drag element is disabled).

These changes toggle the state dynamically depending on the active state.

Fixes #20974.

### CODE REVIEW

File: src/cdk/drag-drop/drag-ref.ts [hunk 1]
```diff
@@ -468,7 +470,10 @@ export class DragRef<T = any> {
    * @param handle Handle element to be enabled.
    */
   enableHandle(handle: HTMLElement) {
-    this._disabledHandles.delete(handle);
+    if (this._disabledHandles.has(handle)) {
+      this._disabledHandles.delete(handle);
+      toggleNativeDragInteractions(handle, this.disabled);
```
Comment (mmalerba) [inline src/cdk/drag-drop/drag-ref.ts:475]: should this say `false` instead of `this.disabled`?

Comment (crisbeto) [reply src/cdk/drag-drop/drag-ref.ts:475]: No, the handle should stay disabled if it is enabled while the drag item is disabled.

Comment (mmalerba) [reply src/cdk/drag-drop/drag-ref.ts:475]: Then should it also use `this.disabled` in `disableHandle`? seems odd that the methods aren't mirrored

Comment (crisbeto) [reply src/cdk/drag-drop/drag-ref.ts:475]: No since `disableHandle` only disables the handle, not the entire draggable item. A handle is considered "inactive" if either it is disabled or the item is disabled. This might be slightly confusing since `toggleNativeDragInteractions(true)` means that interactions should be enabled which is true when dragging is disabled.

Comment (mmalerba) [reply src/cdk/drag-drop/drag-ref.ts:475]: Ok I think I understand it, just a little confusing at first sight

**Review by mmalerba — APPROVED** [review]
LGTM
