### PR TITLE
fix(cdk/drag-drop): avoid conflicts with sticky table headers

### LINKED ISSUE #22781: bug(material/table): cdkDrag of mat-header-cell styling broken when used with "sticky: true"
### Reproduction
I believe that [#21403](https://github.com/angular/components/pull/21403) (released in 11.0.4) introduced this bug. I have included the same StackBlitz, once using 11.0.3, and once using 11.0.4, to demonstrate the bug that was introduced.

Steps to reproduce:
1. Using "@angular/material": "^11.0.4" or greater (I have also tested with 11.2.12 and 12.0.1 and the bug persists)
2. Set up a mat-table using `cdkDrag` on the `mat-header-cell`'s 
3. On the `mat-header-row`, set `*matHeaderRowDef="displayedColumns; sticky: true"`
4. Drag the column header and observe the styling of the header as it is being dragged

StackBlitz of issue: https://mat-table-sticky-after.stackblitz.io
 
### Expected Behavior
The expected behavior is that the styling of the header remains next to the pointer as it is being dragged. This is the behavior **PRIOR** to `11.0.4`.

See this StackBlitz of `11.0.3` for the expected behavior: https://mat-table-sticky-before.stackblitz.io

dragging-11_0_3

### Actual Behavior
The behavior in `^11.0.4` is that the styling is shifted: https://mat-table-sticky-after.stackblitz.io

dragging_11_0_4

#### Environment

- Angular: >= 11.0.4
- CDK/Material: >= 11.0.4
- Browser(s): Chrome 90.0.4430.212
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 11.2.3

### PR DESCRIPTION
**Pull request by crisbeto**
The Material table with sticky headers sets its `position` as `!important` which ends up overriding the dragging styles. These changes rework the internals to use `setProperty` instead of `element.style.position` which allows us to set the `position` as `!important` as well. It also has the advantage that we can write the properties as dash case, instead of having to guess whether the vendor-prefixed properties are camel case or pascal case.

Fixes #22781.

### CODE REVIEW

**Comment by brendanowens** [comment]
Thank you for the quick fix on this @crisbeto!

File: src/cdk/drag-drop/drag-ref.ts [hunk 1]
```diff
@@ -88,6 +88,12 @@ export interface Point {
   y: number;
 }
 
+/** Inline styles to be set as `!important` while dragging. */
+const dragImportantProperties = new Set([
+  // Needs to be important, because some `mat-table` sets `position: sticky !important`. See #22781.
+  'position'
+]);
+
```
Comment (jelbourn) [inline src/cdk/drag-drop/drag-ref.ts:96]: Would problematic would it be to alternatively remove the `!important` from `mat-table`? My inclination would be to avoid an `!important` arms race by avoiding it completely.

Comment (crisbeto) [reply src/cdk/drag-drop/drag-ref.ts:96]: The problem with removing the `!important` is that our sticky header selector currently has really low specificity and can be overwritten by styles that have been encapsulated by Angular. See https://github.com/angular/components/issues/20558.

**Review by jelbourn — APPROVED** [review]
LGTM
