### PR TITLE
fix(material/datepicker): restore focus after closing animation

### LINKED ISSUE #25564: (Bug) Angular Material Date Picker Accessibility Problem, Focus is lost for Year and Month Picker
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

Keyboard Accessiblity issue for Year and Month datepicker.
If you select the Date using keyboard, after selecting the month the focus is not retained on the datepicker rather the focus moves away completely from the datepicker.
It seems like this happens datepicker.close(); is called.
I tried to follow instructions provided over [here](https://material.angular.io/components/datepicker/overview#datepicker-views-selection) 
This bug can be reproduced even in the Official example. I am not sure if there is a way to retain focus for Year and Month datepicker as this doesn't happen with other variations of material datepicker

### Reproduction

Steps to reproduce:
1. Go to this example provided in Angular Material Documentaion https://material.angular.io/components/datepicker/overview#datepicker-views-selection
2. Select Month and year only using Keyboard
3. After Selection Year and Month press TAB and notice the focus is moved to navigation menu rather than staying on the Datepicker

### Expected Behavior

Focus should stay on datepicker or should move to next component

### Actual Behavior

Focus is lost and moves to top of the page

### Environment

- Angular: ng version 7.3.0
- CDK/Material: @angular/cdk : 12.2.13, @angular/material : 12.2.13 (happens with 14.2.0 as well)
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows
-Node: v15.5.0

### PR DESCRIPTION
**Pull request by crisbeto**
Currently the datepicker restores focus when the closing sequence starts, but in some cases that can cause focus to be lost. When the calendar view changes, we delay moving focus for a while in order to work around a VoiceOver issue. This means that if a closing sequence is kicked off while there's an in-progress view change, focus may end up being restored, then moved back into the calendar which then gets destroyed. This can be seen in the "Datepicker emulating a Year and month picker" example.

These changes resolve the issue by moving the focus restoration all the way to the end of the closing sequence.

Fixes #25564.

### CODE REVIEW

File: src/material/datepicker/datepicker-base.ts [hunk 1]
```diff
@@ -613,33 +616,48 @@ export abstract class MatDatepickerBase<
...
+    if (this._componentRef) {
+      const {instance, location} = this._componentRef;
+      instance._startExitAnimation();
+      instance._animationDone.pipe(take(1)).subscribe(() => {
+        const activeElement = this._document.activeElement;
+
+        // Since we restore focus after the exit animation, we have to check that
+        // the user didn't move focus themselves inside the `close` handler.
+        if (
+          canRestoreFocus &&
```
Comment (crisbeto) [inline src/material/datepicker/datepicker-base.ts:642]: I couldn't write a test for this, because there are several timeouts and animations happening at the same time and flushing one of them flushes everything.

**Review by zarend — APPROVED** [review]
LGTM
