### PR TITLE
fix(tabs): not picking up indirect descendant tabs in ivy

### LINKED ISSUE #17336: mat-tab inside ng-container failed to display in ivy
# 🐞 bug report

### Is this a regression?

Yes, disabling ivy works.

### Description

When ivy is enabled, this mat-tab failed to render:

    <mat-tab-group>
      <ng-container *ngIf="title$ | async as title">
        <mat-tab label="Title">{{ title }}</mat-tab>
      </ng-container>
    </mat-tab-group>

## 🔬 Minimal Reproduction

https://github.com/felix-halim/ng-container-ivy-bug

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.5
Node: 10.16.3
OS: darwin x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.5
@angular-devkit/build-angular     0.803.5
@angular-devkit/build-optimizer   0.803.5
@angular-devkit/build-webpack     0.803.5
@angular-devkit/core              8.3.5
@angular-devkit/schematics        8.3.5
@angular/cdk                      8.2.0
@angular/cli                      8.3.5
@angular/material                 8.2.0
@ngtools/webpack                  8.3.5
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

### PR DESCRIPTION
**Pull request by crisbeto**
In ViewEngine `ContentChildren` would pick up indirect descendant items, as long as another directive wasn't matched along the way. This allowed for tabs to be wrapped inside something like an `ng-container`. With Ivy `ContentChildren` is a little more strict and it only works on direct descendants.

These changes turn on `descendants` so that we continue supporting the existing use cases from ViewEngine. Note that it needs a bit of extra logic in order to ensure that nested tab groups continue to work as expected.

Fixes #17336.

### CODE REVIEW

File: src/material/tabs/tab-group.ts [hunk 1]
```diff
@@ -243,11 +248,26 @@ export abstract class _MatTabGroupBase extends _MatTabGroupMixinBase implements
         }
       }
 
-      this._subscribeToTabLabels();
```
Comment (crisbeto) [inline src/material/tabs/tab-group.ts]: I remove this call because I noticed that there's another one just like it a few lines above. It seems like an issue when resolving merge conflicts.

File: src/material/tabs/tab-group.ts [hunk 2]
```diff
@@ -243,11 +248,26 @@ export abstract class _MatTabGroupBase extends _MatTabGroupMixinBase implements
...
+  private _subscribeToAllTabChanges() {
+    // Since we use a query with `descendants: true` to pick up the tabs, we may end up
+    // catching some that are inside of nested tab groups so we need to filter them out manually.
+    this._allTabs.changes
+      .pipe(startWith(this._allTabs))
+      .subscribe((tabs: QueryList<MatTab>) => {
+        this._tabs.reset(tabs.filter(tab => {
+          // @breaking-change 10.0.0 Remove null check for `_closestTabGroup`
+          // once it becomes a required parameter in MatTab.
+          return !tab._closestTabGroup || tab._closestTabGroup === this;
```
Comment (Splaktar) [inline src/material/tabs/tab-group.ts]: I was able to figure it out, but I think that the comments here could use some more clarity around what this is doing. I.e. how it is filtering out tab that are inside nested tab groups.

File: tools/public_api_guard/material/tabs.d.ts [hunk 3]
```diff
@@ -108,7 +112,8 @@ export declare class MatTab extends _MatTabMixinBase implements OnInit, CanDisab
     position: number | null;
     templateLabel: MatTabLabel;
     textLabel: string;
-    constructor(_viewContainerRef: ViewContainerRef);
+    constructor(_viewContainerRef: ViewContainerRef,
+    _closestTabGroup?: any);
```
Comment (Splaktar) [inline tools/public_api_guard/material/tabs.d.ts]: This is the way that clang wants to format this? any benefit to having this be two lines instead of one?

File: src/material-experimental/mdc-tabs/tab-group.spec.ts [hunk 4]
```diff
@@ -881,3 +913,18 @@ class TabGroupWithIsActiveBinding {
...
+  template: `
+    <mat-tab-group>
+      <ng-container [ngSwitch]="true">
+        <mat-tab label="One">Tab one content</mat-tab>
+        <mat-tab label="Two">Tab two content</mat-tab>
+      </ng-container>
+    </mat-tab-group>
+  `,
+})
+class TabGroupWithIndirectDescendantTabs {
```
Comment (Splaktar) [inline src/material-experimental/mdc-tabs/tab-group.spec.ts]: This is all duplicated from what's in `material/`. Do we have a reason for choosing this approach?
Was it too much work or is there a blocker to trying to export something from `material/` tests that could be re-used in the `material-experimental/mdc-x` tests?

File: src/material/tabs/tab-group.ts [hunk 5]
```diff
@@ -88,10 +89,13 @@ interface MatTabGroupBaseHeader {
 // tslint:disable-next-line:class-name
 export abstract class _MatTabGroupBase extends _MatTabGroupMixinBase implements AfterContentInit,
     AfterContentChecked, OnDestroy, CanColor, CanDisableRipple {
-  abstract _tabs: QueryList<MatTab>;
+  abstract _allTabs: QueryList<MatTab>;
```
Comment (jelbourn) [inline src/material/tabs/tab-group.ts]: Can you add a JsDoc comment that explains that this may also contain nested tabs-in-tabs?

File: tools/public_api_guard/material/tabs.d.ts (hunk 3 above)
Comment (crisbeto) [reply tools/public_api_guard/material/tabs.d.ts]: It's not clang, it's what the API goldens script generated.
