### PR TITLE
fix(cdk/overlay): skip trigger interactions in outside click event

### LINKED ISSUE #28949: bug(cdk overlay): open/close overlay behavior
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

The cdkoverlay doesn't close on click of the trigger button after it has been opened, if both `(overlayOutsideClick)="isOpen=false"` is added to the overlay template and `(click)="isOpen = !isOpen"` is added to the trigger button. 

### Reproduction

StackBlitz link: https://stackblitz.com/edit/nxazcw?file=src%2Fexample%2Fcdk-overlay-basic-example.html
Steps to reproduce:
1. Click on a button to open the overlay.
2. Click anywhere outside of the overlay, notice the overlay closes.
3. Click on a button to open the overlay again.
4. Click on the same button to close the overlay - notice that it doesn't close.

### Expected Behavior

The overlay should close on click of the trigger button as well as when the user  clicks anywhere outside the overlay.

### Actual Behavior

If the ability the close the overlay by clicking anywhere outside is added, clicking on the button again doesn't close the overlay.

### Environment

- Angular: 17.3.1
- CDK/Material: 17.3.1
- Browser(s): All major browsers
- Operating System (e.g. Windows, macOS, Ubuntu): All operating systems

### PR DESCRIPTION
**Pull request by crisbeto**
Adds some logic to skip the trigger when considering clicks outside of the overlay since filtering them is the most common case (e.g. we do it in some of our components) and can be annoying to deal with.

Fixes #28949.

### CODE REVIEW

File: src/cdk/overlay/overlay-directives.ts [hunk 1]
```diff
@@ -311,7 +312,12 @@ export class CdkConnectedOverlay implements OnDestroy, OnChanges {
     });
 
     this._overlayRef.outsidePointerEvents().subscribe((event: MouseEvent) => {
-      this.overlayOutsideClick.next(event);
+      const origin = this._getOriginElement();
+      const target = _getEventTarget(event) as Element | null;
+
+      if (!target || !origin || (origin !== target && !origin.contains(target))) {
```
Comment (andrewseguin) [inline src/cdk/overlay/overlay-directives.ts:318]: nit: the null checks appear to be redundant since `contains` returns false if `target` is null. This could be reduced to `origin !== target && !origin?.contains(target))`

**Review by andrewseguin — APPROVED** [review]

File: src/cdk/overlay/overlay-directives.ts (hunk 1 above)
Comment (crisbeto) [reply src/cdk/overlay/overlay-directives.ts:318]: I'll get rid of the `target` check, but I'll leave in the one for `origin` since I don't want to end up comparing nulls.
