### PR TITLE
fix(material/schematics): don't drop prebuilt imports in theming API migration

### LINKED ISSUE #22697: Updating Material from 11 to 12 removes the theme in the styles.scss but forgets to add it back to the angular.json
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 
I have not seen this bug during previous migrations

### Description

During the update of Material from 11 to 12, the link to the theme has been automatically removed from the `style.scss` file (aka 
 this line has been removed : @import "~@angular/material/prebuilt-themes/indigo-pink.css")
But it has not been automatically added back to the `styles` array of the `angular.json`. 

## 🔬 Minimal Reproduction
(sorry I don't know the command line for each step, specially the first one that needs to create a project in version 11)

1. Create new project in version 11 with the cli and add Material support.
2. Add a theme to the `style.scss` (@import "~@angular/material/prebuilt-themes/indigo-pink.css")
3. Launch the `ng update @angular/material`

You will see the line has been removed from the `styles.scss` file ... but no add to styles arry of the `angular.json` file.

## 🔥 Exception or Error

<pre><code>

// no error is returned
</code></pre>

## 🌍 Your Environment

<pre><code>

$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.0
Node: 14.15.1
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
rxjs                            7.0.1
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by crisbeto**
Currently the theming API migration drops any imports starting with `~@angular/material/`, assuming that they're Sass APIs. This can result in prebuilt style imports being removed by mistake.

These changes add a regex based on which we'll exclude some imports from the migration.

Fixes #22697.

### CODE REVIEW

File: src/material/schematics/ng-update/migrations/theming-api-v12/theming-api-migration.ts [hunk 1]
```diff
@@ -22,7 +22,8 @@ export class ThemingApiMigration extends DevkitMigration<null> {
     if (extname(stylesheet.filePath) === '.scss') {
       const content = stylesheet.content;
       const migratedContent = content ? migrateFileContent(content,
-        '~@angular/material/', '~@angular/cdk/', '~@angular/material', '~@angular/cdk') : content;
+        '~@angular/material/', '~@angular/cdk/', '~@angular/material', '~@angular/cdk',
+        undefined, /material\/prebuilt-themes|cdk\/.*-prebuilt/) : content;
```
Comment (devversion) [inline src/material/schematics/ng-update/migrations/theming-api-v12/theming-api-migration.ts:26]: I think we should also capture the obviously uncommon case of `material/core/theming/prebuilt`. IIRC we recommended that in the past (when Gulp was still used for releasing). e.g. https://stackoverflow.com/questions/43436779/how-to-include-theming-the-angular-2-material-in-webpack-app-jhipster/43751541

**Review by devversion — APPROVED** [review]

File: src/material/schematics/ng-update/migrations/theming-api-v12/theming-api-migration.ts (hunk 1 above)
Comment (crisbeto) [reply src/material/schematics/ng-update/migrations/theming-api-v12/theming-api-migration.ts:26]: Those files don't exist in the npm package though. The only prebuilt `.css` files I found were the ones in the regex above.

Comment (devversion) [reply src/material/schematics/ng-update/migrations/theming-api-v12/theming-api-migration.ts:26]: Ops. Good point. I was thinking they exist there. Nevermind this comment then

File: src/material/schematics/ng-update/test-cases/v12/misc/theming-api-v12.spec.ts [hunk 2]
```diff
@@ -716,4 +716,22 @@ describe('v12 theming API migration', () => {
...
+      `@import '~@angular/cdk/overlay-prebuilt.css';`,
+      `@include mat-core();`,
+    ]);
+
+    await runMigration();
+
+    expect(splitFile(THEME_PATH)).toEqual([
+      `@use '~@angular/material' as mat;`,
+      `@import '~@angular/material/prebuilt-themes/indigo-pink.css';`,
+      `@import '~@angular/cdk/overlay-prebuilt.css';`,
```
Comment (Splaktar) [inline src/material/schematics/ng-update/test-cases/v12/misc/theming-api-v12.spec.ts:733]: It should be possible to migrate these to the following
```suggestion
      `@use '@angular/material/prebuilt-themes/indigo-pink.css';`,
      `@use '@angular/cdk/overlay-prebuilt.css';`,
```
Or is that something that you are depending upon the sass-migrator to do?

**Review by Splaktar — COMMENTED** [review]
Thank you for the quick PR on this!

File: src/material/schematics/ng-update/test-cases/v12/misc/theming-api-v12.spec.ts (hunk 2 above)
Comment (crisbeto) [reply src/material/schematics/ng-update/test-cases/v12/misc/theming-api-v12.spec.ts:733]: I believe that imports of `.css` files are still supposed to go through `@import`.

Comment (Splaktar) [reply src/material/schematics/ng-update/test-cases/v12/misc/theming-api-v12.spec.ts:733]: I thought that too at first, but found that they work fine with `@use` as long as the deprecated `sass-loader` feature of using `~` is not used.

If you'd seen an official statement from the Sass team to the otherwise, please do let me know.

**Comment by intellix** [comment]
I'm not seeing any migrations/automatic updates happening when updating from 11 to 12 and I can't see any information anywhere as to when an update comes with a migration or not. 

Is there a list somewhere?
