### PR TITLE
fix(multiple): remove label for attribute on non-native elements

### LINKED ISSUE #27241: feat(MatFormField): Add MatLabel input property to change use of html <label> for non-labelable form elements and prevent page errors
### Feature Description

Add an input property to MatLabel that changes the use of `<label>` into a basic div element without linking it to a control. Perhaps it could be implemented as:
```
<mat-form-field>
  <mat-label [displayOnly]="true">The label</mat-label>
  <non-labelable-form-control/>
</mat-form-field>
```

### Use Case

When using form fields with standard 'labelable' form elements such as `<input>` and `<select>` and using a `<mat-label>` to label the field, the HTML specification for the `<label for="x">` works very nicely. However, there are times when non-standard form elements are desirable to use, such as `<mat-select>` with html formatted options, or other custom form fields that you might build yourself. In these cases when you use the `<mat-label>` element, the resulting `<label for="x">` generates a page error with the violation:

Incorrect use of `<label for=FORM_ELEMENT>`

image

You can leave out `<mat-label>` to work around this, however, it is a better user experience to have the floating label and to also have these form fields match the appearance and behaviour of the other fields in a form.

### PR DESCRIPTION
**Pull request by crisbeto**
Adds an option to remove the `for` attribute from the `<label>` inside the form field from elements that can't be labeled. Also applies the new option to `mat-select` and `mat-date-range-picker`. This isn't an accessibility regression, because those elements were already being labeled using `aria-labelledby`.

Fixes #27241.

### CODE REVIEW

**Review by wagnermaciel — APPROVED** [review]

File: src/material/form-field/form-field-control.ts [hunk 1]
```diff
@@ -68,6 +68,13 @@ export abstract class MatFormFieldControl<T> {
    */
   readonly userAriaDescribedBy?: string;
 
+  /**
+   * Whether to automatically assign the ID of the form field as the `for` attribute
+   * on the `<label>` inside the form field. Set this to true to prevent the form
+   * field from associating the label with non-native elements.
+   */
+  readonly disableAutomaticLabeling?: boolean;
```
Comment (zarend) [inline src/material/form-field/form-field-control.ts:76]: Should this have  @docs-private like the other  disableAutomaticLabeling?

**Review by zarend — APPROVED** [review]

**Comment by dreamstar-enterprises** [comment]
Hi there, but how do you do this without getting this error:

243509402-88ceec48-3c7d-4c7a-a62c-4b9d3694c3f2
