### PR TITLE
Resolve component ID collisions

### LINKED ISSUE #27163: bug(mat-tab): NG0912: Component ID generation collision detected in unit test
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

Getting below error while running unit tests of the application

`Chrome 113.0.0.0 (Windows 10) WARN: 'NG0912: Component ID generation collision detected. Components 'MatTab' and 'MatLegacyTab' with selector 'mat-tab' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912'
`

image

### Reproduction

Steps to reproduce:
1. Create new angular 16 app (npx ng new)
2. Install material (ng add @angular/material)
3. Use legacy version of mat tab inside your component
4. Try to run units of the component in which you are using legacy mat-tab

Or you can use attached zip file

[ng16app.zip](https://github.com/angular/components/files/11561130/ng16app.zip)

### Expected Behavior

Running units should not throw the warning

### Actual Behavior

Running units is throwing the warning

### Environment

- Angular: 16
- CDK/Material: 16
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by crisbeto**
Resolves all of the current component ID collisions and adds an automated CI check to prevent further ones from being introduced.

Fixes #27163.

### CODE REVIEW

File: src/material/legacy-dialog/testing/dialog-opener.ts [hunk 1]
```diff
@@ -27,6 +27,11 @@ import {_MatTestDialogOpenerBase} from '@angular/material/dialog/testing';
   template: '',
   changeDetection: ChangeDetectionStrategy.OnPush,
   encapsulation: ViewEncapsulation.None,
+  host: {
+    // This binding is used to ensure that the component ID
+    // doesn't clash with the `MatTestDialogOpener`.
```
Comment (devversion) [inline src/material/legacy-dialog/testing/dialog-opener.ts:32]: do you think we could have special comments in here that the script could use to tell us if e.g. this trick suddenly is no longer needed? e.g. when dialog test opener changes

Comment (crisbeto) [reply src/material/legacy-dialog/testing/dialog-opener.ts:32]: I think that we could, but I would probably lean more towards a config file. I'm not sure if it's worth the trouble now though given that these workarounds are only there for the legacy components and their perf impact is minimal.

Comment (devversion) [reply src/material/legacy-dialog/testing/dialog-opener.ts:32]: yeah, fine by me if it's just legacy components 👍

**Review by devversion — APPROVED** [review]

File: src/material/legacy-dialog/testing/dialog-opener.ts (hunk 1 above)
Comment (devversion) [reply src/material/legacy-dialog/testing/dialog-opener.ts:32]: (although I can see menu here)

File: src/material/menu/menu.ts [hunk 2]
```diff
@@ -552,6 +552,8 @@ export class _MatMenuBase
     '[attr.aria-labelledby]': 'null',
     '[attr.aria-describedby]': 'null',
     'ngSkipHydration': '',
+    // This binding is used to ensure that the component ID doesn't clash with the `MatTextColumn`.
```
Comment (LayZeeDK) [inline src/material/menu/menu.ts:555]: question: Is the Menu component at risk of clashing with `MatTextColumn` or is this a copy-paste error?

Comment (crisbeto) [reply src/material/menu/menu.ts:555]: It's just me copying the same blob everywhere.

Comment (LayZeeDK) [reply src/material/menu/menu.ts:555]: Which one is the correct one? `MatLegacyMenu`?

Comment (LayZeeDK) [reply src/material/menu/menu.ts]: Resolved in 320a3b8c2e469fc360ed606a031df6b863e6f699.

**Review by LayZeeDK — APPROVED** [review]
