### PR TITLE
fix(material/progress-spinner): animation not working on some zoom levels in Safari

### LINKED ISSUE #23668: Incorrect animation of progress spiner in Safari browser when zoom out
# AngularJS Material is in LTS mode

We are no longer accepting changes that are not critical bug fixes into this project.
See [Long Term Support](https://material.angularjs.org/latest/#long-term-support) for more detail.

## Demo and steps to reproduce the issue
[This blank StackBlitz demo](https://stackblitz.com/edit/angularjs-material-blank?file=app%2Fapp.template.html) can be used to create a reproduction that demonstrates your issue.

**Demo URL (required)***:  

#### Detailed Reproduction Steps
1. Open https://material.angular.io/components/progress-spinner/overview in Safari browser
2. Zoom out

### Explain the expected behavior
animation of progress spiner is correct

### Explain the current behavior
animation of progress spiner is incorrect

### Discuss the use-case or motivation for changing the existing behavior
Users of Safari browser now see broken progress spiner animation when zoon out

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.
- AngularJS Material: 1.
- OS: 
- Browsers: Safari 15.0
- Screen Readers: 

https://user-images.githubusercontent.com/15737899/135403565-9b1a50d2-e22b-4f44-9f0c-e287bb5407a9.mov

 
#### Stack Trace
```

```

#### Screenshots

https://user-images.githubusercontent.com/15737899/135404002-97512048-9bcb-4d66-9b7d-2127c4e70b1f.mov

[](url)

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the progress spinner animation was broken on Safari on non-default zoom levels. The problem seems to be that the `transform-origin` was being offset by the amount of zoom. These changes work around it by setting the origin based on the zoom level.

Fixes #23668.

### CODE REVIEW

File: src/material/progress-spinner/progress-spinner.ts [hunk 1]
```diff
@@ -218,6 +222,14 @@ export class MatProgressSpinner extends _MatProgressSpinnerBase implements OnIni
         this.strokeWidth = defaults.strokeWidth;
       }
     }
+
+    // Safari has an issue where the circle isn't positioned correctly when the page has a
+    // different zoom level from the default. This handler triggers a recalculation of the
+    // `transform-origin` when the page zoom level changes.
+    // See `_getCircleTransformOrigin` for more info.
+    if (_platform.isBrowser && _platform.SAFARI) {
+      window.addEventListener('resize', this._resizeHandler);
```
Comment (crisbeto) [inline src/material/progress-spinner/progress-spinner.ts:231]: I'm not a fan of this, but I couldn't find a better way to trigger a change detection when the zoom changes. Alternatively we could not trigger the change detection ourselves, but we risk having the user see a broken animation when they zoom in/out.
