### PR TITLE
fix(material/datepicker): calendar aria-descriptions start/end date

### LINKED ISSUE #23442: bug(datepicker): Datepicker w/ date range It is not providing audio feedback of whether the date selection is start date or end
Copied from [internal bug report](http://b/195600298)

Environment:
OS| Browser | Screen reader
ChromeOS | Google Chrome 91.0.4472.167 | ChromeVox
macOS Catalina | Google Chrome 92.0.4515.131 | VoiceOver
Windows 10 | Google Chrome 92.0.4515.131 | NVDA/JAWS
Windows 10 | Firefox 90.0.2 (64-bit) | NVDA

Pre-requisites:
1. Enable the respective screen reader

Steps
1. Browse the Datepicker demo
2. Navigate to the "Date range selection" section
3. Activate "Open calendar" button from date range section, say, "Date range selection"
4. Activate any start date
5. Focus on any date to select end date

Actual result:
It is not providing any audio feedback on whether selection is for start date or end date

EXPECTED result:
It should provide audio feedback that calendar is open for start date selection. And on selection of the start date, it should provide audio feedback that calendar is open for end date selection

### PR DESCRIPTION
**Pull request by zarend**
For date ranges, add aria-descriptions to the cell of the current start
date and also for end date.

Popuplate aria descriptions with the expected value of the ARIA accessible name of the
`matStartDate` and `matEndDate` inputs. Introduces `_computeAriaAccessibleName` function to
implement ARIA acc-name-1.2 specificiation.

Fixes https://github.com/angular/components/issues/23442 and https://github.com/angular/components/issues/23445

Screen Shot 2022-08-19 at 2 20 14 PM

### CODE REVIEW

**Comment by zarend** [comment]
This is pretty far along, but still a draft. Here's  the remaining TODO's to make this ready:
 - Fix examples to have both `placeholder` and `aria-label`
 - rename `startdate-arialabelledby` to `startdate-accessible-name`
 - update documentation to reflect best practice of giving `matStartDate`/`matEndDate` an aria label. (will probably be in a separate PR).
  - address 3 failing CI checks

File: src/material/datepicker/aria-accessible-name.ts [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+  isDirectlyReferenced: boolean,
+): string {
+  // NOTE: this differs from accname-1.2 specification.
+  //  - Does not implement Step 1. of accname-1.2: '''If `currentNode`'s role prohibits naming,
+  //    return the empty string ("")'''.
+  //  - Does not implement Step 2.A. of accname-1.2: '''if current node is hidden and not directly
+  //    referenced by aria-labelledby... return the empty string.'''
+
+  // acc-name-1.2 Step 2.B.: aria-labelledby
+  if (currentNode instanceof Element && isDirectlyReferenced) {
```
Comment (crisbeto) [inline src/material/datepicker/aria-accessible-name.ts:82]: `instanceof Element` is going to break during server-side rendering. Instead you can check if `currentNode.nodeType === 1`.

File: src/material/datepicker/aria-accessible-name.ts [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+      return validIdRefs
+        .map(idRef => {
+          return _computeAriaAccessibleNameInternal(idRef, false);
+        })
+        .join(' ');
+    }
+  }
+
+  // acc-name-1.2 Step 2.C.: aria-label
+  if (currentNode instanceof Element) {
```
Comment (crisbeto) [inline src/material/datepicker/aria-accessible-name.ts:103]: This is also going to break during SSR.

File: src/material/datepicker/aria-accessible-name.ts [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+  }
+
+  // acc-name-1.2 Step 2.D. attribute or element that defines a text alternative
+  //
+  // NOTE: this differs from accname-1.2 specification.
+  // Only implements acc-name-1.2 for `<label>` and `<input/>` element. Does not implement all
+  // other elements that have an attribute or element that defines a text alternative.
+  if (currentNode instanceof HTMLInputElement) {
+    // use label with a `for` attribute referencing the current node
+    const labels = document.querySelectorAll(`[for="${currentNode.id}"]`);
```
Comment (crisbeto) [inline src/material/datepicker/aria-accessible-name.ts:118]: I don't think that you need to query the entire DOM to get the labels. Inputs have a `labels` property that points to the connected labels: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/labels

File: src/material/datepicker/aria-accessible-name.ts [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+      return ariaLabel;
+    }
+  }
+
+  // acc-name-1.2 Step 2.D. attribute or element that defines a text alternative
+  //
+  // NOTE: this differs from accname-1.2 specification.
+  // Only implements acc-name-1.2 for `<label>` and `<input/>` element. Does not implement all
+  // other elements that have an attribute or element that defines a text alternative.
+  if (currentNode instanceof HTMLInputElement) {
```
Comment (crisbeto) [inline src/material/datepicker/aria-accessible-name.ts:116]: This will break during SSR too.

File: src/material/datepicker/calendar-body.html [hunk 5]
```diff
@@ -75,3 +76,10 @@
     </button>
   </td>
 </tr>
+
+<label [id]="_startDateLabelId" class="cdk-visually-hidden" aria-hidden="true">
```
Comment (crisbeto) [inline src/material/datepicker/calendar-body.html:80]: If this is both `cdk-visually-hidden` and `aria-hidden="true"`, we might as well just set `display: none` on it.

File: src/material/datepicker/calendar-body.ts [hunk 6]
```diff
@@ -356,6 +364,26 @@ export class MatCalendarBody implements OnChanges, OnDestroy, AfterViewChecked {
     return isInRange(value, this.previewStart, this.previewEnd, this.isRange);
   }
 
+  /** Gets ids of aria descriptions for the start and end of a date range. */
+  _getDescribedby(value: number): string | null {
+    if (!this.isRange) {
+      return null;
+    }
+    const ids: string[] = [];
```
Comment (crisbeto) [inline src/material/datepicker/calendar-body.ts:372]: This is going to be called on each change detection which will generate a bunch of unnecessary arrays. Maybe we can only compute this when the IDs are assigned?

File: src/material/datepicker/calendar.ts [hunk 7]
```diff
@@ -282,6 +282,12 @@ export class MatCalendar<D> implements AfterContentInit, AfterViewChecked, OnDes
   /** End of the comparison range. */
   @Input() comparisonEnd: D | null;
 
+  /** ARIA Accessible name of the `<input matStartDate/>` */
+  @Input() startDateAccessibleName: string | null;
```
Comment (crisbeto) [inline src/material/datepicker/calendar.ts:286]: Do we need something for the comparison range as well?

File: src/material/datepicker/aria-accessible-name.ts [hunk 8]
```diff
@@ -0,0 +1,153 @@
...
+ * Limitations:
+ *  - Only covers the needs of `matStartDate` and `matEndDate`. Does not support other use cases.
+ *  - See NOTES's in implementation for specific details on what parts of the accname-1.2
+ *  specification are not implemented.
+ *
+ *  @param element {HTMLInputElement} native &lt;input/> element of `matStartDate` or `matEndDate` component. Corresponds to the 'Root Element' from accname-1.2
+ *
+ *  @return expected ARIA accessible name of argument &lt;input/>
+ */
+export function _computeAriaAccessibleName(element: HTMLInputElement): string {
```
Comment (crisbeto) [inline src/material/datepicker/aria-accessible-name.ts:57]: Couldn't this be an `HTMLTextareaElement` as well?

File: src/material/datepicker/aria-accessible-name.ts (hunk 3 above)
Comment (zarend) [reply src/material/datepicker/aria-accessible-name.ts:118]: Thanks, didn't know about that 🤯 . Since using `<input matStartDate type="hidden"/>` is not a supported use case, it should be safe to use `labels` property as far as I can tell.

File: src/material/datepicker/calendar.ts (hunk 7 above)
Comment (zarend) [reply src/material/datepicker/calendar.ts:286]: We would probably need to when we do comparison range. Wasn't planning on addressing comparison range in this PR. Do you think that's something simple that I could add to this PR?

File: src/material/datepicker/aria-accessible-name.ts (hunk 8 above)
Comment (zarend) [reply src/material/datepicker/aria-accessible-name.ts:57]: _computeAriaAccessibleName is only inteded to be used for `MatStartDate` and `MatEndDate` components. Since their selector is `input[matStartDate`, text area should not be needed as far as I can tell.

File: src/material/datepicker/aria-accessible-name.ts (hunk 2 above)
Comment (zarend) [reply src/material/datepicker/aria-accessible-name.ts:103]: How do you feel about doing this so that we don't have to type cast in the code? Checking `nodeType` could also be inlined. I don't feel strongly in this case, since it doesn't need to be done many times ¯\_(ツ)_/¯ .

```
/**
 * Determine if argument node is an Element based on `nodeType` property. This function is safe to
 * use with server-side rendering.
 */
function ssrSafeIsElement(node: Node): node is Element {
  return node.nodeType === Node.ELEMENT_NODE;
}
```

File: src/material/datepicker/calendar-body.ts (hunk 6 above)
Comment (zarend) [reply src/material/datepicker/calendar-body.ts]: good catch, I refactored this method to not construct any arrays.

File: src/material/datepicker/aria-accessible-name.ts (hunk 8 above)
Comment (crisbeto) [reply src/material/datepicker/aria-accessible-name.ts:58]: My thinking was in case we decided to move it out in the future. Anyway, it's not a blocker.

**Review by crisbeto — APPROVED** [review]
LGTM

**Comment by zarend** [comment]
@crisbeto my thought process here is that I recommend using `_computeAriaAccessibleName` only as a last resort. In most situations I would expect there to be an easier solution than predicting what the ARIA api will do 😂 . I typed the argument as `HTMLInputElement` because the unit tests only cover the Datepicker's use case.

tomorrow, I can take a look at `HTMLTextareaElement` and see what it would take to add that. IIRC text area would be almost identical to input.

**Comment by crisbeto** [comment]
I was mostly referring to setting the accepted types to `HTMLInputElement|HTMLTextareaElement`, I don't think that we need to unit test `textarea` specifically.

**Comment by zarend** [comment]
Okay, we can do that, we would also need to change [this line that detects input element](https://github.com/angular/components/pull/25457/files#diff-6cb6d86ead3962a39e60b0726fbf13126126d77c97aca1ccde54b1dd8fd5182bR133) to: `  if (ssrSafeIsHTMLInputElement(currentNode) || ssrSafeIsTextareaElement(currentNode)) {`. That way we properly handle the placeholder attribute, title attribute, and for/id with `<textarea/>`.

File: src/material/datepicker/aria-accessible-name.ts (hunk 2 above)
Comment (crisbeto) [reply src/material/datepicker/aria-accessible-name.ts]: I think that's fine, we've done something similar in other places.

**Review by mmalerba — APPROVED** [review]
LGTM
