### PR TITLE
fix(cdk/text-field): autosize text areas using the placeholder

### LINKED ISSUE #22042: bug(cdkTextareaAutosize): cdkTextareaAutosize does not resize when the placeholder or label is long
#### Reproduction

https://stackblitz.com/edit/angular-2ebx1r?file=src/app/./text-field-autosize-textarea-example.html
 
#### Expected Behavior

What behavior were you expecting to see?

When a textarea has a long placeholder or label and the textarea using cdkTextareaAutosize, the text area should be auto-sized to support the length of the placeholder

#### Actual Behavior

What behavior did you actually see?

The text area does not auto-size to the placeholder or label used, and instead stays at the min number of rows and shows an internal (scrollbar?) the scroll through the placeholder

#### Environment

- Angular: latest
- CDK/Material: latest
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): all

### PR DESCRIPTION
**Pull request by jermowery**
Fixes a bug with CdkTextareaAutosize where the textarea would not be autosized when using long placeholders

Fixes #22042

### CODE REVIEW

File: src/cdk/text-field/autosize.ts [hunk 1]
```diff
@@ -222,21 +224,27 @@ export class CdkTextareaAutosize implements AfterViewInit, DoCheck, OnDestroy {
...
 
     // Only resize if the value or minRows have changed since these calculations can be expensive.
-    if (!force && this._minRows === this._previousMinRows && value === this._previousValue) {
+    if (!force && this._minRows === this._previousMinRows && value === this._previousValue &&
+        placeholderText === this._previousPlaceholderText) {
       return;
     }
 
-    const placeholderText = textarea.placeholder;
+    const placeholderLongerThanValue = placeholderText.length > value.length;
```
Comment (jelbourn) [inline src/cdk/text-field/autosize.ts:235]: Comparing the length will probably work most of the time, but could cause a problem in cases when the characters don't end up being close enough to equal in width (e.g. "I" could be 30% the width of a "W"). 

Since placeholders rarely change, we could alternatively cache the height of the textarea with the placeholder text (invalidating if it changes), and use that as an effective lower-bound for this function.

Comment (jermowery) [reply src/cdk/text-field/autosize.ts:235]: That seems reasonable to me. Just to make sure, you are requesting that I make this change right?

Comment (jelbourn) [reply src/cdk/text-field/autosize.ts:235]: If you think it's reasonable then yeah

Comment (jermowery) [reply src/cdk/text-field/autosize.ts]: sadly had to go back to the original approach because I couldn't get the caching approach to work with view-engine

Comment (jermowery) [reply src/cdk/text-field/autosize.ts]: went back to caching as per offline comments

**Comment by jermowery** [comment]
Had to also adjust the input tests

**Review by jelbourn — APPROVED** [review]
LGTM

**Comment by jermowery** [comment]
Sadly this break g3 because the value is changed on the textarea. I think I will have to abandon this completely as I will be unavailable to look at this for a week and we have other high priority things to deal with right now
