### PR TITLE
fix(autocomplete): not emitting opened event if options come in after open

### LINKED ISSUE #15573: Autocomplete doesn't emit opened first time when options are generated asynchronous
#### What is the expected behavior?
Autocomplete should emit opened on first and every opening of the panel when options are generated asynchronous.

#### What is the current behavior?
Autocomplete doesn't emit opened when opened first time.

#### What are the steps to reproduce?
https://stackblitz.com/edit/autocomplete-asyc-bug
Click in the field and wait about 3 seconds. The panel opens but event is not emitted. It will be emitted on the subsequent openings.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2 Material 7.35 (Also occurs on Angular 6) 

#### Is there anything else we should know?
I think it is because panel doesn't have any options at the beginning so it doesn't emit event.

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes `mat-autocomplete` not emitting its `opened` event if it is opened without any options and then the options come in at a later point.

Fixes #15573.

### CODE REVIEW

File: src/lib/autocomplete/autocomplete-trigger.ts [hunk 1]
```diff
@@ -488,24 +488,28 @@ export class MatAutocompleteTrigger implements ControlValueAccessor, OnDestroy {
...
+            // that were created, and flatten it so our stream only emits closing events...
+            switchMap(() => {
+              const wasOpen = this.panelOpen;
+              this._resetActiveItem();
+              this.autocomplete._setVisibility();
+
+              if (this.panelOpen) {
+                this._overlayRef!.updatePosition();
+
+                if (wasOpen !== this.panelOpen) {
```
Comment (jelbourn) [inline src/lib/autocomplete/autocomplete-trigger.ts]: Add a comment here that captures the context for this PR?

**Comment by crisbeto** [comment]
Addressed the feedback @jelbourn.

**Comment by jelbourn** [comment]
@crisbeto this passes presubmit, just needs a rebase

**Comment by crisbeto** [comment]
Rebased.
