### PR TITLE
fix(material/autocomplete): outside click in Angular zone.

### LINKED ISSUE #24811: bug(MatAutocompleteTrigger): callback applied to closed EventEmitter runs outside of the Angular Zone on outside click
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

The callback applied to the `closed` EventEmitter seems to run outside of the Angular Zone when `closed` is emitted via "outside click"

### Reproduction

https://stackblitz.com/edit/components-issue-83t6vu?file=src/app/autocomplete.component.ts

Steps to reproduce:
1. click inside input - should open panel and disable button
2. click outside panel to close it - expect button to be enabled, but remains disabled

### Expected Behavior

clicking outside the panel to close the panel should have disabled the button without using `ngZone.run()`

### Actual Behavior

the button remains disabled

### Environment

- Angular: 13.3.0
- CDK/Material: 13.3.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

### PR DESCRIPTION
**Pull request by volvachev**
Fixes a bug in Angular Material `autocomplete` when outside click doesn't trigger `changeDetection`.

Fixes #24811

### CODE REVIEW

File: src/material/autocomplete/autocomplete-trigger.ts [hunk 1]
```diff
@@ -268,7 +268,16 @@ export abstract class _MatAutocompleteTriggerBase
 
     if (this.panelOpen) {
       // Only emit if the panel was visible.
-      this.autocomplete.closed.emit();
+      // The `NgZone.onStable` always emits outside of the Angular zone,
+      // so all the subscriptions from `_subscribeToClosingActions()` are also outside of the Angular zone.
+      // We should manually run in Angular zone to update UI after panel closing.
+      if (NgZone.isInAngularZone()) {
```
Comment (crisbeto) [inline src/material/autocomplete/autocomplete-trigger.ts:274]: This check isn't necessary since nothing special will happen if you do `NgZone.run` while it's already in the zone.

**Review by crisbeto — COMMENTED** [review]
Can you add a unit test for this?

**Comment by volvachev** [comment]
> Can you add a unit test for this?

I've added test for it.

File: src/material/autocomplete/autocomplete.spec.ts [hunk 2]
```diff
@@ -3371,6 +3371,32 @@ describe('MatAutocomplete', () => {
...
+    flush();
+
+    const subscription = fixture.componentInstance.trigger.autocomplete.closed.subscribe(() =>
+      inZoneSpy(NgZone.isInAngularZone()),
+    );
+    zone.onStable.emit(null);
+
+    dispatchFakeEvent(document, 'click');
+
+    expect(inZoneSpy).toHaveBeenCalled();
```
Comment (crisbeto) [inline src/material/autocomplete/autocomplete.spec.ts:3395]: This is covered by the `toHaveBeenCalledWith` call already.

File: src/material/autocomplete/autocomplete.spec.ts [hunk 3]
```diff
@@ -3371,6 +3371,32 @@ describe('MatAutocomplete', () => {
 
     expect(fixture.componentInstance.trigger.panelOpen).toBe(true);
   });
+
+  it('should emit from `autocomplete.closed` after click outside inside the NgZone', fakeAsync(() => {
+    const inZoneSpy = jasmine.createSpy('in zone spy');
+
+    const fixture = createComponent(SimpleAutocomplete, [
+      {provide: NgZone, useFactory: () => new NgZone({enableLongStackTrace: false})},
```
Comment (crisbeto) [inline src/material/autocomplete/autocomplete.spec.ts:3379]: Why is this necessary?

File: src/material/autocomplete/autocomplete.spec.ts [hunk 4]
```diff
@@ -3371,6 +3371,32 @@ describe('MatAutocomplete', () => {
...
+    ]);
+    const zone = TestBed.inject(NgZone);
+    fixture.detectChanges();
```
Comment (crisbeto) [inline src/material/autocomplete/autocomplete.spec.ts:3382]: This shouldn't be necessary. The zone is already stubbed out for all tests inside `createComponent`. Try searching for `simulateZoneExit` in the same file.

File: src/material/autocomplete/autocomplete.spec.ts (hunk 3 above)
Comment (volvachev) [reply src/material/autocomplete/autocomplete.spec.ts:3379]: > Why is this necessary?

MockZone always returns false for isInAngularZone(), it doesn't depend on running in zone.run or outside

And when common NgZone is used then it displays in correct way.

Otherwise some another test should be implemented, I think this is excessively

I've not found any solution how to pass real NgZone into the function

File: src/material/autocomplete/autocomplete.spec.ts (hunk 4 above)
Comment (volvachev) [reply src/material/autocomplete/autocomplete.spec.ts:3382]: > This shouldn't be necessary. The zone is already stubbed out for all tests inside `createComponent`. Try searching for `simulateZoneExit` in the same file.

 I have got real `NgZone` from DI, instead `MockZone` which get from function `CreateComponent`

File: src/material/autocomplete/autocomplete.spec.ts (hunk 3 above)
Comment (crisbeto) [reply src/material/autocomplete/autocomplete.spec.ts:3379]: ok, I see. I think that you should be able to at least reduce the `providers` array to `[NgZone]` or `[{provide: NgZone, useClass: NgZone}]`.

Comment (volvachev) [reply src/material/autocomplete/autocomplete.spec.ts:3379]: > ok, I see. I think that you should be able to at least reduce the `providers` array to `[NgZone]` or `[{provide: NgZone, useClass: NgZone}]`.

No it is impossible because of [NgZone constructor expects zoneOptions object](https://github.com/angular/angular/blob/3e46a426c47bf6589952c7f2a17d914dd6f38dfe/packages/core/src/application_ref.ts#L201)

Comment (crisbeto) [reply src/material/autocomplete/autocomplete.spec.ts:3379]: Makes sense.

**Review by crisbeto — APPROVED** [review]
LGTM
