### PR TITLE
fix(material/slider): some screen readers announcing long decimal values

### LINKED ISSUE #20719: bug(Slider): Jaws and NVDA incorrectly announcing decimal numbers
#### Reproduction

https://stackblitz.com/edit/components-issue-nr5zgy?file=src%2Fapp%2Fexample-component.html
(stackblitz have weird behaviour, you have to add tabindex="0" for working example)

Steps to reproduce:
1.  Enable Jaws or NVDA
2.  Focus slider
3.  Move slider
 
 
#### Expected Behavior

Screen reader announce 0.2

#### Actual Behavior

Screen reader announcing e.g. 0.20000068

#### Environment

- Angular:  V. 10.1.3
- CDK/Material: V. 10.2.3
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

### PR DESCRIPTION
**Pull request by crisbeto**
Note: this is a resubmit of #20721 which renames the `aria-valuetext` input to `valueText` based on the note in #20849.

It looks like some screen readers announce the value of a slider by calculating the percentage themselves using the `aria-valuemin`, `aria-valuemax` and `aria-valuenow`. The problem is that they don't round down the decimals so for a slider between 0 and 1
with a step of 0.1, they end up reading out values like 0.20000068. These changes work around the issue by setting `aria-valuetext` to the same value that we shown in the thumb which we truncate ourselves.

Fixes #20719.

### CODE REVIEW

**Comment by crisbeto** [comment]
Caretaker note: these changes have been reverted twice before, because there's an app whose `aria-valuetext` we'd override. The app would have to be switched over to the new `valueText` input on `mat-slider`.

File: src/material/slider/slider.ts [hunk 1]
```diff
@@ -134,6 +134,13 @@ const _MatSliderMixinBase:
     '[attr.aria-valuemax]': 'max',
     '[attr.aria-valuemin]': 'min',
     '[attr.aria-valuenow]': 'value',
+
+    // NVDA and Jaws appear to announce the `aria-valuenow` by calculating its percentage based
+    // on its value between `aria-valuemin` and `aria-valuemax`. Due to how decimals are handled,
+    // it can cause the slider to read out a very long value like 0.20000068 if the current value
+    // is 0.2 with a min of 0 and max of 1. We work around the issue by setting `aria-valuetext`
+    // to the same value that we set on the slider's thumb which will be truncated.
+    '[attr.aria-valuetext]': 'valueText || displayValue',
```
Comment (jelbourn) [inline src/material/slider/slider.ts:143]:
```suggestion
    '[attr.aria-valuetext]': 'valueText != null ? valueText : displayValue',
```
The app that was setting this intentionally sets an empty string to avoid reading anything for their initial state

**Comment by crisbeto** [comment]
Reworked based on the feedback and added another test case.

**Review by mmalerba — APPROVED** [review]
LGTM

**Review by jelbourn — APPROVED** [review]
LGTM
