### PR TITLE
fix(ng-update): properly handle update from different working directory

### LINKED ISSUE #19779: bug(cdk): Update Failed : Cannot read property 'length' of null
#### Reproduction

I can't share my code because it's a big project, hope the stack will help you
`ng update @angular/material --force`
 
#### Expected Behavior

Working

#### Actual Behavior

```
 ** Executing migrations for package '@angular/cdk' **
Cannot read property 'length' of null
```
Stack trace in log file : 

```
[error] TypeError: Cannot read property 'length' of null
    at Object.computeLineStartsMap (path\node_modules\@angular\cdk\schematics\update-tool\utils\line-mappings.js:39:23)
    at ComponentResourceCollector.resolveExternalStylesheet (path\node_modules\@angular\cdk\schematics\update-tool\component-resource-collector.js:131:47)
    at path\node_modules\@angular\cdk\schematics\update-tool\index.js:97:50
    at Array.forEach (<anonymous>)
    at UpdateProject.migrate (path\node_modules\@angular\cdk\schematics\update-tool\index.js:95:35)
    at runMigrations (path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:128:42)
    at Object.<anonymous> (path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:83:17)
    at Generator.next (<anonymous>)
    at path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:11:12)
    at path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:57:31
    at MergeMapSubscriber.project (path\node_modules\@angular-devkit\schematics\src\rules\call.js:75:24)
    at MergeMapSubscriber._tryNext (path\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (path\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (path\node_modules\rxjs\internal\Subscriber.js:66:18)
```

#### Environment

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.0
Node: 12.4.0
OS: win32 x64

Angular: 10.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/flex-layout              10.0.0-beta.32
@ngtools/webpack                  10.0.0
@schematics/angular               9.1.9
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
```

- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

### PR DESCRIPTION
**Pull request by devversion**
In some situations, developers will run `ng update` from a sub directory
of the project. This currently results in a noop migration as file
system paths were computed incorrectly. This is because ng-update
always assumed that the CWD is the workspace root in the real file
system. This is not the case and therefore threw off path resolution.

We fix this by fully relying on the virtual file system now. Previously
we mixed virtual and real file system as TypeScript relied on the
real file system for parsing configuration, matching and reading files.

This commit adds a new compiler host for config parsing and program
creation that works fully with a virtual file system. This is something
we had planned a long time ago as schematics should never deal with
the real file system. We can re-use this logic in other repositories
too (such as Angular framework, potentially the CLI, and universal
schematics). Ideally we will share this as part of better tooling for
migrations.

Fixes #19779. Resolves COMP-387.

### CODE REVIEW

File: src/cdk/schematics/ng-update/devkit-file-system.ts [hunk 1]
```diff
@@ -73,4 +62,23 @@ export class DevkitFileSystem extends FileSystem<Path> {
     const buffer = this._tree.read(filePath);
     return buffer !== null ? buffer.toString() : null;
   }
+
+  existsDirectory(dirPath: Path) {
```
Comment (crisbeto) [inline src/cdk/schematics/ng-update/devkit-file-system.ts:66]: Couldn't we bake this into `exists` which would handle both directories and files? I think that's what Node does.

File: src/cdk/schematics/ng-update/devkit-file-system.ts [hunk 2]
```diff
@@ -73,4 +62,23 @@ export class DevkitFileSystem extends FileSystem<Path> {
...
+      if (e instanceof PathIsDirectoryException) {
+        return true;
+      }
+    }
+    return false;
+  }
+
+  readDirectory(dirPath: Path): DirectoryEntry {
+    const {subdirs: directories, subfiles: files} = this._tree.getDir(dirPath);
+    return {directories: directories, files};
```
Comment (crisbeto) [inline src/cdk/schematics/ng-update/devkit-file-system.ts:82]: Can be just `{directories, files}`.

File: src/cdk/schematics/ng-update/find-stylesheets.ts [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+
+/** Regular expression that matches stylesheet paths */
+const STYLESHEET_REGEX = /.*\.(css|scss)/;
+
+/** Finds stylesheets in the given directory from within the specified tree. */
+export function findStylesheetFiles(tree: Tree, baseDir: string): string[] {
+  const result: string[] = [];
+  const visitDir = dirPath => {
+    // Do not visit directories or files inside node modules or `dist/` folders.
+    if (/^\/?(node_modules|dist)\//.test(dirPath)) {
```
Comment (crisbeto) [inline src/cdk/schematics/ng-update/find-stylesheets.ts:20]: 1. I'm not sure whether this is dealing with absolute or relative paths, but it won't match something like `/foo/bar/node_modules/` or `./node_modules`.
2. This won't match if Windows returns a path like `node_modules\\foo\\bar`. I don't know if that's normalized already.

File: src/cdk/schematics/ng-update/find-stylesheets.ts [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+      return;
+    }
+    const stat = tree.getDir(dirPath);
+    stat.subdirs.forEach(fragment => visitDir(join(dirPath, fragment)));
+    result.push(...stat.subfiles.filter(f => STYLESHEET_REGEX.test(f)));
```
Comment (crisbeto) [inline src/cdk/schematics/ng-update/find-stylesheets.ts:25]: nit: wouldn't be better if we pushed to the results first before visiting the sub-directories? That way the traversal should be in descending order.

File: src/cdk/schematics/ng-update/find-stylesheets.ts [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+
+/** Finds stylesheets in the given directory from within the specified tree. */
+export function findStylesheetFiles(tree: Tree, baseDir: string): string[] {
+  const result: string[] = [];
+  const visitDir = dirPath => {
+    // Do not visit directories or files inside node modules or `dist/` folders.
+    if (/^\/?(node_modules|dist)\//.test(dirPath)) {
+      return;
+    }
+    const stat = tree.getDir(dirPath);
```
Comment (crisbeto) [inline src/cdk/schematics/ng-update/find-stylesheets.ts:23]: nit: you could destructure here to `const {subdirs, subfiles}`.

File: src/cdk/schematics/ng-update/devkit-file-system.ts [hunk 6]
```diff
@@ -73,4 +62,23 @@ export class DevkitFileSystem extends FileSystem<Path> {
...
+    } catch (e) {
+      if (e instanceof PathIsDirectoryException) {
+        return true;
+      }
+    }
+    return false;
+  }
+
+  readDirectory(dirPath: Path): DirectoryEntry {
+    const {subdirs: directories, subfiles: files} = this._tree.getDir(dirPath);
```
Comment (crisbeto) [inline src/cdk/schematics/ng-update/devkit-file-system.ts:81]: Not something we control, but it's a little weird for this to be called "sub files" since all files are nested in each other. Maybe we can change it if we're changing other things.

File: src/cdk/schematics/ng-update/devkit-file-system.ts (hunk 1 above)
Comment (devversion) [reply src/cdk/schematics/ng-update/devkit-file-system.ts:66]: I considered it, but wanted to avoid it as that matches with TypeScript's API. I'll play with it. Generally I'd agree that this would be nicer.

File: src/cdk/schematics/ng-update/devkit-file-system.ts (hunk 2 above)
Comment (devversion) [reply src/cdk/schematics/ng-update/devkit-file-system.ts:82]: Ops, good catch! that was by mistake

File: src/cdk/schematics/ng-update/devkit-file-system.ts (hunk 6 above)
Comment (devversion) [reply src/cdk/schematics/ng-update/devkit-file-system.ts:81]: Yeah, it's definitely a bit ambiguous. You mean that we create a proposal upstream for them to change it?

File: src/cdk/schematics/ng-update/find-stylesheets.ts (hunk 3 above)
Comment (devversion) [reply src/cdk/schematics/ng-update/find-stylesheets.ts:20]: This is actually dealing with workspace paths where separators are always POSIX forward. It's also matching the previous logic where we only skip `node_modules` at the top-level of a project. Maybe we should skip nested node modules too if they exist for whatever reason.

File: src/cdk/schematics/ng-update/find-stylesheets.ts (hunk 4 above)
Comment (devversion) [reply src/cdk/schematics/ng-update/find-stylesheets.ts]: That shouldn't matter. I'll change it anyway as I agree that it makes more sense in descending order.

**Comment by devversion** [comment]
@crisbeto I've addressed the feedback. Thanks!
