### PR TITLE
fix(datepicker): year not formatted in multi-year view button

### LINKED ISSUE #17187: MatCalendarHeader at version8 periodButtonText doesn't display TH local format
#### Expected Behavior

get periodButtonText(): string {
    if (this.calendar.currentView == 'month') {
      return this._dateAdapter
          .format(this.calendar.activeDate, this._dateFormats.display.monthYearLabel)
              .toLocaleUpperCase();
    }
    if (this.calendar.currentView == 'year') {
      return this._dateAdapter.getYearName(this.calendar.activeDate);
    }
    const activeYear = this._dateAdapter.getYear(this.calendar.activeDate);
    const firstYearInView = this._dateAdapter.getYearName(
        this._dateAdapter.createDate(activeYear - activeYear % 24, 0, 1));
    const lastYearInView = this._dateAdapter.getYearName(
        this._dateAdapter.createDate(activeYear + yearsPerPage - 1 - activeYear % 24, 0, 1));
    return `${firstYearInView} \u2013 ${lastYearInView}`;
  }

#### Actual Behavior

get periodButtonText(): string {
    if (this.calendar.currentView == 'month') {
      return this._dateAdapter
          .format(this.calendar.activeDate, this._dateFormats.display.monthYearLabel)
              .toLocaleUpperCase();
    }
    if (this.calendar.currentView == 'year') {
      return this._dateAdapter.getYearName(this.calendar.activeDate);
    }

    const activeYear = this._dateAdapter.getYear(this.calendar.activeDate);
    const minYearOfPage = activeYear - getActiveOffset(
      this._dateAdapter, this.calendar.activeDate, this.calendar.minDate, this.calendar.maxDate);
    const maxYearOfPage = minYearOfPage + yearsPerPage - 1;
    return `${minYearOfPage} \u2013 ${maxYearOfPage}`;
  }

What behavior did you actually see?
- Look at firstYearInView and lastYearInView on version 6 has getYearName() but version 8 doesn't
that make some locale time display is unusual.

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes the years that are rendered in the calendar's perioud button not being formatted through the date adapter in the multi-view. This can result in an incorrect value being displayed in some locales.

Fixes #17187.

### CODE REVIEW

File: src/material/datepicker/calendar.ts [hunk 1]
```diff
@@ -82,7 +82,11 @@ export class MatCalendarHeader<D> {
     const minYearOfPage = activeYear - getActiveOffset(
       this._dateAdapter, this.calendar.activeDate, this.calendar.minDate, this.calendar.maxDate);
     const maxYearOfPage = minYearOfPage + yearsPerPage - 1;
-    return `${minYearOfPage} \u2013 ${maxYearOfPage}`;
+    const minYearName =
+      this._dateAdapter.getYearName(this._dateAdapter.createDate(minYearOfPage, 0, 1));
+    const maxYearName =
+      this._dateAdapter.getYearName(this._dateAdapter.createDate(maxYearOfPage, 0, 1));
+    return `${minYearName} \u2013 ${maxYearName}`;
```
Comment (mmalerba) [inline src/material/datepicker/calendar.ts]: Technically, proper i18n should allow for formatting this in whatever way makes sense for the locale ("min - max", "max - min", "[min - max]", "min (╯°□°)╯︵ ┻━┻ max", etc). Have we run into this in any other components? and if so do we have an established pattern for dealing with it?

If not, I would think a method on the i18n injectable would be sufficient. `formatRange(start: string, end: string): string`

Comment (crisbeto) [reply src/material/datepicker/calendar.ts]: We have something similar in the paginator and [we deal in a very similar way with it](https://github.com/angular/components/blob/master/src/material/paginator/paginator-intl.ts#L53). Doesn't `formatRange` also make some assumptions though? E.g. we aren't specifying what kind of range is being formatted. I can imagine a range of dates being formatted differently compared to a range of numbers.

Comment (mmalerba) [reply src/material/datepicker/calendar.ts]: yeah this would go specifically on `MatDatepickerIntl` and we can give it a more specific name that indicates its exact purpose. That was just my placeholder name

Comment (crisbeto) [reply src/material/datepicker/calendar.ts]: I took a quick look and I'm not sure that it'll work in `MatDatepickerIntl` because we need access to the specific date adapter, whereas `MatDatepickerIntl` is `providedIn: 'root'`.

Comment (mmalerba) [reply src/material/datepicker/calendar.ts]: I was thinking the `MatDatepickerIntl` function could take the dates in as strings, already formatted. I guess its still not ideal, maybe there's some language that writes "2019" different in the context of "2018 - 2019", but its at least as close as we can get to the ideal

**Comment by crisbeto** [comment]
Reworked based on the discussion @mmalerba.
