### PR TITLE
fix(cdk/drag-drop): incorrect type DragConstrainPosition

### LINKED ISSUE #30509: bug(cdk/drag-drop): Type DragConstrainPosition does not match @Input('cdkDragConstrainPosition') in CdkDrag
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

Type mismatch in `@Input('cdkDragConstrainPosition')` of `CdkDrag` `constrainPosition: (userPointerPosition: Point, dragRef: DragRef, dimensions: DOMRect, pickupPositionInElement: Point) => Point` and type `DragConstrainPosition` `(point: Point, dragRef: DragRef) => Point;`

### Reproduction

StackBlitz link:  https://stackblitz.com/edit/hn9tjrdg?file=src%2Fexample%2Fcdk-drag-drop-overview-example.ts

### Expected Behavior

**Below code compiles successfully** 

```
@Component({
  selector: 'cdk-drag-drop-overview-example',
  templateUrl: 'cdk-drag-drop-overview-example.html',
  styleUrl: 'cdk-drag-drop-overview-example.css',
  imports: [CdkDrag],
  providers: [
    {
      provide: CDK_DRAG_CONFIG,
      useFactory: () => {
        const config: DragDropConfig = {
          constrainPosition: (
            userPointerPosition: Point, 
            dragRef: DragRef, 
            dimensions: DOMRect, 
            pickupPositionInElement: Point) => {
            return userPointerPosition;
          },
        }

        return config;
      },
    },
  ],
})
export class CdkDragDropOverviewExample {}
```

### Actual Behavior

```
Type '(userPointerPosition: Point, dragRef: DragRef, dimensions: DOMRect, pickupPositionInElement: Point) => Point' is not assignable to type 'DragConstrainPosition'.
```

```
@Component({
  selector: 'cdk-drag-drop-overview-example',
  templateUrl: 'cdk-drag-drop-overview-example.html',
  styleUrl: 'cdk-drag-drop-overview-example.css',
  imports: [CdkDrag],
  providers: [
    {
      provide: CDK_DRAG_CONFIG,
      useFactory: () => {
        const config: DragDropConfig = {
          constrainPosition: (
            userPointerPosition: Point, 
            dragRef: DragRef, 
            dimensions: DOMRect, 
            pickupPositionInElement: Point) => {
            return userPointerPosition;
          },
        }

        return config;
      },
    },
  ],
})
export class CdkDragDropOverviewExample {}
```

Image

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

### PR DESCRIPTION
**Pull request by Veribelll**
Fixes type DragConstrainPosition, which of сorrect configuration of CdkDrag  is not possible when using in providers

Fixes #30509

### CODE REVIEW

File: src/cdk/drag-drop/directives/config.ts [hunk 1]
```diff
@@ -16,7 +16,12 @@ export type DragStartDelay = number | {touch: number; mouse: number};
 export type DragAxis = 'x' | 'y';
 
 /** Function that can be used to constrain the position of a dragged element. */
-export type DragConstrainPosition = (point: Point, dragRef: DragRef) => Point;
+export type DragConstrainPosition = (
```
Comment (crisbeto) [inline src/cdk/drag-drop/directives/config.ts:19]: We should reuse this type for the `cdkDragConstrainPosition` input as well.

Comment (Veribelll) [reply src/cdk/drag-drop/directives/config.ts:19]: Can be used in CdkRef as well?

Comment (crisbeto) [reply src/cdk/drag-drop/directives/config.ts:19]: Yeah I think we can use it wherever the constrain position function is being passed around.

Comment (Veribelll) [reply src/cdk/drag-drop/directives/config.ts:19]: Success

Comment (Veribelll) [reply src/cdk/drag-drop/directives/config.ts:19]: Done

Comment (Veribelll) [reply src/cdk/drag-drop/directives/config.ts:19]: I suggest move the type DragConstrainPosition in DragRef

```
   New circular dependencies which are not allowed:
     • src/cdk/drag-drop/directives/config.ts → src/cdk/drag-drop/drag-ref.ts
```

Comment (crisbeto) [reply src/cdk/drag-drop/directives/config.ts:19]: It's fine to either move the type or use a type-only import for it.

**Comment by crisbeto** [comment]
Looks like the API goldens still need to be updated.

**Review by crisbeto — APPROVED** [review]
