### PR TITLE
fix(material-experimental/mdc-radio): add accessible touch targets

### LINKED ISSUE #22991: MDC-based checkbox & radio click targets are too small
Our MDC-based checkbox and radio have click targets at 40px × 40px instead of 48 × 48px. Slide-toggle is already good here. 

Fix for checkbox is already open in https://github.com/angular/components/pull/22892

### PR DESCRIPTION
**Pull request by crisbeto**
Sets up accessible touch targets on the MDC-based radio button.

Also hides the touch targets on the two lowest densities. This is something I forgot to do in #22892.

Fixes #22991.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

File: src/material/radio/radio.ts [hunk 1]
```diff
@@ -585,24 +585,23 @@ export abstract class _MatRadioButtonBase extends _MatRadioButtonMixinBase imple
...
-   * Triggered when the radio button received a click or the input recognized any change.
-   * Clicking on a label element, will trigger a change event on the associated input.
-   */
-  _onInputChange(event: Event) {
+  /** Triggered when the radio button receives an interaction from the user. */
+   _onInputInteraction(event: Event) {
     // We always have to stop propagation on the change event.
     // Otherwise the change event, from the input element, will bubble up and
     // emit its event object to the `change` output.
     event.stopPropagation();
```
Comment (mmalerba) [inline src/material/radio/radio.ts:593]: Should we check the event type here so we don't stop propagation on the touch target click events? Or are we intentionally stopping those too?

**Comment by Asiabi** [comment]
Why Your Name karistia ofer me for in karistian im cannot soesorry im
isalam profit for busseniss can me can joine not for pray or gote!

File: src/material/radio/radio.ts (hunk 1 above)
Comment (crisbeto) [reply src/material/radio/radio.ts:593]: We were stopping all events on the radio so I assumed that we wanted to do the same for the touch target.
