### PR TITLE
fix(material/list): emit selectionChange event when selecting with ctrl + a

### LINKED ISSUE #15696: mat-selection-list: selectAll and deselectAll methods should trigger selectionChange event
`selectAll()` and `deselectAll()` methods on `MatSelectionList` should automatically trigger the `selectionChange` event.

#### What is the use-case or motivation for this proposal?
Select some documents from a list.

The `MatListOption`s have `[value]` populated with an object containing a number of properties of the document (name, file size, last edited date, expiry date, etc.).
You want to communicate a warning to the user that specifies the number of expired documents in their current selection.
It's easy enough to calculate the number of expired documents in the current selection when the `selectionChange` event is fired, but if the user decides to `selectAll`, this event is not triggered, so additional workarounds need to be made to cover this case.

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that we weren't emitting the `selectionChange` event when the user toggles all options with the ctrl + a shortcut. Also replaces `MatSelectionListChange.option` with `options` which is an array of all options that were changed by the current event.

Fixes #15696.

### CODE REVIEW

File: src/material/list/selection-list.ts [hunk 1]
```diff
@@ -72,8 +72,14 @@ export class MatSelectionListChange {
...
-    /** Reference to the option that has been changed. */
-    public option: MatListOption) {}
+    /**
+     * Reference to the option that has been changed.
+     * @deprecated Use `options` instead, because some events may change more than one option.
+     * @breaking-change 12.0.0
+     */
+    public option: MatListOption,
+    /** Reference to the options that have been changed. */
+    public options: MatListOption[]) {}
```
Comment (crisbeto) [inline src/material/list/selection-list.ts:82]: If we wanted to avoid this future breaking change, we could also emit one event per selected option like we do in `mat-select`. I decided not to do it, because the `mat-select` behavior feels broken.

**Review by jelbourn — APPROVED** [review]
LGTM
