### PR TITLE
fix(material/select): changed after checked error if option label changes

### LINKED ISSUE #14793: Dynamic change in label of mat-option gives ExpressionChangedAfterItHasBeenCheckedError
#### What is the expected behavior?
Error should not occur for this scenario.

#### What is the current behavior?
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null:  '. Current value: 'null: Change to localized version'.

#### What are the steps to reproduce?
**[StackBlitz](https://stackblitz.com/edit/angular-qdpdx7)**

Essentially I mimicked a similar thing that I am seeing with this stackblitz.
In the real world we have pipe that goes to a service to retrieve a localized version of a string.
What happens is we call this pipe and it goes to a service that file does a http get for a json and finds a string that is in the proper language.

Our form field select is like so:
```
<mat-form-field>
  <mat-select
    id="clinicPrefReportsDropdown"
    class="select-reports"
    [disabled]="!isButtonEnabled"
    (selectionChange)="SelectReportsChanged($event)"
    [value]="SelectedReport"
  >
      <mat-option value="ClinicPreferredReports">{{
        'ClinicPreferredReports' | localize: localizationSection
      }}</mat-option>
       <mat-option value="MyPreferredReports">{{
        'MyPreferredReports' | localize: localizationSection
      }}</mat-option>
       <mat-option value="CustomReports">{{
          'CustomReports' | localize: localizationSection
      }}</mat-option>
  </mat-select>
</mat-form-field>
```

What happens is those labels start off as null and when the service comes back with the proper string it changes it and this is where the expressed changed error comes into play. So my stackblitz simulates this with having option1 as a variable in OnInit I put a setTimeout for 2 seconds to change the string and there error comes up.

I guess I am wondering if this is truly a bug or if I need to do something different to not allow this to happen. I did get this to work by manually calling a change detection after the localize variable we have gets populated (and take the pipe out of the equation) but this is a workaround to the problem I feel like.

Any thoughts?

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes a "changed after checked" error that is thrown if the label of a selected option changes dynamically.

This is alternate approach to #14797 which was tricky to land, because it introduced an extra timeout.

Fixes #14793.

**Note:** I'm bumping this to a P2, because the related issue has been getting activity consistently for a long time now.

### CODE REVIEW

File: src/material/select/select.ts [hunk 1]
```diff
@@ -888,7 +888,10 @@ export abstract class _MatSelectBase<C> extends _MatSelectMixinBase implements A
     merge(...this.options.map(option => option._stateChanges))
       .pipe(takeUntil(changedOrDestroyed))
       .subscribe(() => {
-        this._changeDetectorRef.markForCheck();
+        // `_stateChanges` can fire as a result of a change in the label's DOM value which may
+        // be the result of an expression changing. We have to use `detectChanges` in order
+        // to avoid "changed after checked" errors (see #14793).
+        this._changeDetectorRef.detectChanges();
```
Comment (jelbourn) [inline src/material/select/select.ts:894]: What causes `stateChanges` to emit after dirty checking occurs? Are we using a mutation observer or something similar?

Comment (crisbeto) [reply src/material/select/select.ts:894]: We're using an `ngAfterViewChecked` hook that looks at the `textContent` of the option and emits when it changes.

Comment (jelbourn) [reply src/material/select/select.ts:894]: What if we used `cdkObserveContent` instead?

Comment (crisbeto) [reply src/material/select/select.ts:894]: That would work too, but I'm hesitant to apply it on each option since people tend to render lots of them in a single select.

Comment (mmalerba) [reply src/material/select/select.ts:894]: We could debate changing how we do it, but I think we should at least make this change for now. It maintains the same approach but fixes the error.

**Review by mmalerba — APPROVED** [review]
LGTM
