### PR TITLE
fix(cdk/overlay): overriding pointer-events style

### LINKED ISSUE #21656: bug(cdk/overlay): panel 'pointer-events' can not be overridden by panelClass
#### Expected Behavior

I'd like to be able to completely disable `pointer-events` on an overlay. The `.cdk-overlay-pane` is the only element that doesn't have `pointer-events: none`, and there is the `panelClass` feature to add more styling to that so I'd assume that's the way to do it.

#### Actual Behavior

[_togglePointerEvents](https://github.com/angular/components/blob/11.1.0/src/cdk/overlay/overlay-ref.ts#L369-L372) overrides `pointer-events` in the `style` attribute 100% of the time. The [`.cdk-overlay-pane`](https://github.com/angular/components/blob/11.1.0/src/cdk/overlay/_overlay.scss#L55) already sets `pointer-events: auto` so I think `_togglePointerEvents` can set `pointer-events: none` when necessary but otherwise drop the inline one and let the css do  whatever it wants?

#### Environment

- Angular: 11
- CDK/Material: 11

### PR DESCRIPTION
**Pull request by crisbeto**
We set `pointer-events: auto` on the overlay when it is attached and then `none` while it's detaching which ends up overriding any other styles the user might have. These changes reset to `''` instead.

Fixes #21656.

### CODE REVIEW

File: src/cdk/overlay/overlay-ref.ts [hunk 1]
```diff
@@ -368,7 +368,7 @@ export class OverlayRef implements PortalOutlet, OverlayReference {
 
   /** Toggles the pointer events for the overlay pane element. */
   private _togglePointerEvents(enablePointer: boolean) {
```
Comment (jbedard) [inline src/cdk/overlay/overlay-ref.ts:370]: I was debating renaming this at the same time to `_disablePointerEvents` since it never really does enable them anymore, it just disables or defaults...

Comment (crisbeto) [reply src/cdk/overlay/overlay-ref.ts:370]: IMO "toggle" still makes sense since the default is for them to be enabled.

Comment (jbedard) [reply src/cdk/overlay/overlay-ref.ts:370]: The default is in a css class though, this code really doesn't know and shouldn't care what that default is. Just my opinion though 🤷

**Review by jelbourn — APPROVED** [review]
LGTM
