### PR TITLE
fix(icon): handle unescaped characters in names

### LINKED ISSUE #15673: MatIconRegistry cannot find icon with special id
#### What is the expected behavior?
The `MatIconRegistry` returns the correct icon using `MatIconRegistry._extractSvgIconFromSet`.

#### What is the current behavior?
`MatIconRegistry._extractSvgIconFromSet` cannot find the icon due to an incorrect query selector.

#### What are the steps to reproduce?
Register a SVG icon set containing a SVG with id "icon-300 my icon"

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 5.1.0 and higher

#### Is there anything else we should know?
Currently the `MatIconRegistry` makes use of `iconSet.querySelector('#' + iconName)`:
https://github.com/angular/material2/blob/master/src/lib/icon/icon-registry.ts#L452

Instead it should be using `iconSet.getElementById(iconName)`
Then in my case it returns the correct SVG element.

### PR DESCRIPTION
**Pull request by crisbeto**
Handles the icon registry not being able to find icons whose ids contain unescaped characters (e.g. spaces).

Note that for this example in particular having a space in the id is invalid, however I did it since supporting it is trivial.

Fixes #15673.

### CODE REVIEW

File: src/lib/icon/icon-registry.ts [hunk 1]
```diff
@@ -449,7 +449,7 @@ export class MatIconRegistry implements OnDestroy {
    * returns it. Returns null if no matching element is found.
    */
   private _extractSvgIconFromSet(iconSet: SVGElement, iconName: string): SVGElement | null {
-    const iconSource = iconSet.querySelector('#' + iconName);
+    const iconSource = iconSet.querySelector(`[id="${iconName}"]`);
```
Comment (jelbourn) [inline src/lib/icon/icon-registry.ts]: Could you add a comment here like
```ts
// Use the `id="xxx"` syntax in order to escape special characters in the ID
// (versus using the #xxx syntax) 
```

Comment (crisbeto) [reply src/lib/icon/icon-registry.ts]: Done.

**Comment by jelbourn** [comment]
@crisbeto this passes presubmit, just needs a rebase

**Comment by crisbeto** [comment]
Rebased.

**Comment by crisbeto** [comment]
Rebased.
