### PR TITLE
fix(material/slider): incorrectly attributing touches for multiple touch events

### LINKED ISSUE #22614: bug(mat-slider): Multi touch doesn't work as expected
I'm trying to place several mat-sliders next to each other and be able to adjust them with multi-touch.

Problem is that, as soon as I start dragging a second fader, the fader gets the values of the other fader.

#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/components-issue-bvo7wp?file=src/app/example-component.html

Steps to reproduce:
1. open application (stackblitz, link see above) on a multi-touch enabled device, e.g. smartphone (I tried with android / chrome and on a multi touch screen on linux /chrome + firefox)
2. move first slider by touching it. don't lift the finger
3. move the second slider by touching it, also don't lift the finger
 
#### Expected Behavior
The value of the slider is adjusted independently

#### Actual Behavior
The second slider always has the same value as the first slider.

#### Environment

- Angular: 11.2.11
- CDK/Material: 11.2.11
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): ArchLinux, Android

#### Investigation
I already figured out why this bug appears and made an attempt to fix it - which seems to work - at least in my use case.

The problem is, that on the touch events, there is no distinction if the event is for this particular fader or not. 
With my PR, I'm adding a filter before those events and only choose the targetTouch that is relevant for that fader.

Here is the Pull request (first only against my own fork)
https://github.com/puschkin/components/pull/1

### PR DESCRIPTION
**Pull request by crisbeto**
`mat-slider` is set up so that it binds global `touchmove` and `touchend` events after dragging starts so that the user can drag while not keeping their finger right on top of the slider. The problem is that currently we only use the first touch from the list of touches which means that if the user is dragging more than one slider on a multi-touch device, they'll all have the same value.

These changes add some logic that attributes the events to the slider that started the dragging sequence.

**Note:** I haven't included unit tests for this, because we don't seem to have any tests for touch events on the slider (not sure if there are historical reasons for this). I've been testing the fix against a real touch device.

Fixes #22614.

### CODE REVIEW

**Comment by puschkin** [comment]
I couldn't verify this PR.

### Steps to reproduce:
> yarn run dev app
1. open dev app phone
2. go to sliders page
3. touch and move **left** color slider with **finger 1**, don't let go
  -> works
4. touch and move **right** color slider with **finger 2**, don't let go
 -> works for both sliders
5. release _finger 1_ from _left_ slider
6. touch and move **center** color slider with **finger 1**, don't let go
 -> Doesn't work, the center slider jumps immediately to 100%

File: src/material/slider/slider.ts [hunk 1]
```diff
@@ -636,21 +645,26 @@ export class MatSlider extends _MatSliderMixinBase
...
-      this._bindGlobalEvents(event);
-      this._focusHostElement();
-      this._updateValueFromPosition(pointerPosition);
-      this._valueOnSlideStart = oldValue;
-
-      // Emit a change and input event if the value changed.
-      if (oldValue != this.value) {
-        this._emitInputEvent();
+      this._touchId = isTouchEvent(event) ?
+        event.touches[event.touches.length - 1]?.identifier : undefined;
```
Comment (puschkin) [inline src/material/slider/slider.ts:649]: I think that this doesn't work as intended, if the touches are not all released in the opposite order as they are started

Comment (crisbeto) [reply src/material/slider/slider.ts:649]: This is only the `touchstart` though, after this the order of events doesn't matter.

Comment (puschkin) [reply src/material/slider/slider.ts:649]: yes, but here, we get the touch id. I'm not sure if your assumption, that the last touch in the touches list is "our" touch, is correct.

Comment (puschkin) [reply src/material/slider/slider.ts:649]: I added a console.log(this._touchId); in line 650 to verify the ID, and when I am repeating my steps from my comment [1], I get the output:
0
1
1
That means, the middle slider listens on the same ID as the right slider

[1] https://github.com/angular/components/pull/22615#issuecomment-830833842

Comment (crisbeto) [reply src/material/slider/slider.ts:649]: When I was working on it, I tried logging out the identifiers and it seemed like they were being added sequentially any time you tap with a different finger.

**Comment by crisbeto** [comment]
Regarding the issue mentioned above, I couldn't reproduce the issue with step 6. I tried following the instructions, but it worked as expected. Here's a recording from my device:


https://user-images.githubusercontent.com/4450522/116820932-c769f500-ab77-11eb-854e-002c3bbc6d7c.MP4

File: src/material/slider/slider.ts (hunk 1 above)
Comment (puschkin) [reply src/material/slider/slider.ts:649]: My observation is, that the identifiers are always in sorted order in the array.
If the touch 0 is finished, but touch 1 still goes on, and a new touch starts, it gets the ID 0 and this then on position 0 in the array
- touch start 
- [0]
- touch start
- [0, 1]
- touch end (0)
- [1]
- touch start
- [0, 1]

**Comment by puschkin** [comment]
> Regarding the issue mentioned above, I couldn't reproduce the issue with step 6. I tried following the instructions, but it worked as expected. 

Well, yes I agree, that looks as it should.
If you want I can try to make a video as well.

What device/browser are you using? Maybe the touch IDs are always increasing on your setup?

**Comment by crisbeto** [comment]
I've testing it on an iPhone 7 running iOS 14.4.

File: src/material/slider/slider.ts (hunk 1 above)
Comment (crisbeto) [reply src/material/slider/slider.ts:649]: Hmm, that's weird. We might be able to get away with checking the `target` here since the `touchstart` even is bound on the slider itself.

**Comment by puschkin** [comment]
@crisbeto Are you using Safari? Could you maybe try to reproduce my issue with chrome on the IPhone?

File: src/material/slider/slider.ts (hunk 1 above)
Comment (puschkin) [reply src/material/slider/slider.ts:649]: yes, good point!

**Comment by crisbeto** [comment]
Yes, I was testing on Safari, but I just tried Chrome and it worked the same. My understanding is that Chrome on iOS is basically a Safari web view due to some Apple policy that doesn't allow custom web browsers.

File: src/material/slider/slider.ts (hunk 1 above)
Comment (puschkin) [reply src/material/slider/slider.ts:649]: I logged the event.target and also the event.touches[].target at line 650 (_pointerDown)
Depending on where I start the touch, I get different Elements as target:
* <div class="mat-slider-ticks">
* <div class="mat-slider-thumb">
* <mat-slider>
Not sure if there are more, but it should always be mat-slider or a child of it.
But, the event.target is always the one of the latest touch down, so we **could** find the right target like that:
` this._touchId = isTouchEvent(event) ? getLatestTouchId(event) : undefined; ` 
with: 
`function getLatestTouchId(event: TouchEvent): number | undefined {
    for (let i = 0; i < event.touches.length; i++) {
        if (event.touches[i].target === event.target) {
            return event.touches[i].identifier;
        }
    }
    return undefined;
}


`

Comment (puschkin) [reply src/material/slider/slider.ts:649]: Perhaps some advice from someone who has a deep knowledge on multi touch events on different devices would be helpful.
Is there someone who could be tagged?

Comment (puschkin) [reply src/material/slider/slider.ts:649]: I just looked at some code which I implemented for my job. It's simulating a touch device (uinput) on linux.
There, I also have to define the identifier that is used for the touch.

My assumption (which I verify with my code from work) is, that the identifier in the touch event (js in the browser) is given from the touch device (driver) and not from the browser.

That would then explain why it works differently on android and the iPhone

Comment (crisbeto) [reply src/material/slider/slider.ts]: Thank you for looking into it, I'll go with a modified version of your proposal for now and we can iterate on it if it ends up breaking something. 

Also yeah, it's weird that there isn't a standard way for the identifiers to be generated. I noticed that the Chrome dev tools has a different way of doing it too.

File: src/material/slider/slider.ts [hunk 2]
```diff
@@ -661,31 +675,41 @@ export class MatSlider extends _MatSliderMixinBase
...
     if (this._isSliding) {
-      event.preventDefault();
-      this._removeGlobalEvents();
-      this._isSliding = false;
-
-      if (this._valueOnSlideStart != this.value && !this.disabled) {
-        this._emitChangeEvent();
+      if (!isTouchEvent(event) || typeof this._touchId !== 'number' ||
+          // Note that we use `changedTouches`, rather than `touches` because it
+          // seems like in most cases `touches` is empty for `touchend` events.
```
Comment (puschkin) [inline src/material/slider/slider.ts:700]: It would make sense that the ended touch is not anymore in the touches list,

File: src/material/slider/slider.ts (hunk 1 above)
Comment (puschkin) [reply src/material/slider/slider.ts]: I'll test your implementation this evening.

**Comment by puschkin** [comment]
Some general question:
Are there other components which share a similar behavior towards dragging via touch?
Perhaps this multitouch behavior could be outsourced into a directive or something in future.

**Comment by crisbeto** [comment]
I believe that the only other place where this would be a problem is `cdk/drag-drop`, but I'm not sure how we could generalize it well.

**Review by mmalerba — APPROVED** [review]
LGTM

File: src/material/slider/slider.ts (hunk 1 above)
Comment (puschkin) [reply src/material/slider/slider.ts]: Okay, I've tested on android with firefox and chrome.
On both devices, multitouch works now as expected, including the scenario that was not working before.

Great!
Thanks a lot!

Comment (crisbeto) [reply src/material/slider/slider.ts]: yay, thank you for verifying 🎉

**Review by devversion — APPROVED** [review]

**Comment by puschkin** [comment]
Hey, I just want to check back what's blocking this PR from being merged.
