### PR TITLE
fix(cdk/schematics): errors when attempting to read some files

### LINKED ISSUE #19779: bug(cdk): Update Failed : Cannot read property 'length' of null
#### Reproduction

I can't share my code because it's a big project, hope the stack will help you
`ng update @angular/material --force`
 
#### Expected Behavior

Working

#### Actual Behavior

```
 ** Executing migrations for package '@angular/cdk' **
Cannot read property 'length' of null
```
Stack trace in log file : 

```
[error] TypeError: Cannot read property 'length' of null
    at Object.computeLineStartsMap (path\node_modules\@angular\cdk\schematics\update-tool\utils\line-mappings.js:39:23)
    at ComponentResourceCollector.resolveExternalStylesheet (path\node_modules\@angular\cdk\schematics\update-tool\component-resource-collector.js:131:47)
    at path\node_modules\@angular\cdk\schematics\update-tool\index.js:97:50
    at Array.forEach (<anonymous>)
    at UpdateProject.migrate (path\node_modules\@angular\cdk\schematics\update-tool\index.js:95:35)
    at runMigrations (path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:128:42)
    at Object.<anonymous> (path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:83:17)
    at Generator.next (<anonymous>)
    at path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:11:12)
    at path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:57:31
    at MergeMapSubscriber.project (path\node_modules\@angular-devkit\schematics\src\rules\call.js:75:24)
    at MergeMapSubscriber._tryNext (path\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (path\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (path\node_modules\rxjs\internal\Subscriber.js:66:18)
```

#### Environment

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.0
Node: 12.4.0
OS: win32 x64

Angular: 10.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/flex-layout              10.0.0-beta.32
@ngtools/webpack                  10.0.0
@schematics/angular               9.1.9
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
```

- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

### PR DESCRIPTION
**Pull request by crisbeto**
In some cases the schematics fail to read a file which results in an error, because we weren't guarding against it properly. We had the correct types in place, but the tsconfig didn't have `strictNullChecks` enabled which prevented the compiler from reporting the errors.

Fixes #19779.

### CODE REVIEW

File: src/cdk/schematics/update-tool/component-resource-collector.ts [hunk 1]
```diff
@@ -133,13 +133,11 @@ export class ComponentResourceCollector {
         property.initializer.elements.forEach(el => {
           if (ts.isStringLiteralLike(el)) {
             const stylesheetPath = this._fileSystem.resolve(sourceFileDirPath, el.text);
+            const stylesheet = this.resolveExternalStylesheet(stylesheetPath, node);
 
-            // In case the stylesheet does not exist in the file system, skip it gracefully.
-            if (!this._fileSystem.exists(stylesheetPath)) {
-              return;
+            if (stylesheet) {
```
Comment (devversion) [inline src/cdk/schematics/update-tool/component-resource-collector.ts:138]: The change in general is good (enabling strict), but I wonder how this issue surfaces? Do we understand how this can happen? We asserted that a file exists in the virtual tree, and then read from it? Reading the file from the tree should not be `null`, or is this an edge case when a file is not readable somehow?

https://cs.opensource.google/angular/angular-cli/+/master:packages/angular_devkit/schematics/src/tree/host-tree.ts;l=282-291?q=read&ss=angular%2Fangular-cli

Comment (crisbeto) [reply src/cdk/schematics/update-tool/component-resource-collector.ts:138]: The assertion here was fine, but I think it failed [on the one below](https://github.com/angular/components/pull/19783/files#diff-7e114be5b3b61d197fa40462f633cb0bR176) where we didn't have an assertion.

Comment (devversion) [reply src/cdk/schematics/update-tool/component-resource-collector.ts:138]: Unless I miss something, we had a check before we invoked `resolveExternalStylesheet`. And the other one just accepted a glob of source files which are guaranteed to exist in FS.

Maybe the glob returned source files which exist on FS but are not available in the virtual file system. That would seem most likely.

Comment (crisbeto) [reply src/cdk/schematics/update-tool/component-resource-collector.ts:138]: I guess it depends on whether [the `resolve` call here](https://github.com/angular/components/blob/master/src/cdk/schematics/update-tool/index.ts#L106) corresponds to a `path.resolve` from Node which won't check the file system, or whether it's something different that actually does the lookup. If it's the latter, your explanation sounds plausible. Either way, I think that we should get this in for the next release so people that are updating to v10 don't run into it.

Comment (devversion) [reply src/cdk/schematics/update-tool/component-resource-collector.ts:138]: The `resolve` call should not be relevant here. The list of `additionalStylesheetPaths` is based on a real file system query, and `resolve` just turns the absolute FS path into a virtual FS workspace relative path.

So there are two options: Either the files are somehow not readable and are not added to the virtual FS tree, or our path resolution logic is flawed. And this is the point/issue I think we should figure out. Fixing the issue is great, but understanding the root cause seems beneficial. To be clear: From the beginning on I agreed that this is a good change to land either way, but it would be still worth figuring this out I assume. I'll ask the issue reporter for more information.

Also I think since this has been reported only once and seems very edgy/surprising, this is probably not P2 worthy.
