### PR TITLE
fix(material/core): sanity checks not disabled for node-based test environments

### LINKED ISSUE #23365: bug: Sanity checks run in test environement
As I explained in comment on PR ( https://github.com/angular/components/pull/23289 ) I have a lot of warnings coming from angular material sanity checks during my unit test runs, what makes the output unreadable.
@jelbourn advised me to open an issue because sanity checks should not run in test environment.

Thanks for your help !

Steps to reproduce:
1. Fork https://github.com/eweap/angular-material-warn
2. Run `yarn install` then run test with `yarn nx test ui` to run the test for the ui lib (its a nrwl/nx workspace)
 
 
#### Expected Behavior

What behavior were you expecting to see?
No warning should be display during the test run

#### Actual Behavior

What behavior did you actually see?
A warning is displayed:

```
console.warn
      Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming

      at MatCommonModule.Object.<anonymous>.MatCommonModule._checkThemeIsPresent (../../../src/material/core/common-behaviors/common-module.ts:144:15)
      at new MatCommonModule (../../../src/material/core/common-behaviors/common-module.ts:81:12)
      at Object.MatCommonModule_Factory [as factory] (../../node_modules/@angular/material/bundles/material-core.umd.js:189:69)
      at R3Injector.Object.<anonymous>.R3Injector.hydrate (../../../packages/core/src/di/r3_injector.ts:416:29)
      at R3Injector.Object.<anonymous>.R3Injector.get (../../../packages/core/src/di/r3_injector.ts:211:23)
      at ../../../packages/core/src/di/r3_injector.ts:247:51
          at Set.forEach (<anonymous>)
      at R3Injector.Object.<anonymous>.R3Injector._resolveInjectorDefTypes (../../../packages/core/src/di/r3_injector.ts:247:27)
```

#### Environment

- Angular: 12.2.1
- CDK/Material: 12.2.1
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

### PR DESCRIPTION
**Pull request by crisbeto**
In #23374 we expanded the logic that checks for test environments to cover Jest and Mocha. The problem is that we were checking against the `window` which won't work in a Node environment, because the global variables are attached to the `global` object, not the `window`, even though there may be a fake `window` declared by the test tooling.

These changes resolve the issue by first checking against `global` before falling back to `window`.

Fixes #23365.

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM. have you also considered using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#description?

File: src/cdk/a11y/focus-monitor/focus-monitor.ts [hunk 1]
```diff
@@ -99,10 +99,10 @@ export class FocusMonitor implements OnDestroy {
   private _windowFocused = false;
 
   /** The timeout id of the window focus timeout. */
-  private _windowFocusTimeoutId: number;
+  private _windowFocusTimeoutId: any;
```
Comment (crisbeto) [inline src/cdk/a11y/focus-monitor/focus-monitor.ts:102]: These are necessary, because the type now is `number | NodeJS.Timer`.

Comment (devversion) [reply src/cdk/a11y/focus-monitor/focus-monitor.ts:102]: Hmm. looks like these `any` casts are just needed for the legacy Saucelabs setup. Should we instead just declare the `global` type directly instead? I think that would be better than giving up on type safety. e.g.

```ts
declare const global: any;
```

Comment (crisbeto) [reply src/cdk/a11y/focus-monitor/focus-monitor.ts:102]: There's a comment at the top of that file about avoiding `declare const` so that's why I wrote it this way in the first place. Otherwise the same could've been written as `declare cost jest: any`.

Comment (devversion) [reply src/cdk/a11y/focus-monitor/focus-monitor.ts:102]: oh that's unfortunate. What is about `globalThis`? this should work as well and not need any Node types. Seems like it's made specifically for such platform-agnostic checks

Comment (crisbeto) [reply src/cdk/a11y/focus-monitor/focus-monitor.ts:102]: I avoided it since it isn't supported in some browsers (not sure if we care about them) and the workaround wasn't that much more code.

Comment (devversion) [reply src/cdk/a11y/focus-monitor/focus-monitor.ts:102]: okay, I don't feel very strongly about it. It seems supported by all of the browsers we make guarantees for (https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/globalThis), and it would save us from using `any` in all of `cdk/` (for the timers).

**Comment by michaelfaith** [comment]
Thanks for the follow-through on this.
