### PR TITLE
fix(drag-drop): error if next sibling is removed after drag sequence has started

### LINKED ISSUE #18205: CDK Drag and Drop: Unhandled Promise rejection in _cleanupDragArtifacts when ngbTooltip is used on cdkDrag element.
#### Reproduction

Stackblitz: https://stackblitz.com/edit/angular-wkr9so

Steps to reproduce:
1. Drag element from 'To do' to 'Done'
 
#### Expected Behavior

No exception and it gets inserted normally into the 'Done' list. It works when there is no ngbTooltip used.

#### Actual Behavior

Element does not get inserted in 'Done' list and Exception occurs in _cleanupDragArtifacts (because parentNode is undefined where it is expected to be defined):

```
Unhandled Promise rejection:
Cannot read property 'insertBefore' of null
; Zone:
<root>
; Task:
Promise.then
; Value:
Error: Cannot read property 'insertBefore' of null
TypeError: Cannot read property 'insertBefore' of null
at DragRef._cleanupDragArtifacts (https://angular-wkr9so.stackblitz.io/turbo_modules/@angular/cdk@8.2.3/bundles/cdk-drag-drop.umd.js:1032:63)
at eval (https://angular-wkr9so.stackblitz.io/turbo_modules/@angular/cdk@8.2.3/bundles/cdk-drag-drop.umd.js:861:23)
at ZoneDelegate.invoke (https://angular-wkr9so.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:391:26)
at Zone.run (https://angular-wkr9so.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:150:43)
at eval (https://angular-wkr9so.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:910:34)
at ZoneDelegate.invokeTask (https://angular-wkr9so.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:423:31)
at Zone.runTask (https://angular-wkr9so.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:195:47)
at drainMicroTaskQueue (https://angular-wkr9so.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:601:35)
at ZoneTask.invokeTask [as invoke] (https://angular-wkr9so.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:502:21)
at invokeTask (https://angular-wkr9so.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:1693:14)
at HTMLDivElement.globalZoneAwareCallback (https://angular-wkr9so.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:1719:17)
```

#### Environment

- Angular: 8.2.9
- CDK/Material: 8.2.2
- Browser(s): Chrome 79.0.3945.117
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

### PR DESCRIPTION
**Pull request by crisbeto**
When a drag sequence is started, we save a reference to the next sibling of the drag element so that we can use it at the end of the sequence to restore the element's original DOM position. This breaks down and throws an error if the next sibling gets removed while the user is dragging. These changes make the approach a bit more robust by inserting a comment node instead.

Fixes #18205.

### CODE REVIEW

File: src/cdk/drag-drop/drag-ref.ts [hunk 1]
```diff
@@ -93,10 +93,10 @@ export class DragRef<T = any> {
   private _pickupPositionOnPage: Point;
 
   /**
-   * Reference to the element that comes after the draggable in the DOM, at the time
-   * it was picked up. Used for restoring its initial position when it's dropped.
+   * Anchor node used to save the place in the DOM where the element was
+   * picked up so that it can be restored at the end of the drag sequence.
    */
-  private _nextSibling: Node | null;
+  private _anchor: Comment;
```
Comment (jelbourn) [inline src/cdk/drag-drop/drag-ref.ts]: Could we do `_placeholder` instead of `_anchor` to avoid overload with `<a>`?

Comment (crisbeto) [reply src/cdk/drag-drop/drag-ref.ts]: We can't, because there's something different that we're calling a `_placeholder` already (the element shown in the place of the one you're dragging).
