### PR TITLE
fix(material/timepicker): TimepickerInput component in shadow DOM

### LINKED ISSUE #30641: bug(TimepickerInput): Incorrect input behavior when component is in shadow DOM
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When the `MatTimepickerInput` component is within a shadow DOM, the input element's value will get formatted more often than it should, which results in unexpected behavior when typing.

The reason for this is [`MatTimepickerInput._hasFocus()`](https://github.com/angular/components/blob/443df2661fa3174bd2c854d9a094c8ade1b47446/src/material/timepicker/timepicker-input.ts#L408) making the assumption that the component will never be in the shadow DOM, doing a check that `inject(DOCUMENT).activeElement === inject(ElementRef).nativeElement`.

`inject(DOCUMENT)` refers to the root document, so when the `MatTimepickerInput` component instance is in the shadow DOM, the check that `MatTimepickerInput._hasFocus()` is doing will never be `true`.

The comparison that should actually be done is `inject(ElementRef).nativeElement.getRootNode().activeElement === inject(ElementRef).nativeElement`.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-starter-ucheqywm?file=src%2Fmain.ts
Steps to reproduce:
1. Focus on the input
2. Try typing out "12:30 PM"
3. On typing "1", nothing will be in the input.
4. On typing "2", "2" will be in the input.
5. On typing ":", "2:" will be in the input.
6. On typing "3", "2:03 AM" will be in the input.
7. On typing "0", nothing will be in the input.

### Expected Behavior

The expected behavior is typing "12:30 PM", and the "12:30 PM" option being selected.

### Actual Behavior

1. Focus on the input
2. Try typing out "12:30 PM"
3. On typing "1", nothing will be in the input.
4. On typing "2", "2" will be in the input.
5. On typing ":", "2:" will be in the input.
6. On typing "3", "2:03 AM" will be in the input.
7. On typing "0", nothing will be in the input.

### Environment

- Angular: 19.2.2
- CDK/Material: 19.2.3
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by calebkish**
Fixes an issue where the value of the input element referenced by a TimepickerInput component inside a shadow DOM was getting formatted too often due to `TimepickerInput._hasFocus()` assuming the component wasn't in the shadow DOM.

Fixes #30641

### CODE REVIEW

File: src/material/timepicker/timepicker-input.ts [hunk 1]
```diff
@@ -406,7 +407,8 @@ export class MatTimepickerInput<D> implements ControlValueAccessor, Validator, O
 
   /** Whether the input is currently focused. */
   private _hasFocus(): boolean {
-    return this._document.activeElement === this._elementRef.nativeElement;
+    const root = _getShadowRoot(this._elementRef.nativeElement) || this._document;
```
Comment (crisbeto) [inline src/material/timepicker/timepicker-input.ts:410]: We already have the `_getFocusedElementPierceShadowDom` utility for resolving the focused element.

**Review by crisbeto — APPROVED** [review]

File: src/material/timepicker/timepicker-input.ts [hunk 2]
```diff
@@ -42,6 +42,7 @@ import {Subscription} from 'rxjs';
 import {DOWN_ARROW, ESCAPE, hasModifierKey, UP_ARROW} from '@angular/cdk/keycodes';
 import {validateAdapter} from './util';
 import {DOCUMENT} from '@angular/common';
+import {_getFocusedElementPierceShadowDom} from '../../cdk/platform';
```
Comment (crisbeto) [inline src/material/timepicker/timepicker-input.ts:45]: The CI is failing because of this import. Can you change it to be `@angular/cdk/platform`?

**Review by crisbeto — CHANGES_REQUESTED** [review]

**Review by crisbeto — APPROVED** [review]

**Comment by crisbeto** [comment]
The changes were merged into the following branches: main, 19.2.x
