### PR TITLE
fix(cdk/a11y): detect fake touchstart events from screen readers

### LINKED ISSUE #21947: bug(MatMenu): With NVDA enabled, keyboard focus doesn't show up
Repros on https://material.angular.io/components/menu/overview

Everything works fine when NVDA is disabled

Environment: NVDA version - 2019.2.1 - Firefox Version 83.0 - Windows 10 Enterprise (64-bit)

image

### PR DESCRIPTION
**Pull request by crisbeto**
We currently have handling for the case where a `mousedown` event is thrown off by a fake `mousedown` listener that may be dispatched by a screen reader when an element is activated. It turns out that if the device has touch support, screen readers may dispatch a fake `touchstart` event instead of a fake `mousedown`.

These changes add another utility function that allows us to distinguish the fake events and fix some issues where keyboard focus wasn't being shown because of the fake `touchstart` events.

Fixes #21947.

### CODE REVIEW

File: src/cdk/a11y/fake-events.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
+/**
+ * @license
+ * Copyright Google LLC All Rights Reserved.
+ *
+ * Use of this source code is governed by an MIT-style license that can be
+ * found in the LICENSE file at https://angular.io/license
+ */
+
+/** Returns whether an event could be a faked `mousedown` event dispatched by a screen reader. */
```
Comment (jelbourn) [inline src/cdk/a11y/fake-events.ts:9]: nit: prefer "Gets" to "Returns" (since "Returns" is typically used to document the return type signature in JsDoc)

File: src/cdk/a11y/fake-events.ts [hunk 2]
```diff
@@ -0,0 +1,28 @@
+/**
```
Comment (jelbourn) [inline src/cdk/a11y/fake-events.ts:1]: Could we call this file `fake-event-detection`?

File: src/cdk/a11y/fake-events.ts [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+  // We can typically distinguish between these faked mousedown events and real mousedown events
+  // using the "buttons" property. While real mousedowns will indicate the mouse button that was
+  // pressed (e.g. "1" for the left mouse button), faked mousedowns will usually set the property
+  // value to 0.
+  return event.buttons === 0;
+}
+
+/** Returns whether an event could be a faked `touchstart` event dispatched by a screen reader. */
+export function isFakeTouchstartFromScreenReader(event: TouchEvent): boolean {
+  const touch: Touch | undefined = (event.touches && event.touches[0]) ||
```
Comment (jelbourn) [inline src/cdk/a11y/fake-events.ts:20]: Could you add a comment here capturing the screen-reader + browser combinations which exhibit the detected behavior here (including versions)?

**Review by jelbourn — APPROVED** [review]
LGTM
