### PR TITLE
fix(material/datepicker): Return union of view component types

### LINKED ISSUE #22996: bug(datepicker): mat-calendar ngOnChanges incorrectly optimized by Closure compiler
#### Reproduction

1. Click on the mont-year button.
2. Click on the year.
3. Error is logged in the console.
4. Click on the month.
5. Another error logged.

The date picker calendar has code like:
```
const view = this._getCurrentViewComponent();
if (view) {
  view._init();
}
```
where the `getCurrentViewComponent` is:
```
private _getCurrentViewComponent() {
  return this.monthView || this.yearView || this.multiYearView;
}
```

Each view is a non-null property on the class, so TypeScript infers that the return type is `typeof this.monthView` and tsickle propagates that to calendar.closure.js. Then the JavaScript compiler assumes that `view._init` call is always the function from monthView and optimizes code to only that.
 
#### Expected Behavior

No errors.

#### Actual Behavior

Errors are logged to the console:
- RangeError: Invalid time value
- TypeError: a.v is not a function

#### Environment

- Angular: n/a
- CDK/Material: n/a
- Browser(s): n/a
- Operating System (e.g. Windows, macOS, Ubuntu): n/a

### PR DESCRIPTION
**Pull request by rslawik**
TypeScript inferred the return type of `_getCurrentViewComponent` as the type of the month view only. Tsickle propagates that to the JavaScript compiler which optimizes the code as `monthView._init` was the only method that could be called. This causes runtime errors.

Fixed #22996

### CODE REVIEW

File: src/material/datepicker/calendar.ts [hunk 1]
```diff
@@ -428,7 +417,16 @@ export class MatCalendar<D> implements AfterContentInit, AfterViewChecked, OnDes
   }
 
   /** Returns the component instance that corresponds to the current calendar view. */
-  private _getCurrentViewComponent() {
-    return this.monthView || this.yearView || this.multiYearView;
+  private _getCurrentViewComponent(): MatMonthView<D> | MatYearView<D> | MatMultiYearView<D> {
+    // The return type must be a union to ensure that the Closure compiler does not optimize the
+    // calls to _init(). See https://github.com/angular/components/issues/22996.
+    switch (this.currentView) {
```
Comment (crisbeto) [inline src/material/datepicker/calendar.ts:423]: Is this `switch` required for the Closure compiler fix? The comment sounds like only the return type change would be necessary.

Comment (rslawik) [reply src/material/datepicker/calendar.ts:423]: Only the return type change is necessary.

However, `switch` makes it clear that we chose the current view component and does not rely on implicit falsyness of class fields that are non-nullable. The code had two ways of selecting the component (`if`s and `||`), I unified them.

The comment is to ensure that future refactorings do not revert to `||` and reduce the return type to only one type. IMO, it is an easy mistake to remove the return type of:
```
returnValue(): A | B {
  return this.a || this.b;
}
```

Comment (crisbeto) [reply src/material/datepicker/calendar.ts:423]: It might just be me (also since I wrote the code to begin with), but I think I prefer the `||` since it's more compact and it doesn't depend on matching class instances to strings.

Comment (rslawik) [reply src/material/datepicker/calendar.ts]: Ok, changed back to use `||` and extended the comment with little more context.

I assume the existing code that did the string to view mapping (L391-L397) does not need to be restored, so I keep them unified.

**Review by crisbeto — APPROVED** [review]
LGTM

**Comment by crisbeto** [comment]
@rslawik it looks like your latest commit fails our commit title lint check. It needs to be prefixed with `fix(material/datepicker)` or squashed into the initial commit.

**Comment by rslawik** [comment]
Thank you very much for the help, @crisbeto! It passed all the checks.
