### PR TITLE
fix(select): don't handle open key presses while the user is typing

### LINKED ISSUE #17774: mat-select poorly handles "space" when performing typeahead
#### Reproduction

repro: https://stackblitz.com/edit/angular-hr8bq9

Steps to reproduce issue 1:
1. Focus on select with it closed
2. Type "United K"
3. When the space character is typed the select is opened

Steps to reproduce issue 2:
1. Open select
2. Type "United K"
3. When the space character is typed the select is closed and "United States" is selected
 
#### Expected Behavior

What behavior were you expecting to see?
Space does not open/close the select when typeahead is being performed. " " character should be treated as part of the typeahead as long as the debounce time has not yet cleared.

#### Actual Behavior

What behavior did you actually see?
Space always opens the select when closed and always closes the select and selects an option when it is open.

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

### PR DESCRIPTION
**Pull request by crisbeto**
We support typing into a select to skip to an item, as well as pressing space to open the select, however if the user is typing something that has a space in it, the select will open and interrupt the user. These changes add some logic so that we don't trigger the panel while the user is typing.

Fixes #17774.

### CODE REVIEW

File: src/cdk/a11y/key-manager/list-key-manager.ts [hunk 1]
```diff
@@ -274,6 +274,11 @@ export class ListKeyManager<T extends ListKeyManagerOption> {
     return this._activeItem;
   }
 
+  /** Whether the user is currently typing into the manager using the typeahead feature. */
+  get isTyping(): boolean {
```
Comment (jelbourn) [inline src/cdk/a11y/key-manager/list-key-manager.ts]: Could this be a method?

Comment (crisbeto) [reply src/cdk/a11y/key-manager/list-key-manager.ts]: It could. I made it a getter because we have a couple of other similar properties on the `ListKeyManager` that are getters.

Comment (jelbourn) [reply src/cdk/a11y/key-manager/list-key-manager.ts]: I would prefer to make this one a method since it's very obviously a computed value

**Comment by crisbeto** [comment]
I've reworked it based on the feedback @jelbourn.

File: src/cdk/a11y/key-manager/list-key-manager.spec.ts [hunk 2]
```diff
@@ -818,6 +818,18 @@ describe('Key managers', () => {
         expect(keyManager.activeItem).toBe(itemList.items[1]);
       }));
 
+      it('should expose whether the user is currently typing', fakeAsync(() => {
+        expect(keyManager.isTyping()).toBe(false);
+
+        keyManager.onKeydown(createKeyboardEvent('keydown', 79, 'o')); // types "o"
```
Comment (devversion) [inline src/cdk/a11y/key-manager/list-key-manager.spec.ts]: out of curiosity: why not using `cdk/keycodes` for the `O` keycode? (for consistency)

Comment (devversion) [reply src/cdk/a11y/key-manager/list-key-manager.spec.ts]: Nevermind.. I see other tests in this file hardcode the code too.

Comment (crisbeto) [reply src/cdk/a11y/key-manager/list-key-manager.spec.ts]: I think most of the tests in this file were written before we added as many constants to the CDK.
