### PR TITLE
fix(material/tooltip): decouple removal logic from change detection

### LINKED ISSUE #19365: bug(MatTooltip): MatTooltip not work well with cdk-virtual-scroll-viewport
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Run this StackBlitz: https://stackblitz.com/edit/angular-1f53g9
2. Click remove button for each row and the tooltips do not disappear.
 
 
#### Expected Behavior

What behavior were you expecting to see?
The tooltip needs to disappear when the row is removed

#### Actual Behavior

What behavior did you actually see?
The tooltip stay when a row is removed. This is likely similar to this issue: https://github.com/angular/components/issues/6634 because the Angular CDK Virtual Scroller simply detach a view instead of removing it to reuse this view for other rows.

#### Environment

- Angular:
- CDK/Material:
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Mac OS

### PR DESCRIPTION
**Pull request by crisbeto**
Currently the logic in the tooltip that removes it from the DOM is run either if the trigger is destroyed or the exit animation has finished. The problem is that if the trigger is detached from change detection, but hasn't been destroyed, the exit animation will never run and the element won't be cleaned up. These changes switch to using CSS animations and manipulating the DOM node directly to trigger the animation.

Fixes #19365.

### CODE REVIEW

**Comment by crisbeto** [comment]
Caretaker note: these changes have the potential to break people's tests. We should determine whether to move forward, based on how many targets it breaks.

File: src/material/tooltip/tooltip.ts [hunk 1]
```diff
@@ -604,6 +588,33 @@ export class MatTooltip implements OnDestroy, OnInit {
     }
   }
 
+  /**
+   * Attaches the tooltip to the DOM and shows it.
+   * @param isUserInteraction Whether the showing was triggered by a user interaction or
+   *    programmatically. We have to know this in order to figure out whether clicking outside
+   *    show hide the tooltip.
```
Comment (jelbourn) [inline src/material/tooltip/tooltip.ts:595]: "show" -> "should"

File: src/material/tooltip/tooltip.ts [hunk 2]
```diff
@@ -641,42 +651,49 @@ export class TooltipComponent implements OnDestroy {
...
-    private _breakpointObserver: BreakpointObserver) {}
+    private _breakpointObserver: BreakpointObserver,
+    @Optional() @Inject(ANIMATION_MODULE_TYPE) public _animationMode?: string) {}
 
   /**
    * Shows the tooltip with an animation originating from the provided origin
    * @param delay Amount of milliseconds to the delay showing the tooltip.
    */
-  show(delay: number): void {
+  show(delay: number, isUserInteraction?: boolean): void {
```
Comment (jelbourn) [inline src/material/tooltip/tooltip.ts:682]: Technically this is a breaking change since we export `TooltipComponent` in the public API (probably unintentionally)

Comment (crisbeto) [reply src/material/tooltip/tooltip.ts:682]: I don't think it's breaking since the new parameter is optional.

**Comment by jelbourn** [comment]
Looks like it needs a rebase to presubmit

**Comment by crisbeto** [comment]
I pushed one more change to help address the concerns from #15990 by binding the internal `animationend` event outside the `NgZone`. I'm also bumping it to a P2, because this has come up a few times while triaging issues.

**Comment by mmalerba** [comment]
FYI this has 24 failing targets, it would be _possible_ to get in, but would take some effort

**Comment by crisbeto** [comment]
I'm guessing their tests would have to be updated in the same way as ours: to dispatch a fake `animationend` event instead of flushing the animations through Angular, or to switch to use test harnesses.

**Comment by andrewseguin** [comment]
Please rebase

**Comment by crisbeto** [comment]
@andrewseguin I finally got this back into a mergeable state. It took some time, because all of the tooltip code was moved around as a part of the MDC implementation. I've also ported this fix over to the MDC-based tooltip.

**Comment by mmalerba** [comment]
It seems that there's something not being properly flushed when using the harness. There's a test that looks roughly like this:
```
  const tooltip1 = await getHarness(MatTooltipHarness.with({selector: 'tt1'}));
  await (await tooltip1.host()).hover();
  expect(await tooltip1.isOpen()).toEqual(true);
  await (await tooltip1.host()).mouseAway();
  const tooltip2 = await getHarness(MatTooltipHarness.with({selector: 'tt2'}));
  await (await tooltip2.host()).hover();
  expect(await tooltip2.isOpen()).toEqual(true);
  await (await tooltip2.host()).mouseAway();
```

For the second tooltip the `isOpen` check fails, if I comment out the tooltip1 stuff then it passes

**Comment by crisbeto** [comment]
I've rebased and added some logic to the test harnesses to simulate the `animationend` events.
