### PR TITLE
fix(table): not picking up indirect descendant defs

### LINKED ISSUE #17339: Ivy true, error matRowDef/matColumnDef
#### Expected Behavior

I created a tables component of the material, where he receives an object to extract the ids of columns and assemble the array, but there are some checks I do, see the image below

Captura de Tela_selecionar área_20191009084119

#### Actual Behavior

If I do not have ivy active, after deploy it works 100%, if I activate returns the error of the image below

Captura de Tela_selecionar área_20191009084412

Captura de Tela_selecionar área_20191009084421

#### Environment

```
Angular CLI: 8.3.8
Node: 10.15.3
OS: linux x64
Angular: 9.0.0-next.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.8
@angular-devkit/build-angular              0.803.8
@angular-devkit/build-optimizer            0.803.8
@angular-devkit/build-webpack              0.803.8
@angular-devkit/core                       8.3.8
@angular-devkit/schematics                 8.3.8
@angular/cdk                               8.2.2
@angular/cli                               8.3.8
@angular/flex-layout                       8.0.0-beta.27
@angular/material                          8.2.2
@angular/material-moment-adapter           8.2.2
@ngtools/webpack                           8.3.8
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.8
@schematics/update                         0.803.8
rxjs                                       6.5.3
typescript                                 3.5.3
webpack                                    4.39.2

```

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes the table not picking descendants that aren't direct descendants. Currently this isn't a huge problem, however with Ivy it'll become an issue that'll prevent consumers from setting an `ngIf` around the defs.

Fixes #17339.

### CODE REVIEW

File: src/cdk/table/table.ts [hunk 1]
```diff
@@ -375,16 +375,20 @@ export class CdkTable<T> implements AfterContentChecked, CollectionViewer, OnDes
    * The column definitions provided by the user that contain what the header, data, and footer
    * cells should render for each column.
    */
-  @ContentChildren(CdkColumnDef) _contentColumnDefs: QueryList<CdkColumnDef>;
+  @ContentChildren(CdkColumnDef, {descendants: true}) _contentColumnDefs: QueryList<CdkColumnDef>;
```
Comment (crisbeto) [inline src/cdk/table/table.ts]: Note that this makes assumptions that we can't nest tables. AFAIK it's not something we support anyway.

Comment (jelbourn) [reply src/cdk/table/table.ts]: Right, based on the trick we use the get cell outlets after stamping out row views, we absolutely, 100% do not support nested tables.

**Comment by crisbeto** [comment]
You can see an example in initial report: https://github.com/angular/components/issues/17339.

**Comment by jelbourn** [comment]
It seems strange to me, since I I expect people to accomplish things like this either by swapping columns or by putting an `ngIf` inside the cell. Is there some advantage to this approach that I'm not thinking of?

**Comment by crisbeto** [comment]
I'm not sure really. I suppose it's more declarative? It's still something that works with ViewEngine but will break in Ivy.

**Comment by jelbourn** [comment]
Three failing targets in Google, I will investigate today

**Comment by jelbourn** [comment]
Two of the targets were projects that had a nested `mat-table`. Reached out to the teams and they'll hopefully fix this week. Looking into the third failure now.

**Comment by jelbourn** [comment]
The third failure was an instance of the table literally defining each `matColumnDef` twice; I sent a change to remove the extra one.

**Comment by surajtambe** [comment]
Solution for #17339 is to take checkbox outside of *ngfor , it will work as expected. I have implemented in similar way for adding checkbox for MatTable with Ivy Enabled. if checkbox column present in columns Aray it will render.

For above approch i have small questions, 
1. Does above approch adds performance hit ?
2. Does this close doors for nested tables ? 
3. Solution i have added is desired functionality or workaround ?

I am new to open source contribution, not sure whether to comment on PR or else please Ignore.

**Comment by surajtambe** [comment]
> Solution for #17339 is to take checkbox outside of *ngfor , it will work as expected. I have implemented in similar way for adding checkbox for MatTable with Ivy Enabled. if checkbox column present in columns Aray it will render.
> 
> For above approch i have small questions,
> 
> 1. Does above approch adds performance hit ?
> 2. Does this close doors for nested tables ?
> 3. Solution i have added is desired functionality or workaround ?
> 
> I am new to open source contribution, not sure whether to comment on PR or else please Ignore.

As my solution not working for #17339 , we should merge this PR to solve #17339

**Comment by GlauberF** [comment]
any predictions to release this fix?

**Comment by jelbourn** [comment]
Should be in the first 9.0.0 RC
