### PR TITLE
fix(material/datepicker): don't invoke change handler when filter is swapped out if result is the same

### LINKED ISSUE #20967: bug(mat-datepicker): value change firing on filter re assign
#### Reproduction

https://stackblitz.com/edit/angular-ivy-eaktsw?devtoolsheight=33&file=src/app/app.component.ts

Steps to reproduce:
open stackblitz, look at console output, value change triggered incorrectly
 
#### Expected Behavior
value change to fire only when value has changed, not when filter changes

#### Actual Behavior
value change firing for same values

#### Environment
- Angular: 10.2.1
- CDK/Material: 10.2.7
- Browser(s): Version 86.0.4240.111 (Official Build) (x86_64)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

### PR DESCRIPTION
**Pull request by crisbeto**
Doesn't invoke the `ControlValueAccessor` change function when a new date filter is assigned, if the result wouldn't have change the validation state.

Fixes #20967.

### CODE REVIEW

File: src/material/datepicker/datepicker-input.ts [hunk 1]
```diff
@@ -112,8 +112,12 @@ export class MatDatepickerInput<D> extends MatDatepickerInputBase<D | null, D>
   @Input('matDatepickerFilter')
   get dateFilter() { return this._dateFilter; }
   set dateFilter(value: DateFilterFn<D | null>) {
+    const wasMatchingFilter = this._matchesFilter(this.value);
```
Comment (mmalerba) [inline src/material/datepicker/datepicker-input.ts:115]: To keep the naming in line with the range picker (`wasMatchingStart`, `wasMatchingEnd`) I would call this `wasMatchingValue`

**Review by mmalerba — APPROVED** [review]
LGTM
