### PR TITLE
fix(material/select): don't assign typeahead value after blur

### LINKED ISSUE #25452: bug(MatSelect): typeaheadDebounceInterval should not fire after blur
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When the user uses the keyboard to select an option in a mat-select and then tabs out of the field, the value is expected to be the option matching what the user typed.  Instead that value is not set until after the typeaheadDebounceInterval  has expired.

Our app was trying to save a user's selections in a mat-select to the server using the blur event.  But we were getting the wrong value since the debounce interval was still in effect.  We don't want to use selectionChange since that would fire multiple request if the user uses the arrow keys or mouse wheel.

### Reproduction

https://stackblitz.com/edit/components-issue-2uvyjq?file=src/app/example-component.html

Steps to reproduce:
1. Rapidly type 'A' and tab 
2. Value & Value On Blur will both still be N
3. About 3 seconds later value will change to A, but Value On Blur will still be N

### Expected Behavior

The search being debounced would execute immediately on blur and the value would be set correctly.

### Actual Behavior

The value of an unfocused control changes some unknowable amount of time after the user leaves the control.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the select would assign the value triggered by the typeahead even if the select doesn't have focus anymore.

Fixes #25452.

### CODE REVIEW

File: src/cdk/a11y/key-manager/list-key-manager.ts [hunk 1]
```diff
@@ -188,6 +188,12 @@ export class ListKeyManager<T extends ListKeyManagerOption> {
     return this;
   }
 
+  /** Cancels the current typeahead sequence. */
+  cancelTypeahead(): this {
+    this._pressedLetters = [];
```
Comment (devversion) [inline src/cdk/a11y/key-manager/list-key-manager.ts:193]: Just double-checking: From high-level glancing at the issue, would they rather expect the current buffer to be written immediately on blur?

**Review by devversion — APPROVED** [review]
LGTM if you think this is the right behavior

File: src/cdk/a11y/key-manager/list-key-manager.ts (hunk 1 above)
Comment (crisbeto) [reply src/cdk/a11y/key-manager/list-key-manager.ts:193]: I think that it's open to interpretation. My take was that if focus leaves the trigger, we don't know which item the user was intending to focus.

Comment (crisbeto) [reply src/cdk/a11y/key-manager/list-key-manager.ts:193]: I understand, but I think that both behaviors can be equally valid. https://github.com/angular/components/issues/25452 talks about it being confusing that we can write the value after they've tabbed away.

Comment (devversion) [reply src/cdk/a11y/key-manager/list-key-manager.ts:193]: yeah, as said, this was mostly to check if you considered the other alternative. I'm good either way
