### PR TITLE
fix(cdk/testing): add code to keyboard events

### LINKED ISSUE #27034: bug(ComponentHarness): TestElement.sendKeys(TestKey.ENTER) is missing Keyboard Event code
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When calling `sendKey` with `TestKey.ENTER` on a `TestElement`, the keyboard event that gets generated shows blank for the `code` property.

### Reproduction

Steps to reproduce:
1. Run `sendKeys(TestKey.ENTER)` on any `TestElement`
2. Check the Keyboard Event `code` value.

See StackBlitz: https://stackblitz.com/edit/harness-issue-zpusdu?file=src%2Fapp%2Fmy-harness-example.spec.ts

### Expected Behavior

Keyboard Event `code` value should be `'Enter'`.

This is from testing out the Enter key on Mozilla's site with Chrome on Windows showing the correct `code` value:
keyboard-event

### Actual Behavior

Keyboard Event `code` value is `''`.

### Environment

- Angular: 15.2.4
- CDK/Material: 15.2.4
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by crisbeto**
When the `UnitTestElement` dispatches keyboard event sequences, it sends out fake events which didn't have the `code` property. These changes add mappings for common keys to their codes.

Fixes #27034.

### CODE REVIEW

File: src/cdk/testing/testbed/fake-events/type-in-element.ts [hunk 1]
```diff
@@ -22,6 +22,50 @@ const incrementalInputTypes = new Set([
...
+  if ((charCode >= 97 && charCode <= 122) || (charCode >= 65 && charCode <= 90)) {
+    return `Key${char.toUpperCase()}`;
+  }
+
+  // Digits from 0 to 9.
+  if (48 <= charCode && charCode <= 57) {
+    return `Digit${char}`;
+  }
+
+  return charsToCodes[char] ?? '';
```
Comment (crisbeto) [inline src/cdk/testing/testbed/fake-events/type-in-element.ts:66]: Random thought: we could return `<unsupported>` here instead which would make it more obvious that our code doesn't have a mapping for the specific character.

Comment (andrewseguin) [reply src/cdk/testing/testbed/fake-events/type-in-element.ts:66]: Sounds like a good idea to me, could potentially prevent some bad tests

**Review by andrewseguin — APPROVED** [review]
