### PR TITLE
fix(material/autocomplete): reopen panel on input click

### LINKED ISSUE #15177: Autocomplete: https://material.angular.io/components/autocomplete/overview weird behavior with simple autocomplete
#### What is the expected behavior?
Ideally you should be given a choice: what should be the behavior when you click on autocomplete. But current behavior at least looks pretty unfriendly to user (from my point of view).

#### What is the current behavior?
Currently you're only able to open autocomplete again if you eith focus any other control and then focus autocomplete again; or remove the character from the selected option

#### What are the steps to reproduce?
https://material.angular.io/components/autocomplete/overview

1) go to https://material.angular.io/components/autocomplete/overview#simple-autocomplete
2) select any value
3) try to open autocomplete again

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I believe the latest version of Angular

### PR DESCRIPTION
**Pull request by crisbeto**
Currently if the user clicks an autocomplete to open it, selects an option and then clicks again, the panel won't open, because we use `focus` and the input was focused already. These changes add an extra `click` listener so the panel can reopen.

Fixes #15177.

### CODE REVIEW

File: src/material/autocomplete/autocomplete-trigger.ts [hunk 1]
```diff
@@ -445,6 +446,12 @@ export class MatAutocompleteTrigger implements ControlValueAccessor, OnChanges,
     }
   }
 
+  _handleClick() {
+    if (!this.panelOpen) {
```
Comment (jelbourn) [inline src/material/autocomplete/autocomplete-trigger.ts]: Move this check into `this.openPanel()` and just call that from `(click)`?

**Comment by crisbeto** [comment]
Addressed the feedback @jelbourn.

**Comment by patoncrispy** [comment]
Is there any chance this will get merged?

**Comment by wratho** [comment]
what is the news on this. Is this something that material agrees with and is just not focusing on or is this antithetical to how material wants this to be handled

**Comment by jelbourn** [comment]
This PR (and any other that get stalled out) was blocked by some number of test failures when we ran it against Google internal CI/presubmit test system. It's in the backlog to investigate, but has been lower priority than other work going on.

**Comment by DarkSnowy** [comment]
Is there a good workaround in the meantime?
