### PR TITLE
fix(material/menu): render backdrop for context menu if explicitly opted in

### LINKED ISSUE #32350: bug(MatMenu): Opening as context menu ignores hasBackdrop
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

In a place where we define a matMenu, and allow it to be open via a button (`matMenuTriggerFor`), and then the entire element also works as a context trigger `matContextMenuTriggerFor`, it get's a little strange that the behaviours do not align.

The context menu cannot have a backdrop, as far as I can tell, because of a [intentional implementation](https://github.com/angular/components/blob/349708c3e460bb44874882fb2a5b13a1086858dc/src/material/menu/context-menu-trigger.ts#L88), but still closes when click outside. `matMenuTriggerFor` follows the `hasBackdrop` setting on the `matMenu` element, but if you don't have a backdrop, will not automatically close when you click outside.

I can undestand that the default behaviour of `matContextMenuTriggerFor` should be to not have a backdrop, and close when you click elesewhere, but the fact that the `hasBackdrop` configuration is on the `matMenu` element itself, makes it counter-intuitive. There is a setting that the  [documentation](https://material.angular.dev/components/menu/api#MatMenu) states will decide if the menu has a backdrop, but if it's opened via context menu, that config is ignored.

I suggest that: 

1. `matContextMenuTriggerFor` allows backdrop, but in cases where the setting is not defined, uses no backdrop as a default. 
2. `matMenuTriggerFor` adopts the same "click outside" to close, even when there's no backdrop.

### Reproduction

StackBlitz link:  https://stackblitz.com/edit/context-menu-backdrop?file=src%2Fmain.ts
Steps to reproduce:
1. Clicking the button opens as a menu (with backdrop)
2. Rightclicking the context hook opens as a context menu (without backdrop)

### Expected Behavior

- `matContextMenuTriggerFor` opens without backdrop, regardless of `matMenu.hasBackdrop` setting.
- `matMenuTriggerFor` does not close on click outside when opened without a backdrop

### Actual Behavior

- `matContextMenuTriggerFor` opens without backdrop by default, but can have backdrop if `mat-menu` has `hasBackdrop`.
- `matMenuTriggerFor` supports closing when click outside (probably opt-in behaviour to avoid breakages)

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

### PR DESCRIPTION
**Pull request by crisbeto**
When we introduced context menus, we disabled backdrops on them in order to mimic the native behavior where right clicking somewhere else moves the menu there. This seems to not be desirable for some users so these changes add some logic to enable the backdrop if the user explicitly requested it.

Fixes #32350.

### CODE REVIEW

File: src/material/menu/menu-trigger-base.ts [hunk 1]
```diff
@@ -222,7 +222,7 @@ export abstract class MatMenuTriggerBase implements OnDestroy {
       overlayConfig.hasBackdrop =
         menu.hasBackdrop == null ? !this._triggersSubmenu() : menu.hasBackdrop;
     } else {
-      overlayConfig.hasBackdrop = false;
+      overlayConfig.hasBackdrop = menu.hasBackdrop == null ? false : menu.hasBackdrop;
```
Comment (ok7sai) [inline src/material/menu/menu-trigger-base.ts]: `overlayConfig.hasBackdrop = menu.hasBackdrop ?? false` might be easier to read.

**Comment by crisbeto** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 3670e0f6c59e5c78a421658b99da07f15c3a1388
- 21.2.x: 2abe8e6b7330f5281b560b202ab70bdf593782cc
