### PR TITLE
fix(material/chips): Async chips with a delay are not highlighted

### LINKED ISSUE #27370: bug(CHIPS): Async Chips are not highlighted with Forms
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

Async chips are not highlighted when used in conjunction with Forms.

This issue is present in Angular 15 and 16 version and probably older

### Reproduction

StackBlitz link: [Link](https://stackblitz.com/edit/vm5tuk?file=src%2Fexample%2Fchips-overview-example.ts)

Steps to Reproduce:
1. Create a mat-chip-listbox with mat-chip-option and add either formControl or ngModel.
2. Set a value to the formControl, which can be set asynchronously or synchronously.
3. Render the mat-chip-option with a delay, achieved through the usage of an async pipe and the .pipe(observeOn(asyncScheduler, 1000)).
4. Observe that the selected chips are not being highlighted.

### Expected Behavior

The mat-chip-listbox should properly highlight the asynchronously rendered chips

### Actual Behavior

The mat-chip-listbox does not highlight the asynchronously rendered chips.

### Environment

- Angular: 16.1.2
- Material: 16.1.2
- Browser(s): Chrome
- Operating System (macOS):

### PR DESCRIPTION
**Pull request by yurakhomitsky**
Fixes a bug in the Angular Material `chips` component where async chips with a delay were not highlighted correctly.

Fixes #27370

### CODE REVIEW

**Review by mmalerba — APPROVED** [review]
LGTM

File: src/material/chips/chip-listbox.ts [hunk 1]
```diff
@@ -210,14 +209,12 @@ export class MatChipListbox
...
   ngAfterContentInit() {
-    if (this._pendingInitialValue !== undefined) {
-      Promise.resolve().then(() => {
-        this._setSelectionByValue(this._pendingInitialValue, false);
-        this._pendingInitialValue = undefined;
-      });
-    }
-
     this._chips.changes.pipe(startWith(null), takeUntil(this._destroyed)).subscribe(() => {
+      if (this.value !== undefined) {
```
Comment (mmalerba) [inline src/material/chips/chip-listbox.ts:213]: I think this should be `if (this.value === undefined) {`. Previously we were checking `_pendingInitialValue !== undefined`, which implied the value _was_ `undefined`, as the pending value had not been set. Hopefully making this change will resolve the test failures I'm seeing in google

**Review by mmalerba — CHANGES_REQUESTED** [review]

File: src/material/chips/chip-listbox.ts (hunk 1 above)
Comment (yurakhomitsky) [reply src/material/chips/chip-listbox.ts:213]: This change `if (this.value === undefined)` fails even more unit tests

Comment (yurakhomitsky) [reply src/material/chips/chip-listbox.ts:213]: @mmalerba How can I know whether my changes fixed the problem? Where can I look at it?

Comment (mmalerba) [reply src/material/chips/chip-listbox.ts:213]: I will have to rerun the internal test and report back

Comment (yurakhomitsky) [reply src/material/chips/chip-listbox.ts:206]: @mmalerba  Any updates? I have synced  the branch

Comment (mmalerba) [reply src/material/chips/chip-listbox.ts:206]: It's looking better - there's still 3 failing tests, 1 ExpressionChangedAfterChecked and 2 screenshot diffs that look possibly wrong. It's not clear if these are issues with the changes or issues with the tests themselves. Unfortunately I don't think there's much we can do until I have some time to dig deeper into it

Comment (yurakhomitsky) [reply src/material/chips/chip-listbox.ts:206]: Thanks for letting me know! In case you need me to update the branch just ping

Comment (mmalerba) [reply src/material/chips/chip-listbox.ts:206]: Turned out to be issues with the tests, I cleaned it up and we're able to merge this now

**Review by mmalerba — APPROVED** [review]

**Comment by mmalerba** [comment]
The changes were merged into the following branches: main, 19.1.x
