### PR TITLE
fix(material/badge): warn if use with mat-icon

### LINKED ISSUE #27035: feat(badge): Badge should warn when used on an `aria-hidden` `mat-icon`
### Feature Description

From usages across Google, we've seen that's it's common for devs to put `matBadge` on `<mat-icon>`. The problem is that `<mat-icon>` is `aria-hidden` by default, meaning that the badge content is also invisible to screen readers. Our documentation already calls this out as a misuse of the badge, but we can go a step further and actually produce a console warning. This would look something roughly like

```ts
if (ngDevMode && host.nodeName === 'mat-icon' && host.getAttribute('aria-hidden') === 'true') {
  console.warn('Warning: detected matBadge on a "<mat-icon>" with "aria-hidden="true"\n${host.outerHTML}');
}
```

### PR DESCRIPTION
**Pull request by Naaajii**
prior this commit there was no warning for matBadge being use with <mat-icon> as it is aria-hidden by default which means badge content is invisible to screen readers

fixes #27035

### CODE REVIEW

File: src/material/badge/badge.ts [hunk 1]
```diff
@@ -156,6 +156,20 @@ export class MatBadge extends _MatBadgeBase implements OnInit, OnDestroy, CanDis
       if (nativeElement.nodeType !== nativeElement.ELEMENT_NODE) {
         throw Error('matBadge must be attached to an element node.');
       }
+
+      const badgeTagName: string = 'mat-icon';
```
Comment (crisbeto) [inline src/material/badge/badge.ts:160]: Isn't this the icon tag name?

File: src/material/badge/badge.ts [hunk 2]
```diff
@@ -156,6 +156,20 @@ export class MatBadge extends _MatBadgeBase implements OnInit, OnDestroy, CanDis
...
+
```
Comment (crisbeto) [inline src/material/badge/badge.ts:161]: I think that we should wrap this warning in `ngDevMode` so it gets stripped from production builds.

**Review by crisbeto — COMMENTED** [review]
Also I'd say that this is more of a `fix` than a feature.

File: src/material/badge/badge.ts (hunk 2 above)
Comment (Naaajii) [reply src/material/badge/badge.ts:161]: it is wrapped in `ngDevMode` condition before the `matBadge must be attached to an element node.`, at line 154.

image

File: src/material/badge/badge.ts (hunk 1 above)
Comment (Naaajii) [reply src/material/badge/badge.ts]: yes. I forget to make this change after copying content from my previous PR. I've fixed this in latest commit.

File: src/material/badge/badge.ts [hunk 3]
```diff
@@ -156,6 +156,20 @@ export class MatBadge extends _MatBadgeBase implements OnInit, OnDestroy, CanDis
...
+      // Heads-up for developers to avoid putting matBadge on <mat-icon>
+      // as it is aria-hidden by default docs mention this at:
+      // https://material.angular.io/components/badge/overview#accessibility
+      if (
+        nativeElement.tagName.toLowerCase() === matIconTagName &&
+        nativeElement.getAttribute('aria-hidden') === 'true'
+      ) {
+        console.warn(
+          `Warning: detected matBadge on a "<mat-icon>" with "aria-hidden="true"\n${nativeElement.outerHTML}`,
```
Comment (crisbeto) [inline src/material/badge/badge.ts:170]: I think the warning should mention why this is a problem and what the user should do. Otherwise it's unclear why having a badge there is a problem.

Comment (Naaajii) [reply src/material/badge/badge.ts:170]: something like:
```
Warning: detected matBadge on "<mat-icon>" as it's aria-hidden="true" by default, making badge content invisible to screen readers. Consider adding aria-hidden="false" to "<mat-icon>" so matBadge description stay preserved to screen readers. 

${nativeElement.outerHTML}
```

idk, it took me 25m to come up with the above message. I'm not really good with English & explaining things, feel free to correct me on this.

Comment (crisbeto) [reply src/material/badge/badge.ts:170]: Maybe something like this?

> Detected a matBadge on an `aria-hidden` `<mat-icon>`. Consider setting `aria-hidden="false"` in order to surface the information assistive technology.

**Review by crisbeto — APPROVED** [review]
LGTM
