### PR TITLE
fix(material/datepicker): error due to synchronous change detection

### LINKED ISSUE #31959: bug(datepicker): Crash in range picker after selecting start date and moving to next month with arrow keys
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18.2.14

### Description

There is an error in the range picker after selecting a start date and then attempting to navigate to the next month using arrow down key. 

```ASSERTION ERROR: LView must be defined [Expected=> null != undefined <=Actual]```

The navigation works visually and the end date can be selected after the crash.

This is reproducible on the official Angular docs, versions 20 and 19, but not 18.

### Reproduction

**StackBlitz link:** https://stackblitz.com/edit/14k4pgtg?file=src%2Findex.html (official example from Angular docs)

**Steps to reproduce:**
1. Select a start date
2. Press "Arrow Down" until the next month is active

### Expected Behavior

No error.

### Actual Behavior

Crashes with error:

```
ERROR Error: ASSERTION ERROR: LView must be defined [Expected=> null != undefined <=Actual]
    at throwError2 (chunk-AEB3MSDC.js?v=2ae8b288:3777:9)
    at assertDefined (chunk-AEB3MSDC.js?v=2ae8b288:3773:5)
    at assertLView (chunk-AEB3MSDC.js?v=2ae8b288:5079:3)
    at detachExistingView (chunk-AEB3MSDC.js?v=2ae8b288:20947:16)
    at LiveCollectionLContainerImpl.detach (chunk-AEB3MSDC.js?v=2ae8b288:20865:12)
    at reconcile (chunk-AEB3MSDC.js?v=2ae8b288:20587:43)
    at ɵɵrepeater (chunk-AEB3MSDC.js?v=2ae8b288:20911:5)
    at MatCalendarBody_Template (@angular_material_datepicker.js?v=9365a00e:12711:9)
    at executeTemplate (chunk-AEB3MSDC.js?v=2ae8b288:10618:5)
    at refreshView (chunk-AEB3MSDC.js?v=2ae8b288:11304:7)
```

### Environment

- Angular: 20.2.0
- CDK/Material: 20.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

### PR DESCRIPTION
**Pull request by crisbeto**
The month view had a `detectChanges` call that was happening inside a `blur` event which ended up causing re-entrant change detection and hitting an assertion in the framework. These changes remove it since it doesn't appear to be necessary anymore.

Fixes #31959.

I've also converted the internal calendar state to signals to get a feel for how breaking something like this might be.

### CODE REVIEW

File: src/material/datepicker/month-view.ts [hunk 1]
```diff
@@ -458,16 +462,10 @@ export class MatMonthView<D> implements AfterContentInit, OnChanges, OnDestroy {
...
+          this._previewStart.set(this._getCellCompareValue(dragRange.start));
+          this._previewEnd.set(this._getCellCompareValue(dragRange.end));
         }
       }
-
-      // Note that here we need to use `detectChanges`, rather than `markForCheck`, because
-      // the way `_focusActiveCell` is set up at the moment makes it fire at the wrong time
-      // when navigating one month back using the keyboard which will cause this handler
-      // to throw a "changed after checked" error when updating the preview state.
-      this._changeDetectorRef.detectChanges();
```
Comment (crisbeto) [inline src/material/datepicker/month-view.ts:470]: Deleting this line is the fix for #31959.

**Review by andrewseguin — APPROVED** [review]

**Comment by crisbeto** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 542bb6ba8ab4bc339095122ee67705a38438b6e3
- 20.2.x: 6270efed2e87b1c43310b582cb3ec8cab058b740
