### PR TITLE
fix(material/schematics): support stricter TypeScript compiler flags

### LINKED ISSUE #17135: schematics: verify that generated code passes CLI's stricter compiler flags
#### Reproduction
PR https://github.com/angular/angular-cli/pull/14905 introduces a new `strict` option to the Angular CLI. This option is currently `false` by default, but there are plans to make it `true` in version 9 or 10.

```json
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noFallthroughCasesInSwitch": true,
    "strictNullChecks": true,
```
 
#### Expected Behavior
We need to make sure that all of the code generated by our Schematics will compile with these new flags.

We already use these flags for building the [library source](https://github.com/angular/components/blob/master/tsconfig.json) and [examples](https://github.com/angular/components/blob/cf70c4342e7ea277011cf289e721383b7784a18a/src/material-examples/tsconfig-build.json).

PR https://github.com/angular/material.angular.io/pull/631 adds these compiler flags for material.angular.io builds as well.

#### Related Issues
I'm not sure if this is something that we can do in integration tests (https://github.com/angular/components/issues/16479) or not. But it seems possible and would be needed to avoid introducing regressions over time.

https://github.com/angular/components/issues/13329 tracks making the library code follow even stricter checks (`--strictPropertyInitialization`).

https://github.com/angular/components/issues/16028 relates to stricter template checks in Ivy.

### PR DESCRIPTION
**Pull request by Splaktar**
Fixes #17135

### CODE REVIEW

File: src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__-datasource.ts.template [hunk 1]
```diff
@@ -103,6 +103,6 @@ export class <%= classify(name) %>DataSource extends DataSource<<%= classify(nam
 }
 
 /** Simple sort comparator for example ID/Name columns (for client-side sorting). */
-function compare(a, b, isAsc) {
+function compare(a: any, b: any, isAsc: boolean) {
```
Comment (Splaktar) [inline src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__-datasource.ts.template]: This could also be:
```ts
function compare(a: string | number, b: string | number, isAsc: boolean) {
```
But that might be slightly more work to customize. I'm happy to change it, but wanted to get some feedback on it first?

Comment (jelbourn) [reply src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__-datasource.ts.template]: Yeah, I'd prefer to avoid `any` in this situation

File: src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template [hunk 2]
```diff
@@ -84,7 +83,10 @@ export class <%= classify(name) %>Component {
   }
 
   /** Get the children for the node. */
-  getChildren(node: FileNode) {
-    return observableOf(node.children);
+  getChildren(node: FileNode): FileNode[] | null | undefined {
+    if (node.children === null || node.children === undefined) {
+      return node.children;
+    }
+    return node.children;
```
Comment (crisbeto) [inline src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template]: It seems like both of the `if` clause outcomes will return the same value. You should be able to reduce it to just `return node.children`.
