### PR TITLE
fix(button-toggle): static checked value not being picked up

### LINKED ISSUE #18427: mat-button-toggle default checked not wotking
mat-button-toggle default checked not wotking when :

"angularCompilerOptions": {
    "enableIvy": true 
  }

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes the static checked value of a button toggle not having an effect in Ivy, because it ends up being assigned earlier than we expect. This is a side effect of the circular dependency between the toggle group and the toggle which should be cleaned up at some point, because it's not the first time it has caused issues with things going out of sync.

Fixes #18427.

### CODE REVIEW

File: src/material/button-toggle/button-toggle.ts [hunk 1]
```diff
@@ -294,7 +294,7 @@ export class MatButtonToggleGroup implements ControlValueAccessor, OnInit, After
     // the side-effect is that we may end up updating the model value out of sequence in others
     // The `deferEvents` flag allows us to decide whether to do it on a case-by-case basis.
     if (deferEvents) {
-      Promise.resolve(() => this._updateModelValue(isUserInput));
+      Promise.resolve().then(() => this._updateModelValue(isUserInput));
```
Comment (crisbeto) [inline src/material/button-toggle/button-toggle.ts]: This change has nothing to do with the fix, but I noticed that it wasn't actually doing anything so I fixed it.
