### PR TITLE
fix(snack-bar): handle large numbers passed in as duration

### LINKED ISSUE #17234: Snackbar immediately closes if duration is above 1e+21
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Open https://stackblitz.com/angular/jrnynrjaqdo
2. Display a snackbar with duration `durationInSeconds = 1e+21;` or `Number.MAX_VALUE`
3. Launch the snackbar
 
 
#### Expected Behavior

What behavior were you expecting to see?

The snackbar should be displayed for a (very) long time.

#### Actual Behavior

What behavior did you actually see?

Snackbar automatically closes itself after ~300ms.

It seems snackbar doesn't handle numbers with `e` format starting at `e+21`, eg it supports `1+e10` but not `1+e21` or above.

#### Environment

- Angular: 8.2.8
- CDK/Material: 8.2.1
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): ubuntu

### PR DESCRIPTION
**Pull request by crisbeto**
Handles very large numbers being passed in as a snack bar duration (e.g. `Infinity`). We need to cap the duration, otherwise the browser will revert it back to 1 if it's too large.

Fixes #17234.

### CODE REVIEW

File: src/material/snack-bar/snack-bar-ref.ts [hunk 1]
```diff
@@ -17,6 +17,9 @@ export interface MatSnackBarDismiss {
   dismissedByAction: boolean;
 }
 
+/** Maximum amount of milliseconds that can be passed into setTimeout. */
+const MAX_TIMEOUT = Math.pow(2, 31) - 1;
```
Comment (jelbourn) [inline src/material/snack-bar/snack-bar-ref.ts]: Why doesn't `Number.MAX_SAFE_INTEGER` work for this?

Comment (crisbeto) [reply src/material/snack-bar/snack-bar-ref.ts]: AFAIK `MAX_SAFE_INTEGER` is 64bit, whereas `setTimeout` accepts 32bit.
