### PR TITLE
fix(sidenav): restore focus if drawer is closed through backdrop click

### LINKED ISSUE #17749: Sidenav toggle button doesn't clear the button focus state
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1.  Click on sidenav toggle button  on the default Angular Material Example 
https://stackblitz.com/angular/rxplkxebyor?file=src%2Fapp%2Fsidenav-disable-close-example.ts

2. Close Reason backdrop clears the toggle button state but not the toggle button.
 
 
#### Expected Behavior

What behavior were you expecting to see?
Sidenav toggle button should work same as the backdrop click.

#### Actual Behavior

What behavior did you actually see?
Sidenav toggle button doesn't clear the cdk-focus on the nav button

#### Environment

- Angular: 8..2.15
- CDK/Material: 8.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows
togglebutton-Angular
backdrop-nav-angular

### PR DESCRIPTION
**Pull request by devversion**
Currently we do not restore focus properly when a drawer is closed
through backdrop click. This is because we only restore focus when
an element inside the drawer is focused before closing. This is not
the case when the backdrop is clicked, as the focus is usually
redirected to the `document.body` element.

Fixes #17749.

### CODE REVIEW

File: src/material/sidenav/drawer.ts [hunk 1]
```diff
@@ -339,17 +345,18 @@ export class MatDrawer implements AfterContentInit, AfterContentChecked, OnDestr
...
    */
   private _restoreFocus() {
     if (!this.autoFocus) {
       return;
     }
 
     const activeEl = this._doc && this._doc.activeElement;
-
-    if (activeEl && this._elementRef.nativeElement.contains(activeEl)) {
+    if (this._isClosingViaBackdropClick ||
```
Comment (crisbeto) [inline src/material/sidenav/drawer.ts:358]: This feels a little side-effect-ey. Wouldn't it be better if we moved out the toggling logic into a helper method which has a parameter that determines whether to restore focus. E.g.

```
_closeViaBackdrop() {
  this._toggle(true);
}

toggle() {
  this._toggle(false);
}

_toggle(restoreFocus: boolean) {
   // Closing logic goes here
  if (restoreFocus) {
    this._restoreFocus();
  }
}
```

Comment (devversion) [reply src/material/sidenav/drawer.ts:358]: I was slightly concerned about this too, but couldn't think of a case where this would break. I went with the flag as that requires fewest changes and `restoreFocus` seemed already reliant on slide-effects anyway. e.g. `this.autoFocus` being true, reliance on `document.activeElement`.

Maybe this is the chance though to clean this up. I'll experiment with it.

Comment (devversion) [reply src/material/sidenav/drawer.ts:358]: Ah. I remember why I didn't do it that way. It was quite similar to #9257. We'd not go through `MatDrawer#toggle´ anymore and that could break tests. I think it would be worth trying against g3 though.

File: src/material/sidenav/drawer.ts [hunk 2]
```diff
@@ -339,29 +339,31 @@ export class MatDrawer implements AfterContentInit, AfterContentChecked, OnDestr
...
+      this._elementRef.nativeElement.blur();
     }
 
     this._elementFocusedBeforeDrawerWasOpened = null;
     this._openedVia = null;
   }
 
+  /** Whether focus is currently within the drawer. */
+  private _isFocusWithinDrawer(): boolean {
+    const activeEl = this._doc && this._doc.activeElement;
```
Comment (crisbeto) [inline src/material/sidenav/drawer.ts:363]: You should be able to change this to `this._doc?.activeElement`.

File: src/material/sidenav/drawer.ts [hunk 3]
```diff
@@ -403,23 +405,47 @@ export class MatDrawer implements AfterContentInit, AfterContentChecked, OnDestr
     return this.toggle(false);
   }
 
+  /** Closes the drawer with context that the backdrop was clicked. */
+  _closeViaBackdropClick(): Promise<MatDrawerToggleResult> {
+    // If the drawer is closed upon a backdrop click, we always want to restore focus. We
+    // don't need to check whether focus is currently in the drawer, as clicking on the
+    // backdrop causes blurring of the active element.
```
Comment (crisbeto) [inline src/material/sidenav/drawer.ts:412]: FWIW it's not actually the click that causes the blurring, it gets moved on `mousedown`.

Comment (devversion) [reply src/material/sidenav/drawer.ts:412]: Sure, but in this case a simple mousedown doesn't lead to `_closeViaBackdropClick` so in the context of a click, the active element is blurred and other situations are not relevant.

File: src/material/sidenav/drawer.ts (hunk 2 above)
Comment (devversion) [reply src/material/sidenav/drawer.ts]: yeah, I think we can use optional chaining as those will be downleveled.

File: src/material/sidenav/drawer.ts [hunk 4]
```diff
@@ -339,29 +339,31 @@ export class MatDrawer implements AfterContentInit, AfterContentChecked, OnDestr
...
-    const activeEl = this._doc && this._doc.activeElement;
-
-    if (activeEl && this._elementRef.nativeElement.contains(activeEl)) {
-      // Note that we don't check via `instanceof HTMLElement` so that we can cover SVGs as well.
-      if (this._elementFocusedBeforeDrawerWasOpened) {
-        this._focusMonitor.focusVia(this._elementFocusedBeforeDrawerWasOpened, this._openedVia);
-      } else {
-        this._elementRef.nativeElement.blur();
-      }
+    // Note that we don't check via `instanceof HTMLElement` so that we can cover SVGs as well.
```
Comment (mmalerba) [inline src/material/sidenav/drawer.ts:350]: Nice, this is definitely easier to understand with the helper broken out
