### PR TITLE
fix(datepicker): don't revalidate if new date object for same date is passed through input

### LINKED ISSUE #19907: bug(mat-date-range-picker): Unable to pick a date when using functions with [min],[max]
#### Reproduction

https://stackblitz.com/edit/mat-date-range-fn-bug

Steps to reproduce:
1. Pick a date using the first date picker ([min], [max] bound with member variable) - works as expected
2. Pick a date using the second date picker ([min], [max] bound with function) - UNABLE TO PICK A DATE RANGE.
 
#### Expected Behavior

I am expecting that the date-range-picker can be set with dynamic mutable min and max values.

#### Actual Behavior

You are unable to use the picker when [min] or [max] or both is bound to a function that returns new Date or Moment objects every time.

#### Environment

- Angular: 10.0.2
- CDK/Material: 10.0.1
- Browser(s): Chrome and Safari
- Operating System: macOS

### PR DESCRIPTION
**Pull request by crisbeto**
If a function is used to provide a new date object for the `min` or `max` of a datepicker input, we currently trigger a revalidation on each change detection, because the input value is technically different. Historically this is something that we haven't fixed on our end, because it masks an anti-pattern on the user's end, however in this case it breaks in a non-obvious way and detecting it would be more code than just handling it.

These changes add checks in several places so that we don't trigger validators or extra change detections if a new date object for the same date is provided.

These changes also clean up the date range input which had both a `stateChanges` and `_stateChanges` streams which are required by two separate interfaces. Now there's a single `stateChanges`.

Fixes #19907.

### CODE REVIEW

File: src/material/datepicker/date-range-input.ts [hunk 1]
```diff
@@ -261,17 +267,18 @@ export class MatDateRangeInput<D> implements MatFormFieldControl<DateRange<D>>,
...
+  ngOnChanges(changes: SimpleChanges) {
+    if (dateInputsHaveChanged(changes, this._dateAdapter)) {
+      this.stateChanges.next(undefined);
+    }
   }
 
   ngOnDestroy() {
-    this.stateChanges.complete();
-    this._stateChanges.unsubscribe();
+    this.stateChanges.unsubscribe();
```
Comment (mmalerba) [inline src/material/datepicker/date-range-input.ts:281]: should this be `.complete()`?

Comment (crisbeto) [reply src/material/datepicker/date-range-input.ts]: Good catch. Fixed.
