### PR TITLE
fix(material/core): avoid running sanity checks on some test environments

### LINKED ISSUE #23365: bug: Sanity checks run in test environement
As I explained in comment on PR ( https://github.com/angular/components/pull/23289 ) I have a lot of warnings coming from angular material sanity checks during my unit test runs, what makes the output unreadable.
@jelbourn advised me to open an issue because sanity checks should not run in test environment.

Thanks for your help !

Steps to reproduce:
1. Fork https://github.com/eweap/angular-material-warn
2. Run `yarn install` then run test with `yarn nx test ui` to run the test for the ui lib (its a nrwl/nx workspace)
 
 
#### Expected Behavior

What behavior were you expecting to see?
No warning should be display during the test run

#### Actual Behavior

What behavior did you actually see?
A warning is displayed:

```
console.warn
      Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming

      at MatCommonModule.Object.<anonymous>.MatCommonModule._checkThemeIsPresent (../../../src/material/core/common-behaviors/common-module.ts:144:15)
      at new MatCommonModule (../../../src/material/core/common-behaviors/common-module.ts:81:12)
      at Object.MatCommonModule_Factory [as factory] (../../node_modules/@angular/material/bundles/material-core.umd.js:189:69)
      at R3Injector.Object.<anonymous>.R3Injector.hydrate (../../../packages/core/src/di/r3_injector.ts:416:29)
      at R3Injector.Object.<anonymous>.R3Injector.get (../../../packages/core/src/di/r3_injector.ts:211:23)
      at ../../../packages/core/src/di/r3_injector.ts:247:51
          at Set.forEach (<anonymous>)
      at R3Injector.Object.<anonymous>.R3Injector._resolveInjectorDefTypes (../../../packages/core/src/di/r3_injector.ts:247:27)
```

#### Environment

- Angular: 12.2.1
- CDK/Material: 12.2.1
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the sanity checks were running on some testing environments like Jest.

These changes also move the test environment check into a centralized place so that it's easier to keep up to date.

Fixes #23365.

### CODE REVIEW

File: src/material/core/common-behaviors/common-module.ts [hunk 1]
```diff
@@ -65,7 +66,8 @@ export class MatCommonModule {
   constructor(
       highContrastModeDetector: HighContrastModeDetector,
       @Optional() @Inject(MATERIAL_SANITY_CHECKS) sanityChecks: any,
-      @Inject(DOCUMENT) document: any) {
+      @Inject(DOCUMENT) document: any,
+      private _platform?: Platform) {
```
Comment (devversion) [inline src/material/core/common-behaviors/common-module.ts:70]: Are we planning on making this required in the future? or do you think it's always okay being optional?

**Review by devversion — APPROVED** [review]
LGTM. Looks great to have this logic in a single place

File: src/material/core/common-behaviors/common-module.ts (hunk 1 above)
Comment (crisbeto) [reply src/material/core/common-behaviors/common-module.ts:70]: Yeah, it should be required in the future, I think I just missed it before. Adding it now.

**Comment by leonardochaia** [comment]
Hoping that this get merged soon! our test builds logs are crowded with them and makes it hard to find other warnings.

File: src/cdk/platform/platform.ts [hunk 2]
```diff
@@ -37,6 +50,13 @@ export class Platform {
   isBrowser: boolean = this._platformId ?
       isPlatformBrowser(this._platformId) : typeof document === 'object' && !!document;
 
+  /** Whether the application is running inside a testing environment. */
+  isTest: boolean =
```
Comment (jelbourn) [inline src/cdk/platform/platform.ts:54]: I don't know that I want to make this a public API. I worry that it will put us in a hard position in the future with respect to not breaking people. Our own internal usage of this minor enough that I'm much less worries about breaking changes there.

Comment (devversion) [reply src/cdk/platform/platform.ts:54]: We could prefix it with an underscore, or the barrel o character used by Ivy instructions (too avoid the member showing up in autocomplete)

Alternatively we could also just expose an underscore-prefixed method from cdk/platform

Comment (jelbourn) [reply src/cdk/platform/platform.ts:54]: I would probably lean towards an underscore-prefixed function in the cdk/platform package

**Comment by crisbeto** [comment]
I've moved the utility into an underscored function.

**Review by jelbourn — APPROVED** [review]
LGTM

**Review by devversion — APPROVED** [review]

**Comment by michaelfaith** [comment]
Just wanted to check and see if this will be merged in soon?
