### PR TITLE
fix(drag-drop): placeholder element not available in started event

### LINKED ISSUE #19457: bug(drag-drop): cannot get placeholder element on cdkDragStarted
#### Reproduction

https://stackblitz.com/edit/components-issue-jk8rbb
 
#### Expected Behavior

Returns the placeholder element to manipulate

#### Actual Behavior

Returns undefined

#### Environment

- Angular:9.1.9
- CDK/Material:9.2.4
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): latest macOS

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes calling `CdkDrag.getPlaceholderElement` returning undefined if it's called in the `cdkDragStarted` event.

Fixes #19457.

### CODE REVIEW

File: src/cdk/drag-drop/directives/drag.ts [hunk 1]
```diff
@@ -226,18 +226,12 @@ export class CdkDrag<T = any> implements AfterViewInit, OnChanges, OnDestroy {
   /**
    * Returns the element that is being used as a placeholder
    * while the current element is being dragged.
-   * @deprecated No longer being used to be removed.
-   * @breaking-change 11.0.0
```
Comment (crisbeto) [inline src/cdk/drag-drop/directives/drag.ts:230]: I changed my mind on deprecating this, because I can see how it can be useful.
