### PR TITLE
fix(cdk-experimental/column-resize): not working inside OnPush component

### LINKED ISSUE #19670: column-resize (experimental) does not work with ChangeDetectionStrategy.OnPush
#### Reproduction

1. Grab demo from here:  https://github.com/angular/components/blob/master/src/components-examples/material-experimental/column-resize/default-enabled/
2. Add "changeDetection: ChangeDetectionStrategy.OnPush" to default-enabled-column-resize-demo.ts
3. Try to resize columns
 
#### Expected Behavior

Columns should resize.

#### Actual Behavior

Columns do not resize.

#### Environment

"@angular/material-experimental": "^9.2.4"

### PR DESCRIPTION
**Pull request by crisbeto**
Change detection wasn't triggered when attaching the resize handle inside an `OnPush` component which prevented some event listeners from being bound and broke the resizing completely.

Fixes #19670.

### CODE REVIEW

File: src/cdk-experimental/column-resize/resizable.ts [hunk 1]
```diff
@@ -222,6 +224,7 @@ export abstract class Resizable<HandleComponent extends ResizeOverlayHandle>
   private _showHandleOverlay(): void {
     this._updateOverlayHandleHeight();
     this.overlayRef!.attach(this._createHandlePortal());
+    this.changeDetectorRef.markForCheck();
```
Comment (jelbourn) [inline src/cdk-experimental/column-resize/resizable.ts:227]: Could you add a comment that gives the context on this call?

Comment (crisbeto) [reply src/cdk-experimental/column-resize/resizable.ts:227]: Done.
