### PR TITLE
fix(cdk/menu): control + option + space not working on VoiceOver

### LINKED ISSUE #27376: bug(cdk/menu): Mac OS VoiceOver cannot operate menu
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

Using VoiceOver on Mac OS, I am unable to open a CDK-enabled menu using the standard VoiceOver key combination for a button (Ctrl-Option-Space).

The same applies to selecting menu items after the menu is open (if opened some other way first).

### Reproduction

Go to the CDK menu examples page: https://material.angular.io/cdk/menu/examples using Mac OS, with VoiceOver enabled. Tab to the button under "Google Docs Menu Bar" or "Menu with Standalone Trigger" or "Stateful Menu with Standalone Trigger".

VoiceOver announces "To display a list of options, press Ctrl-Option-Space". Press this key combination.

### Expected Behavior

Pressing Ctrl-Option-Space should open the menu. This is the standard VoiceOver command for activating any button or link.

### Actual Behavior

Pressing Ctrl-Option-Space has no effect.

The same occurs for v15: https://v15.material.angular.io/cdk/menu/examples

But it works as expected for v14: https://v14.material.angular.io/cdk/menu/examples

It also works as expected for the latest Material menu: https://material.angular.io/components/menu/examples rather than the CDK.

### Environment

- Angular: 15, 16
- CDK: 15, 16
- Browser(s): latest Chrome, Edge, Firefox, or Safari
- Operating System: Mac OS (reproduced on both latest 13.4.1 and the much older 10.13.6)

### PR DESCRIPTION
**Pull request by crisbeto**
In #26296 I added a condition in the click handler for menu triggers and menu items to skip clicks dispatched by the keyboard so that they don't trigger the menu twice. The problem is that this also ends up ignoring the default keyboard shortcut that VoiceOver mentions should be used to trigger the menu (Control + Option + Space), because it ends up being dispatched as a plain `click` event and it doesn't trigger the `keydown` event at all.

These changes address the issue by removing the previous condition and inferring whether the event will trigger a click by looking at it and the element it's coming from.

Fixes #27376.

### CODE REVIEW

File: src/cdk/menu/menu-trigger.ts [hunk 1]
```diff
@@ -130,7 +129,8 @@ export class CdkMenuTrigger extends CdkMenuTriggerBase implements OnDestroy {
     switch (event.keyCode) {
       case SPACE:
       case ENTER:
-        if (!hasModifierKey(event)) {
+        // Skip events that will trigger clicks so the handler doesn't get triggered twice.
+        if (!hasModifierKey(event) && !eventDispatchesNativeClick(this._elementRef, event)) {
```
Comment (devversion) [inline src/cdk/menu/menu-trigger.ts:133]: OOC: Why are we not always just handling the `click` event. Are we doing this for the focus origin?

**Review by devversion — APPROVED** [review]

File: src/cdk/menu/menu-trigger.ts (hunk 1 above)
Comment (crisbeto) [reply src/cdk/menu/menu-trigger.ts:133]: The problem is that the menu trigger does the same both enter/space events and click events. When the enter event trigger a click, it ends up closing and reopening the menu immediately. Previously we were handling it by calling `preventDefault`, but that ended up breaking links used in the menu.

Comment (devversion) [reply src/cdk/menu/menu-trigger.ts:133]: I see. I don't quite follow why we handle `SPACE/ENTER` in the first place via `keydown`, but I'm sure there are some nuances I'm just missing here. In either case the change LGTM 😄

Comment (crisbeto) [reply src/cdk/menu/menu-trigger.ts:133]: Ah, we need to do it because click events only get dispatched on space/enter for buttons and links, but the menu trigger and menu item can be set on any arbitrary element.

Comment (devversion) [reply src/cdk/menu/menu-trigger.ts:133]: Gotcha
