### PR TITLE
fix(cdk/a11y): correctly detect focus from input label

### LINKED ISSUE #25090: bug(material/radio): Focus styling remains applied after mouseup
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

sadly, the material radiobutton stays focused after being selected.
This could be intended by the material specs - https://github.com/angular/components/issues/14290
But other material components like checkbox or inputs does not have this behavior.
The material specs ( https://material.io/components/selection-controls#radio-buttons ) mention a "Pressed Focus" state - but the animation does show a different behavior after click: https://kstatic.googleusercontent.com/files/bed79fcf6804cded983c22cde6ee42734fce03e47589c4f3d4338405c67cd0b7e28a30c4fbcf9eea0403fb2e8846c4264d432451a31eb7bd364e94d30b1e77d2

perhaps the behavior to keep a "pressed focused" state or to remove focus (and defocus just like all other elements/checkboxes) could be made optional.

### Reproduction

Steps to reproduce:
head to https://material.angular.io/components/radio/examples and click a radio button

### Expected Behavior

the focus / animation / big transparent ripple circle should disappear

### Actual Behavior

the focus / animation / big transparent ripple circle does not disappear

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

### PR DESCRIPTION
**Pull request by crisbeto**
In most cases focus moves during `mousedown` so all of our detection uses `mousedown` events to track it. It breaks down for the common use case where a `label` is connected to an `input`, because there focus moves on the `click` event instead. This has been a long-standing issue with the `FocusMonitor` that has caused problems for `mat-checkbox`, `mat-radio-button` and `mat-slide-toggle`.

These changes add special handling for the `input` + `label` case that checks if the previous mouse interaction was with a label belonging to the current `input` receiving focus.

Fixes #25090.

### CODE REVIEW

File: src/cdk/a11y/focus-monitor/focus-monitor.ts [hunk 1]
```diff
@@ -552,6 +567,40 @@ export class FocusMonitor implements OnDestroy {
 
     return results;
   }
+
+  /**
+   * Returns whether an interaction is likely to have come from the user clicking the `label` of
+   * an `input` or `textarea` in order to focus it.
+   * @param focusEventTarget Target currently receiving focus.
+   */
```
Comment (crisbeto) [inline src/cdk/a11y/focus-monitor/focus-monitor.ts:575]: A much simpler alternative I was considering was to listen to `click` events inside the `InputModalityDetector` instead and set the modality to `mouse` again. I decided against it, because it would've meant that `modalityDetected` would emit two consecutive `mouse` interactions on any click which can be annoying for consumers. Also this seems very much like a focus issue so it makes more sense to handle it in the `FocusMonitor` than the `InputModalityDetector`.

**Review by devversion — APPROVED** [review]
