### PR TITLE
fix(cdk/overlay): sub-pixel deviations throwing off positioning in some cases

### LINKED ISSUE #21350: bug(CdkOverlay): CdkOverlay incorrectly calculates viewport bounds
#### Reproduction

https://stackblitz.com/edit/components-issue-yh1yjm?file=src/app/example-component.ts

Steps to reproduce:
1. Spawn a flexible position based overlay.
2. Make overlay contents height larger than viewport height such that overflow occurs.
3. Make viewport height a floating point number with decimal portion between .0 to .5.
4. The overlay will now overflow out of the viewport bounds.
5. Make the viewport height a floating point number between .5 to next whole number, or a whole number.
6. The overlay will now correctly stay within the viewport bounds.

Notes:
If you just try slowly resizing the window height while the overlay is open, you will see it bounce in and out of the viewport as the window height cycles between bad and good numbers.
 
Problem is that viewport height is a rounded number, and overlay height is a floating point. Therefore when viewport rounds down, the following check fails.

https://github.com/angular/components/blob/e436479a7bef69b87e8954616a9e29a265a1a2b1/src/cdk/overlay/position/flexible-connected-position-strategy.ts#L632

To compare the two numbers, the rounding needs to be consistent.
 
#### Expected Behavior

Flexible dimension overlay should always remain within viewport bounds.

#### Actual Behavior

Flexible dimension overlay does not remain within viewport bounds when viewport height rounds down.

#### Environment

- Angular: 10.2.3
- CDK/Material: 10.2.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

### PR DESCRIPTION
**Pull request by crisbeto**
If the browser is zoomed in beyond the default level, it may report numbers with sub-pixel deviations to `getBoundingClientRect` (e.g. 100.09 vs 100) which can throw off our logic when comparing against the viewport size which is always a whole number.

These changes fix the issue by rounding down the numbers that we get from `getBoundingClientRect`.

Fixes #21350.

### CODE REVIEW

File: src/cdk/overlay/position/flexible-connected-position-strategy.ts [hunk 1]
```diff
@@ -1219,3 +1225,20 @@ function getPixelValue(input: number|string|null|undefined): number|null {
...
   return input || null;
 }
+
+/**
+ * Gets a version of an element's bounding `ClientRect` where all the values are rounded down to
+ * the nearest pixel. This allows us to account for the cases where there may be sub-pixel
+ * deviations in the `ClientRect` returned by the browser (e.g. when zoomed in with a percentage
+ * size, see #21350).
+ */
+function getRoundedBoundingClientRect(clientRect: ClientRect): ClientRect {
```
Comment (jelbourn) [inline src/cdk/overlay/position/flexible-connected-position-strategy.ts:1235]: It just rolls right off the tongue

**Review by jelbourn — APPROVED** [review]
LGTM
