### PR TITLE
fix(cdk/drag-drop): last item not returned at initial index when sorting is disabled

### LINKED ISSUE #23865: Drag and Drop example broken
https://material.angular.io/cdk/drag-drop/overview#cdk-drag-drop-disabled-sorting

In the description it states ```in addition to preserving the dragged item's initial position in the source list, if the user decides to return the item.```

Initial position is not preserved when an item is dragged from left panel to right panel and then returned.

When the item is returned it is placed wherever dropped, not in its initial position.

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes a regression caused by #19116 where dragging the last item into another container and returning it back to the initial one would insert the item into the first index of the list, rather than the last one. The issue was caused by the fact that we relied on the item to always be inserted at the end of the list of there is no position reference, but the condition was superseded by the condition that inserts it at the beginning of the list.

Fixes #23865.

### CODE REVIEW

File: src/cdk/drag-drop/drop-list-ref.ts [hunk 1]
```diff
@@ -299,6 +299,16 @@ export class DropListRef<T = any> {
       newPositionReference = activeDraggables[newIndex + 1];
     }
 
+    // If we didn't find a new position reference, it means that either the item didn't start off
+    // in this container, or that the item request to be inserted at the end of the list.
```
Comment (jelbourn) [inline src/cdk/drag-drop/drop-list-ref.ts:303]:
```suggestion
    // in this container, or that the item requested to be inserted at the end of the list.
```

**Review by jelbourn — APPROVED** [review]
lgtm
