### PR TITLE
fix(cdk/tree): collapse child nodes if top level collapses

### LINKED ISSUE #20665: bug(tree): Leaf nodes are not collapsed if top-level folder is collapsed
#### Reproduction

The bug is reproducible with the flat tree example in the [official documentation](https://material.angular.io/cdk/tree/overview). What is the same as the respective [Stackblitz example](https://stackblitz.com/angular/kerxmngqjav?file=src%2Fapp%2Fcdk-tree-flat-example.ts). 

Steps to reproduce:
1. Expand "Vegetables" node and then "Green" and "Orange" nodes.
2. Collapse "vegetables"
 
 
#### Expected Behavior

All nodes under "Vegetables" should disappear (should be collapsed).

#### Actual Behavior

"Green" and "Orange" disappear, but the leaf nodes are still visible.

Expanded nodes:
image

After collapsing "Vegetables":
image

#### Environment

- Angular: 10.2.2
- CDK/Material: 10.2.2
- Browser(s): Chrome 85
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

### PR DESCRIPTION
**Pull request by bochalito**
Fixes a bug in the Angular CDK Tree examples where the children nodes
are still visible when the top level node is collapsed. This is because
the `shouldRender()` method of the [cdk-flat-tree-example.ts](https://github.com/angular/components/blob/master/src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.ts) is checking
only the parent of current node.

Fixes #20665

### CODE REVIEW

File: src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.ts [hunk 1]
```diff
@@ -88,7 +88,13 @@ export class CdkTreeFlatExample {
   }
 
   shouldRender(node: ExampleFlatNode) {
-    const parent = this.getParentNode(node);
-    return !parent || parent.isExpanded;
+    let parent = this.getParentNode(node);
+    while (parent) {
+        if (!parent.isExpanded) {
```
Comment (crisbeto) [inline src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.ts:93]: The indentation is off on the entire block.

Comment (bochalito) [reply src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.ts]: Changed on commit [06373d3](https://github.com/angular/components/commit/06373d3877ac987ec23da2b38675ea0bbf4d4497)

File: src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.ts [hunk 2]
```diff
@@ -88,7 +88,13 @@ export class CdkTreeFlatExample {
   }
 
   shouldRender(node: ExampleFlatNode) {
-    const parent = this.getParentNode(node);
-    return !parent || parent.isExpanded;
+    let parent = this.getParentNode(node);
+    while (parent) {
+      if (!parent.isExpanded) {
+          return false;
```
Comment (crisbeto) [inline src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.ts:94]: This indentation still seems a bit too much. We use 2 spaces everywhere.

**Review by crisbeto — APPROVED** [review]
LGTM

File: src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.ts (hunk 2 above)
Comment (bochalito) [reply src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.ts]: My bad again. I changed the configuration files on my IDE. Hope it is fine now! [5dfafba](https://github.com/angular/components/commit/5dfafba19c4612c8b91a9421fee945b8b02ce1b6)
