### PR TITLE
fix(stepper): unable to skip step if completed value is overwritten

### LINKED ISSUE #15310: Stepper [completed]="true" cannot skip steps
#### What is the expected behavior?
Linear stepper - Able to Move from Step 1 to Step 3 when [completed]="true" is set

#### What is the current behavior?
Linear stepper -
Need to touch step 2 to be able to move from Step 1 to Step 3 when [completed]="true" is set

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-bmwaq7
[completed]="true" is set on all steps.

1) Click on Step 3 (Not able to move from Step1 to Step3) << Possible Bug
2) Click on Step 2 (Able to move from Step1 to Step2)
3) Click on Step 1 (Able to move to Step 2 to Step 1)
4) Click on Step 3 (Able to move from Step1 to Step3)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2.6
Material 7.3.1

### PR DESCRIPTION
**Pull request by crisbeto**
Currently we allow for the `completed` value of a step to be overwritten, however setting it to `true` still won't allow the user to skip the step, because the `interacted` flag won't be flipped if they haven't been on a particular step before.

Fixes #15310.

### CODE REVIEW

File: src/cdk/stepper/stepper.ts [hunk 1]
```diff
@@ -166,12 +170,12 @@ export class CdkStep implements OnChanges {
...
   get completed(): boolean {
-    return this._customCompleted == null ? this._getDefaultCompleted() : this._customCompleted;
+    return this._completedOverride == null ? this._getDefaultCompleted() : this._completedOverride;
   }
   set completed(value: boolean) {
-    this._customCompleted = coerceBooleanProperty(value);
+    this._completedOverride = coerceBooleanProperty(value);
   }
-  private _customCompleted: boolean | null = null;
+  _completedOverride: boolean|null = null;
```
Comment (mmalerba) [inline src/cdk/stepper/stepper.ts]: is there a reason this was made non-private?

Comment (crisbeto) [reply src/cdk/stepper/stepper.ts]: It's been a long time since I opened this PR, but from what I can tell, it's because `CdkStepper` also checks it.

Comment (mmalerba) [reply src/cdk/stepper/stepper.ts]: Ah ok, yeah sorry was going through my old assigned PRs and found this that I never responded to
