### PR TITLE
fix(menu): internal focus state out of sync if item is focused programmatically

### LINKED ISSUE #17761: Calling MatMenuItem#focus() does not update the MatMenu's focusKeyManager's active item
#### Reproduction

Repro: https://stackblitz.com/edit/components-issue-svmexm

Steps to reproduce:
1. Open a menu
2. Programatically focus some mat-menu-item other than the first one (in the stackblitz repro above, the third mat-menu-item, "C" is focused, due to the onOpen() method in AppComponent, which calls the third mat-menu-item's `focus` method.)
3. Press the down arrow key (note: a similar variant applies to the up arrow case.)
  
#### Expected Behavior

What behavior were you expecting to see?

The next mat-list-item, "D", should be focused.

#### Actual Behavior

What behavior did you actually see?

The second mat-list-item, "B", is focused.

#### Analysis

This is happening because the mat menu's FocusKeyManager still thinks the first mat menu item is the active item, even thought we programatically focused a different mat-menu-item. Since mat menu's key manager is private / not exposed to downstream developers, I don't think there's a way to address it currently without a change to Angular Material.

#### Some possible solutions

* Update the MatMenuItem#focus method to also update the mat menu's active item at the same time
* Expose the mat menu's key manager so downstream developers can call its setActiveItem method.
* Add to the mat menu public API a method to set the active item key manager's active item

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes the internal key manager of the menu being out of sync if one of the menu items is focused via its `focus` method.

Fixes #17761.

### CODE REVIEW

File: src/material/menu/menu.ts [hunk 1]
```diff
@@ -251,6 +251,13 @@ export class _MatMenuBase implements AfterContentInit, MatMenuPanel<MatMenuItem>
     this._updateDirectDescendants();
     this._keyManager = new FocusKeyManager(this._directDescendantItems).withWrap().withTypeAhead();
     this._tabSubscription = this._keyManager.tabOut.subscribe(() => this.closed.emit('tab'));
+
+    // We don't need to unsubscribe here because _focused is
```
Comment (jelbourn) [inline src/material/menu/menu.ts]: Also add a comment that explains why this bit is necessary? Something like
```ts
// If a user manually (programatically) focuses a menu item, we need to reflect
// that focus change back to the key manager.
```

**Comment by crisbeto** [comment]
The feedback has been addressed @jelbourn.
