### PR TITLE
fix(material-experimental/mdc-chips): Mirror aria-describedby to matChipInput

### LINKED ISSUE #24542: bug(mat-chip-grid): mat-error instances are not exposed to screen reader users
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When a `mat-chip-grid` has a `mat-error` associated with it SR users do not hear the error when they focus the grid or its associated `matChipInput`.

### Reproduction

Steps to reproduce:
1. Load this stackblitz: https://stackblitz.com/edit/components-issue-keh175
2. Turn on the Screen Reader of your choice
3. Tab to the chip input
4. Enter any value and hit enter.  You should see an error appear and you should hear it be announced.
5. Tab back to the button above or the button below, then tab back to either the input or chip grid

### Expected Behavior

The SR reads out the error message when the user focuses either the chip grid or the chip input.

### Actual Behavior

The SR does not read out the error message.  Additionally, it does not indicate that the field is invalid until the `matChipInput` is focused.  This seems to be the result of the on-focus behavior of MatChipGrid combined with the way the form field is associating the error with its control.

When a form field has an error associated with it, AM will generally try to add `aria-describedby=ERROR_ELEMENT_ID`.  In this particular case, the control that the error is associated with is the `mat-chip-grid` element.  However, [when focus lands on a chip grid it focuses the first chip if any are available, or otherwise moves the focus to the input if one is present](https://github.com/angular/components/blob/cfd89089f6e1c061c8924fdb40efb7952720cc43/src/material-experimental/mdc-chips/chip-grid.ts#L356).  Effectively, this means that the user cannot ever hear the error message be announced while focused on the control itself.

### Environment

- Angular: 13.2.5
- CDK/Material: 13.2.5
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Any

### PR DESCRIPTION
**Pull request by ByzantineFailure**
Updates mat-chip-grid to associate any ids set for aria-describedby to the matChipInput instance within the grid, if one exists.  See #24542 for information on why this is necessary.

Currently this PR creates a `setAriaDescribedBy` method on `matChipInput` and calls it from `mat-chip-grid` whenever `mat-chip-grid`'s `setAriaDescribedBy` method is called.  The internal logic mirrors that of `mat-chip-grid`.  This may not be the best way to go about this change; let me know if there's a better way to do it!

Fixes #24542

### CODE REVIEW

File: src/material-experimental/mdc-chips/chip-grid.ts [hunk 1]
```diff
@@ -379,6 +379,10 @@ export class MatChipGrid
    */
   setDescribedByIds(ids: string[]) {
     this._ariaDescribedby = ids.join(' ');
+
```
Comment (crisbeto) [inline src/material-experimental/mdc-chips/chip-grid.ts:382]: I'm wondering whether we should be setting `aria-describedby` on the chip grid at all, considering that it never receives focus.

Comment (ByzantineFailure) [reply src/material-experimental/mdc-chips/chip-grid.ts:382]: That's a good point.

I don't see any harm in keeping it on the chip grid itself, but I also don't see any harm in removing it either.

The only (extremely minor) concern I have is if the focus management of the grid instance changes to focus the grid element itself at some point.  That's not the case here, though, and I don't really think it's a big deal if we remove it.

All of that is to say:  I can remove the attribute from the grid if you'd like, just let me know!

File: src/material-experimental/mdc-chips/chip-input.ts [hunk 2]
```diff
@@ -73,6 +74,9 @@ export class MatChipInput implements MatChipTextControl, AfterContentInit, OnCha
   /** Used to prevent focus moving to chips while user is holding backspace */
   private _focusLastChipOnBackspace: boolean;
 
+  /** Value for ariaDescribedby property */
+  private _ariaDescribedby?: string;
```
Comment (ByzantineFailure) [inline src/material-experimental/mdc-chips/chip-input.ts:78]: Currently this attribute is causing the linter to fail since it's not referenced by any of the TS code.  Is there a way to suppress the linter for this attribute or is there another way we can handle that?

File: src/material-experimental/mdc-chips/chip-grid.ts (hunk 1 above)
Comment (crisbeto) [reply src/material-experimental/mdc-chips/chip-grid.ts:382]: I think that we should get rid of it, otherwise it's misleading.

File: src/material-experimental/mdc-chips/chip-input.ts (hunk 2 above)
Comment (crisbeto) [reply src/material-experimental/mdc-chips/chip-input.ts:78]: Since it's used in a host binding, it should be changed to a public property. That'll silence the linter as well.

Comment (ByzantineFailure) [reply src/material-experimental/mdc-chips/chip-input.ts:78]: Makes sense.  Changing.

File: src/material-experimental/mdc-chips/chip-grid.ts (hunk 1 above)
Comment (ByzantineFailure) [reply src/material-experimental/mdc-chips/chip-grid.ts:382]: Works for me!  We still need to keep the property present on the control to satisfy the MatFormFieldControl interface, but we can at least remove the property binding.

Comment (ByzantineFailure) [reply src/material-experimental/mdc-chips/chip-grid.ts:382]: Actually maybe not lemme dig further into that.

Comment (ByzantineFailure) [reply src/material-experimental/mdc-chips/chip-grid.ts:382]: It's defined on MatChipSet, which means we'll need to keep the property itself but can remove the binding.

**Comment by crisbeto** [comment]
It looks like there's still a lint failure.

File: src/material-experimental/mdc-chips/chip-grid.ts [hunk 3]
```diff
@@ -379,6 +379,10 @@ export class MatChipGrid
...
+    if (this._chipInput) {
+      this._chipInput.setDescribedByIds(ids);
```
[the remark this answers is not in the document]
Comment (ByzantineFailure) [reply src/material-experimental/mdc-chips/chip-grid.ts:384]: I don't think we have to deal with that in this particular method -- any time an error spawns this method will be called with all relevant ids and set the complete value of the property bound to the template.

The window for this to happen is very small:  We assert that a chipInput is present during `ngAfterViewInit()`, so the error that we're wanting to propagate would need to occur and be set before that time.  With this in mind we can handle this case by calling `setDescribedByIds` after the assertion.

The downside of doing this is it means we need to keep the value of `this._ariaDescribedby` up to date in this component as well.  Probably a best practice anyway since it's the one implementing `MatFormFieldControl`.

**Comment by ByzantineFailure** [comment]
I _think_ the e2e failure here is a flake, but am not necessarily able to determine that conclusively from the test output.  Is there a way I can re-run the e2e tests on CI?

File: src/material-experimental/mdc-chips/chip-grid.ts [hunk 4]
```diff
@@ -337,6 +335,10 @@ export class MatChipGrid
   /** Associates an HTML input element with this chip grid. */
   registerInput(inputElement: MatChipTextControl): void {
     this._chipInput = inputElement;
+
+    if (this._ariaDescribedby) {
+      this._chipInput.setDescribedByIds(this._ariaDescribedby.split(' '));
```
Comment (crisbeto) [inline src/material-experimental/mdc-chips/chip-grid.ts:340]: Instead of having to split the IDs here, maybe we should just save the string array?

**Review by crisbeto — COMMENTED** [review]
One more nit otherwise LGTM.

File: src/material-experimental/mdc-chips/chip-grid.ts (hunk 4 above)
Comment (ByzantineFailure) [reply src/material-experimental/mdc-chips/chip-grid.ts:340]: This field comes from `MatChipSet`, which `MatChipGridBase` extends:
https://github.com/angular/components/blob/f05e65a02b636d7c3d4e181f65ac0d7e94e091fd/src/material-experimental/mdc-chips/chip-set.ts#L142

The field is defined as a `string`.  I'm more than okay to save the values in an array, but I suspect we'll want to keep the value of `_ariaDescribedby` up to date regardless.

If we're comfortable introducing a new field to store the array, I'm more than happy to do so; let me know one way or the other.

Comment (crisbeto) [reply src/material-experimental/mdc-chips/chip-grid.ts:340]: Hmm, I think that the `aria-describedby` on `MatChipSet` isn't doing much since the element isn't focusable. It should be moved to the chip listbox.

Comment (ByzantineFailure) [reply src/material-experimental/mdc-chips/chip-grid.ts]: Removed.

**Review by crisbeto — APPROVED** [review]
LGTM

File: src/material-experimental/mdc-chips/chip-grid.ts [hunk 5]
```diff
@@ -378,7 +382,13 @@ export class MatChipGrid
    * @docs-private
    */
   setDescribedByIds(ids: string[]) {
-    this._ariaDescribedby = ids.join(' ');
+    // We must keep this up to date to handle the case where ids are set
+    // before the chip input is registered.
+    this._ariaDescribedbyIds = ids;
+
+    if (this._chipInput) {
+      this._chipInput.setDescribedByIds(ids);
```
Comment (andrewseguin) [inline src/material-experimental/mdc-chips/chip-grid.ts:390]: This gets called while the form field gets initialized after content is initialized:
```
MatChipInput.setDescribedByIds (chip-input.ts)
MatChipGrid.setDescribedByIds (chip-grid.ts)
MatFormField._syncDescribedByIds (form-field.ts)
MatFormField._initializeSubscript (form-field.ts)
MatFormField.ngAfterContentInit (form-field.ts)
```

This caused a `ExpressionChangedAfterCheckedError` in an application inside Google. It's probably related to how the grid/input content is provided with an `ngIf`. @crisbeto Is it valid to wrap this in a `setTimeout` to avoid change detection issues?

Comment (crisbeto) [reply src/material-experimental/mdc-chips/chip-grid.ts:390]: Yeah, let's try it with the timeout and we can re-evaluate if it causes even more failures because the timeouts haven't been flushed.

Comment (andrewseguin) [reply src/material-experimental/mdc-chips/chip-grid.ts:390]: Timeout didn't cause any issues, we can replace the logic with this to land the change
```
if (this._chipInput) {
      // Use a setTimeout in case this is being run during change detection
      // and the chip input has already determined its host binding for
      // aria-describedBy.
      setTimeout(() => {
        this._chipInput.setDescribedByIds(ids);
      }, 0);
    }
```

Comment (andrewseguin) [reply src/material-experimental/mdc-chips/chip-grid.ts:390]: Just a heads up that this would be best done ASAP so we don't need to re-run internal tests

Comment (andrewseguin) [reply src/material-experimental/mdc-chips/chip-grid.ts:390]: Sounds good, thanks :)

Comment (ByzantineFailure) [reply src/material-experimental/mdc-chips/chip-grid.ts]: Okay, should be set to go!

Comment (andrewseguin) [reply src/material-experimental/mdc-chips/chip-grid.ts]: Great, we'll start loading up approvals internally to get this in
