### PR TITLE
fix(overlay): don't reset global overlay alignment when width is 100% and there's a maxWidth

### LINKED ISSUE #17841: MatDialog ist not centered if width is set to 100% but maxWidth is lower
#### Reproduction

StackBlitz: https://stackblitz.com/edit/components-issue-nvo6ox

Steps to reproduce:
1. Open a component as a MatDialog using following configuration
`{
  width: '100%',
  maxWidth: '400px'
}`
2. Adjust the window width, so that exceeds the dialog-maxWidth of 400px
 
 
#### Expected Behavior

What behavior were you expecting to see?
- The dialog grows up to its max width of 400px
- As soon as the maxWidth is hit, the dialog stays the same width and is centered on the window

#### Actual Behavior

What behavior did you actually see?
- The dialog is positioned as expected if the width is configured to 99% or lower
- The dialog is aligned to the left of the window if the width configured to 100%
- see StackBlitz link above

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Linux

### PR DESCRIPTION
**Pull request by crisbeto**
A long time ago we introduced some logic that clears the `justifyContent` from a global overlay if it's `width` is set to 100%, in order to ensure that the element is flush against the viewport edge. Some time later we added a `maxWidth` option, but we never accounted for it which means that if an element is set to be `width: 100%; maxWidth: '500px'`, we'll reset the alignment incorrectly. These changes tweak the logic so it only resets if there is no `maxWidth` or if it's set to 100%.

Fixes #17841.

### CODE REVIEW

File: src/cdk/overlay/position/global-position-strategy.ts [hunk 1]
```diff
@@ -213,3 +215,11 @@ export class GlobalPositionStrategy implements PositionStrategy {
     this._isDisposed = true;
   }
 }
+
+/**
+ * Returns whether the element should be flush against the side of the viewport in a
+ * particular dimension, based on the intended size of the element and its maximum size.
+ */
+function shouldBeFlush(value: string|undefined, maxValue: string|undefined): boolean {
+  return value === '100%' && (!maxValue || maxValue === '100%');
```
Comment (jelbourn) [inline src/cdk/overlay/position/global-position-strategy.ts]: Does it make sense to also check `100vh` / `100vw`?

**Comment by crisbeto** [comment]
I must've missed the notification about this one. @jelbourn the feedback is addressed now.
